### ISSUE TITLE
Report all machine addresses

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1001]
/kind feature

**Describe the solution you'd like**
CAPO should report *all* addresses of a machine in OpenstackMachine.Status.Addresses, not just a single internal IP and a single external IP.

This would make the behaviour of CAPO consistent with the only 2 other providers I checked, AWS and GCP, both of which report all addresses.

*AWS:*
reconcileNormal:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/151fb40cbaa2d87d846f4a0f620c2dbf8b440283/controllers/awsmachine_controller.go#L600

SDKToInstance:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/151fb40cbaa2d87d846f4a0f620c2dbf8b440283/pkg/cloud/services/ec2/instances.go#L780

getInstanceAddresses:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/151fb40cbaa2d87d846f4a0f620c2dbf8b440283/pkg/cloud/services/ec2/instances.go#L791-L818

*GCP*
Reconcile:
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/582ef8e5548ee0357689dd9987bf70ac3839695d/cloud/services/compute/instances/reconcile.go#L45-L61

**Anything else you would like to add:**
Another motivation for doing this is removing a use of the problematic instanceStatus.NetworkStatus().IP() and FloatingIP() methods.

**Comment by hidekazuna** [comment]
Thanks for checking other providers implementation. [The Cluster API Book](https://cluster-api.sigs.k8s.io/developer/providers/machine-infrastructure.html) says that we must have a status field with 

>`addresses` (`MachineAddress`): a list of the host names, external IP addresses, internal IP addresses,
            external DNS names, and/or internal DNS names for the provider's machine instance. `MachineAddress` is
            defined as:
                - `type` (string): one of `Hostname`, `ExternalIP`, `InternalIP`, `ExternalDNS`, `InternalDNS`
                - `address` (string)

**Comment by mdbooth** [comment]
> 
> 
> Thanks for checking other providers implementation. [The Cluster API Book](https://cluster-api.sigs.k8s.io/developer/providers/machine-infrastructure.html) says that we must have a status field with
> 
> > `addresses` (`MachineAddress`): a list of the host names, external IP addresses, internal IP addresses,
> > external DNS names, and/or internal DNS names for the provider's machine instance. `MachineAddress` is
> > defined as:
> > - `type` (string): one of `Hostname`, `ExternalIP`, `InternalIP`, `ExternalDNS`, `InternalDNS`
> > - `address` (string)

Thanks! I was looking for this documentation but couldn't find it.

I have a patch in progress, btw.
