### ISSUE TITLE
without lb template need update to external cloud provider

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#1011]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

As in tree Cloud provider is going to deprecate soon, we need switch to OCCM version for CAPI
now cluster-template-external-cloud-provider.yaml is used in our test but
cluster-template-without-lb.yaml (without load balancer version) still use in tree

we need update this to external cloud version and update e2e as well

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mdbooth** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1162 should help with this when I eventually get the external CCM config working 😬 Hopefully nearly there.

**Comment by dulek** [comment]
I think this got addressed by #1514. @jichenjc?

**Comment by jichenjc** [comment]
yes, it's addressed, thanks for reminder
