### ISSUE TITLE
Need a way to update devstack in CI

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1017]
/kind feature

**Describe the solution you'd like**
As we expand the E2E tests we're occasionally going to want to make changes to the devstack which hosts them. This is currently contained in a `preinstalled` image hosted on [Google Storage](http://storage.googleapis.com/artifacts.k8s-staging-capi-openstack.appspot.com/test/devstack/2021-03-28/devstack.raw.tar.gz). The process for creating this image isn't part of the CAPO CI pipeline, so requires a separate process to manage. I am not currently sure what the process is.

Using the preinstalled image optimises the time it takes for devstack to come up when running a test. I haven't yet found the code which generates the image, but from examining the image itself I would guess it:
* Checks out devstack
* Writes a local.conf
* Executes stack.sh to fully install devstack and bring openstack up
* Shuts down the machine
* Takes an image

When bringing it up in CI we still need to execute stack.sh again to bring it up. However, re-executing stack.sh seems to save about 15 minutes over executing it the first time. Very roughly, this means:

***Total test execution time***
* With preinstalled: 60 minutes
* Without preinstalled: 75 minutes

I have been testing in #1009 a patch to replace local.conf in the preinstalled image before re-executing stack.sh. This allowed me to successfully enable trunking in devstack, which was the primary purpose of that PR, while still executing in approximately the same time as before.

However, coincidentally there was an apache 2 regression in Ubuntu which required [a fix in devstack](https://review.opendev.org/c/openstack/devstack/+/811399) that updated the generated uswgi config of OpenStack services. Although devstack was able to add a new service (neutron-trunk) when re-executing, it did not successfully reconfigure one which had previously been configured (apache2), so even pulling in the fixed devstack didn't fix the bug. This was hard to debug and it seems clear devstack isn't intended to be used this way, so I no longer think this is a reasonable approach.

My primary ask here is for a *single source of CI pipeline*: every part of the CI pipeline should be defined by code within the CAPO repo, except for the job definition itself.

I can see 2 obvious ways forward here:
* Integrate generation of the preinstalled image into the CAPO repo
* Stop using the preinstalled image and take the 15 minute hit on every job

The first option would be ideal, but significantly more complicated. I may be able to do this work myself if I can find out how we're currently generating the image, and if prow has access to credentials which can push it somewhere.

The second option is trivial to implement and much simpler to maintain, and honestly 60 minutes vs 75 minutes isn't all that much, so we should not discount it.

**Comment by sbueringer** [comment]
Fyi: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/794#issuecomment-803774885

But overall, my bad. Nowadays I think we should just take the longer test time. I just thought it's a waste of energy to install the devstack essentially on every commit of every PR. But I also thought I can speed up the test way more than what was actually possible (because just starting the devstack is really slow)

Overall +1 to drop the preinstalled variant

**Comment by mdbooth** [comment]
From the above, the preinstalled image is generated by: https://github.com/sbueringer/cluster-api-provider-openstack-images
