### ISSUE TITLE
Support availability zones and volume types for root volumes

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1021]
/kind feature

**Describe the solution you'd like**
Complex OpenStack deployments will often have many availability zones for both compute and storage, and there is no requirement for there to be a 1-1 mapping between the two. Additionally most OpenStack deployments will have more than a single volume type, for example to differentiate storage with different performance. To take advantage of this, we need to allow the user to specify the availability zone and volume type of their root volumes, while still allowing Cinder to pick defaults if they are not given explicitly.

We currently have support for this in OpenShift implemented here: https://github.com/openshift/cluster-api-provider-openstack/blob/36ecd2d1cbd8dc997e88ebbf8ad6c86ff2fb1668/pkg/apis/openstackproviderconfig/v1alpha1/types.go#L245-L252

**Comment by jichenjc** [comment]
/assign

I think it's related to BFV , we can replicate openshift to our code base

**Comment by mdbooth** [comment]
I'm working on test support in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1026.

**Comment by hidekazuna** [comment]
This is done by #1030
