### ISSUE TITLE
Consolidate Networks and Ports in OpenStackMachineSpec

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1023]
/kind feature

**Describe the solution you'd like**
Currently in MachineSpec we have 2 different ways to add a vif to a VM: [Networks](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/007a8278293efdded741831de584fcc4a1d6867e/api/v1alpha4/openstackmachine_types.go#L55) and [Ports](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/007a8278293efdded741831de584fcc4a1d6867e/api/v1alpha4/openstackmachine_types.go#L59) which are defined as lists of [NetworkParam](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/007a8278293efdded741831de584fcc4a1d6867e/api/v1alpha4/types.go#L57-L68) and [PortOpts](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/007a8278293efdded741831de584fcc4a1d6867e/api/v1alpha4/types.go#L123-L154) respectively.

The difference can be summarised as:

Networks:
* Networks and Subnets can be specified explicitly (which is also efficient since  #994) or by filter.
* Cannot specify port options

Ports:
* Networks and Subnets must be specified explicitly
* Possible specify a port with no subnet
* Can specify all port options

Apart from being confusing for the user, the difference is also a source of potential maintenance bugs and different ports can accidentally end up with slightly different semantics.

I think we could easily create a consolidated API which combines the flexible network selection of Networks with the ability to specify all port options of Ports.

**Comment by iamemilio** [comment]
> The other (very) minor consideration is whether network and subnet should be plural in your proposal, since the filter can match multiple networks and I expect the intention is that the behavior would be forEach like the existing networks:. Then it would be strange that network singular specifies the creation of multiple ports. Perhaps the clearest would be if the filter part were explicit, kind of like how networks is now

I think the plural would be appropriate

**Comment by macaptain** [comment]
> This can be handled like this:
> 
> ```yaml
> ports:
>   - network:
>       id: uuid
>     fixedIPs:
>       subnet:
>         networkID: uuid
> ```

The difference between that snippet and the one using the `networks:` API is that the `networks:` API will create a port per subnet. But your example will create a single port with multiple fixed IPs on different subnets.

**Comment by iamemilio** [comment]
## Summary
I want to propose this as what the new PortOpts will look like. **NOTE: Each instance of portOpt will only create one port, which is a loss of functionality from the network and subnet api.** This change adds the following functionality to PortOpts:
- The network UUID for a port can now be discovered by an OpenStack Query with a NetworkFilter
    - This query **must** only return one network
- The Subnet UUID for a fixed IP address can now be discovered by an OpenStack Query with a Subnet Filter
    - This query **must** only return one subnet
- Fields that are not useful for searching for an existing network to create a port on are removed from NetworkFilter
- Fields that are not useful for searching for an existing subnet to create a fixed IP on are removed from SubnetFilter

## API Changes

### types.go
```diff 
type PortOpts struct {
-  NetworkID string `json:"networkID,omitempty"`
+  Network NetworkFilter `json:"network,omitempty"`
  ...
  FixedIPs []FixedIP
  ...
}

type FixedIP struct {
-  SubnetID string `json:"subnetID,omitempty"`
+  Subnet SubnetFilter `json:"subnet,omitempty"`
  IPAddress string `json:"ipAddress,omitempty"`
}

- type Filter struct {
+ type NetworkFilter struct {
-	Status       string `json:"status,omitempty"`
	Name         string `json:"name,omitempty"`
	Description  string `json:"description,omitempty"`
-	AdminStateUp *bool  `json:"adminStateUp,omitempty"`
-	TenantID     string `json:"tenantId,omitempty"`
	ProjectID    string `json:"projectId,omitempty"`
-	Shared       *bool  `json:"shared,omitempty"`
	ID           string `json:"id,omitempty"`
-	Marker       string `json:"marker,omitempty"`
-	Limit        int    `json:"limit,omitempty"`
-	SortKey      string `json:"sortKey,omitempty"`
-	SortDir      string `json:"sortDir,omitempty"`
	Tags         string `json:"tags,omitempty"`
	TagsAny      string `json:"tagsAny,omitempty"`
	NotTags      string `json:"notTags,omitempty"`
	NotTagsAny   string `json:"notTagsAny,omitempty"`
}

type SubnetFilter struct {
	Name            string `json:"name,omitempty"`
	Description     string `json:"description,omitempty"`
-	EnableDHCP      *bool  `json:"enableDhcp,omitempty"`
-	NetworkID       string `json:"networkId,omitempty"`
-	TenantID        string `json:"tenantId,omitempty"`
	ProjectID       string `json:"projectId,omitempty"`
	IPVersion       int    `json:"ipVersion,omitempty"`
	GatewayIP       string `json:"gateway_ip,omitempty"`
	CIDR            string `json:"cidr,omitempty"`
	IPv6AddressMode string `json:"ipv6AddressMode,omitempty"`
	IPv6RAMode      string `json:"ipv6RaMode,omitempty"`
	ID              string `json:"id,omitempty"`
-	SubnetPoolID    string `json:"subnetpoolId,omitempty"`
-	Limit           int    `json:"limit,omitempty"`
-	Marker          string `json:"marker,omitempty"`
-	SortKey         string `json:"sortKey,omitempty"`
-	SortDir         string `json:"sortDir,omitempty"`
	Tags            string `json:"tags,omitempty"`
	TagsAny         string `json:"tagsAny,omitempty"`
	NotTags         string `json:"notTags,omitempty"`
	NotTagsAny      string `json:"notTagsAny,omitempty"`
}
```

### openstackmachine_types.go
```diff
type OpenStackMachineSpec struct {
...
-	// A networks object. Required parameter when there are multiple networks defined for the tenant.
-	// When you do not specify both networks and ports parameters, the server attaches to the only network created for the current tenant.
-	Networks []NetworkParam `json:"networks,omitempty"`

	// Ports to be attached to the server instance. They are created if a port with the given name does not already exist.
	// When you do not specify both networks and ports parameters, the server attaches to the only network created for the current tenant.
	Ports []PortOpts `json:"ports,omitempty"`

-	// UUID, IP address of a port from this subnet will be marked as AccessIPv4 on the created compute instance
-	Subnet string `json:"subnet,omitempty"`
}
```

## Example Use Cases
Here are some examples of how I am envisioning what machinesets will look like when this api replaces and depricated the networks and subnets api.

### Basic Machine Spec

```yaml
cloudName: kube
flavor: large
image: container-linux-image
ports:
  - network:
      name: cluster-network
      tags:
         - devel
         - test
securityGroups:
  - name: worker-security-group
```

### Multiple Specialized Networks: Installation on provider networks with SRIOV networking acceleration

```yaml
cloudName: kube
flavor: large
image: container-linux-image
ports:
  - network:
      name: provider-net-kube'
      projectID: <uuid>'
    fixedIPs:
      - subnet:
          name: kube-cluster-f00
    securityGroups:
      - name: worker-security-group
  - network:
      name: kube-sriov-net
      tags:
        - sriov
    fixedIPs:
      - subnet:
           cidr: 152.99.2.0/16
           name: subnet-bar
        ipAddress: 152.99.2.10
    disablePortSecurity: true
    vnicType: direct
    trunk: false
```

**Comment by mdbooth** [comment]
The above omits a critical piece of historical context: @iamemilio is personally responsible for creating the Networks API! The purpose was never to allow multiple networks/subnets to be specified. The list API was used to enable networks and subnets to be specified by name instead of ID in OpenShift. The ability to theoretically specify multiple networks/subnets this way was accidental complexity, and we're not aware of anybody actually doing this.

If it turns out anybody actually is using it this way it could be added back in, but:
* I very much doubt anybody is
* With a real use case to reference we could design a better API
