### ISSUE TITLE
cluster-api v1beta1 adoption ?

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#1024]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

I heard cluster-api v1beta1 is going to be out soon ... should we start to consider the adoption 
and corresponding v1beta1 version of CAPO as well?

update:
https://kubernetes.io/blog/2021/10/08/capi-clusterclass-and-managed-topologies/ might be something
related as well, need further anaylsis
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by pfisterer** [comment]
I guess that would be very good. I failed to try cluster-api the first time today because the released version v1.0.0 fails with an error when using cluster-api-provider-openstack. Just for your reference, this is the corresponding (closed) issue: https://github.com/kubernetes-sigs/cluster-api/issues/5425

**Comment by mkjpryor** [comment]
The v1beta1 versions of the Cluster API core resources won’t adopt v1alpha4 resources from infrastructure providers. So this needs sorting one way or another, either by this provider moving to v1beta1 or by Cluster API core resources not expecting infrastructure resources to match their version.

**Comment by jichenjc** [comment]
from this https://github.com/kubernetes-sigs/cluster-api/issues/5425#issuecomment-943150790
seems yes, we need v1.0.x implementation for cluster-api now

>>>The current situation means we can’t upgrade the core Cluster API components to benefit from changes there.

I don't fully understand this ... are you suggesting that even upgrade to v1beta1, CAPO still can't work with cluster-api 1.0.x ?

**Comment by mkjpryor** [comment]
@sbueringer I didn’t expect you personally to answer it! It definitely needs to be a community discussion.

What I am saying is that the discussion needs to happen ASAP. I don’t think we want to be lagging too far behind and, in my experience so far, the provider is pretty reliable. If we just need to freeze the API and say this is v1beta1 then we do need to have a discussion about anything else that we want in the API to be able to do that. 

We already have customers now saying “Cluster API is production ready - can we use it?” and we still have to say “well actually the OpenStack provider is still in alpha”, which they are less happy with.

**Comment by mdbooth** [comment]
Incidentally, a volume snapshot in this case would be used very much the same way as a glance image: it would just be stored in Cinder instead of Glance. However, I'm not aware of anybody using it this way. CoreOS specifically isn't designed to be used this way at all. I'm very happy not to maintain 'accidental' support for it, although I'd be happy to add it deliberately if somebody came to us with a use case.

I suspect that the only reason the API looks like this is that the implementation naively followed the Nova block device mapping API.

**Comment by jichenjc** [comment]
>>>I suspect that the only reason the API looks like this is that the implementation naively followed the Nova block device mapping API.

I guess so and I agree with your suggestions above, thanks :)

**Comment by hidekazuna** [comment]
I am going to create v1alpha5 API with CAPI v1beta1(#1033). But now I am thinking that without creating new API version, only create v0.5.0 with CAPI v1beta1 is better option. We actively changing API now and our issue is that we need release with CAPI v1beta1. If we agree that release v0.5.0 only updating CAPI v1beta1, we will create release-0.4 branch, and create v0.5.0 release in the next week as much as possible.

**Comment by jichenjc** [comment]
So the question here is how to sync the changes from r-04 to 0.5 we will create soon
need some criteria on this? e.g some changes will be forward-port to 0.5 after it's settle down at r-0.4?

**Comment by hidekazuna** [comment]
If API version is the same, no reason to stay release-0.4, right?

**Comment by hidekazuna** [comment]
After all, I will do the followings:

| Version | Branch name | CAPO API version | CAPI API version | 
| -------- | -------------- | -------------------- | ------------------ | 
| 0.4.0     | release-0.4    | v1alpha4                | v1alpha4            |
| 0.5.0   | release-0.5      | v1alpha4                | v1beta1             | 
| -         | main                | v1beta1                 | v1beta1             | 

Steps:

1. Create release-0.4 branch
1. Merge #1041
1. Create release-0.5 branch
1. Release 0.5.0 from release-0.5 branch
1. Merge #1047

I will start from 18th 00:00 UTC.

**Comment by jichenjc** [comment]
the approach sounds good, thanks :)

**Comment by jichenjc** [comment]
@hidekazuna given the great PR you made, I think we are ok to close this?

**Comment by hidekazuna** [comment]
@jichenjc Yes, let7s close this PR.
