### ISSUE TITLE
Remove ensure kind binary script from repository

### ISSUE THREAD

**Issue by tobiasgiese** [kubernetes-sigs/cluster-api-provider-openstack#1035]
/kind feature

**Describe the solution you'd like**
~~We should update kind to [v0.11.1](https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1) to have at least Kubernetes v1.21.1 while we're initially deploying CAPI/CAPOCAPI to the kind cluster.~~

We're able to remove the [ensure-kind.sh](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/hack/ensure-kind.sh) script from our repository as this is obsolete. We're not using this binary anymore.

**Anything else you would like to add:**

/assign

**Comment by tobiasgiese** [comment]
If I see this right, we're not using the `kind` binary of the ensure script anymore.
If so, I suggest to rename the issue to sth like `Remove kind binary from ensure script`.

**Comment by jichenjc** [comment]
I knew our e2e use `kind` directly through CAPI repo and I think it's a reasonable change to bump kind and k8s

**Comment by tobiasgiese** [comment]
The CAPI test framework imports kind as go dependency.
I just removed the `ensure-kind.sh` script in the linked PR. If the tests are green, we don't need the binary anymore 🙂
