### ISSUE TITLE
Bastion host is immutable on 0.5.0 while it wasnt on 0.4.0

### ISSUE THREAD

**Issue by nikParasyr** [kubernetes-sigs/cluster-api-provider-openstack#1054]
/kind bug

On a `OpenStackCluster` I ussualy config the bastion specs and set `enable` to `false`. I toggle the enable flag during troubleshooting or checking various components on the nodes. And i disable it again. This is rather useful to not waste capacity when its not required and also not have a backdoor to the nodes when its not required either. 

**What steps did you take and what happened:**
- upgrade to CAPO `0.5.0` and rest of the components to `1.0.1`
- toggle the bastion enable flag to `true`
- error as it is immutable

**What did you expect to happen:**
- create the bastion host as this was possible on 0.4.0

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): `0.5.0`
- Cluster-API version: `1.0.1`
- OpenStack version: `Stein`
- Kubernetes version (use `kubectl version`): many, shouldnt affect it
- OS (e.g. from `/etc/os-release`): ubuntu20.04, shouldnt affect it either

**Comment by hidekazuna** [comment]
@nikParasyr Thank you for raising an issue. I agree the flag is useful for debugging purpose.

**Comment by tobiasgiese** [comment]
I'll take a look at it
/assign

One question @nikParasyr and @hidekazuna.
Should we allow the change of `OpenStackCluserTemplate.Spec.Bastion` at all, or just for the `enabled` flag? At least CAPA isn't allowing any change on the `AWSClusterTemplate.Spec`

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/3e61428d885f2eaeab1a7dffc4d17270a20c6675/api/v1beta1/awsclustertemplate_webhook.go#L56-L64

**Comment by tobiasgiese** [comment]
I just created a PR.
We should discuss whether we want to allow changes to `OpenStackCluserTemplate.Spec.Bastion` or not.

**Comment by nikParasyr** [comment]
> Another question is, if we should allow changes to OpenStackCluserTemplate.Spec.Bastion. 
> We should discuss whether we want to allow changes to OpenStackCluserTemplate.Spec.Bastion or not.

I'd say the`enabled` flag is the most important. That being said, i can also see a user-case for long-running clusters where there might be a need to change flavor/image/image_uuid(if boot from volume) as well after some years of the cluster running.

> At least CAPA isn't allowing any changes to the AWSClusterTemplate.Spec.

I dont think i can properly evaluate this and it's consequences tbh as i just recently started using cluster-api. From a user perspective I can see that there are some fields that it would be nice if they could be updated, e.g `Tags` as mentioned [here](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1044#issuecomment-968750104)

**Comment by tobiasgiese** [comment]
I updated the PR that changes to the complete `OpenStackCluster.Spec.Bastion` is possible.
Also I removed the allow changes to the `OpenStackClusterTemplate.Spec` at all. No other infrastructure provider (i.e., [vsphere](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/apis/v1beta1/vsphereclustertemplate_webhook.go#L43-L50), [aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/3e61428d885f2eaeab1a7dffc4d17270a20c6675/api/v1beta1/awsclustertemplate_webhook.go#L56-L64), [docker](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/infrastructure/docker/api/v1beta1/dockerclustertemplate_webhook.go#L70-L84)) is allowing these changes. Thus, I would suggest to keep it aligned. Further, the `InfrastructureClusterTemplate` is part of [`ClusterClass`](https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-classes.html) ([here is the proposal of `ClusterClass`](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/202105256-cluster-class-and-managed-topologies.md)).

**Comment by tobiasgiese** [comment]
After we have a consensus regarding PR #1070 I'll create two further cherry-pick PRs for the release branches `release-0.4` and `release-0.5`

**Comment by nikParasyr** [comment]
> Maybe there was a misunderstanding between `OpenStackTemplate` (the wording of your issue description) and `OpenStackClusterTemplate`?

You are right on this one. I meant `OpenStackCluster` and not template => thus it is not related to the ClusterClass stuff.
Ill update the description to avoid other misunderstandings

**Comment by hidekazuna** [comment]
@tobiasgiese Thanks taking this issue. Yes, following other providers is good manner, since I implemented bastion watching CAPA and mainly CAPA and CAPZ are our upstream somehow.

**Comment by tobiasgiese** [comment]
/reopen
Just to track the cherry-picks. I‘ll create them soon.

**Comment by tobiasgiese** [comment]
Everything is merged
/close
