### ISSUE TITLE
ArgoCD custom health checks

### ISSUE THREAD

**Issue by MPV** [kubernetes-sigs/cluster-api-provider-openstack#1064]
/kind feature

**Describe the solution you'd like**
ArgoCD Custom Health Checks for CAPO.

**Anything else you would like to add:**

Anyone else using ArgoCD together with CAPO?

Would you be up for collaborating on creating some "Custom Health Checks" for CAPO in ArgoCD?

Here's what they are, and how they can be contributed:
https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#custom-health-checks

Examples of how it can look (from when [ChaosKube added theirs](https://medium.com/matsiremark/custom-health-checks-with-argocd-b49a45ab4d0c)):

![1_0--DGfZ5dEe2ZcVF6E7HaQ](https://user-images.githubusercontent.com/62675/143548193-391dc71a-2b42-4062-a307-7c80fe9fb139.png)

![1_LKvNZ0Wp0yx-fJHucaxE5Q](https://user-images.githubusercontent.com/62675/143548421-c4e4ba3a-c22d-4bef-81c2-52c66ea61954.png)

There's already health checks [contributed for CAPI](https://github.com/argoproj/argo-cd/pull/5142) which we can get inspired by: 🎉 
https://github.com/argoproj/argo-cd/tree/master/resource_customizations/cluster.x-k8s.io
(and it's the same folder in which we would place CAPO's health checks)

**Comment by hidekazuna** [comment]
@MPV I checked the URL you mentioned. It seems that this feature would be archived by contributing to  argo-cd repository.

**Comment by MPV** [comment]
@hidekazuna You're absolutely right. But that repository doesn't contain the community and expertise of CAPO as this repo does, hence why I thought I'd discuss this here.

I'd be open to talking about how to suitably map CAPO's resources' status values into ArgoCD's statuses of; `Healthy`, `Progressing`, and `Degraded`.

**Comment by hidekazuna** [comment]
@MPV I do not use ArgoCD much, but OK to discuss here :)

**Comment by jichenjc** [comment]
I am using ArgoCD time to time, so will check more on the things you provided and let's have more talk later on , and if I understand correctly, the goal is 
`I'd be open to talking about how to suitably map CAPO's resources' status values into ArgoCD's statuses of; Healthy, Progressing, and Degraded.` ,correct?

**Comment by MPV** [comment]
> If I understand correctly, the goal is:
> 
>> `I'd be open to talking about how to suitably map CAPO's resources' status values into ArgoCD's statuses of; Healthy, Progressing, and Degraded.`

Indeed. 👍

**Comment by jichenjc** [comment]
ok, I went through the issue you posted above, I think we can follow the stuffs here
e.g we check openstackcluster and openstackmachine just like they did here
https://github.com/argoproj/argo-cd/blob/master/resource_customizations/cluster.x-k8s.io/Cluster/health.lua#L6

e.g openstackcluster is ready or openstackmachine is ACTIVE
guess that's not that hard (need some spec here) by referring to that status

Also, I would think it's a interesting topic to cluster-api itself as I didn't see any other providers 
have healthy check there, maybe align with them?
