### ISSUE TITLE
IdentityRef is not preserved converting between v1alpha4 and v1beta1

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1065]
/kind bug

Discovered by unit testing. IdentityRef annotated with `+k8s:conversion-gen=false`, possibly because it was new in v1alpha4 and we wanted to ignore it when converting from v1alpha3. However, we don't want to ignore it when converting to v1beta1, but it is still ignored.

**Comment by tobiasgiese** [comment]
I added the annotation in #937 because of the conversion from `v1alpha3` to `v1alpha4`, that's true.
But indeed we don't want to ignore the conversion to `v1beta1` 👍🏻
