### ISSUE TITLE
Missing namespace for load balancers

### ISSUE THREAD

**Issue by garloff** [kubernetes-sigs/cluster-api-provider-openstack#1071]
/kind bug

Deployed capi and capo in a kind cluster on a VM in OpenStack.
(See https://github.com/SovereignCloudStack/k8s-cluster-api-provider if you are interested in details or want to use the code for reproduction.)

Created two clusters with different names. 

Networks and Servers have names which include the cluster name, thus no naming conflicts.
Same is true for loadbalancers that are created in front of the kubernetes control nodes.

BUT: The load balancers created from the ingress controllers do NOT include the cluster name (nor do they append a random suffix), thus two clusters that use the same ingress controller inside the same namespace will create a conflict as OpenStack does not allow two loadbalancers with the same name inside the same project (tenant).

This should not happen! Either we have have consistent namespaces that avoid conflicts or we need (long enough) random suffices that ensure we avoid conflicts. As no two clusters inside the same project should have the same name, using the cluster name as prefix to separate things  

So we can not run two similar development environments from two clusters inside the same tenant.
Let alone clusters from non-cooperating teams ...

**Environment:**

- Cluster API Provider OpenStack version 0.5.0
- Cluster-API version: 1.0.1
- OpenStack version: Wallaby
- Minikube/KIND version: KIND 0.11.1
- Kubernetes version (use `kubectl version`): 1.19.16
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3

**Comment by tobiasgiese** [comment]
> BUT: The load balancers created from the ingress controllers do NOT include the cluster name (nor do they append a random suffix), thus two clusters that use the same ingress controller inside the same namespace will create a conflict as OpenStack does not allow two loadbalancers with the same name inside the same project (tenant).

@garloff To understand this correct: you have a (I can see a nginx) ingress-controller deployed in your kind cluster? And both clusters are using this ingress-controller?
If yes, you should configure nginx to have a proper prefix/suffix for each cluster. But in this case it's rather not CAPO related.
Just want to make things clear to understand the issue completely 🙂

**Comment by tobiasgiese** [comment]
> BUT: The load balancers created from the ingress controllers do NOT include the cluster name (nor do they append a random suffix), thus two clusters that use the same ingress controller inside the same namespace will create a conflict as OpenStack does not allow two loadbalancers with the same name inside the same project (tenant).

@garloff To understand this correct: you have a (I can see a nginx) ingress-controller deployed in your kind cluster? And both clusters are using this ingress-controller?
And you have deployed a single OpenStack Cloud Controller Manager (OCCM) in this cluster, to deployed load balancers for both clusters?
If yes, you should configure OCCM to have a proper prefix/suffix for each cluster. But in this case it's rather not CAPO related.
Just want to make things clear to understand the issue completely 🙂

**Comment by tobiasgiese** [comment]
And keep in mind: CAPO does only create the load balancers for the kube-apiserver. The creation of load balancers for Kubernetes Services of type `LoadBalancer` is **not** done by CAPO itself.

**Comment by garloff** [comment]
@tobiasgiese The created clusters indeed have an openstack-cloud-controller-manager deployed inside.(They also have csi-cinder-controllerplugin as you would expect ...)
If I understand you correctly, the loadbalancer creation by creating ingress controllers is not channeled through CAPO, thus any namespace prefix should be handled by the OCCM?
Looking at the deployment config at https://github.com/kubernetes/cloud-provider-openstack/raw/master/manifests/controller-manager/ , I don't see how I could influence it by tweaking the yamls, unfortunately.
Do we need to move this issue over to OCCM?
PS: CAPO does the loadbalancers for the kube-apiserver with a clustername included, so we're clean there.

**Comment by seanschneeweiss** [comment]
@garloff The name for the load balancer created from the OCCM is defined here for services:
https://github.com/kubernetes/cloud-provider-openstack/blob/9a9976f0e618a634c01198651cba01af107568f6/pkg/openstack/loadbalancer.go#L698

For ingress: https://github.com/kubernetes/cloud-provider-openstack/blob/9a9976f0e618a634c01198651cba01af107568f6/pkg/ingress/utils/utils.go#L37

This includes a service prefix from the const ("kube_service_") or ingress prefix ("kube_ingress_"), the [cluster name](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) (default: kubernetes), and the service's/ingress's namespace and name.

**Comment by seanschneeweiss** [comment]
From [kube-controller-manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/):
> `--cluster-name string`     Default: "kubernetes"  
The instance prefix for the cluster.

**Comment by tobiasgiese** [comment]
I think we can close this issue then. Is it okay for you @garloff? Just type `/close` to close the issue

**Comment by garloff** [comment]
I still need to figure out how to tweak the manifests to set the cluster-name to something else from "kubernetes".
But yes, it's for sure not a capo bug.
Thanks for your insight!
/close

**Comment by seanschneeweiss** [comment]
Probably you can edit your Kubeadm configuration (`--config` option) to include the following:
```
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
clusterName: "example-cluster"
```

See 
https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/#kubeadm-k8s-io-v1beta3-ClusterConfiguration

**Comment by garloff** [comment]
When kubeadm bootstraps the control node, it already uses
``apiServer:                                                                                                                              
  extraArgs:
    cloud-provider: external
apiVersion: kubeadm.k8s.io/v1beta2 
clusterName: ANAME
controlPlaneEndpoint: A.B.C.D:6443
controllerManager:
[...]``
The worker nodes only have a `JoinConfiguration`
The clusterName from there is not propagated into OCCM when it creates LoadBalancers.

**Comment by garloff** [comment]
Found it:
```
apiVersion: apps/v1
kind: DaemonSet
spec:
  template:
    spec:
      containers:
        - name: openstack-cloud-controller-manager
          image: docker.io/k8scloudprovider/openstack-cloud-controller-manager:latest
          args:
            - /bin/openstack-cloud-controller-manager
            - --v=1
            - --cloud-config=$(CLOUD_CONFIG)
            - --cloud-provider=openstack
            - --use-service-account-credentials=true
            - --bind-address=127.0.0.1
            - --cluster-name=ANAME
```
The template at
https://github.com/kubernetes/cloud-provider-openstack/raw/master/manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml does unfortunately not contain this --cluster-name parameter, so it was not as obvious to me as it could have been ...
