### ISSUE TITLE
Proposals for new maintainers and reviewers

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1078]
As we've got a fair bit going on at the moment, I wonder if we should consider adding to the reviewer pool. Purely to start the discussion, how would we feel about the following additions?

### Maintainer

* @chrischdi 
* @seanschneeweiss

### Reviewer

* @mdbooth 
* @tobiasgiese 
* @macaptain 
* @iamemilio 

This is a straw man from the top of my head! My apologies if I missed anybody obvious 😬

/cc @jichenjc @hidekazuna

**Comment by hidekazuna** [comment]
I agree we need more maintainer who can add /approve.

/cc @chrischdi @seanschneeweiss

**Comment by chrischdi** [comment]
I'd also be happy to help :-) I also plan to get more time to do upstream work for next yer :+1:

**Comment by macaptain** [comment]
I also +1 @mdbooth as maintainer given the amount and quality of activity on the project over the last year.

For my part, I'd be happy to take on doing more reviews more regularly in CAPO as a reviewer.

**Comment by hidekazuna** [comment]
+1 for @tobiasgiese  and @mdbooth
 
@tobiasgiese worked on issues like Provide documentation website (like CAPA/CAPZ)(#783), and  Change default branch to "main"(#855) as practical maintainer. 
@mdbooth contributes many functionalities with high quality.

**Comment by tobiasgiese** [comment]
> @tobiasgiese worked on issues like Provide documentation website (like CAPA/CAPZ)(#783), and Change default branch to "main"(#855) as practical maintainer.

Just to clarify, I also worked on coding issues except for documentation and branch renaming 😅 ([xref](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pulls?q=is%3Apr+author%3Atobiasgiese))

**Comment by mdbooth** [comment]
I would also be happy to help out as a maintainer, although I will say that there are changes that I wouldn't yet feel confident to approve myself. It's good to have a broad team!

**Comment by tobiasgiese** [comment]
> And thanks for the suggestion

And I'm also happy to help as a maintainer, for sure! I forgot to mention that 😃
