### ISSUE TITLE
Leak trunks and ports on failure before server create

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1085]
/kind bug

**What steps did you take and what happened:**
This is from code inspection only.

If CreateInstance fails after creating ports but before creating a server and we will delete all created port. However, if we created any trunk ports for those ports we will not attempt to delete the trunk. This means we leak the trunks, but this will also cause the port cleanup to fail when we try to delete the first port with an existing trunk port.

**Comment by jichenjc** [comment]
/assign

let me see what I can do

**Comment by jichenjc** [comment]
so I think you are saying something between 

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/compute/instance.go#L217

and 

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/compute/instance.go#L247



but a quick look like we will delete trunk anyhow? 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/compute/instance.go

**Comment by mdbooth** [comment]
Here's another bug: if we've specified trunking on a port that already exists, we don't create the trunk.

I think I'm starting to see a systematic pattern of edge cases here, btw. I wonder if we should include all created cloud resources in the status object explicitly. Something like:

```
type UUID string

type PortStatus {
    UUID: UUID
    Trunk: UUID (may be empty)
}

OpenStackMachineStatus {
  ...
  Resources: {
    Ports: []PortStatus
    RootVolume: UUID
    Server: UUID
  }
}
```

This idea is still half-baked, but I think there are advantages to it both for robustness of cleanup, and also for robustness of creation.

For example, we have an open bug right now against CCM because the controller serialises the creation of load balancers, which can be very slow depending on the backend. This means that if you have a rapid scale-out of loadbalancers it will take a really long time. We currently have a similar problem with machine creation: both root volume and server creation can take a very long time, but they can also both be effectively parallelised by the cloud, so there's no reason you couldn't do many concurrently.

To do this we'd have to refactor CreateInstance to allow the controller to 'poll' on server/volume creation instead of doing it synchronously. To facilitate that we'd almost certainly want to persist the creation of cloud resource we're polling on. The server creation Reconcile would become something like:

```
portsReady := reconcilePorts()
rootVolumeReady := reconcileRootVolume()

if !(portsReady && rootVolumeReady) {
  return 10 second backoff
}

reconcileServer()
```

Each individual reconciliation persists any resources it has created to the status object, and never cleans anything up on failure. Then the *only* way cleanup happens is in DeleteInstance(), which deletes all resources on the status object.

**Comment by mdbooth** [comment]
@jichenjc I just submitted a PR containing a failing unit test which demonstrates the leak: #1087

**Comment by jichenjc** [comment]
>>>Each individual reconciliation persists any resources it has created to the status object, and never cleans anything up on failure. Then the only way cleanup happens is in DeleteInstance(), which deletes all resources on the status object.

I like the idea and I guess we need some WIP and see how it really helpful e.g from performance and robustness perspective, and maybe need collect more input from folks

>>> I just submitted a PR containing a failing unit test which demonstrates the leak: #1087

sure, thanks and will check soon
