### ISSUE TITLE
Migrate CI from Victoria to Xena

### ISSUE THREAD

**Issue by stephenfin** [kubernetes-sigs/cluster-api-provider-openstack#1092]
/kind feature

**Describe the solution you'd like**
The CI is currently using Victoria. This was released in October 2020 and has been superseded by Wallaby and Xena. We should migrate out CI to Xena.

**Anything else you would like to add:**
This can and should be done in two steps (Victoria -> Wallaby, Wallaby -> Xena) to avoid crazy-complex PRs.

**Comment by jichenjc** [comment]
maybe we should consider some doc or dev guide to remind us for each openstack release
we need some kind of concurrency ..

**Comment by tobiasgiese** [comment]
/reopen
because of #1098

**Comment by apricote** [comment]
##1158 switched to Xena.

/close
