### ISSUE TITLE
A better way to sync with other community?

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#1093]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

inspired by #1092 
we need update according to cluster-api, openstack from various places
not sure whether other community has such kind of sync mechanism ? 
as from process is much better than randomly check...

so hope to get some ideas from folks..

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by lentzi90** [comment]
For [Metal³](https://github.com/metal3-io) and CAPM3 we use [Renovate](https://github.com/renovatebot/renovate) for some automated dependency management. It can create PRs for bumping versions when there are new releases available. Maybe it could be useful for CAPO also?

**Comment by apricote** [comment]
We plan to discuss this issue during the next office hours, 2022-04-23.

**Comment by jichenjc** [comment]
>>>is this something you were thinking of working on?

I can't commit either :( as I am actually part time work on those stuffs and has own job
maybe we can cooperate together in finding a better way e.g several people work together ? 

I agree with all the above comments about the approach on bump and Renovate/Dependabot usage, thanks
