### ISSUE TITLE
Missing input for argument [Address]

### ISSUE THREAD

**Issue by ayetkin** [kubernetes-sigs/cluster-api-provider-openstack#1096]
/kind bug

**What steps did you take and what happened:**
Capo getting an error while creating loadbalancer member pool only if we use network filters with the v0.5 release. 

`E1217 20:44:00.999125       1 openstackmachine_controller.go:408] controller/openstackmachine "msg"="LoadBalancerMember cannot be reconciled: error create lbmember: Missing input for argument [Address]" "error"="UpdateError" "cluster"="capi-test" "machine"="capi-test-control-plane-z5cnt" "name"="capi-test-control-plane-h6wln" "namespace"="default" "openStackCluster"="capi-test" "openStackMachine"="capi-test-control-plane-h6wln" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"`

I take a look loadbalancer.go and openstackmachine_controller.go so i saw _reconcileLoadBalancerMember_
function getting (ip) adress from _openStackCluster.Status.Network.Name spec._ when i describe my openstackcluster i saw wrong network neme in status spec.
```
...
Status:
  Network:
    API Server Load Balancer:
      Id: b062f64e-2ceb-4a6a-a898-7c5546800949
      Internal IP: 10.200.1.177
      Ip: 10.208.255.234
      Name: k8s-clusterapi-cluster-default-capi-test-kubeapi
    Id: c28cca1b-2b1b-4ba1-ad95-ce3bbff2a26c
    Name: k8s-clusterapi-cluster-default-capi-test
...
```
i already added network name (devops-other-net) in OpenStackCluster but i saw openstackClusterStatus has wrong network name. (k8s-clusterapi-cluster-default-capi-test)
maybe that’s why i’m getting error while reconciling lb members.

**Environment:**

- Cluster API Provider OpenStack version: v0.5.0
- Cluster-API version: v1.0.2
- OpenStack version: Victoria
- KIND version: v0.11.1
- Kubernetes version: v1.21.1
- OS (e.g. from `/etc/os-release`): MacOs

**Comment by jichenjc** [comment]
@ayetkin hi, thanks for the bug report, could you please paste the cluster yaml file as reference? 

generally, it dpends on `openStackCluster.Spec.NodeCIDR ` 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/controllers/openstackcluster_controller.go#L380

so if you set this value, it will create a new network for you or it will find the one (should be only one) for you , in your case looks like the network got created but I am curious why you are having that error above given the network already correctly created

**Comment by ayetkin** [comment]
@jichenjc When i deleted `openStackCluster.Spec.NodeCIDR`, loadbalancer was successfully configured. Everything looks healthy. Thank you so much!

**Comment by jichenjc** [comment]
ok, glad it helps , will close this given the problem solved
