### ISSUE TITLE
DOC:https://cluster-api.sigs.k8s.io/user/quick-start.html face OPENSTACK_EXTERNAL_NETWORK_ID issue

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#1099]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```
clusterctl generate cluster capi-quickstart --kubernetes-version v1.23.0 --control-plane-machine-count=1 --worker-machine-count=1   > capi-quickstart1.yaml
Error: value for variables [OPENSTACK_EXTERNAL_NETWORK_ID] is not set. Please set the value using os environment variables or the clusterctl config file

```

tracking update in cluster-api 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by seanschneeweiss** [comment]
I guess this can be closed, as the CAPI PR was merged.

**Comment by jichenjc** [comment]
right :)
