### ISSUE TITLE
✨ More config options for APIServer Loadbalancer (AvailabilityZone, Flavor, ...)

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#1105]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

CPO has many LB related features
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md#supported-features

this will be used in service create through `kubectl create svc`
but our LB for masters doesn't take those into considreations

something like `loadbalancer.openstack.org/availability-zone` etc might be helpful for CAPO.. 
let's use this issue to track..

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mdbooth** [comment]
Can you give a worked example of how we'd use the annotation?

**Comment by mdbooth** [comment]
@apricote was also interested in this.

**Comment by apricote** [comment]
@jichenjc Is there a reason why you want to use annotations to expose these configuration values?

I would suggest to put these into the `OpenStackCluster` CRD instead:

```go
type OpenStackClusterSpec struct {
	// ... existing fields
   
	// Configure a managed loadbalancer for the API Server
	APIServerLoadBalancer Loadbalancer `json:"apiServerLoadBalancer,omitempty"`
}

type Loadbalancer struct {
	// Enabled replaces the current `OpenStackClusterSpec.ManagedAPIServerLoadBalancer`
	Enabled bool `json:"enabled,omitempty"`
	// AdditionalPorts replaces the current `OpenStackClusterSpec.APIServerLoadBalancerAdditionalPorts`
	AdditionalPorts []int `json:"additionalPorts,omitempty"`

	// New Options
	FlavorID         string `json:"flavorID,omitempty"`
	AvailabilityZone string `json:"availabilityZone,omitempty"`
}

**Comment by jichenjc** [comment]
@apricote I am ok if you go with `Spec` :) ,doesn't matter if it's annotation or spec
just make it more flexible and fit for requirement is good enough ~

**Comment by apricote** [comment]
Alright, I will present this during tomorrows office hours and get an approval for the CRD changes :+1:

**Comment by apricote** [comment]
No objections to the general plan during office hours.

I am going to create PRs for this.

/retitle ✨ More config options for APIServer Loadbalancer (AvailabilityZone, Flavor, ...)

**Comment by apricote** [comment]
The spec has been refactored to allow for more options. Please create new issues for any specific features that should be added.

/close
