### ISSUE TITLE
Change warning to Error for failing calls

### ISSUE THREAD

**Issue by Xenwar** [kubernetes-sigs/cluster-api-provider-openstack#1121]
Currently, there are entries that log warning for something that fails. 
Example:

```
record.Warnf(eventObject, "FailedCreatePort", "Failed to create port %s
record.Warnf(eventObject, "FailedCreateServer", "Failed to create server %s
record.Warnf(eventObject, "FailedCreateTrunk", "Failed to create trunk %s
record.Warnf(eventObject, "FailedDeleteAttachInterface", "Failed to delete attach interface
record.Warnf(eventObject, "FailedDeletePort", "Failed to delete port %s with id %s
record.Warnf(openStackCluster, "FailedDeleteFloatingIP", "Failed to delete floating IP %s
record.Warnf(openStackCluster, "FailedDeleteLoadBalancer", "Failed to delete load balancer %s with id %s
record.Warnf(openStackCluster, "FailedDeleteNetwork", "Failed to delete network %s with id %s
record.Warnf(openStackCluster, "FailedDeleteRouter", "Failed to delete router %s with id %s
record.Warnf(openStackCluster, "FailedDeleteSecurityGroup", "Failed to delete security group %s with id %s
record.Warnf(openStackCluster, "FailedUpdateRouter", "Failed to update router %s with id %s
```

To Do:
Collect such entries and make appropriate changes. 
As shown here https://github.com/kubernetes/api/blob/bfe324c0d64befbab416bd4063c0a38a6cda9334/core/v1/types.go#L5650-L5655, there is Event type for Error. So, it needs to be introduced in `pkg/record/recorder.go `

/kind bug

**Comment by jichenjc** [comment]
@Xenwar thanks for the issue

I am curious why the recorder.go itself doesn't have Error and let us add it ..
so if we update to that repo first then we consume it might be a reasonable way?

**Comment by macaptain** [comment]
In the link above for Event types (https://github.com/kubernetes/api/blob/bfe324c0d64befbab416bd4063c0a38a6cda9334/core/v1/types.go#L5650-L5655), I only see `EventTypeNormal` and `EventTypeWarning`? It seems like these are the event severity types we're limited to. The current record.go is consistent with other providers / CAPI itself for these types (c. f. https://github.com/kubernetes-sigs/cluster-api/blob/58905fb5140a7844c3e24aa70d255fb8f9d0c491/util/record/recorder.go)

I will say that there are 'events' in the CAPO codebase which are better expressed as log messages. For example:

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/19889578bf84e92d972ad17ad413c1b243e3eef1/pkg/cloud/services/compute/instance.go#L746

An event should refer to a change of state ('normal'), or an attempted change of state that went wrong ('warning'). I think `record.Warnf` for failures is fine. It would be worth making sure that when we do that, then something is logged to the controller logs.

**Comment by mdbooth** [comment]
@macaptain Events are a nice way to communicate actionable things to users, though, as opposed to log messages which are just for admins.

Take that DuplicateServerNames event, for eg. (I think I wrote that, so I feel safe criticising it 😂)  That's user-actionable, because the resolution for that has to come from the user: we are never going to automatically clean up resources we don't know about. However, I wonder if it should be an error instead of a warning, and what would that mean?

Lets say that we don't want to continue reconciliation of this Machine while this condition exists, and we want to communicate that to the user. In fact, for this one specifically we likely won't even delete the machine without user intervention. Should this be an error condition on the Machine instead of an Event?

**Comment by mdbooth** [comment]
> That's true, I hadn't thought about how to communicate warnings that the user needs to action. What I said above about events is a bit purist. Maybe in this example, we decide to fail right there instead of guessing that there will be problems later? Fail fast is usually a good principle. But I'm all for keeping events that are helpful for users.

I think we'd want to fail *and communicate the reason why to the user*. It's step 2 I'm not clear on. My suggestion was a Condition, but I'd want to check what the user experience is for that. I think this is one of the things they're for, though?

**Comment by mgrote** [comment]
There is a blog post, which discuss should we log an error or not:
https://dave.cheney.net/2015/11/05/lets-talk-about-logging

**Comment by mdbooth** [comment]
@Xenwar Thanks for starting this discussion!

I enjoyed reading the insightful blog post linked above by @mgrote, btw. It got me thinking explicitly about the audience and actionable information. The author suggests there are only 2 interesting log levels:

* Debug - information for developers
* Info - information for users

and that unhandleable errors should be trapped at the top level. In the blog post that causes a program to exit, but that's clearly not appropriate behaviour for a controller. In fact I think this dovetails nicely with https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1116. I think these unhandleable errors should drop into our 'failed state' handling.

I also don't fully agree with the idea that there's only one category of information that the user is interested in, which I think is where @Xenwar was originally coming from. There are 2 reasons I personally typically go looking in Events:

* Is it proceeding?
* Why did it go wrong?

To answer the first question you absolutely want to see a nice reassuring list of 'SuccessfulCreateSubnet' messages, or whatever. But for the second question these are a distraction.

So I propose we have 3 levels of 'log':

* Only of interest to developers: these go to the log
* User-interesting activity information: these are Events at info level
* User-interesting failure information: these are Events at warn level

And a quick grep of the codebase suggests we're not far off that now. Grepping for `record.Warnf` shows only `Failed...` messages and `DuplicateServerNames` which should debatably be in the same category. Grepping for `record.Eventf` shows only `Successful...` messages and `FailedCreateVolume`, which looks like a bug (which muppet wrote that 🙄).

@Xenwar, if we're already differentiating all the events you wanted to call 'Error', does it matter that we're calling them `Warn`?

**Comment by mdbooth** [comment]
Alternatively, again dovetailing with #1116, perhaps we should not produce events corresponding to errors at all because these should be failure conditions on the Machine object? That would make the 'info' level purely informational, and correspond to the argument of the logging blog post.

**Comment by jichenjc** [comment]
>>>perhaps we should not produce events corresponding to errors at all because these should be failure conditions on the Machine object? 

um... I knew `operators`  (OLM concept) and k8s objects such as  `pods` has a lot of info including events, status etc to indicate different info, .e.g if you run `oc describe co` you will get operator's status and last sync while you still get some insight into previous happened things , so event is more like a history and `failing conditions` is more like a latest status? align with k8s conventions to provide user info through their familiar way is more helpful ?


>>>So I propose we have 3 levels of 'log':
    Only of interest to developers: these go to the log
    User-interesting activity information: these are Events at info level
    User-interesting failure information: these are Events at warn level

+1 to this, events for admin and logs for dev debug purpose ..

**Comment by Xenwar** [comment]
> @Xenwar, if we're already differentiating all the events you wanted to call 'Error', does it matter that we're calling them `Warn`?

From the discussion above, I am convinced that it is ok to use `Warn` for three reasons. 

1. The caller is notified about the error
2. Only a single request has failed and the error is relevant in that request's context. i.e. controller keeps running
3. Historical data with such events could be found in `.Status` already and it is informative, regardless of it being `Warn` or `Error`

Therefore, we keep the code as is and close this issue for now.

**Comment by mdbooth** [comment]
Looks like we resolved not to go with this.
