### ISSUE TITLE
unknown field "emeritus_maintainers" in the OWNERS file

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/cluster-api-provider-openstack#1122]
there is a [new tool](https://github.com/dims/maintainers) for parsing the kubernetes/community/sigs.yaml file and it reports an error in the OWNERS file in this repository:
> ERROR: unable to parse owners file at https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-aws/master/OWNERS url - error unmarshaling JSON: while decoding JSON: json: unknown field "emeritus_maintainers"

**solution**

- rename `emeritus_maintainers` -> `emeritus_approvers`
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/OWNERS#L13

**Comment by seanschneeweiss** [comment]
Let's rename our `emeritus_maintainers` to `emeritus_approvers` as suggested.
Not sure what to do with the `emeritus_reviewers`, maybe comment them out or?

**Comment by seanschneeweiss** [comment]
From https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#cleanup
> * if the person is in reviewers section, their GitHub id will be removed from the section
> * if the person is in approvers section, their GitHub id will be moved the emeritus_approvers section.
