### ISSUE TITLE
Wait for port detach to succeed when deleting trunk

### ISSUE THREAD

**Issue by Xenwar** [kubernetes-sigs/cluster-api-provider-openstack#1124]
Based what neutron driver is used, trunk deletion might require a detachment of port. While our local devstack setup does not require that, the CAPO e2e test infra requires it.  Basically, this can happen with drivers that demand that a trunk must be created or deleted on an unbound port.

Currently, the code tries to delete trunk as follows.

1. detach port
2. delete trunk
3. delete port

While the sequence above correct and should work even in the CAPO e2d infra, there is a possibility that `(2) delete trunk `is execute first. This is caused due to OpenStack API call to detach the port responding immediately with success status, despite the operation is not performed yet. This has resulted flaky failures. 

Error log:

`I0126 13:11:53.204487       1 recorder.go:103] events "msg"="Warning"  "message"="Failed to delete trunk cluster-e2e-6ufzl7-control-plane-9hpqc-0 with id 52190a49-381c-4a99-ae3e-02c34b4910c7: Expected HTTP response code [] when accessing [DELETE http://10.0.3.15:9696/v2.0/trunks/52190a49-381c-4a99-ae3e-02c34b4910c7], but got 409 instead\n{\"NeutronError\": {\"type\": \"TrunkInUse\", \"message\": \"Trunk 52190a49-381c-4a99-ae3e-02c34b4910c7 is currently in use.\", \"detail\": \"\"}}" "object"={"kind":"OpenStackMachine","namespace":"e2e-6ufzl7","name":"cluster-e2e-6ufzl7-control-plane-9hpqc","uid":"3c0c49c7-a42a-4986-be8e-d76ca0401a36","apiVersion":"infrastructure.cluster.x-k8s.io/v1beta1","resourceVersion":"7205"} "reason"="FailedDeleteTrunk"
`

**To Do:**
Wait for the port detachment to succeed and perform trunk deletion.

/kind bug

**Comment by jichenjc** [comment]
If I understand correctly, so this is a race and API call to Trunk and port delete is 1->2 order
but handling is 2->1 order to lead to 409 error?
