### ISSUE TITLE
Release v0.5.1

### ISSUE THREAD

**Issue by MPV** [kubernetes-sigs/cluster-api-provider-openstack#1129]
Hi,
Could we organize a release for `v0.5.0`?

**Comment by MPV** [comment]
In particular we're looking for this fix to be in a released (and thus easier-to-install/run) binary:

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1076

Why, one might ask:

We recently upgraded CAPI v1alpha3 -> v1beta1 and CAPO v1alpha3 -> v1alpha4 (`v0.5.0`), and when doing so we noticed that the built-in conversion between versions of the `OpenStackCluster`'s `spec.bastion` section wasn't entirely successful, so we ended up getting a `Cluster` that couldn't continue reconciling since it got stuck in error state due to the bastion gave a diff (and is immutable).

For now we've manually built an image from the `release-0.5` branch and patched our CAPO controller's Deployment, so we could use the new `spec.bastion.enabled` feature for toggling the bastion off first so it comes up okay for new clusters (however the first cluster's `Cluster` is still stuck in permanent block from reconciling).

Semi-related is also a local issue we're having with our OpenStack not allowing us to pick floating IPs with a specific IP (though our provider is working on that now). But since CAPO has bubbled this error to our CAPI `Cluster` it won't reconcile again. Possibly we should raise a new issue for this latter problem, similar to https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1116 (but for `*Cluster` instead).

**Comment by mdbooth** [comment]
@MPV Yes please, can you raise another issue for the floating IP thing?

**Comment by mdbooth** [comment]
All PRs merged in main since 0.5.0. I've subjectively put them each into 1 of 4 categories:

* **Infra**
  - #1049
  - #1052
  - #1048
  - #1069
  - #1091
* **Release/admin**
  - #1047
  - #1050
  - #1051
  - #1042
  - #1058
  - #1055
  - #1061
  - #1056
  - #1068
  - #1080
  - #1083
  - #1084
  - #1082
  - #1088
  - #1090
  - #1102
  - #1108
  - #1113
* **Features**
  - #1057
  - #1053
  - #1059
  - #1101
  - #1110
  - #1030
  - #1119
  - #1125
* **Bugs**
  - #909
  - #1066 _(not relevant to 0.5)_
  - #1063
  - #1070 _(already backported)_
  - #1089
  - #1094
  - #1097
  - #1104
  - #1095
  - #1107
  - #1112
  - #1115

Wow, we've been busy!

I think we can safely exclude 'Infra' and 'Release/admin'. I don't think we should consider including any features, which just leaves bugs. I haven't looking into the feasibility or desirability of backporting any of these, so PTAL and comment if you think we should consider a specific bug.

**Comment by apricote** [comment]
I would like to see #1095 backported, as this has caused issues for us multiple times before.

**Comment by mdbooth** [comment]
I have proposed a backport of #1095 here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1130. Note that I couldn't backport the unit tests.

**Comment by MPV** [comment]
> @MPV Yes please, can you raise another issue for the floating IP thing?

@mdbooth Sorry for the sloppy description, but I created https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1131 as a start for representing what we saw last week.

**Comment by mdbooth** [comment]
> > @MPV Yes please, can you raise another issue for the floating IP thing?
> 
> @mdbooth Sorry for the sloppy description, but I created #1131 as a start for representing what we saw last week.

We won't get a fix for this into a 0.5.1 release, unfortunately.

**Comment by mdbooth** [comment]
Noticed CI was failing on my backport. Hoping https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1133 will fix it. Seems to be a documented issue.

**Comment by jichenjc** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.5.1 
is out , however, I have some issues (not sure why new release have this) 

https://github.com/kubernetes-sigs/cluster-api/issues/6076
created for help now

**Comment by jichenjc** [comment]
Update: 

with manual update of the released metadata.yaml I can use 0.5.1 now

```
root@jitest19:~# clusterctl init --infrastructure openstack
Fetching providers
Installing cert-manager Version="v1.5.3"
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v1.1.0" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v1.1.0" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v1.1.0" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-openstack" Version="v0.5.1" TargetNamespace="capo-system"
I0208 07:52:30.855048 3848516 request.go:665] Waited for 1.037932423s due to client-side throttling, not priority and fairness, request: GET:https://127.0.0.1:44359/apis/clusterctl.cluster.x-k8s.io/v1alpha3?timeout=30s

Your management cluster has been initialized successfully!

You can now create your first workload cluster by running the following:

  clusterctl generate cluster [name] --kubernetes-version [version] | kubectl apply -f -


root@jitest19:~# kubectl get pods  -A
NAMESPACE                           NAME                                                             READY   STATUS    RESTARTS   AGE
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-55f5795c76-lbpv4       1/1     Running   0          34s
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-65f495cf5b-ksncd   1/1     Running   0          33s
capi-system                         capi-controller-manager-57bbc5d67-swxts                          1/1     Running   0          35s
capo-system                         capo-controller-manager-76fdfb96c4-kj6bq                         1/1     Running   0          31s
cert-manager                        cert-manager-848f547974-8m68n                                    1/1     Running   0          52s
cert-manager                        cert-manager-cainjector-54f4cc6b5-wtmz6                          1/1     Running   0          52s
cert-manager                        cert-manager-webhook-58fb868868-p5m5r                            1/1     Running   0          52s
kube-system                         coredns-74ff55c5b-bdzht                                          1/1     Running   0          73s
kube-system                         coredns-74ff55c5b-kjxgz                                          1/1     Running   0          73s
kube-system                         etcd-kind-control-plane                                          1/1     Running   0          87s
kube-system                         kindnet-4j66r                                                    1/1     Running   0          74s
kube-system                         kube-apiserver-kind-control-plane                                1/1     Running   0          87s
kube-system                         kube-controller-manager-kind-control-plane                       1/1     Running   0          87s
kube-system                         kube-proxy-7rhhx                                                 1/1     Running   0          74s
kube-system                         kube-scheduler-kind-control-plane                                1/1     Running   0          87s
local-path-storage                  local-path-provisioner-78776bfc44-db2gb                          1/1     Running   0          73s

```

**Comment by MPV** [comment]
Was the `v0.5.1` release taken from https://github.com/kubernetes-sigs/cluster-api-provider-openstack/tree/main instead of the https://github.com/kubernetes-sigs/cluster-api-provider-openstack/tree/release-0.5 branch? 

Would it maybe be better not to release new features in a patch release, and have them in a later release?

**Comment by jichenjc** [comment]
>>>release new features in a patch release

I am not sure we previously follow that way, usually we do 0.4, 0.4.1, 0.4.2 etc IIRC?
and you made a good point, release-0.5 branch seems more fit, 
I will leave this for folks to decide then I can take actions accordingly

**Comment by mdbooth** [comment]
I was thinking that we would tag 0.5.1 from the 0.5 branch. However, the 0.5.1 tag exists now. Do we roll with it?

**Comment by jichenjc** [comment]
thanks for the confirmation , I can untag it and might need check the latest image on 0.5 branch
will take actions later today or early tomorrow

**Comment by jichenjc** [comment]
please check https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.5.2
and there's reason why it's 0.5.2 (some clue on above history of wrong branch of 0.5.1) 

I confirm at least I can init a cluster... 

```
root@jitest19:~# clusterctl init --infrastructure openstack
Fetching providers
Installing cert-manager Version="v1.5.3"
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v1.1.0" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v1.1.0" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v1.1.0" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-openstack" Version="v0.5.2" TargetNamespace="capo-system"

# kubectl get pods  -A
NAMESPACE                           NAME                                                             READY   STATUS    RESTARTS   AGE
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-55f5795c76-b9qcv       1/1     Running   0          30s
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-65f495cf5b-tplxx   1/1     Running   0          29s
capi-system                         capi-controller-manager-57bbc5d67-6t7b7                          1/1     Running   0          31s
capo-system                         capo-controller-manager-6df5bbf475-s9nmq                         1/1     Running   0          27s
cert-manager                        cert-manager-848f547974-cmwkm                                    1/1     Running   0          71s
cert-manager                        cert-manager-cainjector-54f4cc6b5-6m48j                          1/1     Running   0          71s
cert-manager                        cert-manager-webhook-58fb868868-kzbz2                            1/1     Running   0          71s
kube-system                         coredns-74ff55c5b-f2dnm                                          1/1     Running   0          71s
kube-system                         coredns-74ff55c5b-qtz6w                                          1/1     Running   0          71s
kube-system                         etcd-kind-control-plane                                          1/1     Running   0          84s
kube-system                         kindnet-p7wgk                                                    1/1     Running   0          71s
kube-system                         kube-apiserver-kind-control-plane                                1/1     Running   0          84s
kube-system                         kube-controller-manager-kind-control-plane                       1/1     Running   0          84s
kube-system                         kube-proxy-p9gwh                                                 1/1     Running   0          71s
kube-system                         kube-scheduler-kind-control-plane                                1/1     Running   0          84s
local-path-storage                  local-path-provisioner-78776bfc44-ssrkg                          1/1     Running   0          71s

# kubectl get pod capo-controller-manager-6df5bbf475-s9nmq -n capo-system -o jsonpath='{.spec.containers[0].image}'
k8s.gcr.io/capi-openstack/capi-openstack-controller:v0.5.2
```

**Comment by jichenjc** [comment]
close this as 0.5.2 is out

**Comment by MPV** [comment]
If there's any interest in having any of the other fixes discussed in this issue backported into `v0.5.3`, https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1166 is the issue for that. 😊
