### ISSUE TITLE
Error computing version info/LDFLAGS in postsubmit/nightly image push job

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api-provider-openstack#1139]
/kind bug

**What steps did you take and what happened:**

In the [cluster-api-provider-openstack-push-images-nightly](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cluster-api-provider-openstack-push-images-nightly/1493495296452202496) job, there is an error computing the LDFLAGS in the [build logs](https://storage.googleapis.com/kubernetes-jenkins/logs/cluster-api-provider-openstack-push-images-nightly/1493495296452202496/artifacts/build.log). 

The LDFLAGS are computed from `./hack/version.sh`, and it fails because the workspace directory does not have a `.git` folder and we get this error as a result.

```
make[1]: Entering directory '/workspace'
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
gcloud container images add-tag -q gcr.io/k8s-staging-capi-openstack/capi-openstack-controller:main gcr.io/k8s-staging-capi-openstack/capi-openstack-controller:nightly_main_20220215
Created [gcr.io/k8s-staging-capi-openstack/capi-openstack-controller:nightly_main_20220215].
make[1]: Leaving directory '/workspace'
make[1]: Entering directory '/workspace'
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make out/infrastructure-components.yaml PULL_POLICY=IfNotPresent TAG=nightly_main_20220215
make[2]: Entering directory '/workspace'
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

The LDFLAGs aren't used in those logs, but when you try to use a job to run the following in the Makefile, the LDFLAGS will be an empty string.

```
docker-build: docker-pull-prerequisites ## Build the docker image for controller-manager
	docker build -f $(CONTAINERFILE) --build-arg goproxy=$(GOPROXY) --build-arg ARCH=$(ARCH) --build-arg LDFLAGS="$(LDFLAGS)" . -t $(CONTROLLER_IMG_TAG)
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I had this same issue in the postsubmit jobs for CAPI and CAPZ, and I've opened up a [PR](https://github.com/kubernetes/test-infra/pull/25251/files#) in test-infra that fixes the issue by including a flag in the prow jobs for all the providers listed there. I wanted to let everyone here know since it would affect their jobs and get an LGTM on the PR before merging the changes.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): Any
- Cluster-API version: Any
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
thanks for the heads up, just lgtm to the PR pointed

**Comment by mdbooth** [comment]
Closed by https://github.com/kubernetes/test-infra/pull/25251
