### ISSUE TITLE
🐛 align failureReason and failureMessage also for OpenStackMachines

### ISSUE THREAD

**Issue by tobiasgiese** [kubernetes-sigs/cluster-api-provider-openstack#1149]
/kind bug

Currently, we use `failureReason` and `failureMessage` status for all CAPO resources.
Only for the `OpenStackMachines` we use `errorReason` and `errorMessage` (even the variable names are correct).

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/642d851d3068f90864fedc1a28c283f9218e3850/api/v1alpha4/openstackmachine_types.go#L109
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/642d851d3068f90864fedc1a28c283f9218e3850/api/v1alpha4/openstackmachine_types.go#L128

This should be checked with all other resources to be consistent. 

Proposed for inclusion in 0.6: #1145

<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by tobiasgiese** [comment]
Do we need any documentation regarding this change? WDYT @mdbooth

**Comment by seanschneeweiss** [comment]
A changelog entry for the next release would be sufficient in my opinion.
