### ISSUE TITLE
Support http_proxy

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1151]
/kind feature

**Describe the solution you'd like**
If http_proxy (or any of the related family of environment variables) is set, CAPO should use it to access the OpenStack API.

Proposed for 0.6: #1145

**Comment by jichenjc** [comment]
@mdbooth not expert in this area , I knew OCP has http_proxy
https://docs.openshift.com/container-platform/3.11/install_config/http_proxies.html

are you suggesting we honor it or honor the following process?
CAPO ==> proxy ==> openstack itself

**Comment by mdbooth** [comment]
> @mdbooth not expert in this area , I knew OCP has http_proxy https://docs.openshift.com/container-platform/3.11/install_config/http_proxies.html

Aside: It's infuriating that google always returns OCP 3.11 results first when it's nearly EOL and almost entirely unrelated to OCP 4.x 💢

That said, OCP 4.x also has a concept of a cluster proxy.

> are you suggesting we honor it or honor the following process? CAPO ==> proxy ==> openstack itself

If the CAPO controller has an http_proxy environment variable set, we should use it to access the openstack API. We don't need to worry about what set it.

**Comment by jichenjc** [comment]
I used wrong link but I knew OCP4 has http_proxy as well (we set it time to time) 

but I don't know how we honor this settings , a quick search in cloud provider openstack didn't find `http_proxy` either..

**Comment by pierreprinetti** [comment]
/assign
Let's see if it's a good first issue :)

**Comment by chrischdi** [comment]
Sounds reasonable and to be a default feature which should always work :-) 

Isn't it already there: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/provider/provider.go#L103 ?

**Comment by jichenjc** [comment]
maybe provide some guide / doc on that ?

`http.ProxyFromEnvironment` does this mean set an ENV variable will work?

**Comment by pierreprinetti** [comment]
>does this mean set an ENV variable will work?

That's what it looks like. And indeed, it worked in my tests.

@mdbooth I would tend to close this issue, and consider any malfunction in the proxy department as a new bug. WDYT?

**Comment by mdbooth** [comment]
WFM. Thanks for testing @pierreprinetti (and writing the downstream tests that the other folks didn't see 😉).
