### ISSUE TITLE
Remove Networks from the Machine spec

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1154]
/kind feature

**Describe the solution you'd like**
Ports should have a superset of the functionality of Networks, with one exception. Networks allow the creation of multiple ports from a single filter definition, whereas ports do not. I propose that was never intended behaviour, nobody's actually relying on this, and the most likely outcome of it is user surprise if their filter accidentally has more than one match.

I would like to simply remove Networks.

`NetworkParam` is currently defined as:

```golang
type NetworkParam struct {
	// Optional UUID of the network.
	// If specified this will not be validated prior to server creation.
	// Required if `Subnets` specifies a subnet by UUID.
	UUID string `json:"uuid,omitempty"`
	// A fixed IPv4 address for the NIC.
	FixedIP string `json:"fixedIP,omitempty"`
	// Filters for optional network query
	Filter NetworkFilter `json:"filter,omitempty"`
	// Subnet within a network to use
	Subnets []SubnetParam `json:"subnets,omitempty"`
}
```

This translates as:

`NetworkParam.UUID` -> `PortOpts.Network.ID`
`NetworkParam.FixedIP` -> `PortOpts.FixedIPs[0].IPAddress`
`NetworkParam.Filter` -> `PortOpts.Network`
`NetworkParam.Subnets[]` -> `PortOpts.FixedIPs[].Subnet`

The only functional difference would be that if any of the network or subnet filters return multiple results it will be an error. This is an excellent argument for doing this before v1beta1.

Proposed for 0.6: #1145

**Comment by jichenjc** [comment]
in our doc we mentioned following which is consistent to your description
I think it's reasonable to remove this if we are sure no one rely on that filters 
```
If you have a complex query that you want to use to lookup a network, then you can do this by using a network filter. More details about the filter can be found in [NetworkParam](https://github.com/kubernetes-s igs/cluster-api-provider-openstack/blob/main/api/v1beta1/types.go)                                                                                                                                                                                                                                                                                                                                                                    By using filters to look up a network, please note that it is possible to get multiple networks as a result. This should not be a problem, however please test your filters with `openstack network list` to be ce rtain that it returns the networks you want. Please refer to the following usage example:
```

**Comment by chrischdi** [comment]
I think thats a great cleanup and nicely doable using the conversion prior to a release with v1beta1 :+1:

**Comment by seanschneeweiss** [comment]
We agreed in the office hours to remove network in favor of port.
