### ISSUE TITLE
provider.GetProjectID usage (put into clouds.yaml now) move to `openstackCluster`?

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#1160]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

we are using 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/c052e7e600f0e5ebddc839c08746bb636e79be87/pkg/cloud/services/provider/provider.go#L173

to detect the project ID, but htis means this is per-project setting

should we consider move this project info into openstackCluster side? so that we can benefit for multiple tenant use cases?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by apricote** [comment]
I am currently doing some refactoring of the `ProjectID` handling to support Application Credentials: #1146

**Comment by mdbooth** [comment]
@jichenjc What's the use case you're thinking of here? Are you looking to improve support for multiple tenants using a single management cluster? Are the IdentityRefs in the cluster and machine specs not sufficient for that?

Or are you thinking the we'd store domain-scoped (admin) OpenStack credentials in the management cluster, and then the cluster would specify a project scope in the spec?

**Comment by jichenjc** [comment]
I am considering a multi tenant use case, recently , if we are having multiple projects, each of them need create a clouds.yaml file in order to create such cluster

I am thinking about use admin or user that is able to access multiple projects instead of using multiple cloud configurations ..

**Comment by mdbooth** [comment]
What credentials would the tenant use in the installed cluster?

**Comment by apricote** [comment]
We do something similar in a custom operator.

- The operator has credentials for a Domain Admin
- For every cluster it creates a new project, CAPO user and application credentials
- with these details it creates the `clouds.yaml` and hands over to CAPI/CAPO to actually create the cluster

**Comment by mdbooth** [comment]
I wonder if a separate controller is the more appropriate model. @apricote in fact, in that model can't you can the controller to server project-scoped application credentials, and then you never leak unscoped admin credentials into a user domain? Ah... I guess this is why you're interested in application credentials?

@jichenjc, would something like @apricote's controller meet your needs? Messing with credentials in CAPO makes me a bit nervous.

**Comment by jichenjc** [comment]
@mdbooth @apricote ok, this operator make sense to me, so I will think about same way to do this
