### ISSUE TITLE
`OpenStackCluster.status.failureDomains` is never cleaned up

### ISSUE THREAD

**Issue by apricote** [kubernetes-sigs/cluster-api-provider-openstack#1163]
/kind bug

**What steps did you take and what happened:**

- Have an existing `OpenStackCluster`
- Temporarily add a new Availability Zone in OpenStack
- Remove the Availability Zone again
- Availability Zone is still referenced in `OpenStackCluster.status.failureDomains` and never removed

**What did you expect to happen:**

I expected the temporary Availability Zone to be removed once it's not longer visible in OpenStack.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): `v0.5.2`
- Cluster-API version: `v1.1.2`
- OpenStack version: Wallaby
- Minikube/KIND version: /
- Kubernetes version (use `kubectl version`): `v1.21.9`
- OS (e.g. from `/etc/os-release`): /

**Comment by jichenjc** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/controllers/openstackcluster_controller.go#L271

we only create a new `openStackCluster.Status.FailureDomains` when it's nil

but we never remove from the table as you described...

**Comment by jichenjc** [comment]
so my proposal is to remove this  == nil line, so every reconcile loop we create a new variable
so we will anyway update with latest AZ info,  any thoughts?

if openStackCluster.Status.FailureDomains == nil {
		openStackCluster.Status.FailureDomains = make(clusterv1.FailureDomains)
	}

**Comment by chrischdi** [comment]
> so my proposal is to remove this == nil line, so every reconcile loop we create a new variable so we will anyway update with latest AZ info, any thoughts?
> 
> if openStackCluster.Status.FailureDomains == nil { openStackCluster.Status.FailureDomains = make(clusterv1.FailureDomains) }

Totally makes sense to me. As long as it is reproducible it will lead to no changes at the end.

**Comment by apricote** [comment]
Sounds good. I will implement it like this :+1: 

/assign
