### ISSUE TITLE
Release `v0.5.3`

### ISSUE THREAD

**Issue by MPV** [kubernetes-sigs/cluster-api-provider-openstack#1166]
Issue to track/discuss proposed backports to follow in `v0.5.3` since https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.5.2.

**Comment by MPV** [comment]
@apricote mentioned they'd be interested in seeing this one backported:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1165

**Comment by MPV** [comment]
From our end, we're interested in:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/909

**Comment by MPV** [comment]
@mdbooth Collected a bunch of other candidates over at https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1129#issuecomment-1031349283. 
Only https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1076 was selected then, as seen in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/compare/v0.5.0...v0.5.2.

**Comment by apricote** [comment]
We are still interested in a backport of #1095

**Comment by jichenjc** [comment]
ok, please submit the cherrypick then we can merge and release afterwards :) thanks for bring this out

**Comment by apricote** [comment]
> ok, please submit the cherrypick then we can merge and release afterwards :) thanks for bring this out

We plan to discuss the backports during todays office hours. After that I will open the MRs.

**Comment by apricote** [comment]
There are now open PRs for all three requested backports:

- original: #1095  
  backport: #1130
- original: #1165   
  backport: #1171
- original: #909  
  backport: #1173

**Comment by apricote** [comment]
All requested backports are merged into `release-0.5`. From my side we can go forward with the release.

**Comment by jichenjc** [comment]
https://github.com/kubernetes/k8s.io/pull/3508

is the PR for image, please help to lgtm so we can continue the release process

**Comment by jichenjc** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.5.3

**Comment by apricote** [comment]
Release looks great to me. Thanks a lot for this @jichenjc!
