### ISSUE TITLE
docs: Explain OpenStackCluster.Spec.Bastion mutability in CRD

### ISSUE THREAD

**Issue by apricote** [kubernetes-sigs/cluster-api-provider-openstack#1180]
/kind feature

**Describe the solution you'd like**

We had multiple people reach out on slack because they were unable to modify the Bastion spec. While this topic is explained in [the docs](https://cluster-api-openstack.sigs.k8s.io/clusteropenstack/configuration.html#enabling-the-bastion-host), not everyone reads those.

I suggest we add an explanation to the `sigs.k8s-io/cluster-api-provider-openstack/api/{v1alpha3,v1alpha4,v1beta1}.Bastion` struct, so this information is also available when looking at the CRDs through https://doc.crds.dev/ or `kubectl explain openstackcluster.spec.bastion`.

**Anything else you would like to add:** -

**Comment by jichenjc** [comment]
>>>because they were unable to modify the Bastion spec

can you help point me the link of the question? @apricote 
don't know whether we need update code or not :)

**Comment by apricote** [comment]
> > > > because they were unable to modify the Bastion spec
> 
> can you help point me the link of the question? @apricote don't know whether we need update code or not :)

There was someone in Slack last week: https://app.slack.com/client/T09NY5SBT/CFKJB65G9/thread/C2P1JHS2E-1647882051.537369

**Comment by jichenjc** [comment]
```
That understanding is correct, you will need two upgrade commands:

    Disable Bastion Host
    Make changes and enable bastion host
```

seems this is not reasonable ? unless we want to pause the reconcile (e.g CAPI itself)
the resource update should be able to be done on the fly? 
I don't remember the history of having such restriction, should we consider enhance it somehow?

**Comment by tobiasgiese** [comment]
> I checked CAPA and CAPZ and both allow changing the bastion even while its enabled

In my first implementation of PR #1070 I allowed changes to the bastion even while its running/enabled.
But @mdbooth had some concerns about the behavior, see https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1070#discussion_r762952694

**Comment by mdbooth** [comment]
Yes, I think I still stand by my older comment. If it doesn't work we should reflect that in the API. It's also user-hostile to pretend something works if it doesn't.

It would be best if it did work, of course. Do CAPA and CAPZ have a solution for this? There's always the solution of hashing the bastion spec and storing it in the status. If the status hash doesn't match the current hash you delete and recreate. Is there a neater solution?

**Comment by apricote** [comment]
> Do CAPA and CAPZ have a solution for this?

CAPA does not handle updates to the bastion, they just have a `TODO` comment for this:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/0babdf15d5584744c4693e8be4ab44c580847531/pkg/cloud/services/ec2/bastion.go#L96

CAPZ does updates, but they don't use VMs for this, but their [Bastion Hosts](https://docs.microsoft.com/en-us/azure/bastion/bastion-overview) product.

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/9f899f08d2c4c687889741c5144bf82af0666eb1/azure/services/bastionhosts/client.go#L71

---

Based on this I think our current behaviour is in-line with CAPA but better documented.

**Comment by apricote** [comment]
No first-time contributer picked this up in the planned timeframe.

/assign
