### ISSUE TITLE
📖 Document changes to CRDs in Book

### ISSUE THREAD

**Issue by apricote** [kubernetes-sigs/cluster-api-provider-openstack#1188]
/kind feature
/kind docs

**Describe the solution you'd like**

We should document changes that we make to the CRD schema in our Book. This way, users can easily see what they need to change in their manifests to migrate to the new CRD version, without having to manually find out what changed.

**Anything else you would like to add:**

We currently have a list of planned changes to the next CRD version (`v1alpha5`):

-  https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1186
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1154
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1105
- #1187 

CAPI tracks changes to the Provider Contracts in their book, we could adapt this: https://cluster-api.sigs.k8s.io/developer/providers/v1alpha4-to-v1beta1.html

**Comment by jichenjc** [comment]
@apricote do we want to add things that we updated e.g 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1187
since v1alpha4=>vebeta1?
