### ISSUE TITLE
Cluster phase locks to `Failed` when Loadbalancer is in `PENDING_UPDATE` status

### ISSUE THREAD

**Issue by apricote** [kubernetes-sigs/cluster-api-provider-openstack#1197]
/kind bug

**What steps did you take and what happened:**

- Create cluster with latest CAPO release
- Wait for Cluster to provision
- Observe that sometimes the Cluster moves to phase `Failed`

Cluster has `Status.FailureMessage` of:

> 'Failure detected from referenced resource infrastructure.cluster.x-k8s.io/v1alpha4, Kind=OpenStackCluster with name "$CLUSTER_NAME": failed to reconcile load balancer: load balancer "b7a42f2d-2c99-45e7-a32d-8efd9b4cb301" is not in expected    state ACTIVE, current state is PENDING_UPDATE'

`OpenStackCluster` is marked as `Ready`.

**What did you expect to happen:**

Cluster should not be moved to phase `Failed` and instead always move to phase `Provisioned`.

**Anything else you would like to add:**

Timeline of internal events:

- Cluster infrastructure is provisioned
- Control Plane machines start to come up and are added to managed APIServer loadbalancer
- During a `OpenStackCluster` reconcile, the reconcile errors here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/6ba04de45920c102886bdeeeb21bf1a1119c5967/pkg/cloud/services/loadbalancer/loadbalancer.go#L61-L63
- This error is saved to `OpenStackCluster.Status.FailureMessage`
- During a `Cluster` reconcile, CAPI "pulls" the failure message and persists that to its own status: https://github.com/kubernetes-sigs/cluster-api/blob/4f4c7a1dd7fae352bd59e6a46f6394707cc30232/internal/controllers/cluster/cluster_controller_phases.go#L118-L132
- The `Cluster` phase is set to `Failed` because of the Failure Message now set in the Cluster status: https://github.com/kubernetes-sigs/cluster-api/blob/4f4c7a1dd7fae352bd59e6a46f6394707cc30232/internal/controllers/cluster/cluster_controller_phases.go#L57-L59
- [Assumption] On the next `OpenStackCluster` reconcile, the Loadbalancer is `ACTIVE` again, and the failure message/status on the `OpenStackCluster` resource are cleared
- [Assumption] CAPI never "re-pulls" the status from the `OpenStackCluster` and is therefore stuck in the `Failed` phase.

It looks like this behaviour was introduced in #1115 (backported to release-0.5 in #1164).

The cluster infrastructure provider contract specifies that setting `Failure{Message,Reason}` should be done for **fatal** errors, which I assume they mean _non-recoverable_ errors. With this interpretation, we should not set the Failure fields for this temporary "failure" in the loadbalancer reconcile.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): `v0.5.3`
- Cluster-API version: `v1.1.3`
- OpenStack version: Stein
- Minikube/KIND version: -
- Kubernetes version (use `kubectl version`): Management Cluster is running 1.22.{4,5}, Workload Clusters are running {1.22.4,1.22.5,1.23.5}
- OS (e.g. from `/etc/os-release`): -

**Comment by seanschneeweiss** [comment]
Thank you for the extensive issue description.
This is a similar problem as in #1116 but not for OpenStackMachines but OpenStackClusters.

Transient error, such as a load balancer in PENDING_UPDATE should not prevent further reconciliations. Definitely agree on that.
The fix could be as easy as removing the following line:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/6ba04de45920c102886bdeeeb21bf1a1119c5967/controllers/openstackcluster_controller.go#L485

**Comment by apricote** [comment]
Thanks for the guidance @seanschneeweiss. I am going to create a fix PR soon.

/assign
