### ISSUE TITLE
Specify the subnet id for the External Network using the external cloud provider

### ISSUE THREAD

**Issue by raildo** [kubernetes-sigs/cluster-api-provider-openstack#1210]
/kind feature

Nowadays, CAPO will always choose the first subnet given the `OPENSTACK_EXTERNAL_NETWORK_ID` based on the current code [0]. Would be nice to have a new configuration option, something like `OPENSTACK_EXTERNAL_SUBNET_ID` where we could specify on which subnet of the external network, we want the cluster to get a Floating IP.

The use case that I have is when there is no floating IP available on this first subnet to be used, but we do have others subnets on the public network and I would like to choose another subnet with another range of FIPs for the cluster to be deployed, right now we can't do it.

[0] https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/networking/router.go#L168

We have something similar to that already one on OCCM as you can see here:

https://github.com/kubernetes/cloud-provider-openstack/issues/1328

https://github.com/kubernetes/cloud-provider-openstack/pull/1375

**Comment by jichenjc** [comment]
um... not sure fully understand this , but follow your [0] 
makes me think you want to do on `ExternalRouterIPs` then read your description again seems you want to work on `ExternalNetworkID ` which are 2 different concepts to me 

and I guess you want to work on `ExternalNetworkID ` then yes ,provide a subnet ID seems reasonable (but will openstack use 2nd subnet if 1st used up so anyway 2nd subnet will be used later ??)

and yes, I think it should be good for us to add such param, in case not provided, go with "" should be fine

**Comment by raildo** [comment]
Probably, I pointed out to the wrong code link on [0] when I was trying to find the related code, but you're right on the second statement. When we have a deployment multiple subnets on the external network, I'm looking forward to be able choose on which subnet I want the cluster to grab a Floating IP, that's my suggestion on including that new param `OPENSTACK_EXTERNAL_SUBNET_ID` (or any other similar name that fits for everyone).

Also I'm ok with, as you mentioned on your comment, if not provided, go with "" on it.

**Comment by jichenjc** [comment]
/assign

ok, let me give a try

**Comment by raildo** [comment]
Cool! Thank you, I'm able to test it, if needed, in a real openstack cloud before we merged it. Just let me know :)

**Comment by jichenjc** [comment]
sorry for the confusion, I read the doc and code again and looks like I misunderstand the code a little bit at beginning
in your case [0] ,actually that's logic only when [1] is True

so have you tried openStackCluster.Spec.ExternalRouterIPs.Subnet.UUID to your subnet ID directly 
thus the UUID will indicate the subnet you choose?


[0] https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/networking/router.go#L168
[1] https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/networking/router.go#L158

**Comment by raildo** [comment]
I haven't tried changing this ID directly. Is there a way to do it using the external template, or should I change the openStackCluster.Spec.ExternalRouterIPs.Subnet.UUID directly after the clusterctl generate? I can give it a shoot here and see how it goes. I can poke you on slack if you want to as well, if you prefer.

**Comment by jichenjc** [comment]
>>>directly after the clusterctl generate

I think you can give a try after generate, we use yaml file to apply and that clusterctl is just for simple creation
sure, ping me any time and reply you when I see it :)

**Comment by jichenjc** [comment]
@apricote check above comments, I think existing way can achieve the functions so I didn't submit a PR 
waiting for validation on the way proposed above now

**Comment by raildo** [comment]
Hey all, sorry for the late response. Unfortunately I was not able to uses the openStackCluster.Spec.ExternalRouterIPs.Subnet.UUID during the previous tests. I'm not sure if someone else can tests it as well, or if you guys want we can pair or try to setup some test env to give it a try.

**Comment by jichenjc** [comment]
ok, I will try this later when got some time, fully occupied now :(

**Comment by jichenjc** [comment]
opened https://github.com/gophercloud/gophercloud/issues/2425 for subnet ID into floating ip creation 

for now, can you help to use `APIServerFloatingIP` as workaround so that you can select from 2nd subnet on the floating ip specificly?
