### ISSUE TITLE
Use Kustomize in generate-yaml.sh

### ISSUE THREAD

**Issue by stevesloka** [kubernetes-sigs/cluster-api-provider-openstack#124]
Currently the generate-yaml.sh script utilizes bash and sed to handle building out the yaml files to pass to clusterctl. There can be environmental issues (mac vs linux, tooling version) which makes that script flakey. 

I'd like to propose we move to Kustomize for the generation and reduce this need on bash. I'm happy to take this on and send a PR.

**Comment by chaosaffe** [comment]
@stevesloka we would certainly appreciate the help on this one 😍

**Comment by iamemilio** [comment]
It is looking like a pure kustomize route may not be fully achievable without some modifications to how things are generated and written in the provider-config.yaml script are changed. The following issues would help a lot to make this easier:  #158 #156 #157

**Comment by iamemilio** [comment]
@stevesloka Hi, sorry I didn't assign myself to this. I kinda just blindly threw myself at it, which was a little naive. That being said, there is good news. I realized that this patch is going to take much more than just a kustomize script to make it work, so I broke it down into subtasks that I would definitely appreciate your help on if you are still interested/available!

**Comment by stevesloka** [comment]
Hey no worries @iamemilio, just wanted to communicate and make sure I was on the same page with the project. Let me see what I can help out with. =)
