### ISSUE TITLE
Allow clusters without explicit availability zones

### ISSUE THREAD

**Issue by mkjpryor** [kubernetes-sigs/cluster-api-provider-openstack#1252]
/kind feature

**Describe the solution you'd like**

Currently, CAPO machines require that a failure domain (availability zone) is specified. However there are a number of cases where this results in a sub-optimal user experience, IMHO.

In my particular target case, we are using traits, flavors, host aggregates and project isolation filters to ensure that VMs land on hypervisors that the project is permitted to use and/or have particular specialist hardware and connectivity. This works best when an AZ is not specified, as that allows Nova to pick a suitable host without constraints.

However the operator still wants to use AZs as a housekeeping thing, e.g. corresponding to racks, so they can quickly see what is scheduled where.

Because CAPO requires AZs to be specified, this means that when using CAPI/O users have to make sure that the flavor and AZ that they choose are compatible. This leads to a lot of mistakes leading to "no valid host" errors that we then have to deal with as support. We would prefer not to specify the AZ and let Nova deal with it.

We also have ambitions to use Blazar to control access to resources, in which case it will be even more important that Nova is in full control of the scheduling.

**Anything else you would like to add:**

We should still use a server group with soft anti-affinity to ensure control plane hosts are scheduled on different hypervisors when possible. This can be used whether specifying explicit AZs or not, but becomes more important in the non-explicit case.

**Comment by mkjpryor** [comment]
This makes a lot of sense. For me, I prefer a solution whose default behaviour is backwards compatible as it means we can merge it without making a new API version. But I am happy to implement either version. 

@mdbooth and others - let me know if you have a preference.

**Comment by mkjpryor** [comment]
@mdbooth 

I'm still keen to progress this as it is a blocker for our use case. I am still happy to make the changes and, as stated above, I have a preference for maintaining backwards compatibility by default.

**Comment by jichenjc** [comment]
>>>However the operator still wants to use AZs as a housekeeping thing, e.g. corresponding to racks, so they can quickly see what is scheduled where.
Because CAPO requires AZs to be specified, this means that when using CAPI/O users have to make sure that the flavor and AZ that they choose are compatible. This leads to a lot of mistakes leading to "no valid host" errors that we then have to deal with as support. We would prefer not to specify the AZ and let Nova deal with it.
However the operator still wants to use AZs as a housekeeping thing, e.g. corresponding to racks, so they can quickly see what is scheduled where.

@mkjpryor sorry for late asking questions here as I only focus on the conversion question at beginning
so If I understand you correctly, you want to let CAPO ignore the AZ param but still let operator able to handle (otherwise you can disable the AZ filter so this PR is not needed) ?

**Comment by mkjpryor** [comment]
@jichenjc

What I want is to be able to make CAPO clusters where none of the machines specify an AZ, allowing nova to pick suitable ones based on other scheduling constraints. I want to be able to do this on OpenStack clouds that I do not own (and hence cannot modify Nova configuration).

#1263 made it possible to create machines without specifying a `failureDomain`, and this works for workers.

However CAPI will explicitly spread control plane nodes across the failure domains reported by the infracluster as being suitable for control plane nodes. In order for CAPI to create control plane nodes that do not specify a failure domain, the infracluster must report no suitable failure domains. That is what #1318 does, so it is still required.

Hope that makes sense?

**Comment by jichenjc** [comment]
>>> I want to be able to do this on OpenStack clouds that I do not own (and hence cannot modify Nova configuration).

yes, this is the key thing :) , as we can't modify server side, then yes, CAPO can do something to make it happen
