### ISSUE TITLE
delete port left over by error openstackmachine

### ISSUE THREAD

**Issue by ruifaling** [kubernetes-sigs/cluster-api-provider-openstack#1254]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
This is an abnormal scenario: the VM creation fails, but the port creation succeeds. In this case, the port will be left when the cluster  is deleted

**What did you expect to happen:**
In this case,we could delete port by subnet

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
>>>This is an abnormal scenario: the VM creation fails, but the port creation succeeds. In this case, the port will be left when the cluster is deleted

so you are suggesting `clean` all the resource in one reconcile loop 
or we can keep the port and let the VM deploy again with same port?

**Comment by erkanerol** [comment]
> In this case, the port will be left when the cluster is deleted

@ruifaling And then the left-over port blocks network deletion and cluster deletion. Right?

**Comment by ruifaling** [comment]
> > > > This is an abnormal scenario: the VM creation fails, but the port creation succeeds. In this case, the port will be left when the cluster is deleted
> 
> so you are suggesting `clean` all the resource in one reconcile loop or we can keep the port and let the VM deploy again with same port?

I think we cloud remove it when the cluster is being deleted

**Comment by ruifaling** [comment]
> > In this case, the port will be left when the cluster is deleted
> 
> @ruifaling And then the left-over port blocks network deletion and cluster deletion. Right?

yes

**Comment by Goend** [comment]
I don't think we need this piece of code anymore, because this piece of code can lead to mistakenly delete the same prefix ports for users. @jichenjc how about you?

**Comment by jichenjc** [comment]
>>>@jichenjc how about you?

you mean revert #1260?

**Comment by Goend** [comment]
Yes, I think we need to remove or change this part. Refer to the issue #1320 on [GitHub](https://github.com/kubernetes-sigs/cluster-api). Our recycling method should be more precise. Coarse-grained recycling methods will affect other ports in the same subnet of the user.

**Comment by Goend** [comment]
> > > > @jichenjc how about you?
> 
> you mean revert #1260?

Yes, I think we need to remove or change this part. Refer to the issue #1320 on [GitHub](https://github.com/kubernetes-sigs/cluster-api). Our recycling method should be more precise. Coarse-grained recycling methods will affect other ports in the same subnet of the user.

**Comment by jichenjc** [comment]
ok, make sense to me , so @ruifaling do you want to start this or @Goend will do ?   :)

**Comment by Goend** [comment]
> ok, make sense to me , so @ruifaling do you want to start this or @Goend will do ? :)

Reference https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1446 for this fix. The pull request is a fix for an issue related to virtual machine ports. The pull request suggests that the code segment mentioned in the conversation is no longer useful and can be safely removed.I will submit the code after receiving your approval at the end of October.
