### ISSUE TITLE
kubelet won't start on ubuntu 20.04 

### ISSUE THREAD

**Issue by xinity** [kubernetes-sigs/cluster-api-provider-openstack#1262]
/kind bug

**What steps did you take and what happened:**
creating an ubuntu 20.04 compatible image for CAPO, kubelet doesn't start, with a weird message:
`could not init cloud provider openstack: warning: can't store data at section global,variable tls-insecure`

**What did you expect to happen:**
kubelet to be perfectly up and running

**Anything else you would like to add:**
ubuntu 20.04 image built was done using CAPI ubuntu 20.04 image builder packer sources

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):1.4
- Cluster-API version: 1.4
- OpenStack version:
opensta- Kubernetes version (use `kubectl version`): 1.22.9
- OS (e.g. from `/etc/os-release`): ubuntu 20.04

**Comment by jichenjc** [comment]
your error likely comes from https://github.com/kubernetes/cloud-provider/blob/master/plugins.go#L167

I think some cloud provider settings might be wrong but with limitted info, this is only guess
you might want to check your cloud-provider (external??) settings and see anything interesting

**Comment by xinity** [comment]
@jichenjc for now the cloud provider is defined as : `openstack` if i use the external provider template, kubelet starts , but i can't scale up my control plane, because the `unitiallized:true` taint isn't removed

**Comment by jichenjc** [comment]
check this https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/templates/cluster-template-external-cloud-provider.yaml and 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/docs/book/src/topics/external-cloud-provider.md

external cloud provider is the future
