### ISSUE TITLE
Cann't associate floating IP to Loabalancer

### ISSUE THREAD

**Issue by tranthang2404** [kubernetes-sigs/cluster-api-provider-openstack#1269]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I create a cluster with define subnet_id, network_id, external_network_id and not define NodeCIDR, but it make provision cluster stuck in reconcile Loadbalancer.
- Logs CAPO: ``` events "msg"="Warning"  "message"="Failed to associate floating IP xx.xx.xx.xx with port xxxyxy-xxxx Resource not found" "object"={"kind":"OpenStackCluster","namespace":"default","name":"cluster-21-openstack-cluster","uid":"57092c4f-43d2-47d4-92a1-xxx","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha5","resourceVersion":"163457139"} "reason"="Failedassociatefloatingip"```

- Logs Openstack when run command line to add floating ip to vip loadbalancer port: ``` External network 2b35e3c8-3ef8-424e-90ef-b3d010a6e9da is not reachable from subnet fdd4cf2f-248a-4c56-8cc8-abd30626a169.  Therefore, cannot associate Port 33b2a9ef-88ce-4a3f-918f-939234df824f with a Floating IP. ```

I think problem in `if` condition, it need create a router with `external_network_id`:
 https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/c5ac70e5f13d303e39a6919c0214345f51c4c6bc/controllers/openstackcluster_controller.go#L404-L461

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version: 1.1.1
- OpenStack version: 0.6.3
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by phamchien94** [comment]
I am also facing this problem. Are there any parameters to deal with vlan (external) network id and vpc network both set?

**Comment by FischerLGLN** [comment]
/reopen

Having the same problem. But even the in-network management cluster trying to create a private loadbalancer is failing.
