### ISSUE TITLE
Support different CNI plugin 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#1274]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

we use calico by default now , e.g the security group is set to calico now 
as we envolve, support multiple CNI is reasonable way to move forward

at least, I am thinking about add 
https://github.com/kubeovn/kube-ovn for now ...

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mkjpryor** [comment]
@jichenjc 

Don't forget this flag that I added: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/api/v1alpha6/openstackcluster_types.go#L113

I added that so that I could use Cilium

**Comment by jichenjc** [comment]
ok, great ~ Thanks for the reminder~

**Comment by jichenjc** [comment]
the idea is to e.g make different yaml for rules like this 

e.g for default rule create default-rule.yaml
for all in, create all-in-rule.yaml
for calico , apply calico.yaml 

so we have the flexibility to update and modify 

```
infrav1.SecurityGroupRule{
                        Description:  "Kubernetes API",
                        Direction:    "ingress",
                        EtherType:    "IPv4",
                        PortRangeMin: 6443,
                        PortRangeMax: 6443,
                        Protocol:     "tcp",
                },
```

**Comment by jichenjc** [comment]
#1323 seems not best solution as it introduce configuration into code 

the goal of this feature is to split the CNI settings from code to some configurations, either configmap or CRD (yaml)
- we need provide CNI settings in cluster definition 
```
     -  CNI:  calico
```
   if provided CNI is not recognizable, there is no no CNI setting at all ,it will be named `all`
- we create multiple pre-defined configmap (stored in json) for calico, clium (first) , the name has naming conventions like secgroup-cni-calico etc, for `all`, it's `secgroup-cni-all` means all traffic allowed
like this example https://stackoverflow.com/questions/61653284/does-kubernetes-take-json-format-as-input-file-to-create-configmap-and-secret
- when start, the cluster read the setting and load the config then honor it and create sec group 
- user is eligible to create additional security group and create config map like secgroup-cni-xxxx then it will be load during init process

**Comment by jichenjc** [comment]
@mdbooth can you help review above to see whether you have any comments? Thanks
