### ISSUE TITLE
[question]I want to set different az to every master node,Can it be done now or do I need to change the code to implement it?

### ISSUE THREAD

**Issue by Goend** [kubernetes-sigs/cluster-api-provider-openstack#1306]

**Comment by jichenjc** [comment]
I didn't try this before but I think it's not supported ?
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/controllers/openstackcluster_controller.go#L284
we set the AZ to the whole cluster

And Seems we are using FailiureDomain concept in CAPI for the AZ settings, not sure if we make the AZ into openstackmachine level has any conflict to CAPI concept?

**Comment by Goend** [comment]
ok,thanks,got it
