### ISSUE TITLE
Allow the use of flavor IDs as well as names

### ISSUE THREAD

**Issue by mkjpryor** [kubernetes-sigs/cluster-api-provider-openstack#1310]
/kind bug

**What steps did you take and what happened:**

Tried to make a cluster specifying a flavor ID, which failed.

**What did you expect to happen:**

It to work.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
we only use flavor name now, the option is to add a flavor ID + flavor Name option , just like 
instanceSpec.ImageUUID, instanceSpec.Image should be good enough
