### ISSUE TITLE
Migrate to Ginkgo v2 during cluster-api v1.3 bump

### ISSUE THREAD

**Issue by tobiasgiese** [kubernetes-sigs/cluster-api-provider-openstack#1315]
/kind feature

**Describe the solution you'd like**

Starting from CAPI v1.3, Ginkgo v2 will be used (https://github.com/kubernetes-sigs/cluster-api/pull/6906).
For bumping to CAPI 1.3 version, we should also migrate e2e tests to v2.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by oscr** [comment]
Just to be clear: does it have to wait for the unreleased cluster-api 1.3 bump or can it be done now?

**Comment by seanschneeweiss** [comment]
It was tried to upgrade to Ginkgo with CAPI v1.2 but due to dependencies this seems to be impossible:
