### ISSUE TITLE
Do not set security groups on instances

### ISSUE THREAD

**Issue by mkjpryor** [kubernetes-sigs/cluster-api-provider-openstack#1316]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Currently, the managed security groups are added to the instance, not to individual ports. This prevents clusters that have managed security groups from having one NIC with security group rules and one NIC without, as the instance security groups are applied to the second NIC even if the port itself specifies no security groups  

Nova itself also discourages use of this API - https://docs.openstack.org/nova/latest/contributor/project-scope.html#no-more-api-proxies. 

Instead, all security groups should be applied at the port level, with the managed groups being used when port security is enabled and no explicit groups are set for the port. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mkjpryor** [comment]
Given that it uses a deprecated API, there is actually a strong case for marking this as a bug.

**Comment by jichenjc** [comment]
/kind bug

I am not sure the use case of one NIC w/o sec group and the other w/
but yes, we should think about avoid using deprecated API

**Comment by mkjpryor** [comment]
@jichenjc 

Our use case is clusters with high-performance networking, often in an air-gapped environment. The cluster architecture we would like is:

  * Primary network is project-specific VXLAN, control plane and worker nodes attached. This is the network that the CNI uses, and has a router to an external network for accessing the cluster.
  * Worker nodes have additional high-performance networks attached that are VLAN provider networks (e.g. for connecting to storage). These are attached with SR-IOV (direct ports), have port security off and no security groups.

Because of the way that security groups are attached to the instance rather than the port (which is deprecated), we cannot currently do this with Cluster API.

**Comment by jichenjc** [comment]
@mkjpryor thanks for the sharing, the use case make sense to me
