### ISSUE TITLE
Openstack (gophercloud) Identity and Compute Clients timeout

### ISSUE THREAD

**Issue by gdoctor** [kubernetes-sigs/cluster-api-provider-openstack#132]
In it's current state, the Identity and Compute clients are timing out after 3 hours (I believe), rendering the provider pod useless until a new token is issued. You then begin getting a constant stream of "...Get service list err: Authentication failed". To resolve this during testing, you can just recreate the pod. But for actual use cases we should leverage the ReAuth option within the gophercloud library, which is defaulted to false. Setting this to true for our use cases seems much more sensible.

**Comment by chaosaffe** [comment]
@gdoctor would you be interested in opening a PR for this?
