### ISSUE TITLE
remove v1alpha3/4 ? 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#1326]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

we stated v1alpha3/4 is for CAPI v1alpahx version and now CAPI is already beta
should we remove the early support in main branch so that we can avoid maintain unnecessary complex code e.g conversions?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by tobiasgiese** [comment]
I don't think that we should remove old apiVersions. Kubernetes stores all old apiVersions in the CRDs and starts complaining if an old version was removed. It does need a manual task to remove the versions.

See https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#previous-storage-versions
And CAPI Slack thread https://kubernetes.slack.com/archives/C8TSNPY4T/p1655898088475859?thread_ts=1655898054.621999&cid=C8TSNPY4T

**Comment by jichenjc** [comment]
ok, I will read more in the thread you provided ,thanks :)

a general understanding to me is beta/stable version need keep but why we need keep alpha version?
Given we might have v1alpha7 (maybe but likely or even 8,9) , I think maintain such would be a burden?
We already removed v1alpha1/2 , do we ? Anyway, will read more for the info, thanks~

**Comment by jichenjc** [comment]
I reviewed above links but seems there is no clear indication we can't remove v1alphax version ..

**Comment by lentzi90** [comment]
CAPI is now starting to plan for removal of older versions: https://github.com/kubernetes-sigs/cluster-api/issues/8038
Good to follow how they plan to do it!

**Comment by mdbooth** [comment]
Yep, lets get on this!

**Comment by mdbooth** [comment]
I think we're at the stage where we can just go ahead and do this. clusterctl now upgrades storage versions when upgrading, so this should be safe. I believe anybody running v0.7 will already have been upgraded to v1alpha6.

That said, I haven't tested this, I haven't read the code, and I'm not 100% confident of my assertions here. It would be good to gain this confidence before doing the removal.

@tobiasgiese You expressed concerns before. Any thoughts?

**Comment by jichenjc** [comment]
>>>That said, I haven't tested this, I haven't read the code, and I'm not 100% confident of my assertions here. It would be good to gain this confidence before doing the removal.

I think less likely users stay on too old version we should support .. 
they should consider upgrade and not sure whether CAPI itself has supported list (e.g N-2 or N-3?)
