### ISSUE TITLE
Request for Yoga CI Testing/Compatibility Report

### ISSUE THREAD

**Issue by thg-adamdean** [kubernetes-sigs/cluster-api-provider-openstack#1332]
/kind feature

**Describe the solution you'd like**
Currently the most recent release tested is Xena, would it be possible to bump this to Yoga? (March) 

**Anything else you would like to add:**
Does Canada store all its hate in Geese?

**Comment by tobiasgiese** [comment]
This was already done by PR https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1329 today 🙂

**Comment by tobiasgiese** [comment]
And the readme will be updated with https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1331
