### ISSUE TITLE
CA cert not optional

### ISSUE THREAD

**Issue by Xartos** [kubernetes-sigs/cluster-api-provider-openstack#1334]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Installing the capo controller according to the quick start guide and trying to apply a new cluster that uses an openstack `auth-url` that is signed by a public cert doesn't work.

I get the following error when I'm not including a `cacert` in the identityRef secret:

```
E0902 09:42:07.525365       1 controller.go:317] controller/openstackmachine "msg"="Reconciler error" "error"="providerClient authentication err: Get \"https://foo.bar.baz:5000/\": x509: certificate signed by unknown authority" "name"="ck8s-test-sc-worker-m5zf9" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine" 
```

If I add the public root CA to the secret it will work.

**What did you expect to happen:**

According to [this document](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/v0.6.3/docs/book/src/clusteropenstack/configuration.md#generate-credentials) the CA cert is optional. 
So the capo-controller should load the system ca certificates and not fail to verify publicly signed certificates.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.6.3
- Cluster-API version: v1.2.0
- OpenStack version: Unknown
- Minikube/KIND version: 0.14.0
- Kubernetes version (use `kubectl version`): v1.24.0
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04

**Comment by jichenjc** [comment]
that optional means http/https, if it's http, the CA is optional, https CA is mandatory
I will update the doc soon

**Comment by Xartos** [comment]
> that optional means http/https, if it's http, the CA is optional, https CA is mandatory I will update the doc soon

Aaah, yea that kind of makes sense.

But I still think that trusting system CAs also would be great, or is there a reasoning for not doing that?

**Comment by jichenjc** [comment]
>>>But I still think that trusting system CAs also would be great, or is there a reasoning for not doing that?

it's openstack issue, you set openstack endpoint to https, then we need CA here
it's not CAPO's choice

**Comment by Xartos** [comment]
> > But I still think that trusting system CAs also would be great, or is there a reasoning for not doing that?
> 
> it's openstack issue, you set openstack endpoint to https, then we need CA here it's not CAPO's choice

Gotcha

**Comment by jichenjc** [comment]
I will close this issue and feel free to reopen :)
