### ISSUE TITLE
nil pointer if `osc.status` is empty (clusterctl move) and apiserver access is restricted

### ISSUE THREAD

**Issue by bavarianbidi** [kubernetes-sigs/cluster-api-provider-openstack#1339]
/kind bug

The current unreleased CAPO code contains a bug (introduced by myself :see_no_evil: ) which only occurs during `clusterctl move` and maybe during some `CR` restore procedure

**What steps did you take and what happened:**

If a cluster has restricted API access configured (introduced in PR #1247 ) and the `osc.status` is empty, the reconciliation might fail due a nil-pointer, caused by the following lines https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/loadbalancer/loadbalancer.go#L231-L237

**What did you expect to happen:**

No nil-pointer

**Anything else you would like to add:**
Possible implementations:
1. check if `osc.status` is empty and not calling [`getOrUpdateAllowedCIDRS`](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/loadbalancer/loadbalancer.go#L221)
2. ignore `openStackCluster.Status.Network.Subnet.CIDR` and `openStackCluster.Status.Network.Router.IPs` during the reconciliation with empty `status` (will lead to the following behavior: `routerIP` and `SubnetCIDR` is configured on the `allowedAddressPair` field in Openstack, will be removed during the `clusterctl move` and than added back again)

Option 1 seems to me as the best approach. As it doesn't change anything on Openstack side during the first reconciliation after `clusterctl move` was triggered. Once the `osc.status` got filled up again, it should be ok to update the `allowedAddressPair` field in Openstack.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): `058f560669885cdec0487ce043bdb0408d559818`
- Cluster-API version: `v1.1.2`
- OpenStack version: 
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by bavarianbidi** [comment]
> Option 1 seems to me as the best approach. As it doesn't change anything on Openstack side. 

If this seems to be an acceptable solution i will implement this change to get this fix into the next CAPO release.

**Comment by tobiasgiese** [comment]
> If this seems to be an acceptable solution i will implement this change to get this fix into the next CAPO release.

Sounds totally fair to me 👍🏻

**Comment by jichenjc** [comment]
>>>Option 1 seems to me as the best approach. As it doesn't change anything on Openstack side during the first reconciliation after clusterctl move was triggered. Once the osc.status got filled up again, it should be ok to update the allowedAddressPair field in Openstack.

 Curious why it's related to `cluster move` as move just move the k8s objects from bootstrap to created openstack cluster..
but yes, we should avoid nil point and checking the status field is reasonable

**Comment by bavarianbidi** [comment]
> Curious why it's related to `cluster move` as move just move the k8s objects from bootstrap to created openstack cluster.. but yes, we should avoid nil point and checking the status field is reasonable

The `status` field wont get moved during `clusterctl move` (https://cluster-api.sigs.k8s.io/reviewing#controller-reentrancy). Maybe there are more use-cases where the `status` could be empty but to be honest i don't know any real world use-case yet (e.g. some backup-and-restore implementations will drop the `status` field)

**Comment by jichenjc** [comment]
>>>The status field wont get moved during clusterctl move

THanks, I missed this point :)
