### ISSUE TITLE
Impossible to have port security on with no security groups

### ISSUE THREAD

**Issue by mkjpryor** [kubernetes-sigs/cluster-api-provider-openstack#1341]
/kind bug

**What steps did you take and what happened:**

I set `disablePortSecurity: false` and `securityGroups: []` on a port, and the port got the default security groups for the instance.

**What did you expect to happen:**

The port to have port security on but no security groups.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Having this will allow us to have all the anti-spoofing bits, e.g. allowed address pairs, without having to have security groups. This is important for some high-performance use cases.

**Comment by jichenjc** [comment]
>>>I set disablePortSecurity: false and securityGroups: [] on a port, and the port got the default security groups for the instance.

I don't remember correctly, but openstack seems honor `default` settings, so if you didn't give a sec group
default in that tenant will be used, maybe create a sec group with different name and no rules (e.g sec group `no_rule`)
and try again might help

**Comment by mdbooth** [comment]
@mkjpryor We add them from the cluster object if they're defined there: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/18226ed88988b360f3cc88ad54960c08255ff43a/controllers/openstackmachine_controller.go#L524-L537

Do you have any defined on the cluster?

**Comment by EmilienM** [comment]
I've hit the issue today. I'll investigate a fix.
