### ISSUE TITLE
Failed to pull k8s.gcr.io/coredns:v1.9.3

### ISSUE THREAD

**Issue by criscola** [kubernetes-sigs/cluster-api-provider-openstack#1348]
/kind bug

**What steps did you take and what happened:**

I created a cluster using CAPO. Control plane fails initialization and shows error `k8s.gcr.io/coredns:v1.9.3 not found`.

**What did you expect to happen:**

Control plane on CAPO would be initialized successfully on CAPO cluster.

**Anything else you would like to add:**

Related issue upstream: https://github.com/kubernetes/kubernetes/issues/112131

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): OpenStack Provider v1alpha6
- Cluster-API version: v1.2.2
- OpenStack version: 18.0.0
- Minikube/KIND version: 0.15.0
- Kubernetes version (use `kubectl version`): Client Version: v1.24.4, Kustomize Version: v4.5.4 Server Version: v1.25.0
- OS (e.g. from `/etc/os-release`): ubuntu 20.40 built from image-builder repository.

**Comment by jichenjc** [comment]
>>> fails initialization and shows error k8s.gcr.io/coredns:v1.9.3 not found.

CAPO doesn't penetrate into that detail, CAPO(CAPI) use kubeadmin as control plan  I think coredns is come from kubeadm init process and maybe your version 1.9.3 doesn't exist? or failed to pull might also mean network issue ?
anyway, I Think it's not CAPO's issue

**Comment by mdbooth** [comment]
This appears to be an issue with the coredns image on k8s.gcr.io.

It might be worth talking to the coredns project in case they're able to fix it.

Alternatively, as this affects everybody using kubeadm it might be worth talking to the kubeadm project to see if they have a workaround.
