### ISSUE TITLE
Additional e2e tests for various scenarios

### ISSUE THREAD

**Issue by lentzi90** [kubernetes-sigs/cluster-api-provider-openstack#1363]
/kind feature

**Describe the solution you'd like**

Currently, the [e2e tests](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/test/e2e/suites/e2e/e2e_test.go) mainly check that it is possible to create (and delete) clusters with various configurations.
However, we have no  tests for things like upgrading CAPO from older releases or [pivoting into a self hosted cluster](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/e2e/self_hosted.go) (`clusterctl move`).

Luckily, CAPI has already [implemented some test specs](https://github.com/kubernetes-sigs/cluster-api/tree/main/test/e2e) for these scenarios and more.
They can be easily reused in CAPO for validating the functionality.
I would like to add some of these tests to CAPO.

Now the question is when and how to run the tests.
I think it may be too much to ask to run them automatically on all PRs, so perhaps a periodic or manually triggered jobs would be better?
For example we could make sure to run it before every release.

**Anything else you would like to add:**

I have started working on this already but thought it would be better to discuss it a bit in an issue first.
Will open a PR once I have something more substantial.

**Comment by jichenjc** [comment]
>>>However, we have no tests for things like upgrading CAPO from older releases or [pivoting into a self hosted cluster](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/e2e/self_hosted.go) (clusterctl move).

FYI, I proposed this before but folks think it's a CAPI function , should not be part of CAPO
but I am still in favor of add such 

>>>For example we could make sure to run it before every release.

our internal dev for other projects has weekly run on one time effort job to avoid put too much effort in every PR
not sure this is doable here

**Comment by lentzi90** [comment]
Adding here some findings from working on clusterctl upgrade tests.

1. The CAPI [clusterctl upgrade test spec](https://github.com/kubernetes-sigs/cluster-api/blob/release-1.2/test/e2e/clusterctl_upgrade.go) is a bit special since it creates not just a workload cluster, but a secondary management cluster also. The flow goes like this: Bootstrap cluster -> create secondary management cluster with older CAPI/CAPO -> create workload cluster -> clusterctl upgrade -> scale workload cluster. The reason for this is to avoid any issues with parallel jobs requiring different versions so the bootstrap cluster can be shared.
2. Due to the above, we cannot use the normal way of loading the e2e artifacts. (It works only for the bootstrap cluster, not the secondary management cluster.) In other words, we need a way to build, upload and pull at least the CAPO container if we want to test the latest code. My current idea is to enable swift in the devstack and upload the image there. It can then be pre-pulled via cloud-init on the nodes.
3. Where to draw the line? Do we want to test v0.5? v0.4? v0.3? The older releases makes things a bit complicated for two reasons.
   1. We get different combinations of CAPI/CAPO API versions so it is no longer enough to have just [v1alpha5 or v1alpha6](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/tree/main/kustomize) like we do now. Instead we would need separate CAPI v1alpha4 + CAPO v1alpha4 and CAPI v1beta1 + CAPO v1alpha4 for example. Perhaps the most sensible thing would be to create kustomizations per minor release instead of API versions in that case?
   2. v0.5 and older do not support the newest OpenStack versions. This is not a problem in itself but if we want to test the upgrade with the latest OpenStack version for v0.6 then we need to separate the upgrade tests depending on what they support.

**Comment by jichenjc** [comment]
>>>Where to draw the line? Do we want to test v0.5? v0.4? v0.3

maybe we can ask in the slack channel to get input from current users
usually for simpility we might only want to use latest stable release (0.5 in our case)

>>> In other words, we need a way to build, upload and pull at least the CAPO container if we want to test the latest code. My current idea is to enable swift in the devstack and upload the image there. It can then be pre-pulled via cloud-init on the nodes.

not sure it's doable (as need more explore into this scenario) how about create a local registry in the bootstrap cluster?
or through cloud-init to write some script to build the containers?

**Comment by lentzi90** [comment]
/remove-lifecycle stale
This is progressing nicely in the linked PRs. One the two remaining PRs are merged we can close this.

**Comment by seanschneeweiss** [comment]
All linked PRs are closed - anythin left here? Or can we close?

**Comment by lentzi90** [comment]
Good point! Closing
/close
