### ISSUE TITLE
Ability to mount additional volumes

### ISSUE THREAD

**Issue by mnaser** [kubernetes-sigs/cluster-api-provider-openstack#1365]
/kind feature

**Describe the solution you'd like**
There is no way to allow the user to mount/create a specific volume with a MachineTemplate.  An example of this would be someone who wants to mount `/var/lib/containers` or `/var/lib/etcd` on a different volume with a different volume type.

**Anything else you would like to add:**
Not much :)

**Comment by mdbooth** [comment]
@mnaser This is specifically on my todo list!

**Comment by jichenjc** [comment]
is this simliar to https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1286 ?

**Comment by mdbooth** [comment]
It is. I'll close this one as a dup as the other has more info in it. I'll also retitle the other one.
