### ISSUE TITLE
Ability to select the interface to contact openstack apis

### ISSUE THREAD

**Issue by IDerr** [kubernetes-sigs/cluster-api-provider-openstack#1368]
/kind feature

**Describe the solution you'd like**
Add a way to select which interface to use when contacting openstack api, by default, it'll use the public interface with gophercloud,
but in some cases, from internal enterprise network, it's only possible to hit the intenal interface.

**Anything else you would like to add:**
I think I can try to add the Availability parameter in all clients functions, but not sure on my side
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/c2593345fcbf829b54670df1aff0240ae1a3b551/pkg/clients/compute.go#L67

Thanks for your work !

**Comment by mdbooth** [comment]
This sounds like a good feature. We'd need a design for it, but I'm in favour.

**Comment by jichenjc** [comment]
+1 to this , I think we can refer to https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/openstack/openstack.go#L156
 and its assoiciated code/design..
