### ISSUE TITLE
Propose new release

### ISSUE THREAD

**Issue by mnaser** [kubernetes-sigs/cluster-api-provider-openstack#1373]
/kind bug

**What steps did you take and what happened:**
There hasn't been a release since May and we're in November now, there's a few critical fixes such as the following which at least hits us:

- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1250
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1295 (for `ClusterTopology`)

Could we look into a new release?

**Comment by jichenjc** [comment]
agree we should have a newer version ,e.g 0.6.4 
I will take this as a todo but not sure I can handle soon
if someone want to create release ,feel free to do it or I will come back in 1-2 days to do the release

**Comment by mnaser** [comment]
@jichenjc is this something I can help with or it's a maintainer sort of task?

**Comment by jichenjc** [comment]
@mnaser all the process are open, but I think one step (create tag or something ?) need privilege 
I don't remember clearly on this but I will make sure I create release soon

**Comment by jichenjc** [comment]
https://github.com/kubernetes/k8s.io/pull/4436/files proposed 
need a lgtm there 

detailed container info 
https://console.cloud.google.com/gcr/images/k8s-staging-capi-openstack/global/capi-openstack-controller@sha256:3f5be9474b9c653a7bb4e86f72f8f5ce92726d6a25e612f08775a313c100225d/details

**Comment by seanschneeweiss** [comment]
I would like to include #1301 in the release - as discussed in the Office Hours. This is the only issue in the milestone https://github.com/kubernetes-sigs/cluster-api-provider-openstack/milestone/4

**Comment by jichenjc** [comment]
looks like not merged yet, I already created a tag, how about create 0.6.5 soon ?

**Comment by seanschneeweiss** [comment]
It's merged now.

**Comment by seanschneeweiss** [comment]
#1301 cannot be cherry-picked into 0.6 as it requires v1alpha6. So waiting for the next minor release 0.7. I guess it is then OK to continue with 0.6.4.

**Comment by jichenjc** [comment]
try this please 

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.6.4
```
# docker pull gcr.io/k8s-staging-capi-openstack/capi-openstack-controller:v0.6.4
v0.6.4: Pulling from k8s-staging-capi-openstack/capi-openstack-controller
8fdb1fc20e24: Pull complete
0df751480165: Pull complete
Digest: sha256:3f5be9474b9c653a7bb4e86f72f8f5ce92726d6a25e612f08775a313c100225d
Status: Downloaded newer image for gcr.io/k8s-staging-capi-openstack/capi-openstack-controller:v0.6.4
gcr.io/k8s-staging-capi-openstack/capi-openstack-controller:v0.6.4



```
