### ISSUE TITLE
IPAM support for CAPO

### ISSUE THREAD

**Issue by geetikabatra** [kubernetes-sigs/cluster-api-provider-openstack#1377]
/kind feature
Umbrella issue for all tasks required to implement IPAM support for CAPO
This issue will be updated over time

- [ ]  IPAM Contract implementation - https://github.com/kubernetes-sigs/cluster-api/pull/6313

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by hiromu-a5a** [comment]
Hi, I am interested in this feature. Is there any roadmap for the implementation?

**Comment by mdbooth** [comment]
There is not, but I am also interested in it.

Out of curiosity, what is your use case? Why is this better than DHCP in your circumstances?

**Comment by bl0m1** [comment]
I could se this being used to manage public IPs. I currently looking into the possibility of having a list(or range) of public IP-addresses that could be assigned to workers. The reasons for this is to have a known source IP on each worker allowing for whitelisting at a 3rd party.

I'm willing looking into implementing the IPAM API however it would be good to know what use cases others have.

/remove-lifecycle rotten

**Comment by hiromu-a5a** [comment]
Sorry for the delayed response.
For some historical reasons, our environment uses many fixed IPs, and IPs are used to connect services that are geographically isolated. We need to be aware of which IPs are used in which machines and by which services. DHCP is not enough to cover this use case.

**Comment by mdbooth** [comment]
Example use in CAPV: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/a5feda0b204f3351da0c16ba8cde82921d434025/apis/v1beta1/types.go#L321-L325

**Comment by mdbooth** [comment]
Tracked in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1750
