### ISSUE TITLE
Reconcile Amphora Loadbalancer for Workload Cluster API access

### ISSUE THREAD

**Issue by cunningr** [kubernetes-sigs/cluster-api-provider-openstack#1382]
/kind feature

**Describe the solution you'd like**

We currently deploy clusters with a highly available k8s control-plane behind an Openstack Amphora Loadbalancer instance.  The Amphora service itself is deployed with a single instance and is subject to failures in the Openstack layer.  It would be desirable in some circumstances to be able to rebuild the Openstack Loadbalancer from scratch without having to redeploy the entire k8s cluster.

**Anything else you would like to add:**

We could help to test such a solution.

**Comment by anaperic** [comment]
It can easily happen that one loses OpenStack compute node where amphora is located in which case one does not have much options restoring from such an operation.

We appreciate any guidance on this matter.

**Comment by seanschneeweiss** [comment]
This should actually be possible by just deleting the faulty load balancer `openstack loadbalancer delete --cascade <lb-id>`. CAPO will reconcile and create a new load balancer.

**Comment by seanschneeweiss** [comment]
Closing for now, feel free to re-open the issue.
