### ISSUE TITLE
Gophercloud error provisioning cluster on cloud with no external networks

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1383]
/kind bug

**What steps did you take and what happened:**
Only reproduced in the simulator using the default 'cluster-template' release template. The simulated cloud had no external networks.

[`ReconcileExternalNetwork`](https://github.com/Nordix/cluster-api-provider-openstack/blob/38027fbd81c44a1263eb3bf027dbe2005b76649f/pkg/cloud/services/networking/network.go#L44-L45) does not find an external network and [sets an empty external network](https://github.com/Nordix/cluster-api-provider-openstack/blob/38027fbd81c44a1263eb3bf027dbe2005b76649f/pkg/cloud/services/networking/network.go#L75-L79). This later results in an error [creating a floating IP](https://github.com/Nordix/cluster-api-provider-openstack/blob/38027fbd81c44a1263eb3bf027dbe2005b76649f/pkg/cloud/services/networking/floatingip.go#L50-L54):

```
ERROR Reconciler error err="failed to reconcile load balancer: CreateFloatingIP: creating floating ip map: Missing input for argument [FloatingNetworkID]" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" openStackCluster="default/test-cluster" namespace="default" name="test-cluster" reconcileID=dc998a46-3295-41fb-81d6-36f7ea3be595
```

**What did you expect to happen:**
Not sure, but definitely something else. What do with do with the API in a network with no external networks? If we can't do anything correct we should give a sensible validation failure.

**Comment by jichenjc** [comment]
>>>Only reproduced in the simulator using the default 'cluster-template' release template

you mean with default template? I think our CI covers this logic (find external network and use it)?
curious but if we can provide the exact yaml used might be helpful ?
