### ISSUE TITLE
clusterctl --init on Target-Cluster

### ISSUE THREAD

**Issue by PatrickLaabs** [kubernetes-sigs/cluster-api-provider-openstack#1388]
/kind bug

**What steps did you take and what happened:**
Hi erveryone,
I startet a DevStack OpenStack Environment from the Yoga Release.
Followed the Quick-Start Guide the OpenStack Provider.
Everything is working fine so far, but i experienced a weird behaviour...

As I wanted to init the targeting Cluster inside my OpenStack environment, it took ages to deploy. 
So i gave it some time and the 'clusterctl init' command showed me green lights.

I watched the deployment of the pods, and the Pods for the 'capi-kubeadm-bootstrap-controller-manager' and the ' capo-controller-manager' always restartet (almost 15 times) and by describing I noticed, that the probes are failing.. So i started to find out what was happening.

Inside the Pods-Yaml definitions I found out, that Calico assigned these two pods different ip addresses than the others. 
The ones that are failing had '192.168.39.xxx' and the other, that are working, got '192.168.66.xxx'.. 

A little strange, but I just changed the assigned ip addresses inside the yamls of the pods and let k8s create new ones.
And tada, its working.

I am just a little bit confused now, since I don't get it, why they got a differend ip address.
Has anyone experienced the same? 
Is this expected and my OpenStack configuration is just missing something?

**What did you expect to happen:**

I expected that
'capi-kubeadm-bootstrap-controller-manager'
and 
'capo-controller-manager' 
are getting the same ip adr. as the other (working) pods got.

**Environment:**
It is a DevStack environment from the Yoga Release.

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): Not sure where to find it? :( 
- Cluster-API version: v1.2.5
- OpenStack version: Yoga
- Minikube/KIND version: v0.17.0
- Kubernetes version (use `kubectl version`): 1.22.1
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.5 LTS Focal

**Comment by jichenjc** [comment]
>>>Inside the Pods-Yaml definitions I found out, that Calico assigned these two pods different ip addresses than the others.
The ones that are failing had '192.168.39.xxx' and the other, that are working, got '192.168.66.xxx'..

I think it's less likely that openstack got some problem
just curious whether it's CNI issue 

maybe worthy check CAPO logs as well but no reason why different IP set lead to issue
192.168.39. is not a well known IP range to me ..

**Comment by mnaser** [comment]
indeed, this sounds like a CNI issue and not a CAPO issue to be honest.

**Comment by PatrickLaabs** [comment]
Thanks for your reply.
I was also guessing it's more coming from CNI.
I will do some more testing, maybe I find out if why exactly this is happening 🤔

Shall I close this issue for now?

**Comment by jichenjc** [comment]
we can keep this open for a while, if no clue or found it's CNI issue, we can close it later on(e.g a few weeks)
