### ISSUE TITLE
Baremetals as k8s nodes 

### ISSUE THREAD

**Issue by RakeshAMD** [kubernetes-sigs/cluster-api-provider-openstack#1389]
/kind feature

**Describe the solution you'd like**
By default this provider is picking only VM's for creating nodes. we also need baremetal (ironic) as k8s nodes

**Comment by jichenjc** [comment]
I think you might want to check https://metal3.io/

**Comment by mnaser** [comment]
Wouldn't it also work out of the box if you deployed using a bare metal flavour using Nova?

As long as you use Nova and a flavour that boots BM, I thin kit should work ok.

**Comment by RakeshAMD** [comment]
@mnaser , yes you are absolutely right.
