### ISSUE TITLE
Deprovisioning Improvements

### ISSUE THREAD

**Issue by spjmurray** [kubernetes-sigs/cluster-api-provider-openstack#1392]
/kind feature

**Describe the solution you'd like**
I may be missing something here, so please let me know!

Typically when you provision things it's a case of `clusterctl generate cluster | kubectl apply -f -`, and to deprovision you'd expect just to just do the same in reverse.  It's a similar kind of model with Helm, create all the things, then delete all the things.

One thing I noted was that doing so deletes the openstack credentials secret, no secret means the CAPO controller cannot talk to openstack to remove the openstack resources, thus you are in a deadlock situation.

My initial thought here would be to add a finalizer to the secret and release it when all the openstack* resources are done with.  At the moment I kinda hack it by saying "delete all the things, except the secret", which is functional, but not really idiomatic.

**Anything else you would like to add:**
Quite happy to author this and drive it if/when a technical solution can be agreed upon.

**Comment by mdbooth** [comment]
Thanks for this and the PR! The finalizer approach seems entirely reasonable to me. However, I wonder if this issue is common to multiple/all providers and it requires/already has a common solution.

I don't know the answer, though. I've asked in CAPI slack here: https://kubernetes.slack.com/archives/C8TSNPY4T/p1669123067159709

I'd encourage you to join the conversation.

**Comment by mdbooth** [comment]
So... the (quicker than expected!) outcome of that conversation is that this use case isn't supported in CAPI yet: https://cluster-api.sigs.k8s.io/user/quick-start.html?highlight=delete%20-f%20cluster-template.yaml#clean-up

That's disappointing and my personal feeling is that this could be supported. However, I'm hesitant to implement a partial/snowflake solution in CAPO.

Would you mind opening an issue in CAPI instead? If we can agree a common design for handling this in CAPI I'll be very happy to implement that in CAPO. For now the workaround is to delete the cluster first.

**Comment by mdbooth** [comment]
Incidentally @mkjpryor commented in that thread:

> I had a similar issue when deleting clusters creating using Helm (https://github.com/stackhpc/capi-helm-charts) using helm delete.
> 
> I ended up adding the helm.sh/resource-policy: keep annotation to almost all the resources except the CAPI cluster in order to let it control deletion - I think all except MachineHealthCheck and MachineDeployment, which can be deleted during the course of normal operation of the Helm chart.

This might be a better workaround until we agree how to fix this.

Incidentally, I appreciate that you're a first time contributor and asking you to raise another issue in the parent project isn't necessarily the friendliest. However, you also seem to know what you're doing. Are you comfortable raising the CAPI issue and driving the discussion there?

**Comment by spjmurray** [comment]
It's all good, I was kinda expecting a can of worms 😸

**Comment by spjmurray** [comment]
I will say for posterity here -- while musing over a Greggs steak bake -- it may not be entirely unreasonable that secrets be shared, at which point you have multiple references, so a single finalizer may not be the be all and ans end all.

**Comment by mnaser** [comment]
In our case, we actually keep the secret and remove it once the Cluster class is gone, so we have to wait a bit and it feels like a bit of a workaround, the finalizer idea sounds great and feels like it should live in CAPI

**Comment by seanschneeweiss** [comment]
Thank you for bringing this to our attention. Closing the issue in favor of https://github.com/kubernetes-sigs/cluster-api/issues/7624.
