### ISSUE TITLE
CAPO leaks ports if machines can not be created (HTTP 500 NoValidHosts)

### ISSUE THREAD

**Issue by anaperic** [kubernetes-sigs/cluster-api-provider-openstack#1404]
/kind bug

**What steps did you take and what happened:**

Running CAPO 0.6.3 (plus a no_volume patch but this may be irrelevant to what we see).
If CAPO tries to create a machine and OpenStack returns an error (can't create VM) in this process, capo will not clean up the ports.
This means if one reaches the "breaking point" of what OpenStack can create, CAPO will leak the ports till one reaches the quota, or some other limit.
Ports never get cleaned up on 500 HTTP error msg on VM creation.

The order of operation:
1. md is configured to some value of machines that OpenStack can't create
2. md is stuck in ScalingUp state
3. OpenStack returns HTTP 500 (no valid hosts)
4. CAPO deletes the machine properly from the OpenStack but leaves the port
5. This causes ports to leak and eventually hit the quota

Here are some logs:

In this case 11 replicas is a "breaking point" for Openstack (it is able to create 10 machines but not the 11th).
This is what kicks in the port leak avalanche

```
➜  ~ kubectl get md
NAME                  CLUSTER          REPLICAS   READY   UPDATED   UNAVAILABLE   PHASE       AGE     VERSION
test-md-0    test    11         10      11        1             ScalingUp   11d     v1.21.3
```

This OpenStack was brought to it's knees by CAPI creating excessive ports:
(10 real active VMs, other are down leaked ports):
```
root@2481423024b3:# openstack port list  | grep test-md-0 | grep DOWN | wc -l
457
root@2481423024b3:/# openstack port list  | grep lab-sjc3-blue-md-0 | grep ACTIVE | wc -l
10
```

osm/ma showing:
```
status:
  failureMessage: 'OpenStack instance cannot be created: error creating Openstack
    instance: error creating OpenStack instance 4c18a354-1b05-403f-b228-b6cd8bdb6452,
    status changed to error'
  failureReason: UpdateError
```
OpenStack showing 500 (before capi deletes the port):

```
| fault                               | {'code': 500, 'created': '2022-11-28T18:26:18Z', 'message': 'No valid host was found. There are not enough hosts available.', 'details':
```

### CAPO logs (one example of one failed VM / leftover port):

```
I1128 18:22:15.237468       1 openstackmachine_controller.go:97] controller/openstackmachine "msg"="Machine Controller has not yet set OwnerRef" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:15.345805       1 openstackmachine_controller.go:97] controller/openstackmachine "msg"="Machine Controller has not yet set OwnerRef" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:15.450520       1 openstackmachine_controller.go:97] controller/openstackmachine "msg"="Machine Controller has not yet set OwnerRef" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:15.498447       1 openstackmachine_controller.go:97] controller/openstackmachine "msg"="Machine Controller has not yet set OwnerRef" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:16.238332       1 openstackmachine_controller.go:293] controller/openstackmachine "msg"="Bootstrap data secret reference is not yet available" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:16.950686       1 openstackmachine_controller.go:293] controller/openstackmachine "msg"="Bootstrap data secret reference is not yet available" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:17.674630       1 openstackmachine_controller.go:300] controller/openstackmachine "msg"="Reconciling Machine" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:17.674670       1 service.go:70] controller/openstackmachine "msg"="failed to create volume service client, no volume related operations allowed" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:18.291380       1 openstackmachine_controller.go:402] controller/openstackmachine "msg"="Machine not exist, Creating Machine" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine" "Machine"="test-md-0-rg6wq"
I1128 18:22:20.122215       1 recorder.go:103] events "msg"="Normal"  "message"="Created port test-md-0-rg6wq-0 with id 3fa740bc-d456-486e-8341-830ab036a78f" "object"={"kind":"OpenStackMachine","namespace":"tenant-capi-mgmnt","name":"test-md-0-rg6wq","uid":"ea9a23da-bd7f-4363-94b2-0a97a74431d9","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha5","resourceVersion":"65612058"} "reason"="Successfulcreateport"
E1128 18:22:32.214637       1 openstackmachine_controller.go:493] controller/openstackmachine "msg"="OpenStack instance cannot be created: error creating Openstack instance: error creating OpenStack instance 34528e59-6c1c-4c6b-aec0-eee89fc40db0, status changed to error" "error"="UpdateError" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:32.214781       1 recorder.go:103] events "msg"="Warning"  "message"="Failed to create server test-md-0-rg6wq: error creating OpenStack instance 34528e59-6c1c-4c6b-aec0-eee89fc40db0, status changed to error" "object"={"kind":"OpenStackMachine","namespace":"tenant-capi-mgmnt","name":"test-md-0-rg6wq","uid":"ea9a23da-bd7f-4363-94b2-0a97a74431d9","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha5","resourceVersion":"65612058"} "reason"="Failedcreateserver"
E1128 18:22:32.238193       1 controller.go:317] controller/openstackmachine "msg"="Reconciler error" "error"="error creating Openstack instance: error creating OpenStack instance 34528e59-6c1c-4c6b-aec0-eee89fc40db0, status changed to error" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:32.924530       1 openstackmachine_controller.go:275] controller/openstackmachine "msg"="Not reconciling machine in failed state. See openStackMachine.status.failureReason, openStackMachine.status.failureMessage, or previously logged error for details" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:33.638860       1 openstackmachine_controller.go:202] controller/openstackmachine "msg"="Reconciling Machine delete" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:33.638902       1 service.go:70] controller/openstackmachine "msg"="failed to create volume service client, no volume related operations allowed" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:36.153249       1 openstackmachine_controller.go:265] controller/openstackmachine "msg"="Reconciled Machine delete successfully" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:36.153332       1 recorder.go:103] events "msg"="Normal"  "message"="Deleted server test-md-0-rg6wq with id 34528e59-6c1c-4c6b-aec0-eee89fc40db0" "object"={"kind":"OpenStackMachine","namespace":"tenant-capi-mgmnt","name":"test-md-0-rg6wq","uid":"ea9a23da-bd7f-4363-94b2-0a97a74431d9","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha5","resourceVersion":"65612239"} "reason"="Successfuldeleteserver"
E1128 18:22:36.170527       1 controller.go:317] controller/openstackmachine "msg"="Reconciler error" "error"="openstackmachines.infrastructure.cluster.x-k8s.io \"test-md-0-rg6wq\" not found" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
```

This is not the correct behavior and CAPO should clean up the ports if the ma/osm is in error state.
Cleanup of the VM works, but it seems we would delete  ports only on cluster deletion (or some other err scenarios), but not this one.

**What did you expect to happen:**

In the case of 500 message (or any failure to create VM), corresponding port should be deleted.
It may be that CAPO is looking at the server properties in the vm creation flow, but in the case of 500 err message, there are  not port data to be fetched (looking at the code for this).

**Anything else you would like to add:**

### According to instance.go we do garbage collect the ports.
I would have expected that this would work, as the logs do indicate that we detect `infrav1.InstanceStateError` as the instance state, so I would expect that the garbage collection kicks in here:

https://github.com/anaperic/cluster-api-provider-openstack/blob/0648aa47c0396198cf55aaf23de6e7b39bfa5d82/pkg/cloud/services/compute/instance.go#L580-L581

### One similar issues is fixed but only on cluster delete it seems (not tried)

I did see this issue and a fix, that we did not try yet, but it seems this solves only the cluster delete port deletion.
And here we are talking about port deletion upon unsuccessful VM creation.

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1254
There was a previous bug for port leak but this is merged back in 2021 and the 0.6.3 should have this fix:

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/798/files#diff-5e7dbfd52305a21a11fb94fab201062ae2c7b851db93c2a8443a1d82d7aa7936

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
(https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1345)

Manually patched (no_volume PR patch) on top of:
```
commit e103e434b851a2a017445cd581de2145a7ee09e9 (origin/release-0.6, release-0.6)
Merge: ecc4cb10 3f35be7a
Author: ji chen <jichenjc@cn.ibm.com>
Date:   Mon Sep 5 15:45:59 2022 +0800

    Merge pull request #1336 from apricote/remove-myself-0.6

    🌱 remove apricote from reviewers
```

- Cluster-API version: 1.2.1
- OpenStack version: xena
- Minikube/KIND version: n/a
- Kubernetes version (use `kubectl version`): 1.21.3
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.5 LTS

**Comment by jichenjc** [comment]
>>>This is not the correct behavior and CAPO should clean up the ports if the ma/osm is in error state.
Cleanup of the VM works, but it seems we would delete ports only on cluster deletion (or some other err scenarios), but not this one.

>>>In the case of 500 message (or any failure to create VM), corresponding port should be deleted.
It may be that CAPO is looking at the server properties in the vm creation flow, but in the case of 500 err message, there are not port data to be fetched (looking at the code for this).

port life cycle is currently independent of VM and should be independent from design IMO

will the port be deleted during the cluster creation ? if so I think we are fine 
but if the port is kept after clsuter is gone?

**Comment by anaperic** [comment]
@jichenjc thanks for your comment.
Did you mean on the cluster deletion (not the creation)?

I assume that on cluster delete the garbage collection will kick in (but can test next week).

But the real problem here is that if the flow is:
- create port
- create vm and attach the port

the correct deletion sequence needs to be:
- delete vm
- delete port
And do this in both happy path and unhappy path (vm could not be created).

We have a situation where the ports used are limited by two factors:
1. OpenStack quota
2. Available count of PCI-PT interfaces
so we really can't wait for cluster to be deleted so the ports are cleaned up (on the md roll or on the VM creation error).

If any of those is hit, we have unusable cluster that can't either scale up or down, and needs very much manual intervention where one:

1. Pauses reconciliation of the cluster (so that the cluster stuck in scalingUp does not cause an avalanche of new ports)
2. Manually clears up the excessive (detached / not-active) ports from the OpenStack
3. Scales the cluster down to the Machine count that OpenStack can sustain
4. Unpauses the cluster
And this is quite annoying and manual process that can by mistake go wrong once one is in the production.

Besides, I believe that in other situations ports do get cleared up on VM deletion. 
I think the described "port leak" happens only if we OpenStack is unable to create a VM (500 error msg), where CAPO leaves the ports and does not clean them.
I can test this other path one more time.

**Comment by cunningr** [comment]
I think the case we are looking at is described in the code comments here; https://github.com/anaperic/cluster-api-provider-openstack/blob/0648aa47c0396198cf55aaf23de6e7b39bfa5d82/pkg/cloud/services/compute/instance.go#L519

In our case, instead of dangling volumes, we are being left with dangling ports.

**Comment by yankcrime** [comment]
We're hitting this problem as well - in fact it's actually very easy to hit this issue when you're using cluster-autoscaler.

**Comment by jichenjc** [comment]
>>>In our case, instead of dangling volumes, we are being left with dangling ports.

yes, the BFV was introduced recently and I think that's right, we should the port creation with same method for the root volume


and If I remember correctly on previous logic(old design) , the VM might not be able to create at some situation (e.g temporary situation) and we might retry in some cases but the port is not deleted so we can reuse it 
thus we need think about the overall flow ,e.g some thing bad happen, what to clean and where do we retry from ..

need read more code on the original design and logic here as it's long time :)

**Comment by jichenjc** [comment]
I proposed to add logic here https://github.com/anaperic/cluster-api-provider-openstack/blob/0648aa47c0396198cf55aaf23de6e7b39bfa5d82/pkg/cloud/services/compute/instance.go#L519 as above mentioned

and also, if VM creation failed, the port might not be attached to the VM due to it's too early stage
so how about we get all ports from 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/compute/instance.go#L291
then we do the deletion

thoughts?

**Comment by anaperic** [comment]
@jichenjc I think this may work - combining the two above. I think the later will def help in this case we are seeing - get ports by vm name and then delete them (as they are not getting even attached as it may be too early).

**Comment by jichenjc** [comment]
@anaperic I found this logic 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/compute/instance.go#L149

seems we do have a clean up method but guess not collected handled

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/compute/instance.go#L282
should set `server = nil` so we let the defer function handle the port deletion

**Comment by jichenjc** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/compute/instance_test.go#L809

from here, the `not delete` port is intentionly
but I think it might be wrong, I knew in some cases, the port will not be attached the VM e.g no valid 
host, but sometimes it might be , e.g after port attach but later than that process

so I think we might change the logic to avoid that logic, as delete isntance then delete port 
or delete port first seems doesn't matter in our case

**Comment by mdbooth** [comment]
**Unconfirmed theory**: I suspect this may be a difference in behaviour on server delete between a server which has been scheduled to a host and one which has not.

This cleanup code assumes that once we have called CreateServer passing in the port list, deleting the ports will subsequently be handled by nova when the server is deleted. My guess is that this isn't happening for NoValidHost, and we leak the ports.

Honestly I'm not at all sure how valid this assumption is or what caveats it may have. I won't be surprised to discover that it's a bug in nova or an invalid assumption in our code.

I suspect the root volume cleanup is more robust, but honestly I'm not a huge fan of that code either. I think we can do better here. Ideally we shouldn't be deleting ports here at all, and always ensuring they're cleaned up in DeleteInstance.

**Comment by mdbooth** [comment]
That's not it, sorry. The problem is that we're assuming on deletion that the ports are attached. If the server was not created successfully then the ports are not attached. We need that to be more robust.

**Comment by cunningr** [comment]
Makes sense @mdbooth.  Just to note another subtlety of Openstack; If you create your port explicitly, outside of the instance creation, and the then attach the port at instance creation time (I think this is what we do here), which you might want to do for various reasons, simply deleting the instance will not delete the port.  If you create an instance and just specify the network(s) to attach to and let Openstack create the ports with default settings, simply deleting the instance will also clean up those ports.

**Comment by mdbooth** [comment]
To correct my previous comment: the code assumes that once we have called CreateServer passing in a port list, a subsequent list of attached interfaces will return those same ports. This assumption is invalid. Specifically it is incorrect when creation fails with NoValidHosts.

**Comment by mdbooth** [comment]
I think there was a suggestion earlier that we could use `getPortName` to delete the ports by name in DeleteInstance (apologies if I misunderstood). We could make that work, but it creates an upgrade problem:

The names of the created ports is not just a function of [`getPortName`](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/e3167e80e5221bd296338e7656ef8bd858b26b37/pkg/cloud/services/compute/instance.go#L291-L297), but also [`constructNetworks`](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/e3167e80e5221bd296338e7656ef8bd858b26b37/pkg/cloud/services/compute/instance.go#L50-L128). The latter is currently 78 moderately complex lines of code. Any change in this code which altered its output, even by reordering, could result in a different set of port names. This would mean that a Machine created before the change would leak ports if deleted after the change. I think it would be futile to try to maintain this as a robust interface: we would almost definitely break it eventually.

I think we have to store the output somehow. Specifically I think it makes most sense to store the list of created ports.

**Comment by jichenjc** [comment]
>>>This would mean that a Machine created before the change would leak ports if deleted after the change. I think it would be futile to try to maintain this as a robust interface: we would almost definitely break it eventually.

the proposal is to use name prefix, with following name creation convention , we can delete port with `instanceName-`prefix... in this tenant, so I am not sure why this won't work or break by constructNetworks function?
```
return fmt.Sprintf("%s-%d", instanceName, netIndex)
```

and I agree we may record the ports created somewhere, e.g into Instance.Status so with that we can delete those ports one by one when we do DeleteInstance, but given we already have such logic:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1413/files#diff-5e7dbfd52305a21a11fb94fab201062ae2c7b851db93c2a8443a1d82d7aa7936L281

if the port is associated with instance, the delete instance action will delete the ports anyway , so all the handling here is about the error case, so if error in create instance, we delete all resources that used for create instance, otherwise delegate the lifecycle to the VM lifecycle handles..

**Comment by mdbooth** [comment]
The whole function is:

```golang
	if opts != nil && opts.NameSuffix != "" {
		return fmt.Sprintf("%s-%s", instanceName, opts.NameSuffix)
	}
	return fmt.Sprintf("%s-%d", instanceName, netIndex)
```

so it already depends on more than just the instance name, and we've changed it in the past. The name may be dependent on some option specific to the port which we may change again in the future.

On top of that, constructNetworks is pretty complex. Any change we made which changed the order of the ports it returns could break this. We've done this before, too.

This code is already janky and hard to reason about. I feel like this is an apparently simple fix which is only simple as long as everybody touching it remembers a whole lot of non-local context. In practise that makes it a much more complex fix than just stashing a list of the ports we created somewhere.

I don't think this needs to be very complex, btw. If I were coding this I think I'd pull port creation out of CreateInstance into CreatePorts. Controller pseudocode:

```
// Upgrade case
if instance exists and status.ports is empty {
  set status.ports from ListAttachedInterfaces
  return for re-reconcile
}

// Create case
if status.ports is empty {
  status.ports = CreatePorts()
  return for re-reconcile
}

CreateInstance(..., status.ports)
```

In DeleteInstance we can just use status.ports because we know it was always set by the controller before invocation, even in the upgrade case.

The only edge case I can think of here is when we fail to update the status after port creation. This is mitigated because we use getOrCreate. Because we reconcile again immediately we're almost guaranteed to be running the same code as the previous reconcile, so the opportunity for leaking resources when changing this interface is extremely limited.

**Comment by jichenjc** [comment]
>>>In DeleteInstance we can just use status.ports because we know it was always set by the controller before invocation, even in the upgrade case.

yes I think it make sense to record all ports we created and upgraded so we can delete them in a batch mode

>>>return for re-reconcile

ok, let's give a try on this logic ..
