### ISSUE TITLE
Ubuntu image for e2e workload clusters is outdated

### ISSUE THREAD

**Issue by tobiasgiese** [kubernetes-sigs/cluster-api-provider-openstack#1407]
/kind bug

**What steps did you take and what happened:**

We have an issue with our ubuntu image where we're not able to update the apt sources due to outdated public keys. To fix this issue we recreate the image via image-builder.

To have updated images we can update the CirrOS image as well.

Error

```
W: GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05 NO_PUBKEY FEEA9169307EA071
E: The repository 'https://apt.kubernetes.io/ kubernetes-xenial InRelease' is not signed.
failed 10 times: apt-get update
```

Example Prow job: [1406/pull-cluster-api-provider-openstack-e2e-test/1599665554006740992](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1406/pull-cluster-api-provider-openstack-e2e-test/1599665554006740992)

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by tobiasgiese** [comment]
Already [built the image locally via image-builder](https://image-builder.sigs.k8s.io/capi/providers/openstack.html) and pushed it to the GCP object storage under https://storage.googleapis.com/artifacts.k8s-staging-capi-openstack.appspot.com/test/ubuntu/2022-12-05/ubuntu-2004-kube-v1.23.10.qcow2

**Comment by tobiasgiese** [comment]
Currently building a new amphora image from `zed` as well. We should update this image with every OpenStack bump as well.
Working on some documentation for this.

**Comment by tobiasgiese** [comment]
@mnaser isn't it better to build the amphora image with every OpenStack release? Or is it fair to say that it's a haproxy image and will not change dramatically?
Currently we're building the image by ourselves and push it to the GCP Cloud Storage.

**Comment by tobiasgiese** [comment]
Btw, the new amphora image is also already uploaded, see https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/0f2169599473951bd3dba6dc8a125ab6065226f4/hack/ci/cloud-init/controller.yaml.tpl#L54-L57

**Comment by mnaser** [comment]
> Btw, the new amphora image is also already uploaded, see https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/0f2169599473951bd3dba6dc8a125ab6065226f4/hack/ci/cloud-init/controller.yaml.tpl#L54-L57

Those images are rebuilt every time there is a change for the Octavia images, so it _should_ be ok, but if you've already built then we're good!
