### ISSUE TITLE
Support value_specs for Ports

### ISSUE THREAD

**Issue by lentzi90** [kubernetes-sigs/cluster-api-provider-openstack#1415]
/kind feature

**Describe the solution you'd like**

We have a need for using [value_specs](https://docs.openstack.org/heat/zed/template_guide/openstack.html#OS::Neutron::Port-prop-value_specs) for Ports. This is an optional map of extra parameters to send as part of the request.

~~Unfortunately, gophercloud does not seem to [want to support this directly](https://github.com/gophercloud/gophercloud/issues/2180).
However, we can still work around that the same way the terraform provider for openstack has done (see [this](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/1db102468904804e2613d02a89d7949474549d71/openstack/types.go#L53-L63) and [this](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/1db102468904804e2613d02a89d7949474549d71/openstack/util.go#L24)).~~

Edit: Gophercloud has added support for value_specs in https://github.com/gophercloud/gophercloud/pull/2537. Now we just need to make use of it and expose it to the users of CAPO.

**Anything else you would like to add:**

**Comment by mdbooth** [comment]
@EmilienM @pierreprinetti @mandre is gophercloud still opposed to adding this? I agree it looks like an ugly API extension point, but it's an *official* ugly API extension point. Could we add it?

**Comment by EmilienM** [comment]
I'm not opposed to it, since OpenStack now provides the API for it.

**Comment by mandre** [comment]
@lentzi90's [patch](https://github.com/gophercloud/gophercloud/pull/2537) to add support for value_specs for ports just landed in gophercloud. Perhaps this can be closed now?

**Comment by lentzi90** [comment]
> @lentzi90's [patch](https://github.com/gophercloud/gophercloud/pull/2537) to add support for value_specs for ports just landed in gophercloud. Perhaps this can be closed now?

We still need a way for users to specify value_specs on the CAPO side. Updated the description to clarify this.
