### ISSUE TITLE
Wrong kubeadm, kubelet versions in e2e tests

### ISSUE THREAD

**Issue by lentzi90** [kubernetes-sigs/cluster-api-provider-openstack#1429]
/kind bug

**What steps did you take and what happened:**

Checking the [cloud-final-log](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/periodic-cluster-api-provider-openstack-e2e-test-main/1605411522220134400/artifacts/clusters/bootstrap/instances/e2e-xlwutp/cluster-e2e-xlwutp-control-plane-5q5mb/) for the periodic e2e tests shows this:

```
Dec 21 04:47:03 cluster-e2e-xlwutp-control-plane-5q5mb cloud-init[648]: [2022-12-21 04:45:34] kubeadm version:  v1.23.10
Dec 21 04:47:03 cluster-e2e-xlwutp-control-plane-5q5mb cloud-init[648]: [2022-12-21 04:45:34] kubectl version:  Client Version: v1.23.10
Dec 21 04:47:03 cluster-e2e-xlwutp-control-plane-5q5mb cloud-init[648]: [2022-12-21 04:45:34] kubelet version:  Kubernetes v1.23.10
Dec 21 04:47:03 cluster-e2e-xlwutp-control-plane-5q5mb cloud-init[648]: [2022-12-21 04:45:34] *************************************************
Dec 21 04:47:03 cluster-e2e-xlwutp-control-plane-5q5mb cloud-init[648]: [2022-12-21 04:45:34] [init] Using Kubernetes version: v1.25.0
```

Note that v1.23.10 is the installed version of kubeadm, kubelet and kubectl even though the test is supposed to run with v1.25.0.
The reason for this can be seen earlier in the log:

```
Dec 21 04:46:42 cluster-e2e-xlwutp-control-plane-5q5mb cloud-init[648]: [2022-12-21 04:45:14] The following packages will be upgraded:
Dec 21 04:46:42 cluster-e2e-xlwutp-control-plane-5q5mb cloud-init[648]: [2022-12-21 04:45:14]   kubeadm
Dec 21 04:46:42 cluster-e2e-xlwutp-control-plane-5q5mb cloud-init[648]: [2022-12-21 04:45:14] 1 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
Dec 21 04:46:42 cluster-e2e-xlwutp-control-plane-5q5mb cloud-init[648]: [2022-12-21 04:45:14] E: Held packages were changed and -y was used without --allow-change-held-packages.
```

**What did you expect to happen:**

The asked version should be installed.

**Anything else you would like to add:**

I'm not sure how it worked before, probably it was either 1) the packages were not marked as "held" or 2) they were not in the image to begin with (fresh install). I'm guessing 1 because the previous image was also named as with a kubernetes version.

**Comment by jichenjc** [comment]
good catch~
guess we didn't pay attention about the test result before. and yes, from naming convention like we installed 1.23.10 
so remove the held should give us a green light to install newer version like 1.25.x

```
/opt/stack/devstack/tools/upload_image.sh https://storage.googleapis.com/artifacts.k8s-staging-capi-openstack.appspot.com/test/ubuntu/2022-12-05/ubuntu-2004-kube-v1.23.10.qcow2
```

**Comment by mdbooth** [comment]
@tobiasgiese How did we build that image?

**Comment by tobiasgiese** [comment]
@mdbooth How I have built the image is (kinda) documented in the PR description of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1408

**Comment by jichenjc** [comment]
I setup in yaml file to be `version: v1.24.2` but got 
```
# kubectl --kubeconfig=./${CLUSTER_NAME}.kubeconfig get node
NAME                                  STATUS   ROLES                  AGE   VERSION
capi-quickstart-control-plane-qx5tx   Ready    control-plane,master   13d   v1.23.10
capi-quickstart-md-0-bvdm2            Ready    <none>                 13d   v1.23.10
```

so, this is not a CI only bug

**Comment by jichenjc** [comment]
I unhold then image and capture the image (so should eligible to install new kubeadm)

I tried locally and seems even though kubeadm define 1.24.2 , my env still create 1.23.10
not sure this is CAPI desired behavior (which is different to what I learned before) or maybe my env got some problem
still checking
```
root@capi-quickstart-control-plane-cbz4l:/var/lib/cloud# cat /run/kubeadm/kubeadm.yaml
---
apiServer:
  extraArgs:
    cloud-provider: external
apiVersion: kubeadm.k8s.io/v1beta3
clusterName: capi-quickstart
controlPlaneEndpoint: 172.24.4.209:6443
controllerManager:
  extraArgs:
    cloud-provider: external
dns: {}
etcd: {}
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.24.2
networking:
  dnsDomain: cluster.local
  podSubnet: 192.168.0.0/16
scheduler: {}

```

**Comment by tobiasgiese** [comment]
> I tried locally with new image and seems even though kubeadm define 1.24.2 , my env still create 1.23.10

The `kubelet` must be updated as well, it's not enough to just update kubeadm.

**Comment by jichenjc** [comment]
>>>The kubelet must be updated as well, it's not enough to just update kubeadm.

yes, I do updated all 3 (kubeadm/kubelet/kubectl)

**Comment by jichenjc** [comment]
>>>The kubelet must be updated as well, it's not enough to just update kubeadm.

yes, I do updated all 3 (kubeadm/kubelet/kubectl)

**Comment by lentzi90** [comment]
@jichenjc not sure if I understood correctly what you are trying to do, but I think there may be a confusion between how e2e works and how "normal" clusters work.

In e2e tests we set `USE_CI_ARTIFACTS=true` (e.g. [here](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/6af7e0193c89a5617fd34e5761b24719a304d697/test/e2e/suites/e2e/e2e_test.go#L81)). This variable is used by [GenerateCIArtifactsInjectedTemplateForDebian](https://github.com/kubernetes-sigs/cluster-api/blob/901d52098e627478064db67592522d8b7f50e7b2/test/framework/kubernetesversions/template.go#L71) that we call [here](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/6af7e0193c89a5617fd34e5761b24719a304d697/test/e2e/shared/suite.go#L81). But this is only true for e2e tests.
What it does is to add the script that @tobiasgiese linked in the preKubeadmCommands. It downloads the correct versions of kubeadm/kubelet/kubectl/ctr.

If you use a "normal" cluster template, this script will not be there and you would always get the versions that were already in the image. In this case the `kubernetesVersion` in `kubeadm.yaml` is not really relevant to what you get, but it is important to keep it the same as what's in the image. Otherwise you may get issues from incompatible versions.

**Comment by FischerLGLN** [comment]
The maximum kubernetes version is related to the kubeadm installed within the image:

https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/packer/config/kubernetes.json
Currently this is 1.23.15.

I tried to use 1.25.5 or 1.26.0 in this json, but somehow the install is still related to the imagerepositoy
k8s.gcr.io, when registry.k8s.io should be used, resulting in API Server not coming up.

**Comment by jichenjc** [comment]
>>>k8s.gcr.io, when registry.k8s.io should be used, resulting in API Server not coming up.

exactly this is what I found when I upgrade to 1.26.0 in my local env 

>>> If you use a "normal" cluster template, this script will not be there and you would always get the versions that were already in the image. In this case the kubernetesVersion in kubeadm.yaml is not really relevant to what you get, but it is important to keep it the same as what's in the image. Otherwise you may get issues from incompatible versions.

yes, I found this as well after read your comments, yes, I think I messed up the 2 versions 
for now, seems use identical version in image w/ kubeadm config seems reasonable and less error leading :)

**Comment by jichenjc** [comment]
I updated this to new registery and it works fine now 

```
kind: KubeadmControlPlane
....
    clusterConfiguration:
      imageRepository: registry.k8s.io


# kubectl get node
NAME                                  STATUS     ROLES           AGE    VERSION
capi-quickstart-control-plane-hgsl4   NotReady   control-plane   2m3s   v1.26.0
capi-quickstart-md-0-lsshq            NotReady   <none>          33s    v1.26.0

```

**Comment by FischerLGLN** [comment]
@jichenjc I didn't know about the setting in the kubeadmcontrolplane, I'll try it out on a test cluster right away!

I want to upgrade a production Capo cluster from 1.23.3 to 1.26.0. 

I have the current resources from an older cluster API version. 
Cluster with apiVersion: cluster.x-k8s.io/v1beta1
OpenStackCluster with infrastructure.cluster.x-k8s.io/v1alpha4

current is v0.6.4
OpenStackCluster with infrastructure.cluster.x-k8s.io/v1alpha5

and still to be released
OpenStackCluster with infrastructure.cluster.x-k8s.io/v1alpha6

What is the best order to do the upgrade?

Just guessing, as I am following Ubuntu OS upgrades:

* Upgrade the apps (ingress-nginx, cinder-csi, etc.) in the downstream cluster to a version just before K8s 1.26 came out (so every app should support at least 1.24).
* Downscale the cluster to support Blue Green upgrades (limited resources Openstack).
* Upgrade the Openstack version of the cluster API infrastructure in the management cluster to support v1alpha5.
* Carefully dry run a new cluster with the same parameters and the new template + move to the new registry.k8s.io.
* Change the infrastructure OpenstackCluster YAML within the management cluster.
* Create a capi image with v1.23.14.
* Roll out the capi image by creating a new YAML with the version and referencing the existing infrastructure to start the upgrade.
* Creating a capi image with v1.24.8
* Rolling out the capi image by creating a new YAML with the version and referencing the existing infrastructure to start the upgrade.
* Creating a capi image with v1.25.5
* Roll out the capi image by creating a new YAML with the version and referencing the existing infrastructure to start the upgrade.
* Creating a capi image with v1.26.0
* Upgrading the apps (ingress-nginx, cinder-csi, etc.) in the downstream cluster to the latest version.
* Roll out the capi image by creating a new YAML with the version and referencing the existing infrastructure to start the upgrade.

@jichenjc Can you correct me where there are still errors in the procedure?

**Comment by lentzi90** [comment]
Issues with image registry could also be related to this: https://github.com/kubernetes-sigs/cluster-api/issues/7833

**Comment by FischerLGLN** [comment]
@lentzi90 Thanks for the related issue, this wrong coredns image url is exactly the error I faced. 
So after updating to v1.24.8 and during updating to v1.25.5 I would set the new registry in the template to inform kubeadm to switch that, since this is becoming the new default.
