### ISSUE TITLE
Option to deploy CAPO to the internal network and create "peering" with another where lives bootstrap cluster or VPN endpoint for users.

### ISSUE THREAD

**Issue by lukasmrtvy** [kubernetes-sigs/cluster-api-provider-openstack#1435]
/kind feature

**Describe the solution you'd like**
Would be superb to have the option to deploy CAPO to the internal network ( not the provider one ) for private use. The problem is that API would not be visible from the bootstrap cluster and the creation process would fail.

But there is a real use case where:
- VPN endpoint is deployed in network1 
- (or/and) K8s ( bootstrap cluster ) is deployed in network1 
- Resources from network1 can allocate Public IPs from external network ( VPN is exposed to the internet, or even K8s ingress, but that's out of the scope )

Possible options:

**Option 1 ( preferred ):**
1. Automatically create internal network2  ( optional ) 
2. Automatically create a router / or use pre-existing router
3. Automatically add interface from network1 ( optional -> `export OPENSTACK_PEER_WITH_NETWORK=network1` ) 
4. Deploy CAPO  ( `export OPENSTACK_USE_PRIVATE_NETWORKING=true` -> mutually exclusive with `OPENSTACK_EXTERNAL_NETWORK_ID`  )

Does it make sense? 

**Anything else you would like to add:**
```mermaid
graph LR
  subgraph ExternalResources
    User -->|VPN network| VPN
    User-.->|cluster create|CAPO
    User-.->|kubectl get pods|ILB
    subgraph OpenStack
        router1<-->|network peering|router2
        K8s-.->|cluster create|CAPO
        subgraph Network1[Network1 - 10.0.0.0/16]
            VPN[Public VPN endpoint]
            K8s[Bootstrap K8s cluster]
            router1((Router))
        end
        subgraph Network2[Network2 - 10.1.0.0/16]
            CAPO[CAPO K8s cluster]
            router2((Router))
            ILB[Internal Load Balancer - API]-->CAPO
        end
    end
  end
```

Related: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1322

**Comment by jichenjc** [comment]
>>>VPN endpoint is deployed in network1

I am wondering whether it's a general CAPI question? as other cloud providers might have same issue (through VPN access)? 
if this is general question I suggest move to CAPI issue discussion.. or it's a CAPO only question(Maybe I misunderstand)?

**Comment by lukasmrtvy** [comment]
@jichenjc Hi, I believe its related to https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1370, but there are few things to pinpoint:
- external network ( `OPENSTACK_EXTERNAL_NETWORK_ID` ) should not be mandatory when deploying CAPO if a custom `RouterName` is selected and `disableAPIServerFloatingIP`  is `true`, as this custom router can handle the default route to the internet and load balancer has still additional IP assigned from `network1`s subnet, so there wouldn't be a need for external network.

- another option would be to create CAPO router ( `OPENSTACK_EXTERNAL_NETWORK_ID` should be still optional ), and add another interface of the custom network to peer with.

**Comment by jichenjc** [comment]
sorry for late reply

>>>Automatically create internal network2 ( optional )
Automatically create a router / or use pre-existing router
Automatically add interface from network1 ( optional -> export OPENSTACK_PEER_WITH_NETWORK=network1 )

I think we can add support pre-existing router thought #1322 first which make sense

>>>external network ( OPENSTACK_EXTERNAL_NETWORK_ID ) should not be mandatory when deploying CAPO if a custom RouterName is selected and disableAPIServerFloatingIP is true, as this custom router can handle the default route to the internet and load balancer would still have additional IP assigned from network1s subnet, so there wouldn't be a need for external network.

yes, I think it make sense, reuse existing router should handle more of the question you have?
with that, the network2 is not required ? the reason is don't want to create unnecessary resources since we already create many ..
