### ISSUE TITLE
Openstack weird keystone error

### ISSUE THREAD

**Issue by stefanpinterBE** [kubernetes-sigs/cluster-api-provider-openstack#1437]
**What steps did you take and what happened:**

- use clusterctl and kind to create a temporary management cluster locally with cluster

`clusterctl init --infrastructure openstack`

- create ubuntu 20.04 image with image-builder and upload it to openstack

- creating a management cluster on openstack (just 1 control plane)
`clusterctl generate cluster $CLUSTER_NAME --kubernetes-version $KUBERNETES_VERSION > $CLUSTER_NAME.yaml
`
- cluster API uses my clouds.yaml credentials to create the openstack objects but from within the instance/VM it fails to authenticate: it says the project does NOT exist, but it does (it even created the instance/VM in it)

**What did you expect to happen:**
kubelet starting on the openstack instance/VM and opening port 6443

**Anything else you would like to add:**
kubelet log:
```
Jan 09 14:40:20 siebetercluster-control-plane-q74m2 kubelet[3520]: E0109 14:40:20.183159    3520 server.go:302] "Failed to run kubelet" err="failed to run Kubelet: could not init cloud provider \"openstack\": Authentication failed"
Jan 09 14:40:20 siebetercluster-control-plane-q74m2 systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
```

keystone.log
`keystone.log:2023-01-09 15:27:30.421 9916 WARNING keystone.auth.core [req-3614ea04-36d7-4737-a19d-eaad9e1b1131 - - - - -] Could not find project: project_spinter.: ProjectNotFound: Could not find project: project_spinter.
`
**Environment:**

- Cluster-api version: 1.3.1
- minikube/kind version: kind v0.17.0 go1.19.2 linux/arm64
- Kubernetes version: Image created by image-build: v1.23.15
- OS (e.g. from `/etc/os-release`): 20.04.5
- Openstack version: rocky

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by mdbooth** [comment]
Looks like your credentials are incorrect.

**Comment by jichenjc** [comment]
>>>failed to run Kubelet: could not init cloud provider \"openstack\": Authentication failed

yes, it's likely either you didn't set pwd correctly or maybe https endpoint didn't provide cert

**Comment by stefanpinterBE** [comment]
> > > > failed to run Kubelet: could not init cloud provider "openstack": Authentication failed
> 
> yes, it's likely either you didn't set pwd correctly or maybe https endpoint didn't provide cert

hi!
thing is, that it created the instance/VM in this exact same project a few minutes earlier.

but then the kubelet service fails with those exact same credentials with an error message that is simply not true, because the project DOES exist.

**Comment by jichenjc** [comment]
no I don't think the log you posted is root cause
I suspect following log is latest 
```
failed to run Kubelet: could not init cloud provider \"openstack\": Authentication failed
```

are you using in-tree cloud provider or external cloud provider ? 
the reason I am ask is https://github.com/kubernetes/cloud-provider-openstack time to time we met simliar question

**Comment by stefanpinterBE** [comment]
i am using the in-tree one i think
keystone is answering a HTTP 401, so this is why i think kubelet says "Authentication failed"

```
2023-01-10 08:44:30.166 18314 WARNING keystone.auth.core [req-56c64d38-d63f-43dc-8a4d-5eb5cc8d7714 - - - - -] Could not find project: project_spinter.: ProjectNotFound: Could not find project: project_spinter.
2023-01-10 08:44:30.166 18314 WARNING keystone.common.wsgi [req-56c64d38-d63f-43dc-8a4d-5eb5cc8d7714 - - - - -] Authorization failed. The request you have made requires authentication. from 172.31.241.102: Unauthorized: The request you have made requires authentication.
```

**Comment by nikParasyr** [comment]
@stefanpinterBE  Are you using domains? and if so have you specified the domain the project is in on your creds? I've hit similar issues when ive miscofigured the domain

**Comment by stefanpinterBE** [comment]
> @stefanpinterBE Are you using domains? and if so have you specified the domain the project is in on your creds? I've hit similar issues when ive miscofigured the domain

hi!
Thank you! :) 
no, everything is in domain "default"

but i was able to make kubelet start by doing this:

i added this to /etc/kubernetes/cloud.conf
tenant-id=61ea50fb392d49b19f2a9889e5a96220

tenant-id was not in there... i wonder how i can make it appear here automatically (i guess cloud-init adds it?)

**Comment by nikParasyr** [comment]
@stefanpinterBE can this be closed then?

**Comment by stefanpinterBE** [comment]
well I needed to add "tenant-id" the way I mentionend. 
i don't know if this should be added via variable by default or documented somewhere.
for me it is working now. thanks again!

**Comment by jichenjc** [comment]
I most use external cloud provider ,so not very sure how in-tree is handling 
FYI, we have 2 places in provide such info 

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/docs/book/src/topics/external-cloud-provider.md
we create cloud-config which contains tenant-id

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/templates/cluster-template-external-cloud-provider.yaml#L4
we create the secret to talk to openstack API endpoint

kubelet issue I guess is related to first one ..but need someone who with in-tree cloud provider experience to help..
