### ISSUE TITLE
Support configurable microversions for optional features like multi-attachable volumes

### ISSUE THREAD

**Issue by lentzi90** [kubernetes-sigs/cluster-api-provider-openstack#1448]
/kind feature

Specifically we have a use case for running CAPO in an OpenStack environment where all volumes are multi-attachable. This requires Nova microversion >2.73 if I'm not mistaken. (Currently CAPO is hard coded to 2.53.)

**Describe the solution you'd like**

Ideally, I think CAPO should work similar to other OpenStack clients in that users should be able to specify the default microversions used. This is normally done either with environment variables or in the `clouds.yaml`:

> A user of the REST layer may set the default microversion by setting `{service_type}_default_microversion` in clouds.yaml or `OS_{service_type|upper}_DEFAULT_MICROVERSION` environment variable.
https://docs.openstack.org/openstacksdk/rocky/user/microversions.html

However, it seems that gophercloud is currently lacking support for this (https://github.com/gophercloud/utils/issues/178).
But this is the way I would like to see things work. We would add support for it in gophercloud and then use the specified version (if any) in CAPO, instead of hard coding it.
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/02a31730ef1ae7962f1cc36c090b624025a2f5bc/pkg/clients/compute.go#L42
If no default version is specified, we could fall back to the minimum supported version in CAPO. Although it would be nice to try to detect the latest version that works instead.

**Comment by jichenjc** [comment]
>>>Ideally, I think CAPO should work similar to other OpenStack clients in that users should be able to specify the default microversions used

yes, I think it's reasonable approach 

>>>But this is the way I would like to see things work. We would add support for it in gophercloud and then use the specified version (if any) in CAPO, instead of hard coding it.

yes, we should add such , guess there are 2 use cases so far 
- we need minimum because mandatory feature like 2.53 in CAPO is for tag which is required 
- there are optional cases like https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/util/openstack/loadbalancer.go#L100 , which is if current version support , we enbale the feature ..

>>>If no default version is specified, we could fall back to the minimum supported version in CAPO. Although it would be nice to try to detect the latest version that works instead.

based on my formal microversion experience, I think it's not that easy to detect the latest version ? 
as if we want to compare, we still have to know which version add the support and that's still hard code

**Comment by mdbooth** [comment]
I think I've said this elsewhere, but just in case: a brief recap.

Microversions define different APIs with different interfaces and different semantics. They are usually (but not always) pretty similar to what came before, but `pretty similar` != `the same`. IOW users don't get to pick supported microversions: developers have to develop against microversions, because they're different APIs.

If we want to support multiple microversions we need to have support in code for multiple microversions. If there's some code which doesn't work with microversion <X or >Y then we need to guard that code appropriately.

That isn't to say we shouldn't do it. Just that:
* It can't be user-configurable
* It's expensive to support and test

If we do it, we should confine it to specific parts of the code. We don't want to change the base microversion everywhere without a lot of testing.

**Comment by dulek** [comment]
To me microversions can be used to detect support for a feature. In this case we'd do multi-attachable volumes if available microversion exceeds 2.73 and then we use 2.73 for such requests directly (as technically microversion can remove support for that too in the future). So it's not support for any microversion, it's a support for certain microversion to do a certain thing supported by that microversion.

**Comment by mdbooth** [comment]
The 'user' in the context of that documentation is the entity making the REST API call, so in that context the user is CAPO. The 'user' (i.e. CAPO) gets to pick the API contract they're expecting.

The problem of giving that to our 'user' is that CAPO expects a certain API contract. If somebody changes that, the CAPO developers (i.e. we) need to have considered that in advance: it's a different API. Setting it in clouds.yaml is useful for a user to define the contract used by their shell tools. They are making their own choice which API contract they are using. But if some tool is going to *consume* the output then that tool had better support the microversion they picked, or it won't work. That's the situation we're in.

Gophercloud doesn't know about it, btw. Gophercloud just marshals and unmarshals whatever is in the request and response. It basically supports a superset of everything and leaves it up to the caller to know what's required in the request and will be returned in the response for a given microversion.

Here's an idea how we could do this, though:

We define a 'base' microversion. This is the absolute minimum we support at all and the default microversion for all code not covered by a feature gate. It's hard-coded, and not user-configurable.

We define a set of feature gates which require a higher microversion, e.g. `tags`. Each feature is associated with a microversion. Code for that feature will:
* Be conditional on the feature being enabled
* Execute API calls for *only that feature* with the higher microversion

All feature gates will be enabled by default, but can be disabled individually on the command line.

**Comment by mdbooth** [comment]
> To me microversions can be used to detect support for a feature. In this case we'd do multi-attachable volumes if available microversion exceeds 2.73 and then we use 2.73 for such requests directly (as technically microversion can remove support for that too in the future). So it's not support for any microversion, it's a support for certain microversion to do a certain thing supported by that microversion.

Good point. If we did the feature gate thing we would already have a map of features to microversions. If we detected the maximum microversion supported by the server it should be trivial to automatically disable non-supported features.

**Comment by stephenfin** [comment]
> > Microversions define different APIs with different interfaces and different semantics. They are usually (but not always) pretty similar to what came before, but `pretty similar` != `the same`. IOW users don't get to pick supported microversions: developers have to develop against microversions, because they're different APIs.
> > If we want to support multiple microversions we need to have support in code for multiple microversions. If there's some code which doesn't work with microversion Y then we need to guard that code appropriately.
> > That isn't to say we shouldn't do it. Just that:
> > ```
> > * It can't be user-configurable
> > 
> > * It's expensive to support and test
> > ```
> > 
> > If we do it, we should confine it to specific parts of the code. We don't want to change the base microversion everywhere without a lot of testing.
> 
> I may not be aware of the full picture here, but my understanding of this is quite different. Probably the core question here is who the "user" is in this case. The user must be able to set the version, but is it CAPO that is the user or is it the user of CAPO that is the user?

It's a bit weird to think about semantically but I'd argue they're *both* users. Both `openstackclient` or `openstacksdk` allow you to request a microversion, but to actually _support_ this microversion they need to be able to understand it. I think it's the same for CAPO. We can allow humans to set arbitrary microversions but if we do then we're opening ourselves up to bugs. Microversions can change absolutely anything - the fields or headers required in a response and provided in a response, the status codes of responses, or even the existence of the API - and unless we plan to evolve CAPO in lock-step with nova's microversion evolution, we can't be sure that we will make a request in the correct format or understand what we get back.

> For reference, [here is a document](https://opendev.org/openstack/nova-specs/src/branch/master/specs/kilo/implemented/api-microversions.rst) about the microversion support in OpenStack. It says the following:
> 
> > Users of the REST API are able to, on a per request basis, decide which version of the API they want to use (assuming the deployer supports the version they want).
> 
> So if CAPO is the user, then CAPO decides the version. But if I'm the user, then I decide the version. In my opinion CAPO is just the tool I use to talk to the API, and so it does not get to decide the version. CAPO may not _support_ all versions though, and that is fine. However, CAPO in itself relies on gophercloud for talking to the API, so I would say that is where the supported/not supported decision should come from.

You the human aren't talking to the (nova) API: you're talking to CAPO. I think CAPO has to be opinionated for the reasons above.

> The other part of this is about support and test. I'm a bit conflicted here honestly, but I'm leaning in the direction of pushing more responsibilities on the user (of CAPO). We can have a default version that is well tested and supported. But users that accept the risk must be able to configure the version without making code changes. There are so many different OpenStack providers out there. Some require a specific minimum version because of their configuration (e.g. required multi-attachable volumes), other run very old versions and cannot support anything recent.

I'm not sure why you would not add that logic to CAPO and upgrade/downgrade capabilities depending on what we're running on? This is what tools like `openstackclient` and libraries like `openstacksdk` do. Nova (and virtually all other OpenStack services) expose their supported versions via the API root so it's certainly possible to know what we can do ahead of time. You can check against your own cluster with `openstack versions show`.

(Also, fwiw, 2.73 is pretty old ([from Train](https://docs.openstack.org/nova/latest/reference/api-microversion-history.html#id66)) - I'd suspect this feature to be pretty widely supported these days)

> I guess what I'm saying is, please allow the version to be set by the user (through the clouds.yaml). This way of setting the version is already supported by other clients. Just as with these other clients, the user must understand the implications when setting specific versions or risk all kinds of issues. But if we don't allow the user to set the version, then we make CAPO unusable in many environments.

Per above, I don't think this is the thing to do. I'd be all for dynamic version configuration but I don't think we should blindly use what a user gives us unless we want to specifically support all microversions (which ideally requires good testing)

> Also, the current behavior is quite surprising if you are used to configuring these things in clouds.yaml. I can set a version, it will not produce any errors, but a completely different version will anyway be used.

We should log that we ignore this.

**Comment by lentzi90** [comment]
Thanks for the comments! I guess I will have to swallow it and start working on those feature gates :slightly_smiling_face: 

Just for the records though, I'm not saying we should claim to *support* any user configurable microversion, I'm saying that CAPO *already* works with multiple versions and that the only thing preventing people from using it is that the version is hard coded. (We have forks for this sole purpose.) So I suggest allowing the user to set the version, while acknowledging that this may break things.

That said, I agree that having feature gates for this sounds like a good way forward to provide explicit support for different versions. My question then would be how to handle versions that *doesn't* impact CAPO directly and how to indicate the version to use?

As an example, the multi-attachable volumes didn't require any changes to CAPO at all, except bumping the microversion. So let's say there is a server that requires a specific version. This version is not the default hard coded version in CAPO, and it doesn't impact CAPO in itself. Then is there a reason to have a feature gate for it, and if not, how would I go about configuring CAPO to use this version?

Detecting what the server requires is of course one way to know what version to use at least. But it is not clear to me how to handle the feature gates to allow CAPO to go outside of the well-tested hard coded version. Would every microversion get their own feature flag (e.g. `--feature-gate-nova-2.73`)?

**Comment by lentzi90** [comment]
Waiting for gophercloud v2
/remove-lifecycle stale
