### ISSUE TITLE
Allow lower microversions for maximum compatibility when explicitly requested

### ISSUE THREAD

**Issue by lentzi90** [kubernetes-sigs/cluster-api-provider-openstack#1449]
/kind feature

There are many ways to configure OpenStack, and there are environments out there that run really old versions or with minimal features enabled. I would like to make it possible to request older microversions than what is officially supported in order to run CAPO in these special environments.

**Describe the solution you'd like**

We currently have [hard coded minimum microversions](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/02a31730ef1ae7962f1cc36c090b624025a2f5bc/pkg/clients/compute.go#L42). Anything below this is not officially supported and actually impossible to use without changing the constant in the code. I don't suggest supporting older versions, but I do think we could make the minimum version easier to configure in special circumstances.

This would allow CAPO to also raise the minimum versions without completely breaking older environments. If, for example, multi-attachable volumes at some point become a "default feature" that CAPO wants to support, the minimum version could be raised. But in environments where this is not needed or available, the user could still ask for a lower version (no guarantees given that it will work though).

**Anything else you would like to add:**

This is related to https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1448, which is about allowing higher versions. Both of these issues could potentially be solved together.

**Comment by mdbooth** [comment]
@lentzi90 Do you want to keep this open?

**Comment by lentzi90** [comment]
Yes!
/remove-lifecycle stale

**Comment by lentzi90** [comment]
Yes, closing
