### ISSUE TITLE
Handle scenario when flavour is too small

### ISSUE THREAD

**Issue by mnaser** [kubernetes-sigs/cluster-api-provider-openstack#1450]
/kind bug

**What steps did you take and what happened:**
When trying to launch a cluster with little number of vCPUs, CAPO does not validate it and therefore the cluster won't build because of `kubeadm` failing with this:

```
[2023-01-17 18:01:50] [preflight] Running pre-flight checks
[2023-01-17 18:01:51] error execution phase preflight: [preflight] Some fatal errors occurred:
[2023-01-17 18:01:51] 	[ERROR NumCPU]: the number of available CPUs 1 is less than the required 2
```

**What did you expect to happen:**
Since this is an expected failure case and the only way to find out that this was broken is by SSH-ing into the system and looking at cloud-init logs, it would be nice for CAPO to simply refuse to spawn the system if the flavour has 1 CPU only.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
yes, this seems to be a valid requirement .. maybe need CAPI to define the kubeadmconfig so that we can obtain from it? (1 is what we know but technically CAPO should not make such definition?)

anyway, we can check flavors and reject such configuration with clear error msg .
