### ISSUE TITLE
Add tags to loadbalancer resources too

### ISSUE THREAD

**Issue by qeqar** [kubernetes-sigs/cluster-api-provider-openstack#1455]
/kind feature

**Describe the solution you'd like**
With v1alpha6 tags where added to nearly all openstack resources, but not to the loadbalancer, pools, listeners and members . 
I would like to have them there too.

Any special reason why this is missing?

**Comment by mdbooth** [comment]
There's likely no good reason they were left out. I would be very much in favour of adding them, and it should (although I haven't checked) be possible to do without bumping the API.

**Comment by qeqar** [comment]
As far as i can tell, the API don't need to be touched, as we would take the tags from OpenstackCluster, like all the other.

So adding tags to the loadbalancer package should be enough, and probably test ;-)

**Comment by mdbooth** [comment]
That's a great point: we would want to inherit the cluster tags in any case so an implementation which only did this would be fine.

Is this something you might be able to contribute?

**Comment by qeqar** [comment]
Yes i will give it try, would be my first real Golang PR....
