### ISSUE TITLE
make lint failing with OOM recently

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1469]
/kind bug

**What steps did you take and what happened:**
Failure looks like:

```
hack/tools/bin/golangci-lint run -v --fast=false
level=info msg="[config_reader] Config search paths: [./ /home/prow/go/src/sigs.k8s.io/cluster-api-provider-openstack /home/prow/go/src/sigs.k8s.io /home/prow/go/src /home/prow/go /home/prow /home / /root]"
level=info msg="[config_reader] Used config file .golangci.yml"
level=info msg="[lintersdb] Active 49 linters: [asasalint asciicheck bidichk bodyclose cyclop depguard dogsled dupword durationcheck errcheck exportloopref forbidigo gci goconst gocritic gocyclo godot gofmt gofumpt goheader goimports gomodguard goprintffuncname gosec gosimple govet importas ineffassign makezero misspell nakedret nestif nilerr noctx nolintlint prealloc predeclared revive rowserrcheck sqlclosecheck staticcheck stylecheck thelper typecheck unconvert unparam unused wastedassign whitespace]"
level=info msg="[loader] Using build tags: [e2e]"
level=info msg="[loader] Go packages loading at mode 575 (compiled_files|exports_file|imports|name|deps|files|types_sizes) took 46.430316521s"
level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 23.917606ms"
make: *** [Makefile:233: lint] Killed
```

e.g.:
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1468/pull-cluster-api-provider-openstack-test/1623673176628137984
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1466/pull-cluster-api-provider-openstack-test/1623670056078544896

This appears to be related to using go 1.20. The failure does not happen on go 1.19. I am guessing that the CI image was upgraded.

**Comment by tobiasgiese** [comment]
We had the same issue with golangci-lint v1.49.0 and go1.20 downstream and a bump to golangci-lint v1.51.1 fixes the issue.
Seems that there is a memory leak. The golangci-lint uses my 64GB memory client completely (OOM killed at a usage of 59GB).

**Comment by mdbooth** [comment]
I wasn't able to bump the go mod to v1.51.1 because it wouldn't build. Fails with:

```
> go build -tags=tools -o golangci-lint github.com/golangci/golangci-lint/cmd/golangci-lint
/home/mbooth/go/pkg/mod/github.com/ryancurrah/gomodguard@v1.3.0/tools.go:5:8: import "github.com/t-yuki/gocover-cobertura" is a program, not an importable package
```

I even tried it in its own module. I looked at what CAPI is doing and they're just downloading it, so I've submitted #1470 to do the same.
