### ISSUE TITLE
Security group rule already exists - Update error.

### ISSUE THREAD

**Issue by fmoctezuma** [kubernetes-sigs/cluster-api-provider-openstack#1475]
/kind bug

**What steps did you take and what happened:**
Was able to create a k8s cluster using CAPI, CAPO and Openstack train, I'm able to describe the openstackcluster resource and it shows ready.

```
kubectl get openstackclusters xyz
NAME   CLUSTER   READY   NETWORK                                SUBNET                                 BASTION IP     AGE
xyz    xyz       true    fe5b39d1-4d4a-4753-8fad-4b08b3094d1d   4933956a-1836-413f-9118-a46572dfe1d2   <bastion ip>   23h
```
But when I describe the cluster only it shows as `Failed`
```
kubectl get clusters xyz
NAME   PHASE    AGE   VERSION
xyz    Failed   23h
```
```
kubectl describe cluster xyz

--snippet output

Failure Message:    Failure detected from referenced resource infrastructure.cluster.x-k8s.io/v1alpha6, Kind=OpenStackCluster with name "xyz": failed to reconcile security groups: Expected HTTP response code [201 202] when accessing [POST https://<OpenstackAPI>:9696/v2.0/security-group-rules], but got 409 instead
{"NeutronError": {"type": "SecurityGroupRuleExists", "message": "Security group rule already exists. Rule id is 66e729f0-bd8b-4030-af2f-dccbc400bf7a.", "detail": ""}}
  Failure Reason:        UpdateError
  Infrastructure Ready:  true
  Observed Generation:   3
  Phase:                 Failed
  ```
I confirmed the `SecurityGroupRuleExists` is in the neutron database, and also **disappears** when the cluster is deleted/gone, no more `SecurityGroupRule` remains.

Also found this old issue, https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/771#issuecomment-792588671 , but I'm not able to edit the `openStackCluster.Spec.ManagedSecurityGroups` and set it to `false`.

**What did you expect to happen:**
OpenstackCluster and Cluster resources are on READY and Provisioned status

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version: **v1.3.3** 
- OpenStack version: **Train**
- Minikube/KIND version: **N/A** 
- Kubernetes version (use `kubectl version`): **Management cluster k8s v1.24 , Workload cluster v1.23**
- OS (e.g. from `/etc/os-release`): **Workload cluster and management cluster Ubuntu 20.04**

NAME                                 CURRENT VERSION  
bootstrap-kubeadm                     *v1.3.3*         
bootstrap-talos                             *v0.5.6*       
control-plane-kubeadm               *v1.3.3*           
cluster-api                                     *v1.3.3*
infrastructure-openstack            *v0.7.0*

**Comment by jichenjc** [comment]
>>>but I'm not able to edit the openStackCluster.Spec.ManagedSecurityGroups and set it to false.

this issue is long time ago, not sure the issue still can be fixed by that change or not,
but I am curious why you mentioned `not able to edit` , you can't use kubectl edit to update this ?

Wondering is it because you did something wrong so the previous cluster is in an incorrect status
so from then on you have the sec group created but not deleted correctly then next create will always fail at such code path...

**Comment by fmoctezuma** [comment]
Thanks @jichenjc for taking the time to read the issue,
When I mentioned that I'm `not able to edit`, is because kubernetes is not accepting the change editing the clusterresource.

e.g
```
kubectl edit openstackcluster xyz
```
On the line  `managedSecurityGroups: true` under spec, trying to change it to false
I'm getting `* spec: Forbidden: cannot be modified`  when I tried to save the object simple editing, (I haven't try to do the patch way)

Also I have checked when I delete a cluster, no Securitygroups or Securitygrouprules are left behind on the specific tenant, I also took a look to the OpenStack Database under the neutron, securitygroup and rules are properly being deleted when the cluster is deleted.
 
 > _Wondering is it because you did something wrong so the previous cluster is in an incorrect status
so from then on you have the sec group created but not deleted correctly then next create will always fail at such code path..._

This might be also an option, probably I'm doing something wrong here since I'm just starting, I'm thinking to try again from a different OpenStack tenant? I have been creating and deleting many clusters on this one, doing trial and error.

**Comment by jichenjc** [comment]
ok, my bad, I didn't read the code before add that comment, the ManagedSecurityGroup field ca'nt be updated
you can check https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/api/v1alpha6/openstackcluster_webhook.go#L119 for further info 

>>>This might be also an option, probably I'm doing something wrong here since I'm just starting, I'm thinking to try again from a different OpenStack tenant? I have been creating and deleting many clusters on this one, doing trial and error.

yes, you may try aother tenant, and if possible, you can also paste your cluster configuration (I think your yaml comes from template folder cluster-api-provider-openstack/templates) and that also be helpful ..

**Comment by fmoctezuma** [comment]
Sure this is the template I'm using 
https://gist.github.com/fmoctezuma/e6e43242417cf74df10c3faf53509683

**Comment by jichenjc** [comment]
the manifests seems fine , nothing special, so from 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/networking/securitygroups.go#L331
seems there are some v6 log so could you please help enable --v=6 in CPO and see whether we can obtain more info about 
what the code is trying to create and whether it report same error and compare the name in the log with existing openstack DB info might give us more clue

**Comment by cwrau** [comment]
> the manifests seems fine , nothing special, so from [`main`/pkg/cloud/services/networking/securitygroups.go#L331](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/networking/securitygroups.go?rgh-link-date=2023-02-22T00%3A35%3A17Z#L331) seems there are some v6 log so could you please help enable --v=6 in CPO and see whether we can obtain more info about what the code is trying to create and whether it report same error and compare the name in the log with existing openstack DB info might give us more clue

We got the same problem, I've upped the log level and can see the following;

```shell
Accept: application/json
Content-Type: application/json
User-Agent: gophercloud/2.0.0
X-Auth-Token: ***
  "security_group_rule": {
    "description": "SSH",
    "direction": "ingress",
    "ethertype": "IPv4",
    "port_range_max": 22,
    "port_range_min": 22,
    "protocol": "tcp",
    "remote_group_id": "51031ee8-2e83-4f7f-9724-d609f61cf9d1",
    "security_group_id": "1ba8d41f-6f20-4654-bc76-601d05d770df"
  }
}
Content-Length: 602
Content-Type: application/json
Date: Thu, 23 Feb 2023 09:06:21 GMT
X-Openstack-Request-Id: req-e319aa91-86eb-44bb-b682-87b51267f458
  "security_group_rule": {
    "created_at": "2023-02-23T09:06:21Z",
    "description": "SSH",
    "direction": "ingress",
    "ethertype": "IPv4",
    "id": "1b5ddf00-4617-4de4-96aa-9b22041366aa",
    "normalized_cidr": null,
    "port_range_max": 22,
    "port_range_min": 22,
    "project_id": "31836b99655b461c9525dc6100026e80",
    "protocol": "tcp",
    "remote_address_group_id": null,
    "remote_group_id": "51031ee8-2e83-4f7f-9724-d609f61cf9d1",
    "remote_ip_prefix": null,
    "revision_number": 0,
    "security_group_id": "1ba8d41f-6f20-4654-bc76-601d05d770df",
    "tenant_id": "31836b99655b461c9525dc6100026e80",
    "updated_at": "2023-02-23T09:06:21Z"
  }
}
Accept: application/json
Content-Type: application/json
User-Agent: gophercloud/2.0.0
X-Auth-Token: ***
  "security_group_rule": {
    "description": "SSH",
    "direction": "ingress",
    "ethertype": "IPv4",
    "port_range_max": 22,
    "port_range_min": 22,
    "protocol": "tcp",
    "remote_group_id": "51031ee8-2e83-4f7f-9724-d609f61cf9d1",
    "security_group_id": "1ba8d41f-6f20-4654-bc76-601d05d770df"
  }
}
Content-Length: 166
Content-Type: application/json
Date: Thu, 23 Feb 2023 09:06:21 GMT
X-Openstack-Request-Id: req-1dc01986-e0d2-485e-8bc0-b74e483736a8
  "NeutronError": {
    "detail": "",
    "message": "Security group rule already exists. Rule id is 1b5ddf00-4617-4de4-96aa-9b22041366aa.",
    "type": "SecurityGroupRuleExists"
  }
}
```

It looks like capo tries to create the "same" security group rule twice? And OpenStack detects that and errors out

I can provide more info if needed, didn't want to flood this here 😅

**Comment by jichenjc** [comment]
ok, this info is really helpful :)

I proposed https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1492 after review code
I doubt it's previous typo lead to 1 sec groups have 2 identical rules when bastion is enabled (https://gist.github.com/fmoctezuma/e6e43242417cf74df10c3faf53509683 seems bastion = true)  , but seems in my local previous test didn't encounter this
and I think our CI should have bastion covered as well (will double check), so not 100% sure it's the root cause even though the code seems incorrect from the context ...

can you @fmoctezuma or @cwrau give a quick try on the proposed fix (e.g bulid a test image if possible)? Thanks for the help

**Comment by fmoctezuma** [comment]
The fix is working as expected, built an image based on your PR @jichenjc , and the cluster was created successfully and no longer complaining about the securitygrouprule.
Thank you!
