### ISSUE TITLE
Ports deleted for wrong cluster when two clusters with the same name coexist in one project

### ISSUE THREAD

**Issue by yankcrime** [kubernetes-sigs/cluster-api-provider-openstack#1476]
/kind bug

**What steps did you take and what happened:**

Deploy two clusters with the same name into the same OpenStack project.  From an end-user perspective, this seems like a reasonable thing to do, and aligns with expectations around the behaviour of OpenStack i.e UUIDs.

Both clusters provision fine, however deleting one cluster triggers the deletion of network ports for _both_ clusters.

This is exactly the scenario that @mkjpryor mentions in #1320 around port deletion.  When you have two clusters with the same name provisioned into the same OpenStack project, deleting one cluster causes all ports to be deleted for both clusters, rendering the original cluster useless.

Instance list for one cluster called `demo` (3 x control plane, 1 x worker):

```
+--------------------------------------+-----------------------------------+--------+------------------------------------------------+--------------------------+--------------+
| ID                                   | Name                              | Status | Networks                                       | Image                    | Flavor       |
+--------------------------------------+-----------------------------------+--------+------------------------------------------------+--------------------------+--------------+
| 781f976c-ada2-4782-ac5d-a01bd9c74398 | demo-control-plane-fa2e8ed3-tkx9x | ACTIVE | k8s-clusterapi-cluster-demo-demo=192.168.2.76  | ubu2204-v1.25.5-9d105bc5 | g.4.standard |
| acb33e64-76cd-46a4-91dc-7197aa05b155 | demo-pool-worker-32be72d2-57s7x   | ACTIVE | k8s-clusterapi-cluster-demo-demo=192.168.1.214 | N/A (booted from volume) | g.4.standard |
| 3b86fe77-c3cd-4c0b-8f9b-838fdc6c373a | demo-control-plane-fa2e8ed3-zvzqk | ACTIVE | k8s-clusterapi-cluster-demo-demo=192.168.0.34  | ubu2204-v1.25.5-9d105bc5 | g.4.standard |
| 7e9bc58e-ca4b-4273-8934-64b12bc94236 | demo-control-plane-fa2e8ed3-mqbql | ACTIVE | k8s-clusterapi-cluster-demo-demo=192.168.2.103 | ubu2204-v1.25.5-9d105bc5 | g.4.standard |
+--------------------------------------+-----------------------------------+--------+------------------------------------------------+--------------------------+--------------+
```

Instance list when a second cluster called `demo` is provisioned into the same project (1 x control plane, 1 x worker):

```
+--------------------------------------+-----------------------------------+--------+------------------------------------------------+--------------------------+--------------+
| ID                                   | Name                              | Status | Networks                                       | Image                    | Flavor       |
+--------------------------------------+-----------------------------------+--------+------------------------------------------------+--------------------------+--------------+
| 2c8d811e-cfac-41b5-bb6e-de351049c91f | demo-worker-3416f7ba-4b5ps        | ACTIVE | k8s-clusterapi-cluster-default-demo=10.7.0.170 | N/A (booted from volume) | g.2.standard |
| 66fa8235-89f6-48d5-adfc-86eee0ac927f | demo-control-plane-bd323c85-2jqdc | ACTIVE | k8s-clusterapi-cluster-default-demo=10.7.0.116 | N/A (booted from volume) | g.2.standard |
| 781f976c-ada2-4782-ac5d-a01bd9c74398 | demo-control-plane-fa2e8ed3-tkx9x | ACTIVE | k8s-clusterapi-cluster-demo-demo=192.168.2.76  | ubu2204-v1.25.5-9d105bc5 | g.4.standard |
| acb33e64-76cd-46a4-91dc-7197aa05b155 | demo-pool-worker-32be72d2-57s7x   | ACTIVE | k8s-clusterapi-cluster-demo-demo=192.168.1.214 | N/A (booted from volume) | g.4.standard |
| 3b86fe77-c3cd-4c0b-8f9b-838fdc6c373a | demo-control-plane-fa2e8ed3-zvzqk | ACTIVE | k8s-clusterapi-cluster-demo-demo=192.168.0.34  | ubu2204-v1.25.5-9d105bc5 | g.4.standard |
| 7e9bc58e-ca4b-4273-8934-64b12bc94236 | demo-control-plane-fa2e8ed3-mqbql | ACTIVE | k8s-clusterapi-cluster-demo-demo=192.168.2.103 | ubu2204-v1.25.5-9d105bc5 | g.4.standard |
+--------------------------------------+-----------------------------------+--------+------------------------------------------------+--------------------------+--------------+
```

Instance list after a deletion of the second cluster is triggered:

```
+--------------------------------------+-----------------------------------+--------+----------+--------------------------+--------------+
| ID                                   | Name                              | Status | Networks | Image                    | Flavor       |
+--------------------------------------+-----------------------------------+--------+----------+--------------------------+--------------+
| 66fa8235-89f6-48d5-adfc-86eee0ac927f | demo-control-plane-bd323c85-2jqdc | ACTIVE |          | N/A (booted from volume) | g.2.standard |
| 781f976c-ada2-4782-ac5d-a01bd9c74398 | demo-control-plane-fa2e8ed3-tkx9x | ACTIVE |          | ubu2204-v1.25.5-9d105bc5 | g.4.standard |
| acb33e64-76cd-46a4-91dc-7197aa05b155 | demo-pool-worker-32be72d2-57s7x   | ACTIVE |          | N/A (booted from volume) | g.4.standard |
| 3b86fe77-c3cd-4c0b-8f9b-838fdc6c373a | demo-control-plane-fa2e8ed3-zvzqk | ACTIVE |          | ubu2204-v1.25.5-9d105bc5 | g.4.standard |
| 7e9bc58e-ca4b-4273-8934-64b12bc94236 | demo-control-plane-fa2e8ed3-mqbql | ACTIVE |          | ubu2204-v1.25.5-9d105bc5 | g.4.standard |
+--------------------------------------+-----------------------------------+--------+----------+--------------------------+--------------+
```

The associated CAPO logs for port-related deletion activity show this kind of thing:

```
I0216 15:55:56.866134       1 recorder.go:103] "events: Deleted port with id 0e46f68a-cfd8-4878-ad65-6865d862f4ed" type="Normal" object={Kind:OpenStackCluster Namespace:default Name:demo UID:eebc8832-ac46-4fc5-9f1a-ed4c61c32281 APIVersion:infrastructure.cluster.x-k8s.io/v1alpha6 ResourceVersion:16633 FieldPath:} reason="Successfuldeleteport"
E0216 15:55:56.895556       1 controller.go:326] "Reconciler error" err="failed to delete ports: delete port 0e46f68a-cfd8-4878-ad65-6865d862f4ed of network \"\" failed : <nil>" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="default/demo" namespace="default" name="demo" reconcileID=d2ca4c0c-a8a6-49e6-97fa-8b12fa85665d
I0216 15:55:57.198614       1 openstackcluster_controller.go:136] "Reconciling Cluster delete" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="default/demo" namespace="default" name="demo" reconcileID=ad5485b3-3e28-4f3e-b150-3ec8eb7b6ed9 cluster="demo"
I0216 15:55:57.927321       1 recorder.go:103] "events: Deleted port with id 914f37df-862c-4413-aba7-a005eef8c400" type="Normal" object={Kind:OpenStackCluster Namespace:default Name:demo UID:eebc8832-ac46-4fc5-9f1a-ed4c61c32281 APIVersion:infrastructure.cluster.x-k8s.io/v1alpha6 ResourceVersion:16638 FieldPath:} reason="Successfuldeleteport"
E0216 15:55:57.959319       1 controller.go:326] "Reconciler error" err="failed to delete ports: delete port 914f37df-862c-4413-aba7-a005eef8c400 of network \"\" failed : <nil>" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="default/demo" namespace="default" name="demo" reconcileID=ad5485b3-3e28-4f3e-b150-3ec8eb7b6ed9
I0216 15:55:58.257214       1 openstackcluster_controller.go:136] "Reconciling Cluster delete" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="default/demo" namespace="default" name="demo" reconcileID=76807f52-7324-425f-87c5-34ea7ec5d1ac cluster="demo"
I0216 15:55:58.944866       1 recorder.go:103] "events: Deleted port with id b0e00572-711d-41ee-ab11-4e1651cc0339" type="Normal" object={Kind:OpenStackCluster Namespace:default Name:demo UID:eebc8832-ac46-4fc5-9f1a-ed4c61c32281 APIVersion:infrastructure.cluster.x-k8s.io/v1alpha6 ResourceVersion:16643 FieldPath:} reason="Successfuldeleteport"
E0216 15:55:58.976431       1 controller.go:326] "Reconciler error" err="failed to delete ports: delete port b0e00572-711d-41ee-ab11-4e1651cc0339 of network \"\" failed : <nil>" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="default/demo" namespace="default" name="demo" reconcileID=76807f52-7324-425f-87c5-34ea7ec5d1ac
I0216 15:55:59.276602       1 openstackcluster_controller.go:136] "Reconciling Cluster delete" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="default/demo" namespace="default" name="demo" reconcileID=4445c340-e618-411d-bddf-e1dc1a58272c cluster="demo"
I0216 15:55:59.975497       1 recorder.go:103] "events: Deleted port with id d5b24919-c52a-482d-a567-4585af035367" type="Normal" object={Kind:OpenStackCluster Namespace:default Name:demo UID:eebc8832-ac46-4fc5-9f1a-ed4c61c32281 APIVersion:infrastructure.cluster.x-k8s.io/v1alpha6 ResourceVersion:16647 FieldPath:} reason="Successfuldeleteport"
```

**What did you expect to happen:**

Only the resources related to the second cluster are deleted.  The original cluster should be left intact.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): 0.7.0
- Cluster-API version: v1.3.2
- OpenStack version: Yoga
- Minikube/KIND version: N/A
- Kubernetes version (use `kubectl version`): 1.25.5
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04

**Comment by mkjpryor** [comment]
I actually think it is worse than just two clusters sharing the same name - I think this might even happen when another cluster has the name of a deleted cluster _as a prefix_ in its name.

So if I have two clusters, `demo` and `demo-matt` then the ports for `demo-matt` will be deleted when I delete `demo`.

I haven't verified this.

**Comment by mkjpryor** [comment]
Either way it is a major problem.

**Comment by mdbooth** [comment]
> I actually think it is worse than just two clusters sharing the same name - I think this might even happen when another cluster has the name of a deleted cluster _as a prefix_ in its name.
> 
> So if I have two clusters, `demo` and `demo-matt` then the ports for `demo-matt` will be deleted when I delete `demo`.
> 
> I haven't verified this.

What makes you think this? I'm guessing you've seen some suspicious code? We should definitely address this.

I would like to address the general problem of clusters with the same name, but that's likely to be a significant project in multiple phases, and even then there will be edge cases. Honestly, I would say it's just best not to do this. It would be so much simpler if OpenStack had never permitted objects with the same name in the same tenant.

**Comment by jichenjc** [comment]
>>>It would be so much simpler if OpenStack had never permitted objects with the same name in the same tenant.

this is k8s design :) , but openstack use uuid instead so nothing we can do now (and ever..）

so is it possible that we can do something in the CAPO side, e.g abstract the resource we created in openstack by adding random string as prefix or suffix or other info that unique to the created cluster ? so we can distinguish them from CAPO side?

**Comment by mkjpryor** [comment]
@mdbooth 

This code, executed as part of `reconcileDelete`, deletes every port on the cluster network with the cluster name as a prefix:

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/96ee54aab679d8403eef04c0f87e0dde36098e57/pkg/cloud/services/networking/port.go#L247-L271

So that means, if they share a network, all the ports for `cluster12` would be deleted when `cluster1` is deleted, which is most definitely wrong.

The pragmatic fix for now is only to execute this code when the cluster owns the network and needs to delete it, in which case any extra ports deserve to be deleted.

**Comment by jichenjc** [comment]
CPO use tags/description it created to identify the resource it created

how about we tag the resource that created by CAPO, like <clustername>-<namespace> (so less likely conflict)?
then we manipulate all the resources deletion through the tag... (e.g the volume, the port, the LB etc)

of course there are rare case that multiple CAPO run on multiple k8s on 1 openstack then maybe clustername-namespace is not enough, we can add the cluster identifier into the tag as well

**Comment by mdbooth** [comment]
There's a fundamental issue here[^1]: creating a resource in openstack and recording the creation of that resource in k8s are 2 separate transactions, either of which can fail. We can naïvely write:
```
Reconcile:
    if server.Status.UUID == "" {
        createParams.Name = "cluster-foo-worker-0"
        server.Status.UUID := OpenStackCreateServer(createParams)
        k8sClient.Update(server)
    }
```

But if the update fails, which it does in practise reasonably often, then the next time we run reconcile we will create a second server with the same name.

So instead we write:
```
Reconcile:
    if server.Status.UUID == "" {
        createParams.Name = "cluster-foo-worker-0"
        uuid = OpenStackGetServer(name=createParams.Name)
        if Err404 {
            uuid = OpenStackCreateServer(createParams)
        }
        server.Status.UUID = uuid
        k8sClient.Update(server)
    }
```

This is safe, but comes with an additional assumption: that the only thing that would have created a server called "cluster-foo-worker-0" is us. Once server.Status.UUID is set we're good from that point on because we can always use the uuid, but we still need an additional assumption during creation to avoid leaking resources.

Incidentally this also extends to resource deletion. Even if we record the UUIDs of all the ports we create for a server in Status (which I think we should), we don't know on deletion if the absence of those UUIDs means that they weren't created, or just that the write to the status object failed. Therefore we still end up with naming assumptions on delete.

However, I wonder if we could make this essentially impossible in practise by using tags as @jichenjc suggests, but instead of using name/namespace use the k8s uid of the OpenStackCluster object. These are unlikely to conflict even between clusters created by different management clusters. So we could have:

```
Reconcile:
    if server.Status.UUID == "" {
        createParams.Name = "cluster-foo-worker-0"
        createParams.Tag = openStackCluster.uid // abccb137-6335-429d-a941-b868d02f3c94
        uuid = OpenStackGetServer(name=createParams.Name, tag=createParams.Tag)
        if Err404 {
            uuid := OpenStackCreateServer(createParams)
        }
        server.Status.UUID = uuid
        k8sClient.Update(server)
    }
```

Port deletion would then become:
```
    for port in OpenStackGetPorts(tag=openStackCluster.uid) {
        OpenStackPortDelete(port)
    }
```

The biggest technical issue is like to be upgrades: we're going to want to add these tags to all objects. We're also going to add them incrementally to each resource type we create in turn, hence multiple phases. This is a whole lot of work to fix.

[^1]: At least I think it's fundamental. I'd be delighted to be wrong about this.

**Comment by mkjpryor** [comment]
@mdbooth 

Using the Kubernetes UID of the `OpenStack{Cluster,Machine}` objects as a tag, then using that to control what we delete, makes perfect sense to me. I think we should do this literally everywhere that we can!

**Comment by mkjpryor** [comment]
/remove-lifecycle stale

This is most certainly not stale. In fact, IMHO it is the most serious bug in CAPO at the moment.

I recently hit this bug in a production system, where a user had two clusters called `<something>` and `<something>2`. They deleted `<something>`, and all the ports for `<something>2` got deleted as well, bricking that cluster.

**Comment by EmilienM** [comment]
I think I'll address that issue via https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1788

/remove-lifecycle stale

**Comment by mdbooth** [comment]
@EmilienM I'm not convinced that #1788 will fix this. This problem happens when 2 clusters share:
* The same name
* The same cluster network

The problem occur(s|ed) in [DeleteClusterPorts](https://github.com/shiftstack/cluster-api-provider-openstack/blob/e8a4ae4aa5042c762974431eb92f5d2b5c28b3f8/pkg/cloud/services/networking/port.go#L272-L301), which deletes all ports remaining in a network before deleting the network during deletion of the cluster infrastructure.

However, as pointed out above that no longer happens because since #1680 we no longer delete cluster ports if we didn't create the network. I think this is fixed already, I just failed to reference it in the PR.

However, #1788 *will* hopefully eliminate leaked ports from machine creation which are one of the reasons this method is required in the first place.
