### ISSUE TITLE
AZ Availabilty Not Being Checked

### ISSUE THREAD

**Issue by spjmurray** [kubernetes-sigs/cluster-api-provider-openstack#1477]
/kind bug

**What steps did you take and what happened:**

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/02a31730ef1ae7962f1cc36c090b624025a2f5bc/pkg/cloud/services/compute/availabilityzone.go#L25 or https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/f4e61b626eec3c5eb82e5f3328de0da6fe1d540d/pkg/clients/compute.go#L79 don't filter out unavailable availability zones.

**What did you expect to happen:**

It filters unavailable zones out so the control plane etc. gets scheduled on an available AZ.

**Anything else you would like to add:**

We could/should work around this problem by explicitly stating the AZs in the OSC resource, but that's not available to us as we punt everything through a single Helm chart, adding the field gets rejected because of the validating webhook for existing clusters.  If we try to switch the OSC out with a new one, that gets really broken as it tries to allocate a new VIP on the load balancer, fails as the old one is in place, uses up all the floating IPs on the platform in the process.  Disassociating the VIP to lend a helping hand is even worse because everything loses the ability to talk to the API.  Non fun 😸 

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by mdbooth** [comment]
Would this be addressed by https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1466?

**Comment by spjmurray** [comment]
I'll have a look thanks.  I was also going to raise one about the lack of block storage AZs, so it's good to know about!

**Comment by spjmurray** [comment]
I don't think it does @mdbooth .  Specifically, I don't see https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/extensions/availabilityzones/results.go#L20 being checked anywhere (except correctly in e2e testing 😄 ).

In my specific case, we let CAPO do its thing with:

```
+-----------+---------------+
| Zone Name | Zone Status   |
+-----------+---------------+
| POD-2     | available     |
| nova      | available     |
| POD-1     | not available |
+-----------+---------------+
```

What I'm seeing is my first CP node getting provisioned to POD-1, and obviously failing.

This brings me onto another query.  I do hope all this data isn't cached in the status and relied upon as the source of truth for all time.  What if I took a pod out of service for some maintenance, you're in a bit of a bind then as you could get stuck in a world where recovery is impossible (other than manually hacking the status, which I'd rather avoid).

I guess the final thing based on tearing my hair out yesterday was making the OSC AZz mutable.  It does provide a workaround for the above lifecycle problem, at least in the case where you have control over the platform and get notified about topology changes in advance. I can see that switching out the whole OSC resource causes unrecoverable damage (unless I'm doing it wrong).  Use cases:

* Migrating existing clusters from implicit to explicit AZs (what I _was_ trying to do), the "hard" bit here is a rolling upgrade of CP nodes that fall on AZs outside of the new working set.
* Supporting AZ maintenance, same thing as above really, constraining the working set so things can get re-sceduled out of the way to evacuate the AZ for maintenance.

I know this is a lot of work, I can give it an attempt, but I imagine you'd be more efficient.

**Comment by spjmurray** [comment]
Added a fix ^^^ I'm now actually able to provision clusters again!  Obviously I'd prefer this to land in 0.7.1 so we don't have to maintain a separate image, so let the discussion begin!
