### ISSUE TITLE
Add fuzzy conversion tests for other API versions

### ISSUE THREAD

**Issue by lentzi90** [kubernetes-sigs/cluster-api-provider-openstack#1478]
/kind feature

**Describe the solution you'd like**

We currently have fuzzy conversion tests for [v1alpha4 to v1alpha6](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/4cd95fa2a6bd0ba60faf1d5484431662df707b37/api/v1alpha4/conversion_test.go#L207) and [v1alpha3 to v1alpha6](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/4cd95fa2a6bd0ba60faf1d5484431662df707b37/api/v1alpha3/conversion_test.go#L121) but not for v1alpha5 to v1alpha6. I think we should add tests also for v1alpha5 (and future API versions).

**Anything else you would like to add:**

I don't currently have time to work on this, but I wanted to document it so we don't forget it. At some point I may get time to pick it up and would then be happy to do it.

**Comment by mdbooth** [comment]
I just opened #1508 as I suspect we may also have an actual problem there. I'm going to close this in favour of the new issue as it also contains some additional details.
