### ISSUE TITLE
No need to ReconcileExternalNetwork when disableApiserverFloatingIP and NodeCIDR is empty string

### ISSUE THREAD

**Issue by ruifaling** [kubernetes-sigs/cluster-api-provider-openstack#1490]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
In openstackcluster_controller，when disableApiserverFloatingIP, will not use external network to create a floatingIP;when NodeCIDR is empty string, there is no need to reconcile network and create router between external network and subnet; 

**What did you expect to happen:**
when disableApiserverFloatingIP and the NodeCIDR is empty string, it won't excute the  ReconcileExternalNetwork

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:1.1.4
- OpenStack version:0.6.3
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by mdbooth** [comment]
I'm guessing that the bug here is that you get an error related to external network when you aren't using external network?

**Comment by ruifaling** [comment]
> I'm guessing that the bug here is that you get an error related to external network when you aren't using external network?

yes

**Comment by EmilienM** [comment]
@ruifaling could you please tell us if using `openstackcluster.spec.disableExternalNetwork` fits your needs? And if not please let us know.

**Comment by ruifaling** [comment]
> @ruifaling could you please tell us if using `openstackcluster.spec.disableExternalNetwork` fits your needs? And if not please let us know.

yes,it is highly likely to meet my needs. With  `openstackcluster.spec.disableExternalNetwork` ,where is the bastion port,is there still bastion

**Comment by EmilienM** [comment]
If you enable the bastion, CAPO will need an external network because it'll try to attach a floating IP.
If you don't enable the bastion, you're fine and you don't need an external network and can safely set `openstackcluster.spec.disableExternalNetwork` to false.
