### ISSUE TITLE
VMs fail to go up with mutliattach backends

### ISSUE THREAD

**Issue by mnaser** [kubernetes-sigs/cluster-api-provider-openstack#1496]
/kind bug

**What steps did you take and what happened:**
CAPO fails to boot up VMs when a backend supports multi-attach, this is because the API microversion that's set in CAPO is 2.53.  2.60 allows the use of multiattach backends and it's the maxmium in Queens, a release that was EOL'd last month.

**What did you expect to happen:**
I expected CAPO to be able to bring up a VM just fine.

**Anything else you would like to add:**
I think we should be able to safely bump the microversion to 2.60 without any impact but an advantage.

https://docs.openstack.org/nova/latest/reference/api-microversion-history.html#maximum-in-queens
https://releases.openstack.org/

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by mdbooth** [comment]
Sounds reasonable. Do you want to throw up a PR to run it through CI?

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/3c3c0bde1f53e4df534a4a88f2526e1c9b67ab7d/pkg/clients/compute.go#L34-L43

**Comment by mdbooth** [comment]
@jichenjc You had some reservations about support for old versions in the past. Any thoughts?

**Comment by jichenjc** [comment]
>>>You had some reservations about support for old versions in the past. Any thoughts?

I think we want to support older version as much as we can (so we can increase the adoption of CAPO)
so are we able to set a flag like (support_multi_attach=true by default) and set v=2.60
then configurable it to =false and set v=2.53? 

so older version they can disable/enable to workaround this .. thoughts?

**Comment by mdbooth** [comment]
This would be a bump to the oldest version which isn't EOL. Do we want to support EOL versions of OpenStack?

**Comment by jichenjc** [comment]
I knew some user still use older openstack even though it's EOL (but technically still functional) due to various reason and they can't upgrade ,  from CAPO perspective we can claim that , if we can do minor(some smaller logic) things to help expansion of CAPO ecosystem I think it's still worthy though ,but of course in the README we still only claim supported version, thoughts?

**Comment by mnaser** [comment]
> I knew some user still use older openstack even though it's EOL (but technically still functional) due to various reason and they can't upgrade , from CAPO perspective we can claim that , if we can do minor(some smaller logic) things to help expansion of CAPO ecosystem I think it's still worthy though ,but of course in the README we still only claim supported version, thoughts?

I see your point, however, this is a bit of a weird balance.  Do we cater for those that do not upgrade their clouds or do we cater for those running up-to-date clouds?

On one side, someone with an EOL release of OpenStack can create clusters, but on the other, someone who's up to date (and by up to date, we're talking about like.. running almost a 5 year release of OpenStack -- Queens) is not able to..

**Comment by mnaser** [comment]
> > > > You had some reservations about support for old versions in the past. Any thoughts?
> 
> I think we want to support older version as much as we can (so we can increase the adoption of CAPO) so are we able to set a flag like (support_multi_attach=true by default) and set v=2.60 then configurable it to =false and set v=2.53?
> 
> so older version they can disable/enable to workaround this .. thoughts?

We could do that too, but I feel like that adds a lot of complexity, at least to the scope of this small initial fix.

**Comment by jichenjc** [comment]
>>>but on the other, someone who's up to date (and by up to date, we're talking about like.. running almost a 5 year release of OpenStack -- Queens) is not able to..

don't get me wrong :) 
I am looking for support both with minor effort, if we have to balance, I am certainly want to support up-to-date version
so feel free to submit your fix to this and we can talk about how to help those older user with minor effort
