### ISSUE TITLE
build CAPO supported images

### ISSUE THREAD

**Issue by tormath1** [kubernetes-sigs/cluster-api-provider-openstack#1502]
/kind feature

**Describe the solution you'd like**:

During the CAPO office hours, @mdbooth suggested to build CAPO supported images in the CI. These images could be directly consumed by the tests (and consumed by the users?).

These images could be built for multiple Kubernetes version and multiple OS version (ubuntu-2004, flatcar, etc.)

**Anything else you would like to add:**

On the implementation side, we could use Github Actions and image-builder Docker image. Example with Flatcar:
```
sudo docker run --privileged --net host -v "${PWD}/docker-output:/output" -v /dev:/dev --rm \
    -e PACKER_FLAGS="--var 'kubernetes_semver=v1.26.2' --var 'kubernetes_series=v1.26'" \
    -e OEM_ID=openstack \
    tormath1/cluster-node-image-builder-amd64 \
    build-qemu-flatcar
```

(Note: it needs https://github.com/kubernetes-sigs/image-builder/pull/1092)

For Flatcar: https://github.com/flatcar/Flatcar/issues/928 (https://github.com/kubernetes-sigs/image-builder/issues/924)  can be interesting

Produced images could be then stored on a GCS bucket.

**Comment by mdbooth** [comment]
@tormath1 We would probably use cloudbuild rather than GH actions, and I think that *might* support KVM.

**Comment by mdbooth** [comment]
That's awesome!

I think we're going to need this in cloudbuild for 2 reasons:
* We need the artifacts in a GCS bucket for CI or we'll exceed our ingress quota.
* The only automated way (caveat: that I'm aware of) to use the project's gcloud credentials is from the prow secure cluster.

That said, I don't currently know when I or anybody else will find time to implement this and you seem to have something looks close to useful for at least some people already. I wonder if we should merge a GH actions solution now and aim to replace it with a cloudbuild solution in prow when we get to it.

Thoughts?
/cc @lentzi90 @tobiasgiese @jichenjc

**Comment by mdbooth** [comment]
> Moving it to cloudbuild is not an issue as it mainly relies on the Makefile and Docker to run. It's just less community friendly as one can easily browse the logs on the Github actions (or maybe we can have the logs from cloubuild ? I don't know how it works :D)

Yeah, we have the logs: they're in the prow job that runs the cloudbuild, same as regular tests. Admittedly they're not as easy to find, though. This feels like an opportunity for improved docs 🤔

**Comment by mdbooth** [comment]
For reference, here's the logs of one of our nightly image builds: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1503/pull-cluster-api-provider-openstack-build/1635583768574038016

Incidentally, that job seems pointless. We should probably kill it.

**Comment by mdbooth** [comment]
Example of automatic uploading of artifacts from a cloudbuild job: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/b2b2a3ec4565c146b57ce1c9634469ddfd9a078c/Makefile#L405-L406

**Comment by mdbooth** [comment]
Could it just be timeouts? It's probably fine to run them sequentially as separate cloudbuild steps, I guess.

**Comment by mnaser** [comment]
could a step below this be to maybe build out the Makefile's needed to make this happen so users can easily build things out.. and _then_ this could be using that toolset?

**Comment by lentzi90** [comment]
@tormath1 what is the status of this? Do you have something for the Makefile that could be useful? I would like to take a shot at getting the cloudbuild operational :smile: 
From what I understand the image-builder PR has been merged now and the cloudbuild works sequentially. Parallel builds are flaky though. If this is correct then I vote for pushing what we have and setting up the cloudbuild to run sequentially over night :slightly_smiling_face:

**Comment by mnaser** [comment]
FTR, we are doing this on our side at the moment in the Cluster API driver for Magnum.  The images are purely generated using GitHub Actions running inside our cloud which have nested virtualization.  The images are also then tested with Sonobuoy + CAPI afterwards to make sure they are functional.

https://github.com/vexxhost/magnum-cluster-api/blob/main/.github/workflows/test.yml#L143-L191

**Comment by mdbooth** [comment]
Yep. My motivations for preferring Prow over GH actions are mostly operational, but having nothing remains even more painful. I think we should resurrect the work you already did to get this working a while back.

**Comment by lentzi90** [comment]
/remove-lifecycle rotten
As an added complication, the exception request for using packer in image-builder (despite its BUSL v1.1 license) was rejected by CNCF: https://github.com/cncf/foundation/issues/625#issuecomment-2127628513.
Image-builder has pinned the latest acceptable version for now, but who knows what will happen with the project going forward?
