### ISSUE TITLE
Do we need the nightly image building job

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1505]
/kind bug

The job is defined here: https://github.com/kubernetes/test-infra/blob/63153430263844755d78c5893958b6b220804002/config/jobs/image-pushing/k8s-staging-cluster-api.yaml#L382-L414

It runs [cloudbuild-nightly.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/b2b2a3ec4565c146b57ce1c9634469ddfd9a078c/cloudbuild-nightly.yaml), which runs the [`release-staging-nightly` make target](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/b2b2a3ec4565c146b57ce1c9634469ddfd9a078c/Makefile#L396-L402).

This feels like it should be a postsubmit job rather than a daily cron job. But more than that, I wonder if we need it at all. Is anybody using it?

/cc @jichenjc @lentzi90 @tobiasgiese

**Comment by jichenjc** [comment]
>>>It would probably be a bit much if we merged dozens of PRs every day. So from that perspective it makes sense to do it nightly instead.

I am not using it either, I think most users use released images and with dev we can build by our own
so I think we don't need either of postsubmit/daily unless someone really need it

**Comment by mdbooth** [comment]
Ok, thanks. I propose we remove this job. We can always add it back if anybody comes up with a use case for it.

**Comment by mdbooth** [comment]
This was the original use case: https://github.com/kubernetes-sigs/cluster-api/issues/4006

It seems potentially valid, but I still wonder if it's worthwhile. How else might a user do this if they wanted to or, more likely, we asked them to in order to test something.

Thoughts:
* How can we ask a user to test a PR which hasn't merged yet?
* Could we define some process for explicit staging releases, e.g. with tags?
* Is this use case worth keeping the job for?
