### ISSUE TITLE
No error found on OpenStack failure

### ISSUE THREAD

**Issue by franzudev** [kubernetes-sigs/cluster-api-provider-openstack#1506]
/kind bug

**What steps did you take and what happened:**
- Create cluster
- OpenStack throws `500 No Valid Host was Found`, visible in the UI
- No errors/events found on controllers

**What did you expect to happen:**
I expect to see the error in logs and/or events, something similar to the one below

```bash
E0315 10:59:28.971256       1 controller.go:317] controller/openstackcluster "msg"="Reconciler error" "error"="failed to delete load balancer: Expected HTTP response code [] when accessing [DELETE https://10.112.70.238:9876/v2.0/lbaas/loadbalancers/ac1600c2-28ce-4939-98e2-55619fe06609?cascade=true], but got 409 instead\n{\"faultcode\": \"Client\", \"faultstring\": \"Invalid state PENDING_DELETE of loadbalancer resource ac1600c2-28ce-4939-98e2-55619fe06609\", \"debuginfo\": null}" "name"="example-error" "namespace"="example" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster"
```

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): 0.6.4
- Cluster-API version: 1.3.2
- OpenStack version: zed
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`): 1.23.7
- OS (e.g. from `/etc/os-release`):

**Comment by qeqar** [comment]
This is a more general error, I had the same behavior with a different kind of error `no port found, network not attached` (or something like that).

So if the vm goes into error state the machine resource does not know or recognized, just keeps waiting.

**Comment by jichenjc** [comment]
>>>OpenStack throws 500 No Valid Host was Found, visible in the UI

**Comment by franzudev** [comment]
Yes, I was wondering why on lb failure it logs the error with the HTTP status code, but when it's the instance to fail it doesn't show the error's log. I think it's a bit inconsistent behavior, don't you think?

**Comment by mdbooth** [comment]
I *think* we can get the fault code and message from the server object even as an unprivileged user. I wouldn't want to match on the message, though, so I don't think we can distinguish this 500 from other 500s. Thinking about it, 500 doesn't seem like the right fault code here. Not 100% sure what would be most appropriate. Maybe 409? Regardless, this error code means that we can't distinguish this error from actual internal server errors.

That said, to the best of my knowledge nova never retries anything anyway, so I think we can say that as long as the server hasn't been created yet a 500 is terminal and we should mark the server failed.

How about if the controller loop sets a FAILURE condition (i.e. unrecoverable, will not retry) if we get an ERROR status before the server first becomes active, and a different, new ERROR condition with a message if we get an ERROR status after the server has become active?

In both cases the server should be deleted before the Machine is deleted.

@stephenfin thoughts?

**Comment by seanschneeweiss** [comment]
> if we get an ERROR status before the server first becomes active, and a different, new ERROR condition with a message if we get an ERROR status after the server has become active?

> In both cases the server should be deleted before the Machine is deleted.

@mdbooth Could you help me with the deletion order. In my understanding, deleting the openstackmachine would then trigger the deletion of the server.

**Comment by mdbooth** [comment]
> > if we get an ERROR status before the server first becomes active, and a different, new ERROR condition with a message if we get an ERROR status after the server has become active?
> 
> > In both cases the server should be deleted before the Machine is deleted.
> 
> @mdbooth Could you help me with the deletion order. In my understanding, deleting the openstackmachine would then trigger the deletion of the server.

That's right. I was referring to the cleanup order due to the Finalizer. i.e.:

```mermaid
sequenceDiagram
    User->>API: Delete
    API->>Controller: Sees DeletionTimestamp
    Controller->>Nova: Delete
    Controller->>API: Remove Finalizer
    API->>User: Object is deleted
```

**Comment by mdbooth** [comment]
> Sounds reasonable. tbh, `fault.message` == `No valid host was found. ` is a pretty reliable signal to watch for wrt scheduling failures. That will capture the vast majority of them.
> 
> > In both cases the server should be deleted before the Machine is deleted.
> > @stephenfin thoughts?

My concern here is matching on fault description strings in general. I've been burned before by:
* Typos being fixed
* Updates for style (e.g. removing that trailing '.')
* Servers whose local language is French, and the strings are translated

These are just examples. Your painful memories may be different 😉

**Comment by stephenfin** [comment]
You could also just watch the `fault` field. Any value here would likely imply a scheduling failure, at least early on.

**Comment by EmilienM** [comment]
/reopen
/remove-lifecycle rotten
we still have this bug, we can see it in CI in fact.

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/2122/pull-cluster-api-provider-openstack-e2e-test/1800607078713135104/artifacts/clusters/bootstrap/logs/capo-system/capo-controller-manager/capo-controller-manager-7d957cb6cd-5dgc2/manager.log

**Comment by mdbooth** [comment]
> /reopen /remove-lifecycle rotten we still have this bug, we can see it in CI in fact.
> 
> https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/2122/pull-cluster-api-provider-openstack-e2e-test/1800607078713135104/artifacts/clusters/bootstrap/logs/capo-system/capo-controller-manager/capo-controller-manager-7d957cb6cd-5dgc2/manager.log

Which error are you referring to?

**Comment by EmilienM** [comment]
`Invalid state PENDING_DELETE of loadbalancer resource`

This causes the LB to be deleted.

**Comment by EmilienM** [comment]
I just realized this bug report isn't about this Octavia issue :man_facepalming: 
I'll open a new one.
