### ISSUE TITLE
add unit tests for mock.go

### ISSUE THREAD

**Issue by khareyash05** [kubernetes-sigs/cluster-api-provider-openstack#1533]
/kind feature

**Describe the solution you'd like**
Add unit tests for `pkg/scope/mock.go`

**Anything else you would like to add:**
NA

**Comment by mdbooth** [comment]
I feel like this is probably adequately covered in practise by its use in other unit tests. What would you add?

**Comment by jichenjc** [comment]
I don't think it's a feature, so use another tag instead and curious on what's to be added as well
