### ISSUE TITLE
Delete obsolete master branch

### ISSUE THREAD

**Issue by tuminoid** [kubernetes-sigs/cluster-api-provider-openstack#1540]
/kind bug

**What steps did you take and what happened:**

Master branch still exists in this repository, while the main branch has been default branch since 2021.

**What did you expect to happen:**

Delete the master branch.

**Comment by tobiasgiese** [comment]
I cannot see this branch @tuminoid

**Comment by tobiasgiese** [comment]
![image](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/assets/23076619/af71477d-321b-4e8b-8fa4-456163e86686)

**Comment by tobiasgiese** [comment]
Maybe the branch is still in your fork and you have to delete it there? 🙂 
IIRC I have deleted this branch while I have migrated CAPO to `main`.

**Comment by tuminoid** [comment]
Well I'll be damned, it exists in our fork, and thanks to confusing remote naming, I got confused. Sorry for the noise :blush: 

/close

**Comment by tobiasgiese** [comment]
> Well I'll be damned, it exists in our fork, and thanks to confusing remote naming, I got confused. Sorry for the noise blush

No problem at all, happy to help 🙂
