### ISSUE TITLE
Node/server name mismatch due to dots in name

### ISSUE THREAD

**Issue by lentzi90** [kubernetes-sigs/cluster-api-provider-openstack#1547]
/kind bug

**What steps did you take and what happened:**

I created an OpenStackMachineTemplate with a name like `my-cluster-md-0-v1.26.4` and tried to use it.
This caused a strange issue where the kubelet of the new Node managed to register the Node, but the cloud controller then deleted the Node because it could not find a matching server.

Why is this? The name of the OpenStackMachine is derived from the OpenStackMachineTemplate and contains dots.
When translated to a host name the dots are translated to dashes somewhere (not sure where). Thus, the kubelet will register a name with dashes but the server in OpenStack has a name with dots and the cloud controller will get confused.

```console
❯ openstack server list
+--------------------------------------+----------------------------------+--------+-----------------------------------------------------------------------+---------------------------------------+--------------+
| ID                                   | Name                             | Status | Networks                                                              | Image                                 | Flavor       |
+--------------------------------------+----------------------------------+--------+-----------------------------------------------------------------------+---------------------------------------+--------------+
| cee32b6e-b1f8-4f41-97e8-07fb4ee73189 | lennart-test-md-0-v1.26.3-2rgwx  | ACTIVE | k8s-clusterapi-cluster-default-lennart-test=10.6.0.130                | ubuntu-2204-kube-v1.26.3              | 4C-4GB-100GB |
| c5732758-f16e-483c-a676-08685cd2cf12 | lennart-test-md-0-mphbw          | ACTIVE | k8s-clusterapi-cluster-default-lennart-test=10.6.0.99                 | ubuntu-2204-kube-v1.26.3              | 4C-4GB-100GB |
| 24df95e5-c823-4bc4-add0-a6952f5b1c77 | lennart-test-control-plane-nf4fh | ACTIVE | k8s-clusterapi-cluster-default-lennart-test=10.6.0.133                | ubuntu-2204-kube-v1.26.3              | 4C-4GB-100GB |
| 46f461f4-34b2-48cc-997f-8c6eebcc9b56 | lennart-test-bastion             | ACTIVE | k8s-clusterapi-cluster-default-lennart-test=10.6.0.243, <redacted> | Ubuntu 22.04.1 Jammy Jellyfish 230124 | 1C-2GB-50GB  |
+--------------------------------------+----------------------------------+--------+-----------------------------------------------------------------------+---------------------------------------+--------------+

❯ k get nodes
NAME                               STATUS   ROLES           AGE   VERSION
lennart-test-control-plane-nf4fh   Ready    control-plane   37m   v1.26.3
lennart-test-md-0-mphbw            Ready    <none>          30m   v1.26.3

❯ k get machine
NAME                                       CLUSTER        NODENAME                           PROVIDERID                                          PHASE         AGE     VERSION
lennart-test-control-plane-kbzhl           lennart-test   lennart-test-control-plane-nf4fh   openstack:///24df95e5-c823-4bc4-add0-a6952f5b1c77   Running       36m     v1.26.3
lennart-test-md-0-5fd584f555xwjd5q-9w6fk   lennart-test   lennart-test-md-0-mphbw            openstack:///c5732758-f16e-483c-a676-08685cd2cf12   Running       39m     v1.26.3
lennart-test-md-0-69457bc9b8xw8xjn-pl6vg   lennart-test                                      openstack:///cee32b6e-b1f8-4f41-97e8-07fb4ee73189   Provisioned   6m25s   v1.26.3

❯ k get openstackmachine
NAME                               CLUSTER        INSTANCESTATE   READY   PROVIDERID                                          MACHINE                                    AGE
lennart-test-control-plane-nf4fh   lennart-test   ACTIVE          true    openstack:///24df95e5-c823-4bc4-add0-a6952f5b1c77   lennart-test-control-plane-kbzhl           37m
lennart-test-md-0-mphbw            lennart-test   ACTIVE          true    openstack:///c5732758-f16e-483c-a676-08685cd2cf12   lennart-test-md-0-5fd584f555xwjd5q-9w6fk   39m
lennart-test-md-0-v1.26.3-2rgwx    lennart-test   ACTIVE          true    openstack:///cee32b6e-b1f8-4f41-97e8-07fb4ee73189   lennart-test-md-0-69457bc9b8xw8xjn-pl6vg   6m37s
```

Cloud controller logs:

```
I0512 10:01:03.068981       1 openstack.go:359] Claiming to support Zones
I0512 10:01:03.315683       1 node_controller.go:484] Successfully initialized node lennart-test-control-plane-nf4fh with cloud provider
I0512 10:01:03.315732       1 node_controller.go:415] Initializing node lennart-test-md-0-mphbw with cloud provider
I0512 10:01:03.316150       1 event.go:294] "Event occurred" object="lennart-test-control-plane-nf4fh" fieldPath="" kind="Node" apiVersion="v1" type="Normal" reason="Synced" message="Node synced successfully"
I0512 10:01:04.439483       1 openstack.go:359] Claiming to support Zones
I0512 10:01:04.701816       1 node_controller.go:484] Successfully initialized node lennart-test-md-0-mphbw with cloud provider
I0512 10:01:04.702219       1 event.go:294] "Event occurred" object="lennart-test-md-0-mphbw" fieldPath="" kind="Node" apiVersion="v1" type="Normal" reason="Synced" message="Node synced successfully"
I0512 10:10:25.179835       1 node_controller.go:415] Initializing node lennart-test-md-0-v1-26-3-2rgwx with cloud provider
E0512 10:10:25.339485       1 node_controller.go:229] error syncing 'lennart-test-md-0-v1-26-3-2rgwx': failed to get provider ID for node lennart-test-md-0-v1-26-3-2rgwx at cloudprovider: failed to get instance ID from cloud provider: instance not found, requeuing
I0512 10:10:25.339517       1 node_controller.go:415] Initializing node lennart-test-md-0-v1-26-3-2rgwx with cloud provider
E0512 10:10:25.487962       1 node_controller.go:229] error syncing 'lennart-test-md-0-v1-26-3-2rgwx': failed to get provider ID for node lennart-test-md-0-v1-26-3-2rgwx at cloudprovider: failed to get instance ID from cloud provider: instance not found, requeuing
I0512 10:10:25.488143       1 node_controller.go:415] Initializing node lennart-test-md-0-v1-26-3-2rgwx with cloud provider
E0512 10:10:25.654573       1 node_controller.go:229] error syncing 'lennart-test-md-0-v1-26-3-2rgwx': failed to get provider ID for node lennart-test-md-0-v1-26-3-2rgwx at cloudprovider: failed to get instance ID from cloud provider: instance not found, requeuing
I0512 10:10:25.654614       1 node_controller.go:415] Initializing node lennart-test-md-0-v1-26-3-2rgwx with cloud provider
E0512 10:10:25.806657       1 node_controller.go:229] error syncing 'lennart-test-md-0-v1-26-3-2rgwx': failed to get provider ID for node lennart-test-md-0-v1-26-3-2rgwx at cloudprovider: failed to get instance ID from cloud provider: instance not found, requeuing
I0512 10:10:25.806761       1 node_controller.go:415] Initializing node lennart-test-md-0-v1-26-3-2rgwx with cloud provider
E0512 10:10:25.964009       1 node_controller.go:229] error syncing 'lennart-test-md-0-v1-26-3-2rgwx': failed to get provider ID for node lennart-test-md-0-v1-26-3-2rgwx at cloudprovider: failed to get instance ID from cloud provider: instance not found, requeuing
I0512 10:10:25.964049       1 node_controller.go:415] Initializing node lennart-test-md-0-v1-26-3-2rgwx with cloud provider
E0512 10:10:26.133396       1 node_controller.go:229] error syncing 'lennart-test-md-0-v1-26-3-2rgwx': failed to get provider ID for node lennart-test-md-0-v1-26-3-2rgwx at cloudprovider: failed to get instance ID from cloud provider: instance not found, requeuing
I0512 10:10:26.133431       1 node_controller.go:415] Initializing node lennart-test-md-0-v1-26-3-2rgwx with cloud provider
E0512 10:10:26.269076       1 node_controller.go:229] error syncing 'lennart-test-md-0-v1-26-3-2rgwx': failed to get provider ID for node lennart-test-md-0-v1-26-3-2rgwx at cloudprovider: failed to get instance ID from cloud provider: instance not found, requeuing
I0512 10:10:26.294300       1 node_controller.go:415] Initializing node lennart-test-md-0-v1-26-3-2rgwx with cloud provider
I0512 10:10:26.450831       1 event.go:294] "Event occurred" object="lennart-test-md-0-v1-26-3-2rgwx" fieldPath="" kind="Node" apiVersion="" type="Normal" reason="DeletingNode" message="Deleting node lennart-test-md-0-v1-26-3-2rgwx because it does not exist in the cloud provider"
E0512 10:10:26.472366       1 node_controller.go:229] error syncing 'lennart-test-md-0-v1-26-3-2rgwx': failed to get provider ID for node lennart-test-md-0-v1-26-3-2rgwx at cloudprovider: failed to get instance ID from cloud provider: instance not found, requeuing
```

**What did you expect to happen:**

I would expect that this is handled either by

1. rejecting invalid names at some level (webhook when creating OpenStackMachineTemplate?)
2. handle it transparenlty, e.g. by transforming the name in the same way everywhere so that there is no mismatch, or by relying on a different way to match the servers to the nodes (providerID?).

**Anything else you would like to add:**

Initially reported in CAPI https://github.com/kubernetes-sigs/cluster-api/issues/8631.

Just want to highlight also how dangerous this bug is when happening with control plane nodes. The kubelet is able to register the node and the etcd instance is able to become a member. But CAPI/CAPO is unable to remove this etcd member later since the node doesn't exist. This means that it is very easy to lose quorum and break the cluster! :boom: 

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.7.2
- Cluster-API version: v1.4.2
- OpenStack version: Victoria
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`): v1.26.4
- OS (e.g. from `/etc/os-release`): ubuntu 22.04

**Comment by mdbooth** [comment]
Not sure if it's useful, but leaving it here as I've noticed it: from microversion 2.90 you can set an explicit hostname for a server on creation.

We probably don't want hostnames with dots in, though, as that's going to break assumptions in the OS.

I still think the most robust solution here is if we can conspire to pass providerID on the kubelet command line. Do you know of any instance in any CAPI provider where kubelet config is being dynamically configured based ultimately on information from the environment?

**Comment by jichenjc** [comment]
>>>handle it transparenlty, e.g. by transforming the name in the same way everywhere so that there is no mismatch, or by relying on a different way to match the servers to the nodes (providerID?).

providerID likely be set by OCCM so not sure it's early enough for all CAPO expected functions? not sure but if we do, I think match through providerID is the right approach, if not doable, `transforming the name in the same way everywhere so that there is no mismatch` is the desired way as it's common convention for various IT , like public cloud or DNS make 1.2.3.4 become 1-2-3-4 as hostname..

**Comment by mdbooth** [comment]
> > > > handle it transparenlty, e.g. by transforming the name in the same way everywhere so that there is no mismatch, or by relying on a different way to match the servers to the nodes (providerID?).
> 
> providerID likely be set by OCCM so not sure it's early enough for all CAPO expected functions? not sure but if we do, I think match through providerID is the right approach, if not doable, `transforming the name in the same way everywhere so that there is no mismatch` is the desired way as it's common convention for various IT , like public cloud or DNS make 1.2.3.4 become 1-2-3-4 as hostname..

providerID can be set by kubelet (see https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/) as discussed above. providerID is trivial to get on-node from metadata, but it would require us to configure kubelet before it runs somehow. This means that the OCCM node controller doesn't need to set it, because it's already set on the initial Node object. If there's any way we can run something before kubelet I think this is the most robust way to address this.

Failing that, I wouldn't want to artificially restrict the names of k8s objects, but tranforming the name of the created server as described would be a reasonable fix I think.

**Comment by lentzi90** [comment]
Update after some discussions and findings:

It is possible to work around this issue by configuring the kubelet to set the provider ID. Then the cloud controller never needs to compare the node names with the server names and so there is no problem if they differ. We can configure the kubelet through the KubeadmConfigTemplate and KubeadmControlPlane:

```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: lennart-test-control-plane
spec:
  kubeadmConfigSpec:
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: "openstack:///'{{ instance_id }}'"
        name: '{{ local_hostname }}'
...
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: lennart-test-md-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: "openstack:///'{{ instance_id }}'"
          name: '{{ local_hostname }}'
...
```

We could do this directly in our [templates](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/tree/main/templates).
