### ISSUE TITLE
move cloud.conf to a secret, and take it out of plaintext scripts and code

### ISSUE THREAD

**Issue by iamemilio** [kubernetes-sigs/cluster-api-provider-openstack#156]
exhibit a: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/4908a8d40eb6cab3cb7e424dfef35603528ab482/cmd/clusterctl/examples/openstack/centos/provider-components.yaml.template#L190

**Comment by ainmosni** [comment]
I think we need to move to https://github.com/kubernetes/cloud-provider-openstack to make this possible. As long as we use --cloud-provider=openstack on the kubelets, this file needs to be present on the local filesystem.

**Comment by iamemilio** [comment]
I'm not sure how writing it in this config map is any different than writing it in a secret an mounting the data to the file system

**Comment by ainmosni** [comment]
Except that this data needs to be mounted before kubelet starts. Sure, we could start the kubelets without a cloud configuration, then have a container mount the secret, copy the secret out, reconfigure kubelet and then restart kubelet with the cloud configuration. But, in my opinion, this is a less-than-optimal solution, and the time spent on that could be spent on moving to the external cloud provider which would be the right way to solve this problem.

**Comment by iamemilio** [comment]
Ah, I didn't realize that. That is going to be a problem for the kustomize script then.

**Comment by ainmosni** [comment]
Yeah, I will take a look at getting the external cloud provider in there so that we can put the cloud.conf in a secret.

**Comment by iamemilio** [comment]
@ainmosmi I have already begun an implementation of this in my kustomize pr. That being said, it's not fully functional. So feel free to take a look if you would like to finish, otherwise I'll pick it up on Monday

**Comment by iamemilio** [comment]
I'm going to close this issue because I dont think this is viable. I will open a new issue addressing the current bash script we need to use to load the cloud.conf into the user-data.sh scripts though. We want to move towards a pure kustomize approach.
