### ISSUE TITLE
Default subnet filter broken in 0.7.2

### ISSUE THREAD

**Issue by mkjpryor** [kubernetes-sigs/cluster-api-provider-openstack#1570]
/kind bug

**What steps did you take and what happened:**

I have a pre-existing network with exactly one subnet, and I create an `OpenStackCluster` as follows:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackCluster
spec:
  network:
    id: <network-id>
```

i.e. specify a network filter but not a subnet filter.

Up to 0.7.1, this would deploy nodes on the single subnet for the network. As of 0.7.2, I get the following error:

```
failed to find subnet: filter matched more than one resource
```

**What did you expect to happen:**

To use the single subnet for the specified network.

**Anything else you would like to add:**

Prior to 0.7.2, the network ID from the network discovered from the network filter was added to the subnet filter. In 0.7.2 this appears to have changed so that all subnets are searched, regardless of network.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): 0.7.2
- Cluster-API version: 1.3.3
- OpenStack version: devstack HEAD
- Minikube/KIND version: N/A
- Kubernetes version (use `kubectl version`): 1.26
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by mkjpryor** [comment]
@mdbooth

**Comment by mdbooth** [comment]
@mkjpryor Can you share the whole cluster spec? Specifically interested in the subnet definition, but everything would be good just in case.

**Comment by mdbooth** [comment]
Actually I think I can see it. It's in commit 36111421da40a6d0586338cc4d63c0c5d962d5a5 (cherry picked from 6a6b86a66ae6137d8343aa6aeb94aacbdde9daa1):

```diff
-               subnetOpts := openStackCluster.Spec.Subnet.ToListOpt()
-               subnetOpts.NetworkID = networkList[0].ID
-               subnetList, err := networkingService.GetSubnetsByFilter(&subnetOpts)
-               if err != nil || len(subnetList) == 0 {
-                       handleUpdateOSCError(openStackCluster, errors.Errorf("failed to find subnet: %v", err))
-                       return errors.Errorf("failed to find subnet: %v", err)
-               }
-               if len(subnetList) > 1 {
-                       handleUpdateOSCError(openStackCluster, errors.Errorf("failed to find only one subnet (result: %v): %v", subnetList, err))
-                       return errors.Errorf("failed to find only one subnet (result: %v): %v", subnetList, err)
+               subnet, err := networkingService.GetSubnetByFilter(&openStackCluster.Spec.Subnet)
+               if err != nil {
+                       err = fmt.Errorf("failed to find subnet: %w", err)
+
+                       // Set the cluster to failed if subnet filter is invalid
+                       if errors.Is(err, networking.ErrFilterMatch) {
+                               handleUpdateOSCError(openStackCluster, err)
+                       }
+
+                       return err
                }
```

It previously added an implicit filter to the subnet filter of the discovered network ID, and now it just uses the subnet spec as-is. I'm guessing you don't have a subnet spec and therefore this is returning all subnets.

I'll try to get a fix up ASAP.

**Comment by mkjpryor** [comment]
@mdbooth Exactly correct - we specify a network filter and no subnet filter at all.

**Comment by mdbooth** [comment]
Retro note: This is a testing peril of not running CI against a 'dirty' cloud. How could this have been prevented?

**Comment by mdbooth** [comment]
This isn't really fixed. It'll be fixed by the backport.
