### ISSUE TITLE
Cluster stays on phase:  `failed` after Octavia downtime

### ISSUE THREAD

**Issue by nikParasyr** [kubernetes-sigs/cluster-api-provider-openstack#1574]
/kind bug
Hello

**What steps did you take and what happened:**
We had a downtime on our octavia api. During that time CAPO could not reconcile the loadbalancers:
```
E0601 07:24:27.848387       1 controller.go:326] "Reconciler error" err="failed to reconcile load balancer: load balancer \"k8s-clusterapi-cluster-daphne-satellite-dev-kubeapi\" with id 121470d9-6867-45c3-84e4-fc31c4ce860a is not active after timeout: Gateway Timeout" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="daphne/satellite-dev-q5jjz" namespace="daphne" name="satellite-dev-q5jjz" reconcileID=b9d32e02-4f64-4174-aeac-f46e69f9de64
E0601 07:24:28.598708       1 controller.go:326] "Reconciler error" err="reconcile load balancer member: network.APIServerLoadBalancer is not yet available in openStackCluster.Status" controller="openstackmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackMachine" OpenStackMachine="daphne/satellite-dev-control-plane-fcbs5-rj2kp" namespace="daphne" name="satellite-dev-control-plane-fcbs5-rj2kp" reconcileID=b87acea3-6b50-4bab-9203-1af22c6cfc3d
E0601 07:24:28.601363       1 controller.go:326] "Reconciler error" err="reconcile load balancer member: network.APIServerLoadBalancer is not yet available in openStackCluster.Status" controller="openstackmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackMachine" OpenStackMachine="daphne/satellite-dev-control-plane-fcbs5-sxprk" namespace="daphne" name="satellite-dev-control-plane-fcbs5-sxprk" reconcileID=5f80fd1f-647f-4574-a237-e358f43b714d
E0601 07:24:28.728599       1 controller.go:326] "Reconciler error" err="reconcile load balancer member: network.APIServerLoadBalancer is not yet available in openStackCluster.Status" controller="openstackmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackMachine" OpenStackMachine="daphne/satellite-dev-control-plane-fcbs5-6r669" namespace="daphne" name="satellite-dev-control-plane-fcbs5-6r669" reconcileID=be32e507-a4c1-434c-9170-2278bdc3c7f1
```

Moreover, this was added to the `Cluster` resource:
```
  Failure Message:       Failure detected from referenced resource infrastructure.cluster.x-k8s.io/v1alpha6, Kind=OpenStackCluster with name "satellite-dev-q5jjz": failed to reconcile load balancer: load balancer "k8s-clusterapi-cluster-daphne-satellite-dev-kubeapi" with id 121470d9-6867-45c3-84e4-fc31c4ce860a is not active after timeout: Gateway Timeout
  Failure Reason:        UpdateError
```

After a while octavia service was fixed and was operational. Capo was able to reconcile the loadbalancer (nothing had changed) and no more errors were on the logs. The cluster is fully operational (also was during octavia downtime).

But the cluster is stuch on phase: `Failed` with the same Failure message and reason as above.

**What did you expect to happen:**
The cluster should not stay in the `failed` state.

**Anything else you would like to add:**
From a short chat on capi slack channel:
> Failures in CAPI object statuses represent terminal failures - so if there's a terminal failure on an infrastructure object like a load balancer CAPI treats this as a state that can not be recovered from. Transient issues should not result in Failures in status.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): 0.7.1
- Cluster-API version: 1.4.2
- OpenStack version: Victoria
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by seanschneeweiss** [comment]
There was a similar discussion and fix in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1116 for OpenStackMachine.

I agree that transient errors shouldn't be set in the `failureMessage` and `failureReason` of `openStackCluster.status`.


If you like you could start with a similar fix as in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1301 to start the discussion.

**Comment by jichenjc** [comment]
@nikParasyr do you want to provide a simliar fix like above suggested? or I can provide a quick fix ..

**Comment by nikParasyr** [comment]
@jichenjc please go ahead. I won’t have time in the coming weeks
