### ISSUE TITLE
Reconciliation stops working as soon as machine is in error state

### ISSUE THREAD

**Issue by mquhuy** [kubernetes-sigs/cluster-api-provider-openstack#1582]
/kind bug

**What steps did you take and what happened:**
We had a little incidence, which broke the network for a while, the instance went in error state, causing the openstackmachine to change to Failed state.
Once the network was back, the instance went back to running state, the node (on k8s point of view) returned in Ready state, but the openstackmachine didn't recover.

This is due to the fact that capo code doesn't even try to reconcile the machine if the FailureReason (UpdateError) or FailureMessage are not nil https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/152c874c666eaa87e52bbe5591b2e7bfe4452130/controllers/openstackmachine_controller.go#L298

And this stops reconciliation even before attempting to verify instance status here https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/152c874c666eaa87e52bbe5591b2e7bfe4452130/controllers/openstackmachine_controller.go#L370

So my understanding is that this machine will never be able to recover, once it enters in error state. Even if the instance comes back.

Reconciliation is not active, so I guess it will stay stuck forever?

**What did you expect to happen:**
Reconciliation should have picked up the new state

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by seanschneeweiss** [comment]
Which CAPO version are you using currently? 
Some work around this was done in #1301.

**Comment by seanschneeweiss** [comment]
You can patch the failure message and failure reason:
```bash
kubectl patch osm <osm-name> -n <namespace> --subresource='status'  --type 'merge' -p '{"status":{"failureReason":null,"failureMessage":null}}'
```

**Comment by mquhuy** [comment]
Thanks guys. Yes, we've the latest CAPO, which includes #1301 . The workaround that @seanschneeweiss pointed out solved the issue, but as I understand that was just to break the reconciliation out of the if clause that I posted above, wasn't it? Should it then be considered a bug that needs fixing?

**Comment by lentzi90** [comment]
Yes I see now that the issue is exactly what @seanschneeweiss mentioned in #1301. We set the failure message for instances in error state. This is exactly what you describe @mquhuy . If the instance goes to error state (e.g. due to network issues between CAPO and OpenStack) then reconciliation stops.

I think we should not set failure message for this. Does that make sense?

**Comment by mdbooth** [comment]
In general we should only set the failed state when the error state is unambiguously terminal.

As for error states specifically, I think at one point we discussed:
* If the server goes to ERROR *before* the Machine has become ready it is a failure.
* If the server goes to ERROR *after* the Machine has become ready we continue to reconcile.

IIRC the thinking was:
* ERROR state always requires admin action
* If the machine has not yet become ready that action can always be deletion
* If the machine has become ready it may be less disruptive to save it

Would the above fit your experience here?

**Comment by mquhuy** [comment]
Hi @mdbooth . Sorry it took me a bit long to answer your question.

I'm not sure I totally understand your statement, so please forgive me if my answer here goes a bit out of focus. The problem I was trying to explain is that in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/152c874c666eaa87e52bbe5591b2e7bfe4452130/controllers/openstackmachine_controller.go#L349, we set the node as Failure as soon as we cannot find the openstack instance, and while that may represent the state of the node at the time, that failed node will stay failed permanently, since we never reconcile nodes in failure state as I mentioned (and if I understand correctly, that happens regardless of whether the Machine has become ready or not, but please feel free to educate me otherwise).

Imo the requirement that ERROR state should always need manual intervention is a bit harsh, as the errors may have been caused by some temporary glitch, or just a network instability (like in our case). While I agree to some extent that we shouldn't keep reconciling on a node if it stays offline for too long, stopping the reconciliation as soon as there's an error doesn't sound very ideal either. 

I notice that in https://github.com/metal3-io/cluster-api-provider-metal3/pull/910, we already mark the node False when the instance cannot be found. Should that be enough, without setting the node as failed (i.e. without SetFailure())?

**Comment by mquhuy** [comment]
I created #1637 which implements this suggestion
