### ISSUE TITLE
kubectl describe reports empty subnet in v1alpha7

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1608]
/kind bug

Created a v1alpha6 cluster against current main (approx 0.8-alpha.0).

```
> kubectl get openstackcluster.v1alpha7.infrastructure.cluster.x-k8s.io
NAME          CLUSTER       READY   NETWORK                                SUBNET   BASTION IP        AGE
mbooth-test   mbooth-test   true    d040cb4e-8f1f-4c99-9f8e-e6ea5806f26a            192.168.235.225   16m

> kubectl get openstackcluster.v1alpha6.infrastructure.cluster.x-k8s.io
NAME          CLUSTER       READY   NETWORK                                SUBNET                                 BASTION IP        AGE
mbooth-test   mbooth-test   true    d040cb4e-8f1f-4c99-9f8e-e6ea5806f26a   1ab2fb93-b701-4850-a528-b8cd44e44d75   192.168.235.225   16m
```

Note that SUBNET is empty for v1alpha7.

**Comment by jichenjc** [comment]
The `describe` command give the output of SUBNET, right?

**Comment by mdbooth** [comment]
> The `describe` command give the output of SUBNET, right?

I haven't looked into the details of how this works at all yet, but I'm guessing some metadata needs to be updated following the changes to network status in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1577
