### ISSUE TITLE
Use reasonable User-Agent for requests

### ISSUE THREAD

**Issue by mnaser** [kubernetes-sigs/cluster-api-provider-openstack#1611]
/kind bug

**What steps did you take and what happened:**
No details for the version of CAPO in the User Agent.

**What did you expect to happen:**
It would be very nice to be able to have the CAPO version in the User Agent to simplify troubleshooting.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
@mnaser assume you will work on this :) ?

**Comment by mnaser** [comment]
> @mnaser assume you will work on this :) ?

done. :)
