### ISSUE TITLE
Randomly deleted port for VMs

### ISSUE THREAD

**Issue by mnaser** [kubernetes-sigs/cluster-api-provider-openstack#1612]
/kind bug

**What steps did you take and what happened:**
At some point, a VM will simply get it's interface deleted, nothing gets logged anywhere.  Access logs confirm that it was CAPO responsbile behind it.

**What did you expect to happen:**
CAPO to not delete logs.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by mnaser** [comment]
I believe I am into the root cause, I am seeing an OpenStack API call which is listing ports with the name of the instance and the network ID.  

The only reference to this is here:

https://github.com/mnaser/cluster-api-provider-openstack/blob/95ef1e3f511a09dc693b79aaf9aec5840e14a1c5/pkg/cloud/services/networking/port.go#L57-L60

Now, the only place this function gets called from is here:

https://github.com/mnaser/cluster-api-provider-openstack/blob/95ef1e3f511a09dc693b79aaf9aec5840e14a1c5/pkg/cloud/services/compute/instance.go#L196-L197

and within the same exact function.. we have this:

https://github.com/mnaser/cluster-api-provider-openstack/blob/95ef1e3f511a09dc693b79aaf9aec5840e14a1c5/pkg/cloud/services/compute/instance.go#L160-L169

Now the only way we are in that function is if `CreateInstance` is called, which is called here:

https://github.com/mnaser/cluster-api-provider-openstack/blob/95ef1e3f511a09dc693b79aaf9aec5840e14a1c5/controllers/openstackmachine_controller.go#L437-L438

It seems that it is for some reason failing to get the instance status.. trying to create a new server with the same name, failing somewhere after `GetOrCreatePort` successfully returns the list of ports and getting appended then being deleted because of the `defer`'d function...

I _believe_ that's how we've ended up here.. now why did the instance status not be correct.. looking

**Comment by mnaser** [comment]
Another proof for this, I see a request to `/flavors/detail` at the same timeline which is part of `getAndValidateFlavor`.

**Comment by mnaser** [comment]
bingo.

```
2023-07-15 09:06:44.022 23 WARNING nova.compute.multi_cell_list [req-52e0b57e-7d9c-456c-98cd-69755cc2b15e 1b23ea79cd454800094ea06e0c319d2eb2585879745d43a2787a2f004bd86950 27f0c0244502435bbde078259cea6201 - b9b8e05b25c64b03abc10069c08b6217 b9b8e05b25c64b03abc10069c08b6217] Cell 1dd95335-7be1-47df-a076-a4fac1cba152 is not responding and hence is being omitted from the results
```

I think what's happened was that the server was not in the server list because `$some_other_issue` and then CAPO started creating a new server and my guess is the cell started responding again at some point so the server was not nil (cause it exists) but the ports got deleted... gah

I don't know how we can handle this cleanly @mdbooth tbh..

**Comment by mnaser** [comment]
I thought about this a little... we've got two alternatives:

1. Propose that users absolutely must run their clouds with `[api]/list_records_by_skipping_down_cells` to `false` which will return a 500 instead of a 200 with missing items.
2. Bump micro-version in CAPO to 2.69 (it's me again... causing bumps) which would require us to bump minimum supported OpenStack to Stein which has been out for 4 years now and handle a "retry" mechanism for `UNKNOWN` instance types: https://docs.openstack.org/api-guide/compute/down_cells.html

Not really much we can do other than this I think :\

**Comment by jichenjc** [comment]
>>>I think what's happened was that the server was not in the server list because $some_other_issue and then CAPO started creating a new server and my guess is the cell started responding again at some point so the server was not nil (cause it exists) but the ports got deleted... gah

I didn't use cell myself before but from above description seems you are saying is temporary not responding lead to CPO think VM not exist and create a new one then we become double create ?

>>>Bump micro-version in CAPO to 2.69 (it's me again... causing bumps) which would require us to bump minimum supported OpenStack to Stein which has been out for 4 years now and handle a "retry" mechanism for UNKNOWN instance types: https://docs.openstack.org/api-guide/compute/down_cells.html

I think we are talking about microversion support in other threads now. no objection to bump the version but for now
I think we have some logic like:
if support microversion:
           xxxx
else
           yyyy

then we can follow the logic above and no impact to version older than S, after settle down the microversion topic we can
revisit the logic above?

**Comment by mnaser** [comment]
> >>>I think what's happened was that the server was not in the server list because $some_other_issue and then CAPO started creating a new server and my guess is the cell started responding again at some point so the server was not nil (cause it exists) but the ports got deleted... gah
> 
> 
> 
> I didn't use cell myself before but from above description seems you are saying is temporary not responding lead to CPO think VM not exist and create a new one then we become double create ?

Not entirely, at some point there is some other failure that occurs and in the create server function we have a defer function whcih deletes all ports is server is nil 

> >>>Bump micro-version in CAPO to 2.69 (it's me again... causing bumps) which would require us to bump minimum supported OpenStack to Stein which has been out for 4 years now and handle a "retry" mechanism for UNKNOWN instance types: https://docs.openstack.org/api-guide/compute/down_cells.html
> 
> 
> 
> I think we are talking about microversion support in other threads now. no objection to bump the version but for now
> 
> I think we have some logic like:
> 
> ```
> 
> if support microversion:
> 
>            xxxx
> 
> else
> 
>            yyyy
> 
> ```
> 
> then we can follow the logic above and no impact to version older than S, after settle down the microversion topic we can
> 
> revisit the logic above?

This is a possibility so we can handle things based on the supported micro version in the cloud. 

This would mean someone with an older cloud risks running into this issue.. I'm not sure if it makes sense to store the instance ID in the status and behave differently during reconciles if a VM is supposed to already exist (or we can use providerID for this)

**Comment by mdbooth** [comment]
I think we can fix this. We can definitely improve the situation without a microversion bump, and possibly fix it depending of the semantics of `GET /servers/{server_id}` prior to microversion 2.69.

From what I understand, what's happening in the machine controller is most likely:

```
    CreateServer()
    PollImmediate() {
        GetInstanceStatus (by ID) -> returns... error? Weird result?
    }
    unwind deletes ports
```

All of this code needs re-architecting, but as long as we can distinguish a  `GET /servers/{server_id}` for a server that doesn't exist from one whose cell is down I don't think we need a version bump. Even if it returns an error with no useful info that's workable. Just as long as it doesn't return a 404. If a (non-LIST) request for a specific server tells us that it doesn't exist when it actually might, I don't think there's anything we can do about that in CAPO.

**Comment by mnaser** [comment]
@mdbooth : i did a bit of homework...

https://github.com/openstack/nova/blob/b6f4c57b433231ba922abaededeb5fef57a293d4/nova/compute/api.py#L2886-L2922

**Comment by mdbooth** [comment]
I'm convinced we can work with that, even without a microversion bump. I think we should:

* Set providerID as immediately the server is created
* Return from the reconciler immediately after setting provider ID and requeue
* Subsequent reconciles check `status` and don't proceed unless it is `ACTIVE`
* Failure get status is not an error
    * Unless it returns 404, in which case we mark the machine failed.

**Comment by seanschneeweiss** [comment]
Very happy to see you analyzing this. We faced the same problem multiple times in production environments and didn't get to the root cause yet. So far our mitigation strategy was to recreate the port of course.

**Comment by jichenjc** [comment]
```
    Set providerID as immediately the server is created
    Return from the reconciler immediately after setting provider ID and requeue
    Subsequent reconciles check status and don't proceed unless it is ACTIVE
    Failure get status is not an error
        Unless it returns 404, in which case we mark the machine failed.
```

>>>there is currently an [active polling in CreateInstanceImpl](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/821a1a2ef25ac615db5fb26379eb0c4b947ad284/pkg/cloud/services/compute/instance.go#L337-L349) that waits for server to become active prior to return the instance object. As it won't return anything in case of instance error or timeout, I was wondering whether this polling logic should be [moved to main reconcile loop](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/821a1a2ef25ac615db5fb26379eb0c4b947ad284/controllers/openstackmachine_controller.go#L361),


I assume you are looking for above approach, then with the proposal seems we don't need wait for server ACITVE any more as 
the proposal is `Subsequent reconciles check status and don't proceed unless it is ACTIVE` ?

**Comment by zioc** [comment]
Thanks for the reply @jichenjc

While considering the removal of polling in CreateInstanceImpl, I figured out that it would require a significant refactoring of both controllers as:
- instanceCreateTimeout parameter would have to be re-impemented in machine controller if we want to keep honoring this parameter
- cluster controller should also be largely refactored as current bastion implementation is [relying on createInstance](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/821a1a2ef25ac615db5fb26379eb0c4b947ad284/controllers/openstackcluster_controller.go#L352C9-L352C9) to assert the status of the server.

As all this refactoring may be a bit ambitious for a first contribution, I submitted a first PR that preserves current polling implementation in createInstanceImpl. I just changed it to ensure that instance is returned in any case, this way instanceID will be set even if server is in error.

**Comment by mnaser** [comment]
@zioc thanks for taking care of this. I think this should be a lot more critical. In a big cloud failure situation where things are flapping, we had a situation where over 50 ports were deleted, including control plane nodes which had to be recreated. 

It was very painful, so this should have importance to it
