### ISSUE TITLE
New cluster after Application Credential expiration

### ISSUE THREAD

**Issue by framctr** [kubernetes-sigs/cluster-api-provider-openstack#1613]
/kind bug

**What steps did you take and what happened:**
After the creation of a cluster, changing the application credential implies the creation of a new Machine object which schedules a new instance in openstack. Practically this requires to recreate the Kubernetes cluster every time the application credential changes or to set a application credential without expiration date that is a security issue.

**What did you expect to happen:**
Changing the application credential does not require to recreate the entire cluster.

**Environment:**

- Cluster API Provider OpenStack version:
- Cluster-API version: any
- OpenStack version: Wallaby
- Minikube/KIND version: -
- Kubernetes version (use `kubectl version`): 1.24+
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04 or any other

**Comment by mdbooth** [comment]
Is there anything preventing you from updating the secret referenced in the MachineSpec without changing the MachineSpec?

**Comment by framctr** [comment]
Yes the fact that if I change the secret, the openstack instances are destroyed and rebuild together with all Kubernetes installation and services on top of it...

**Comment by mdbooth** [comment]
I mean change the *contents* of the *existing* secret. I'm guessing you're trying to update the MachineSpec with a reference to a new secret?

**Comment by jichenjc** [comment]
right, change secret contents seems didn't update the pod itself 
https://stackoverflow.com/questions/62913187/if-i-update-a-secret-does-it-automatically-gets-updated-to-all-resources-in-whi
so should not update machine/cluster as well .. 

by the way, assume gophercloud will honor the secret change as CAPO seems doesn't have those logic..

**Comment by mdbooth** [comment]
CAPO and CPO are very different here, btw. CPO is only concerned with a single cloud and mounts the OpenStack credentials as a volume. However CAPI uses an IdentityRef in the Cluster/Machine object and therefore always fetches it from the API directly: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/434cfe26c624685cc574cab23e3805add6766dde/pkg/scope/provider.go#L207-L215

IOW unlike CPO, CAPO doesn't have to restart the operator or watch for file changes to detect the change to the secret. It will just be picked up automatically on the next reconcile.

**Comment by mdbooth** [comment]
@framctr Can you confirm that updating the existing secret fixes your issue? If not then we would have a fairly serious issue, but I suspect we can close this.

**Comment by framctr** [comment]
@mdbooth Unfortunately I'm very busy now and I didn't found much time to re-evaluate things. But this is a serious issue for me and I want to dive into the problem better to update you as soon as possible.

**Comment by mnaser** [comment]
> > @mdbooth for the record, we have a very ugly workaround for when users delete clusters and we have to replace the existing application credential:
> > https://vexxhost.github.io/magnum-cluster-api/admin/troubleshooting/#project-deleted
> > and it works™ with no problems
> 
> Eww (but understandable)!
> 
> In cases where you are sure the cloud resources are gone, would it be simpler just to remove the finalizers?

It could be, but I figured I rather let CAPO clean up properly so I don't forget a subnet, a network, a load balancer or something somewhere.. since sadly OpenStack resources can become orphan
