### ISSUE TITLE
Floating IPs can leak if they cannot be attached

### ISSUE THREAD

**Issue by mnaser** [kubernetes-sigs/cluster-api-provider-openstack#1632]
/kind bug

**What steps did you take and what happened:**
If you have a scenario where you create a cluster in a network that doesn't have a router (or a router that has no path to the external network) .. then it will keep looping on every reconcile and allocate a new floating ip but fail to attach it without cleaning up..

**What did you expect to happen:**
It shouldn't keep leaking them non-stop

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by mdbooth** [comment]
I think this was fixed by https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1829
