### ISSUE TITLE
Recommendations for providing external access to cluster created by Cluster API

### ISSUE THREAD

**Issue by seanrmurphy** [kubernetes-sigs/cluster-api-provider-openstack#1634]
/kind feature

**Describe the solution you'd like**
A recommended way of supporting external access to a cluster on specific ports
when a load balancer is in use.

I have been able to create clusters with CAPI and am working through the different
possibilities. I've been able to deploy k8s manifests to the workload cluster using
our gitops workflow and it has been working quite nicely so far.

One issue which I'm struggling with is providing controlled access to the cluster. In 
our config, I've been using the api load balancer which has been basically working
out of the box. I'm now at the stage of wanting to provide access to services which
are running on the cluster, specifically on port 443; however, I now see that the
load balancer is explicitly configured just to give API access (and yes, I see this
is quite clear from the naming).

Is there a recommended way to provide access to services other than the API?
I could imagine, for example, some fields in the cluster config which make ports
accessible on the cluster. Alternatively, if the recommended solution is to add
a second load balancer for non API traffic, it would be good to know that also.
I guess modifying the config of the api load balancer for this purpose is not an
option as presumably CAPI removes any extra config.

**Anything else you would like to add:**
For our setup, we're trying to find the right balance between what needs to
be configured using non-CAPI mechanisms and what needs to be configured
using CAPI (and how they can interact in a repeatable way). Something which
clearly cannot be automated is not ideal for us.

Also, if a second load balancer needs to be added, it would be good to understand
the cleanup implications of this; what cannot be removed automatically by CAPI
if this was added; it would also be good to know how it could relate to addition/
removal of machines/machinedeployments on the cluster.

**Comment by mdbooth** [comment]
CAPO is very specifically and deliberately *only* concerned with the API server. Exposing workload services externally is a 'runtime' concern of the running cluster.

The way to achieve what you want is through
* Ingress
* Loadbalancer services

[cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack) has solutions for both of these depending on your needs.
