### ISSUE TITLE
Crontroller doesn't cache keystone tokens

### ISSUE THREAD

**Issue by alexandrevilain** [kubernetes-sigs/cluster-api-provider-openstack#1647]
/kind bug

**What steps did you take and what happened:**

We have a management cluster with the following resource count:
```console
$ kubectl get openstackclusters -A --no-headers | wc -l
4
$ kubectl get openstackmachines -A --no-headers | wc -l
67
```

When we update the `-v` flag to increase the verbosity, we can check the numbers of requests done to Keystone to get a new token.
```console
I0707 15:54:50.698548       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:50.701020       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:50.708509       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:50.712483       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:50.712982       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:50.715120       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:50.716857       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:50.739230       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:50.739574       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:50.753020       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:50.957990       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:50.960890       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:50.961781       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:50.964750       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:51.067514       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:51.672278       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:51.748524       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:51.954898       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:51.972360       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:52.168773       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:52.206942       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:52.345482       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:52.601283       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:52.810803       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:52.846344       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:52.886106       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:52.938195       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:53.026489       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens
I0707 15:54:54.846506       1 provider.go:127] OpenStack Request URL: POST [keystone_endpoint]/v3/auth/tokens  
```

We can see that we're doing many requests to keystone leading to some rate limiting when using public providers.

**What did you expect to happen:**

We can see that for each reconciliation on OpenStackClusters and OpenStackMachine we call `openstack.Authenticate` (see: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/scope/provider.go#L178). 
Maybe we can have some token caching mechanism ?

**Anything else you would like to add:**

I would be happy to discuss on finding the best solution to prevent this behavior and to implement a fix.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.7.1
- Cluster-API version: v1.3.5
- OpenStack version: stein
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`): v1.25.6
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
I think it's improvement instead of bug, but yeah, something need optimize
do you have any suggestion on this ?e.g a cache valid for 1 hour (token default expire time) and if
we met 401, then create another token and do it again?

**Comment by alexandrevilain** [comment]
@jichenjc ! Yes caching the token for a predefined duration and expire it when an Unauthorized error is hit looks like the most straightforward way to implement this.

My biggest concern was that you didn't want to introduce complexity for this use case. But let's see what we can do!

**Comment by mdbooth** [comment]
Is this steady state, or only during cluster creation? If it's steady state, are you able to tell what is causing the reconciliation?

My thoughts here are that we should only be getting a keystone token if we're going to need it for some OpenStack API call, so we could either:
  - not call reconcile in the first place, or
  - not get an auth token if we're not going to make an OpenStack API call which needs it

Keystone authentication itself tends to be pretty cheap compared to other calls, so I'm comfortable authenticating once at the beginning of a reconcile. I would hope we can address this by fixing an underlying problem.

**Comment by alexandrevilain** [comment]
Hi @mdbooth !
This is steady state. 

For a clarification, only one keystone token is generated per reconcile. But we're reconciling 67 machines in 3 differents tenants in few seconds. 

For instance we can observe this behavior when the controller restarts.

IMO as we're working on only 3 tenants, the controller could keep a cache for tokens for some times. So when the controller restarts only 3 calls are done on keystone and others reconcile are using tokens stored in the cache. WDYT ?

**Comment by mdbooth** [comment]
> Hi @mdbooth ! This is steady state.
> 
> For a clarification, only one keystone token is generated per reconcile. But we're reconciling 67 machines in 3 differents tenants in few seconds.
> 
> For instance we can observe this behavior when the controller restarts.
> 
> IMO as we're working on only 3 tenants, the controller could keep a cache for tokens for some times. So when the controller restarts only 3 calls are done on keystone and others reconcile are using tokens stored in the cache. WDYT ?

I agree, but with some major qualifications.

A keystone call tends to be cheap relative to, e.g. most Nova or Neutron calls. If we're a steady state reconcile looks like:
* get auth token (keystone)
* get server (nova)

My (untested) assumption is that the latter is very substantially more expensive than the former, so caching the former isn't likely to have a major benefit in performance or scalability. However, it will add substantially to complexity, and therefore weird bugs and edge cases.

If for some reason we are fetching an authentication token when we aren't going to make any OpenStack API call, I would consider that a bug which we should definitely fix.

So while I agree that caching keystone auth tokens would be a performance benefit, without more data I'm not yet convinced that it's enough of a performance benefit to warrant the added complexity.

Something else which would change that calculation is my estimation of the added complexity, btw. I don't suppose gophercloud already has something which would make this easy?

Pinging @pierreprinetti and @EmilienM

**Comment by pierreprinetti** [comment]
Gophercloud [does have](https://github.com/gophercloud/utils/blob/de873b9cf00d4b57e384f3f8e6a52dfcb290ecd8/openstack/clientconfig/results.go#L133-L138) token reauthentication built in.

By default, the way that works is by caching authentication credentials, as opposed to a reference to where to fetch those credentials.

---

Essentially, with simply `AllowReauth == true` Gophercloud does this:
1. cache the Keystone token AND the OpenStack credentials
2. when the token ceases to function (ie 401), then authenticate again using the same credentials

Here in CAPO, the requirement is:
1. cache the Keystone token AND the place where to fetch OpenStack credentials
2. when the token ceases to function (I get a 401), then fetch creds again and use them to authenticate again

---

**The needed functionality may be available through [the `ReauthFunc` property of `ProviderClient`](https://github.com/gophercloud/gophercloud/blob/a6cf3572970b308ae4c776e7cc4719ae5d95c285/provider_client.go#L82-L85).**

Unfortunately, the code around reauthentication is not easy to read. It even looks like during reauthentication, the reauth function [gets overwritten](https://github.com/gophercloud/gophercloud/blob/a6cf3572970b308ae4c776e7cc4719ae5d95c285/openstack/client.go#L279-L285).

What I propose is:
1. In a controlled environment, test setting `ReauthFunc` on a `*gophercloud.ProviderClient`
2. If that works, wonderful. If it doesn't, please file an issue to Gophercloud and let's see if that's something we can change

**Comment by pierreprinetti** [comment]
Let me know if you need help in any of these steps, should you choose to walk them.

**Comment by mdbooth** [comment]
Is ProviderClient multi-thread safe?

**Comment by pierreprinetti** [comment]
Great effort seems to have been poured in making it so. Please report as bug if it isn't.

**Comment by alexandrevilain** [comment]
Alright, let's do this  👍
I'll keep you posted once I start implementing this

**Comment by alexandrevilain** [comment]
I started implementing this. You can check it out here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/commit/bcf68272b58a534b1f710646a282cc3bc4f130c5

I did not tested it for now, but I share my progress :)

**Comment by mdbooth** [comment]
Would it be possible to avoid the new external dep by using https://github.com/kubernetes/utils/blob/master/lru/lru.go?

**Comment by mdbooth** [comment]
I also wouldn't bother creating a new cached provider factory. Just update the regular one to use the cache.

**Comment by alexandrevilain** [comment]
Looks way easier now: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/commit/a0ab03a8fbeb5b328f9edf7f3a3dd3999242d7d9

I still have to test this. Some questions remains open:
- how to evict cache when the credentials has changed (maybe we can compare current cloudconfig and cached cloudconfig in the retrieved scope)
- do the reauthfunc will behave as expected

I'll keep you posted.

**Comment by mdbooth** [comment]
Couple of ideas:

I'm assuming there's some way we can determine the expiry time of a token. When fetching an existing token we should probably get a new one and replace it in the cache if we're at, e.g. expiry/2.

Eviction of expired credentials we're no longer using is a bit more complicated. We could kick off a go thread which sweeps the cache every so often?

I don't think we're ever going to need reauthfunc, btw. We should just fetch new credentials as required.

**Comment by alexandrevilain** [comment]
I hopened a draft pull request to continue discussions on it 😊
