### ISSUE TITLE
Possible failure to cleanup ports when not using a BYO network

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1650]
/kind bug

This is from code inspection only:

DeletePorts is called on cluster deletion and is intended to cleanup dangling ports on the cluster network owned by the cluster on the cluster network. However, it references the network definition from the *spec*, not the *status*, which is not required to be set and will not be set if CAPO created the network.

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/77411ad335cae0029bc7cbdd5092ea2d8b82ae2e/pkg/cloud/services/networking/port.go#L266-L272

This should probably be `networkID := openStackCluster.Status.Network.ID`.

**Comment by jichenjc** [comment]
yes, seems it's set 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/networking/network.go#L131
or 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/networking/network.go#L169

so using Status seems reasonable
