### ISSUE TITLE
Changes on OpenstackCluster spec is forbidden

### ISSUE THREAD

**Issue by okozachenko1203** [kubernetes-sigs/cluster-api-provider-openstack#1653]
/kind bug

**What steps did you take and what happened:**
I installed clusters with `spec.allowAllInClusterTraffic` disabled. Then I attempted to set `spec.allowAllInClusterTraffic` as true to let kube-prom-stack to communicate w/ k8s components. But admission webhook declined this change.

**What did you expect to happen:**
There are usecases apparently to be required to change not only `allowAllInClusterTraffic` but also other fields in OpenstckCluster's spec. I expect for CAPO to allow to change OpenstackCluster spec.

**Environment:**
Environment(version infor) doesn't matter. Btw, here is my version infor

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):  v0.7.1
- Cluster-API version: v1.4.4
- OpenStack version: zed
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`): 1.24
- OS (e.g. from `/etc/os-release`): ubuntu jammy

**Comment by jichenjc** [comment]
all validate updates are https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/api/v1alpha7/openstackcluster_webhook.go#L70

you can certainly update this file to allow more update with
- some use case introduction
- code logic to honor the settings updated, 

give following logic, I think if we want to honor the update ,we need recreate the sec group which seems make sense to me
@dulek @mdbooth thoughts?

```
if openStackCluster.Spec.AllowAllInClusterTraffic {
                // Permit all ingress from the cluster security groups
                controlPlaneRules = append(controlPlaneRules, GetSGControlPlaneAllowAll(remoteGroupIDSelf, secWorkerGroupID)...)
                workerRules = append(workerRules, GetSGWorkerAllowAll(remoteGroupIDSelf, secControlPlaneGroupID)...)
        } else {
                controlPlaneRules = append(controlPlaneRules, GetSGControlPlaneGeneral(remoteGroupIDSelf, secWorkerGroupID)...)
                workerRules = append(workerRules, GetSGWorkerGeneral(remoteGroupIDSelf, secControlPlaneGroupID)...)
        }
```

**Comment by dulek** [comment]
@jichenjc: Why do we need to recreate the whole SG? Reconciling the SG rules to the desired state feels more Kubernetes-like to me.

**Comment by jichenjc** [comment]
>>>Why do we need to recreate the whole SG? Reconciling the SG rules to the desired state feels more Kubernetes-like to me.

sorry, my bad, Acutally I mean kill previous rules and recreate new rules based on the new param

**Comment by dulek** [comment]
> > > > Why do we need to recreate the whole SG? Reconciling the SG rules to the desired state feels more Kubernetes-like to me.
> 
> sorry, my bad, Acutally I mean kill previous rules and recreate new rules based on the new param

Okay, so my understanding is that we should rather replace the rules in an as granular way as possible to avoid connectivity interruptions. Again, it's fairly easy, I coded that in CPO previously.

**Comment by jichenjc** [comment]
>>>Okay, so my understanding is that we should rather replace the rules in an as granular way as possible to avoid connectivity interruptions. Again, it's fairly easy, I coded that in CPO previously.

ok, I think AllowAllInClusterTraffic  is a special case as it handles all  traffic ..

**Comment by okozachenko1203** [comment]
> > > > Okay, so my understanding is that we should rather replace the rules in an as granular way as possible to avoid connectivity interruptions. Again, it's fairly easy, I coded that in CPO previously.
> 
> ok, I think AllowAllInClusterTraffic is a special case as it handles all traffic ..

@dulek @jichenjc I think we just need to allow the chanage on `spec.allowAllInClusterTraffic` in `ValidateUpdate`. Then reconciler will do the rest things. Current implementation includes already such a logic what @dulek implemented in CPO.
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/cc258104235783a276c4c094fd98ad1e1f26f32d/pkg/cloud/services/networking/securitygroups.go#L248-L316
