### ISSUE TITLE
delete port behavior on capoerrors.IsNotFound

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#1656]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

maybe someone can help me in understand this logic
why if it's not NotFound error we will report error  here ?  line 287 check if capoerrors.IsNotFound(err) otherwise it return error..
as the DeletePort will report nil if it's success??

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/networking/port.go#L263

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/ad164b340a71ceeb39323532a910706223b9b056/pkg/cloud/services/networking/port.go#L285-L289

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by mdbooth** [comment]
Looks like an oversight. We should probably remove the redundant check in DeletePorts().
