### ISSUE TITLE
Add option to customize private network MTU

### ISSUE THREAD

**Issue by alexandrevilain** [kubernetes-sigs/cluster-api-provider-openstack#1670]
/kind feature

**Describe the solution you'd like**

For now, when we create the network using CAPO, we have no option to set the network's maximum transmission unit (MTU). 
We can add a new `OpenStackCluster` api optional field to provide this customization option.

For instance it could be:
```golang
// OpenStackClusterSpec defines the desired state of OpenStackCluster.
type OpenStackClusterSpec struct {
  // [...]

  // NetworkMTU sets the maximum transmission unit (MTU) value to address fragmentation for the private network ID.
  // This value will be used only if the Cluster actuator creates the network.
  // If leaved empty, the network will have the default MTU defined in Openstack network service.
  // +optional
  NetworkMTU *int `json:"networkMtu,omitempty"`

  // [...]
}
```
 
**Anything else you would like to add:**

I would be happy to add this option if you approve it.

**Comment by mdbooth** [comment]
This sounds like a good feature. My only concern is that it would be adding to a mess I'm already uncomfortable with: namely the lack of distinction between 'BYO' network resources, and controller-managed networks.

Has this shown to be useful for management network traffic, btw?

**Comment by mdbooth** [comment]
@dulek thoughts?

**Comment by alexandrevilain** [comment]
Can't agree more, understanding the distinction between required field for "BYO" network resources and those for controller-managed networks is pretty hard for new comers.

**Comment by dulek** [comment]
This is totally a useful thing, we get requests for supporting this. It's also solved by bringing a BYON IIUC.

**Comment by seanschneeweiss** [comment]
Great addition - we also need to set the MTU :)
