### ISSUE TITLE
Cluster API Provider for OpenStack Retrieves Networks Outside User Project Scope

### ISSUE THREAD

**Issue by bbezak** [kubernetes-sigs/cluster-api-provider-openstack#1672]
/kind bug

**What steps did you take and what happened:**
While creating a Kubernetes cluster using the Cluster API Provider for OpenStack, using tags it retrieved multiple networks from different OpenStack projects, causing an error.
User - non admin (application credential) which is used by Cluster API - can only see his network via openstack cli/api 

error:
E0914 09:42:09.669384       1 controller.go:326] "Reconciler error" err="failed to find only one network (result: [{dad43b54-8674-4165-8c1e-c22ccd4d0111 portal-internal  true ACTIVE [03026f24-e29c-4fa7-a949-2471fc10e22c] e4529e5a687e4128af2935fb33cfa7c2 2023-09-14 09:31:02 +0000 UTC 2023-09-14 09:31:02 +0000 UTC e4529e5a687e4128af2935fb33cfa7c2 false [] [portal-internal] 3} {f7a412b9-f6ef-43ac-9f9a-4190c7540c33 portal-internal  true ACTIVE [2c12dfdb-750d-4621-b478-82ab97386876] 421f6e7634fa4fe5a219f30bab4dc1df 2023-08-22 11:10:44 +0000 UTC 2023-08-22 11:10:44 +0000 UTC 421f6e7634fa4fe5a219f30bab4dc1df false [] [portal-internal] 3}]): <nil>" 

**What did you expect to happen:**
Expected the controller to consider only the network specific to the current project during cluster creation.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Ensuring the controller is project-aware during resource retrieval is crucial for error-free cluster provisioning.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.7.3
- Cluster-API version: v1.4.4
- OpenStack version: yoga
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`): v1.26.6
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.5 LTS

**Comment by mdbooth** [comment]
Please can you provide the relevant CAPO templates, and some OpenStack cli output highlighting the issue?

**Comment by bbezak** [comment]
sorry @mdbooth it was my error, our application which uses CAPI is creating app cred with default user roles - so admin if one creates k8s cluster with admin - I'm fixing it here - https://github.com/stackhpc/azimuth/pull/65/files

**Comment by bbezak** [comment]
so admin seen all networks ;)
