### ISSUE TITLE
Remove FloatingIP from OpenStackMachineSpec

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1674]
/kind feature

FloatingIP is not used by the machine controller, only the Bastion. We should move the floating IP configuration to the Bastion spec (OpenStackCluster.Spec.Bastion) instead.

**Comment by EmilienM** [comment]
I agree with Matt, it's only used in the Bastion, see https://github.com/shiftstack/cluster-api-provider-openstack/blob/070714eaa24a25ec6774cbae1c6e140eb8babebe/controllers/openstackcluster_controller.go#L362-L363

**Comment by EmilienM** [comment]
/reopen

We are reverting. I'll re-add it to main once we have v1alpha8.

**Comment by mdbooth** [comment]
@EmilienM We put this back, right?
