### ISSUE TITLE
OpenStackMachineSpec.ServerMetadata should not be a map

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1684]
/kind feature

OpenStackMachineSpec.ServerMetadata should not be a map. To comply with k8s API conventions it should be a list of name/value pairs with listType=map.

**Comment by EmilienM** [comment]
@mdbooth I was about to look at this one but I have a doubt. Should we still try to improve the API here, while in Gophercloud this is exposed as `Metadata map[string]string` ?

**Comment by mdbooth** [comment]
How would you improve it?

This is a breaking chance, btw, so it depends on another version bump. We're going to have to do that eventually, and before long, but we may not want to do it immediately.

**Comment by EmilienM** [comment]
/remove-lifecycle stale
this is getting merged
