### ISSUE TITLE
Generate reference documentation automatically from godocs in the API

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1694]
/kind feature

We should automatically generate user-referenceable documentation for our APIs from the APIs themselves. We should publish them in/with the CAPO book.

Whether the documentation is generated directly from the API or indirectly via the CRDs is not important. We should investigate how this is solved in other projects to determine existing best practise.

**Comment by lentzi90** [comment]
Since CAPO was created as a kubebuilder project, I think this should be useful to us: https://book-v1.book.kubebuilder.io/beyond_basics/generating_documentation

**Comment by mdbooth** [comment]
> Since CAPO was created as a kubebuilder project, I think this should be useful to us: https://book-v1.book.kubebuilder.io/beyond_basics/generating_documentation

This looks ideal, but I can't see any reference to it in the v2 docs at first glance.

**Comment by alexandrevilain** [comment]
Hi! 

I think that you can use [ahmetb/gen-crd-api-reference-docs](https://github.com/ahmetb/gen-crd-api-reference-docs). 

It used in many well-known projects and I use it in a personal project, it work like a charm, for instance: https://github.com/alexandrevilain/temporal-operator/blob/main/docs/api/v1beta1.md

**Comment by mdbooth** [comment]
> Hi!
> 
> I think that you might use [ahmetb/gen-crd-api-reference-docs](https://github.com/ahmetb/gen-crd-api-reference-docs).
> 
> It's used in many well-known projects and I use it in a personal project, it works like a charm. For instance: https://github.com/alexandrevilain/temporal-operator/blob/main/docs/api/v1beta1.md

That looks good!

**Comment by alexandrevilain** [comment]
I created a PR using [ahmetb/gen-crd-api-reference-docs](https://github.com/ahmetb/gen-crd-api-reference-docs).

I hope it can help.
