### ISSUE TITLE
Implement creation of SecurityGroups in cluster actuator

### ISSUE THREAD

**Issue by chrigl** [kubernetes-sigs/cluster-api-provider-openstack#170]
With #150 in, we have a basic reconciler to create Network, Subnet and Router.

We need to extend this to create appropriate SecurityGroups for control plane and worker nodes.

This ticket must be filled with needed Rules, but I already created it as a reminder for myself.

**Comment by ainmosni** [comment]
Having spoken with @chrigl, I'm going to steal this ticket from him.

**Comment by ainmosni** [comment]
My current idea is to create two security groups, one for the controlplane and one for all the nodes that are hardcoded (maybe I'll add some parameters like ports for the API/sshd).

The controlplane secgroup will allow all to the the API and sshd ports and the general group will allow all to/from all the members in the group.

**Comment by jichenjc** [comment]
I might need go and check openstack logic, will the security group rule update will be updated in VM on the fly? e.g VM we created for k8s cluster will update ssh/ping after reconcile?

**Comment by chrigl** [comment]
@jichenjc We are not at that point yet. The scope of this ticket is just to create securitygroups in the cluster actuator and write them back to `ClusterStatus.ProviderStatus`. Everything else like using the SecurityGroups (and the Network, which is also not yet used) will be tackled later. Here we won't touch any machine.
