### ISSUE TITLE
Tag the OpenStack resources created by CAPO

### ISSUE THREAD

**Issue by flaper87** [kubernetes-sigs/cluster-api-provider-openstack#171]
#150 added network, subnet, and router creation as part of the cluster reconciler. We'll likely be adding logic to create other resources like SecurityGroups (#170). We should tag all these resources in order to ease their management not only for the provider itself but also for operators.

Support for Neutron tags was recently added: https://github.com/gophercloud/gophercloud/pull/1259

**Comment by flaper87** [comment]
@chrigl since you worked on #150, would you be interested in doing this too?

**Comment by chrigl** [comment]
@flaper87 any preferences on how to call that tag? Just `cluster-api-provider-openstack`?

I would only implement tags as an additional information on each resource, and not use it to find the resource in the reconciliation loop. Adding tags is an additional API call, and as far as I understood, not doable during create. So when for whatever reason the controller dies between creating a resource and adding the tag, the resource would be lost. In the current reconciler, I use the name to find existing resources... which for sure is not very nice.

**Comment by flaper87** [comment]
@chrigl fully agree on not using tags to finding the resources throughout the lifecycle of the resource. However, tags may be useful during a cluster deletion to get all the resources that belong to the cluster. This is to avoid having to keep track of all the resources' names.

As for the name, `cluster-api-provider-openstack` should do it. We should also add a tag with the cluster name.

**Comment by chaosaffe** [comment]
Since you may have more than one cluster per tenant, and may want easily identify which resources belong to which cluster, why not use the `name` from the cluster spec if available, falling back to some general identifier if not? This at least gives cluster administrators control over the naming scheme for their clusters and tags

**Comment by chrigl** [comment]
The `name` is not enough in this case. But currently cluster-api only supports a single cluster object per namespace, in finding and creating resources, I use `$PREFIX-$NAMESPACE-$CLUSTER_NAME`. So using something like this (maybe stripped by the PREFIX) makes sense.

**Comment by chaosaffe** [comment]
Following with the Kubernetes naming schema can we use `<namespace>/<name>` if OpenStack allows `/` in tags?

**Comment by chrigl** [comment]
I thought, I read something somewhere on the internet that slashes are not supported. But after testing... they do work. So I will use `<namespace>/<name>`.
