### ISSUE TITLE
Old flags used in ensure-kubectl.sh

### ISSUE THREAD

**Issue by lentzi90** [kubernetes-sigs/cluster-api-provider-openstack#1717]
/kind bug

**What steps did you take and what happened:**
A periodic job failed due to

```console
$ kubectl version --client --short
error: unknown flag: --short 
```

in [ensure-kubectl.sh](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/hack/ensure-kubectl.sh).

See: <https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-openstack-e2e-full-test-main/1711561098999631872>

**What did you expect to happen:**

The job should not fail.

**Anything else you would like to add:**

We just need to update the way we extract the version from `kubectl version`.

**Comment by mdbooth** [comment]
Possible fix(es) in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1713
