### ISSUE TITLE
CEL support

### ISSUE THREAD

**Issue by EmilienM** [kubernetes-sigs/cluster-api-provider-openstack#1736]
/kind feature

**Describe the solution you'd like**
* Add testing structure (ginkgo based) for API testing with [CEL](https://kubernetes.io/docs/reference/using-api/cel/)
* Add CEL to our APIs

I think this issue can be closed once we have the testing structure and at least one CEL + its test, successfully working.

**Comment by jichenjc** [comment]
>>>Add testing structure (ginkgo based) for API testing with [CEL](https://kubernetes.io/docs/reference/using-api/cel/)

seems this are for general API handling, are we introducing CEL for openstackcluster/openstackmachine etc API handling? 
just curious on the use case which have description here will be helpful

**Comment by mdbooth** [comment]
@EmilienM Should we close this? Seems like we've pretty much gone this way now.

**Comment by EmilienM** [comment]
indeed
/close
