### ISSUE TITLE
Remove hard stop if flavor check returns vCPU equals to 1

### ISSUE THREAD

**Issue by SimoneRoma** [kubernetes-sigs/cluster-api-provider-openstack#1742]
/kind feature

**Describe the solution you'd like**

Trying to create WN or CP machine with 1vcpu gives the following error:
`E1004 13:23:42.046633       1 controller.go:324] "Reconciler error" err="create OpenStack instance: kubeadm requires a minimum of 2 vCPUs, pick a flavor with at least 2 vCPUs"`

Suggestion is to remove this check and let kubeadm to eventually log the error. 
Another option is to actually restrict this check on the flavor used for CP machine.

**Comment by jichenjc** [comment]
>>>Suggestion is to remove this check and let kubeadm to eventually log the error.

this is on purpose as we don't want kubeadm do a lot of things and finally find this issue

>>>Another option is to actually restrict this check on the flavor used for CP machine.

you mean the mutation phase? I think that's only check param validation but not for understand the logic behind it

**Comment by SimoneRoma** [comment]
I think that this is over-opinioneted: before 0.8.0 we had a lot of cluster with worker node with just 1 vCPU, and they suite perfectly for small dev environment.
Can we, at least, intruduce a way to easily override this beahvior for folks who know what they're doing?

thx.

**Comment by jichenjc** [comment]
um.. maybe we can remove that code and doc the suggestions ? 
the 2 vcpu limit comes from kubeadmin formal version, guess it's released recently

**Comment by jichenjc** [comment]
https://stackoverflow.com/questions/60804280/kubadm-init-error-cpus-1-is-less-than-required-2
there is a way to ignore the error check in kubeadm but we need add such param if we need adopt it 
and given technically we should support more than kubeadm though not support yet, other tools might not have such
so I think it seems better to remove this check
