### ISSUE TITLE
HTTPS for Loadbalancer Health Monitor

### ISSUE THREAD

**Issue by MPV** [kubernetes-sigs/cluster-api-provider-openstack#1748]
/kind feature

**Describe the solution you'd like**

Be able to use `HTTPS` as type for the load balancer's health monitor (on the `/readyz` path).

**Anything else you would like to add:**

Hopefully this would solve problems such as:
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1749

Related issues:

1. Most-recent improvement (to avoid incidents seen in #1221 and #1374):
   - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1375
2. Making load balancer health checks configurable overall (though only TCP settings discussed yet):
   - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1221
   - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1360

**Comment by MPV** [comment]
Though [searching for `shutdown-delay-duration` in CAPI repo](https://github.com/search?q=repo%3Akubernetes-sigs%2Fcluster-api+shutdown-delay-duration&type=issues), I found issues like these:
- https://github.com/kubernetes-sigs/cluster-api/issues/2753 (mentioned, but solved other issues)
- https://github.com/kubernetes-sigs/cluster-api/issues/2937
   ...closed in favor of:
   - https://github.com/kubernetes-sigs/cluster-api/issues/1250
      ...closed in favor of:
      - https://github.com/kubernetes-sigs/cluster-api/pull/8500
         ...merged 2 days ago, aiming to solve:
         - https://github.com/kubernetes-sigs/cluster-api/issues/7494

**Comment by MPV** [comment]
I think we should also take into account what @mnaser said over in #1374:

> I would have liked to change the following too:
> 
> * `type`: HTTPS
> * `url_path`: `/healthz`
> 
> This will give us actual health checks that involve the API endpoint telling us that it's happy, and it should be OK to accept the unknown cert since [openstack/octavia@`8c793f2`/octavia/common/jinja/haproxy/split_listeners/templates/macros.j2#L178-L182](https://github.com/openstack/octavia/blob/8c793f2e8ff7857a97cc68a4706bdcdfdff1fde5/octavia/common/jinja/haproxy/split_listeners/templates/macros.j2#L178-L182) is OK with it however OVN doesnt support this so we can keep TCP for now.

**Comment by MPV** [comment]
For example, here's one current monitor:
><img width="907" alt="Skärmavbild 2023-11-15 kl  11 16 24" src="https://github.com/kubernetes-sigs/cluster-api-provider-openstack/assets/62675/b297f3cf-7286-4f38-a3f2-e9deda6824b6">

And here's a manually drafted one which I'd like to be able to use instead:
><img width="909" alt="Skärmavbild 2023-11-15 kl  11 17 59" src="https://github.com/kubernetes-sigs/cluster-api-provider-openstack/assets/62675/d99f20e1-d309-478d-a0ec-06602e785f90">

**Comment by mdbooth** [comment]
@dulek What do you think about using HTTPS health monitors here? There's a question about how to support the OVN provider. Does it support HTTPS?

**Comment by dulek** [comment]
> @dulek What do you think about using HTTPS health monitors here? There's a question about how to support the OVN provider. Does it support HTTPS?

It makes perfect sense from my perspective as long as it's opt-in. The OVN provider does not support HTTP or HTTPS health monitors and most likely never will as it lives in layers below. That shouldn't block us from trying to improve things for Amphora.
