### ISSUE TITLE
No obvious failure if `identityRef` is omitted from `OpenStackMachineTemplate`

### ISSUE THREAD

**Issue by stephenfin** [kubernetes-sigs/cluster-api-provider-openstack#1759]
/kind bug

**What steps did you take and what happened:**

Create an `OpenStackMachineTemplate` that omits the `spec.template.spec.identityRef` field. The machine fails to be created and we see the following error from the controller:

```
E1127 16:20:23.342436       1 controller.go:324] "Reconciler error" err="auth option failed for cloud : Missing input for argument [auth_url]" controller="openstackmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackMachine" OpenStackMachine="***/***" namespace="***" name="***" reconcileID=***
```

**What did you expect to happen:**

Ideally we could attempt to retrieve credentials from the cluster. In any case, if no identity ref is provided we should provide a clear failure rather than silently ignoring the issue and failing later.

**Anything else you would like to add:**

None.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.7.0
- Cluster-API version:
- OpenStack version: Wallaby
- Minikube/KIND version: N/A
- Kubernetes version (use `kubectl version`): v1.28.2
- OS (e.g. from `/etc/os-release`): N/A

**Comment by jichenjc** [comment]
>>>Ideally we could attempt to retrieve credentials from the cluster. In any case, if no identity ref is provided we should provide a clear failure rather than silently ignoring the issue and failing later.

+1 , or should we do in webhook?

**Comment by stephenfin** [comment]
From a quick read through, we have the cluster object available earlier in the code path so it _should_ be easy to fix this. I can take a look into this.

/assign @stephenfin
