### ISSUE TITLE
OpenStackCluster.Status.Ready being required causing issues in reconcile

### ISSUE THREAD

**Issue by EmilienM** [kubernetes-sigs/cluster-api-provider-openstack#1841]
/kind bug

**What steps did you take and what happened:**

When fixing https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1838 - I noticed this error in our logs:
```
OpenStackCluster.infrastructure.cluster.x-k8s.io \"cluster-e2e-rha0r3\" is invalid: ready: Required value"
```

This is because the reconcile leaves early when the OpenStackCluster.Status.Ready is not set yet and this field is required.
I think this think should not be required like it's the case for the OpenStackMachine.Status.Ready (omitempty) so we don't have these troubles.

**Comment by EmilienM** [comment]
@kubernetes-sigs/cluster-api-provider-openstack-maintainers please add v1beta1 to milestone.

**Comment by mdbooth** [comment]
I don't currently see this as a v1beta1 issue, btw. It's a bug, but I don't think it's an API issue. I think the error message is a red herring and indicates some code problem elsewhere.
