### ISSUE TITLE
CI: check apidiff once v1beta1 is released

### ISSUE THREAD

**Issue by EmilienM** [kubernetes-sigs/cluster-api-provider-openstack#1860]
/kind feature

**Describe the solution you'd like**
Once we release CAPO v1beta1, our API should remain stable.

One way to check that in CI is to use github.com/joelanford/go-apidiff as it's already done in other providers.
We could add a job that will run apidiff against PR and return an error if the API change is major and not minor.

**Comment by lentzi90** [comment]
I think we should care about the Go API also, so this would be useful.

**Comment by mdbooth** [comment]
It would be good to agree the scope of our Go stability guarantees.

We should probably also switch to proper semver for CAPO releases to account for breaking changes.
