### ISSUE TITLE
`OS_CLOUD` environment variable should be ignored

### ISSUE THREAD

**Issue by stephenfin** [kubernetes-sigs/cluster-api-provider-openstack#1881]
/kind bug

**What steps did you take and what happened:**

Users pass cloud credentials by placing a `clouds.yaml` in a `Secret` and configuring `OpenStackClusterSpec.Cloud` (for the cloud name) and `OpenStackClusterSpec.IdentityRef`. However, if `OS_CLOUD` is defined, we can end up with a mismash of clouds.

**What did you expect to happen:**

We should ignore environment variables. All configuration should be pulled from the `Secret`.

**Anything else you would like to add:**

none.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): `master`
- Cluster-API version: n/a
- OpenStack version: n/a
- Minikube/KIND version: n/a
- Kubernetes version (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): n/a

**Comment by mdbooth** [comment]
This was fixed by https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1882
