### ISSUE TITLE
`identityRef.kind` is ignored

### ISSUE THREAD

**Issue by stephenfin** [kubernetes-sigs/cluster-api-provider-openstack#1882]
/kind bug

**What steps did you take and what happened:**

Identified while working on fix for #1881. The `identityRef` field has a `kind` child field to allow you to specify the kind of object we inspect. Alas, it is completely ignored. We should either remove this field, make it an enum (`["Secret"]`), or otherwise *not* ignore it.

**What did you expect to happen:**

The field should do something.

**Anything else you would like to add:**

None.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): `master`
- Cluster-API version: n/a
- OpenStack version: n/a
- Minikube/KIND version: n/a
- Kubernetes version (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): n/a

**Comment by mdbooth** [comment]
Lets make it an enum of ['Secret']. Lets also give it a default value of 'Secret' so it can be safely omitted.

The upgrade will be a bit weird. We need to ensure that objects with an invalid kind can be upgraded, and on upgrade the kind will be set to 'Secret'.

I think:
* Convert v1alphaN->v1alpha8 should unconditionally set the value to 'Secret'
* For v1alpha8->v1alphaN a restore function unconditionally restores its previous value

**Comment by mdbooth** [comment]
Actually the API guidelines have a specific section on this: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#object-references.

Specifically we should probably follow the [Single resource reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#single-resource-reference) pattern omitting `namespace` as suggested. The guidelines note that this is an extensible pattern which can be upgraded to a [Multiple resource reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#multiple-resource-reference) in the future if required without breaking backwards compatibility.

So... I guess just delete the kind field.
