### ISSUE TITLE
Recreate worker machine failed with "Skipped creating a VM that already exists."

### ISSUE THREAD

**Issue by shiftky** [kubernetes-sigs/cluster-api-provider-openstack#190]
Currently, when the worker machine resource is updated, machine-controller creates new VM immediately after deleting the old VM.

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/fb2ac747965a625bf2119d3551da47fcf377aa9a/pkg/cloud/openstack/machine/actuator.go#L237-L246

But the old VM might still exist right after the controller run "oc.Delete()".
In this case, the VM creation process is skipped with "Skipped creating a VM that already exists" message.

```
I0116 10:18:54.291231       1 controller.go:114] Running reconcile Machine for cluster-api-test-node-hr4vl
I0116 10:18:55.091933       1 controller.go:164] Rejjjconciling machine object cluster-api-test-node-hr4vl triggers idempotent update.
I0116 10:18:55.099080       1 actuator.go:237] re-creating machine cluster-api-test-node-hr4vl for update.
I0116 10:18:57.147586       1 actuator.go:102] Skipped creating a VM that already exists.
```

I think the machine-controller need to check or wait what the old VM is deleted before creating new VM.

**Comment by flaper87** [comment]
@shiftky thanks for reporting this. Is this something you want to work on? If not, I'm happy to take it :smile:

**Comment by shiftky** [comment]
I would like to work on it :smiley:

I'm planning to use `util.util.PollImmediate()` to wait until the old VM is deleted.

I was thinking to add the code between `oc.Delete()` and `oc.Create()`, but this waiting process may also be useful in other cases of deleting a VM.
So I'm considering whether I should add it to `oc.Delete()` as process at a VM deletion. What do you think about it?

**Comment by jichenjc** [comment]
This recreate is a special case so we don't need wait for other normal delete?
maybe a param to indicate whether oc.Delete(wait=false) (by default is true) is enough..

**Comment by shiftky** [comment]
@jichenjc Thank you for your opinion!
The recreate VM (Create immediately after Delete) is a special case as you say.
I will add the waiting process as part of the re-creation process (oc.Update).
