### ISSUE TITLE
GetManagementPort returning an error causing floating ip mapping failure.

### ISSUE THREAD

**Issue by mouad-eh** [kubernetes-sigs/cluster-api-provider-openstack#1921]
/kind bug

**What steps did you take and what happened:**
I am trying to create a single node openstack cluster (without-lb flavor) using clusterctl command. The infrastructure is provisioned and I can see that in the openstack dashboard but the mapping between the floating ip and the fixed ip is not happening.

**What did you expect to happen:**
CAPO automatically maps between the Foating IP and the fixed IP.

**Anything else you would like to add:**
- the openstack cloud is created by using microstack
- when I did the troubleshooting, I find out that [this ](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/a405eebcc2db7985975b1c6f56d9f2f167e17b08/controllers/openstackmachine_controller.go#L471) line of code is failing

- Here are the logs from the CAPO-controller-manager:
<img width="960" alt="image" src="https://github.com/kubernetes-sigs/cluster-api-provider-openstack/assets/80008527/d33f6dab-79f1-4e4d-a205-f6cafb68da2a">

- Here is the status of the Cluster Resource:
<img width="960" alt="image" src="https://github.com/kubernetes-sigs/cluster-api-provider-openstack/assets/80008527/efb2bd35-2c8a-4d2b-a258-3efd9b2f9544">

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.9.0
- Cluster-API version: v1.6.1
- OpenStack version:  5.2.0
- Minikube/KIND version: I am using a kubeadm cluster (kubernetes version v1.29.1)
- Kubernetes version (use `kubectl version`): v1.28.3(client) - v1.29.1(server)
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.3 LTS

**Comment by mdbooth** [comment]
This looks like a configuration quirk relating to this deployment. CAPO is trying to access the OpenStack endpoint on localhost and doesn't find it there.
