### ISSUE TITLE
Error reported before being able to acess via floating IP

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#202]
There is a short period of time the master node can be accessed via floating IP after allocating floating IP.
During the period, clusterctl returns the following error.

```bash
E0124 01:34:57.770799   26526 util.go:150] error executing command "ssh -i /home/ubuntu/.ssh/openstack_tmp -o StrictHostKeyChecking no -o UserKnownHostsFile /dev/null -o BatchMode=yes ubuntu@10.0.0.206 echo STARTFILE; sudo cat /etc/kubernetes/admin.conf": exit status 1
```

This error message should be deleted.

**Comment by jichenjc** [comment]
there might be some time needed in order to let openstack honor the new floating ip
guess this is only error log and after that everything is fine? 
IMO we can safety ignore this error ,user won't pay attention if everything is fine...

**Comment by hidekazuna** [comment]
@jichenjc Yes, creating cluster worked fine after this message. I think it is better to remove this message when Creating cluster ended successfully.

**Comment by hidekazuna** [comment]
I understand this tiny issue as of now via discussing #207 .
