### ISSUE TITLE
We don't test clusterctl move

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#2025]
/kind bug
clusterctl move does not copy object status. While we are *probably* ok with the new state fields in OpenStackMachine (and the bastion) because we considered upgrade where they were not previously set, we should certainly test this.

CAPI's `SelfHostedSpec` exercises this: https://github.com/kubernetes-sigs/cluster-api/blob/ec900f852f8dc45887a4972632b789176ab6ec08/test/e2e/self_hosted.go#L42

We should implement this as soon as possible.

**Comment by lentzi90** [comment]
I'm pretty sure we do test this in the optional suite! I'm after all the one who added it :sweat_smile: 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/test/e2e/suites/e2e/self_hosted_test.go

**Comment by mdbooth** [comment]
Well that came to a rapid conclusion 😎
