### ISSUE TITLE
v1alpha7 e2e tests are actually testing v1alpha6

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#2027]
/kind bug

This can be seen clearly in the v1alpha7 kustomization, which references v1alpha6, and verified to running `make e2e-templates` and checking the contents of the v1alpha7 test template.

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/62dda693422ae490b690192d4ce83c1021ae6893/test/e2e/data/kustomize/v1alpha7/kustomization.yaml#L1-L4

The impact is that our v1alpha7 e2e test is actually testing v1alpha6.

**Comment by kashifest** [comment]
I think this issue is also good to close as I can see a fix here https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2028 @mdbooth
