### ISSUE TITLE
In Cluster conversion bug from v1alpha7 to v1beta1

### ISSUE THREAD

**Issue by qeqar** [kubernetes-sigs/cluster-api-provider-openstack#2050]
/kind bug

**What steps did you take and what happened:**
After updating the capo controller to v0.10.1, all existing openstackcluster have the bastion host enabled, also all where disabled before.

**What did you expect to happen:**
No change in bastion host state

**Anything else you would like to add:**
We are using cluster class.

That was the OpenStackClusterTemplate that was applied while the cluster was still capo v0.9.0

      ---
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
      kind: OpenStackClusterTemplate
      metadata:
        name: test2
        namespace: gks-cdc1061c
      spec:
        template:
          spec:
            tags:
              - GKSv3
              - clustertype=manifest
              - clusterid=cdc1061c
              - customerid=xxxxx
            apiServerLoadBalancer:
              enabled: true
            bastion:
              enabled: false <----
            cloudName: openstack
            externalNetworkId: 54258498-a513-47da-9369-1a644e4be692
            identityRef:
              kind: Secret
              name: test2-cloud-config
            managedSecurityGroups: true
            allowAllInClusterTraffic: true
            nodeCidr: 192.168.1.0/24

After upate we have:

      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackClusterTemplate
      metadata:
        annotations:
          cluster.x-k8s.io/conversion-data: '{"spec":{"h":"paezU1TJYTA=","d":{"template":{"spec":{"cloudName":"openstack","nodeCidr":"192.168.1.0/24","network":{},"subnet":{},"externalNetworkId":"54258498-a513-47da-9369-1a644e4be692","apiServerLoadBalancer":{"enabled":true},"disableAPIServerFloatingIP":false,"managedSecurityGroups":true,"allowAllInClusterTraffic":true,"tags":["GKSv3","clustertype=manifest","clusterid=cdc1061c","customerid=xxx"],"controlPlaneEndpoint":{"host":"","port":0},"bastion":{"enabled":false,"instance":{"cloudName":"","flavor":""}},"identityRef":{"kind":"Secret","name":"test2-cloud-config"}}}}}}'
          kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha7","kind":"OpenStackClusterTemplate","metadata":{"annotations":{},"name":"test2","namespace":"gks-cdc1061c"},"spec":{"template":{"spec":{"allowAllInClusterTraffic":true,"apiServerLoadBalancer":{"enabled":true},"bastion":{"enabled":false},"cloudName":"openstack","externalNetworkId":"54258498-a513-47da-9369-1a644e4be692","identityRef":{"kind":"Secret","name":"test2-cloud-config"},"managedSecurityGroups":true,"nodeCidr":"192.168.1.0/24","tags":["GKSv3","clustertype=manifest","clusterid=cdc1061c","customerid=xxx"]}}}}
        creationTimestamp: "2024-04-11T11:33:12Z"
        generation: 1
        name: test2
        namespace: gks-cdc1061c
        ownerReferences:
        - apiVersion: cluster.x-k8s.io/v1beta1
          kind: ClusterClass
          name: cluster-class-test2
          uid: 42f97373-c6b2-41fe-8231-13aa55e41f76
        resourceVersion: "61008076"
        uid: 9a85caf3-a7da-412e-a881-0d492872d177
      spec:
        template:
          spec:
            apiServerLoadBalancer:
              enabled: true
            bastion: {} <-----
            externalNetwork:
              id: 54258498-a513-47da-9369-1a644e4be692
            identityRef:
              cloudName: openstack
              name: test2-cloud-config
            managedSecurityGroups:
              allowAllInClusterTraffic: true
            managedSubnets:
            - cidr: 192.168.1.0/24
            tags:
            - GKSv3
            - clustertype=manifest
            - clusterid=cdc1061c
            - customerid=xxx

And we have a error message in the ClusterObject:
`error reconciling the Cluster topology: failed to create patch helper for OpenStackCluster/test2-6jn42: server side apply dry-run failed for original object: OpenStackCluster.infrastructure.cluster.x-k8s.io "test2-6jn42" is invalid: spec.bastion: Invalid value: "object": spec is required if bastion is enabled`

Which make sense as we never wanted a bastion host

If more resources are need i can try to provide!

For newly applied resources, the behavior seems a little bit different.  For old one `bastion: {}` is in indirect enabled true

Wen I create a new cluster:

      ---
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
      kind: OpenStackClusterTemplate
      metadata:
        name: test-conversion
        namespace: gks-c34f002a
      spec:
        template:
          spec:
            tags:
              - GKSv3
              - clustertype=manifest
              - clusterid=c34f002a
              - customerid=xxx
            apiServerLoadBalancer:
              enabled: true
            bastion:
              enabled: false <----
            cloudName: openstack
            externalNetworkId: 54258498-a513-47da-9369-1a644e4be692
            identityRef:
              kind: Secret
              name: test-conversion-cloud-config
            managedSecurityGroups: true
            allowAllInClusterTraffic: true
            nodeCidr: 192.168.1.0/24

If see it explicitly enabled:

      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackClusterTemplate
      metadata:
        annotations:
          cluster.x-k8s.io/conversion-data: '{"spec":{"h":"fKff97WHSbw=","d":{"template":{"spec":{"cloudName":"openstack","nodeCidr":"192.168.1.0/24","network":{},"subnet":{},"externalNetworkId":"54258498-a513-47da-9369-1a644e4be692","apiServerLoadBalancer":{"enabled":true},"disableAPIServerFloatingIP":false,"managedSecurityGroups":true,"allowAllInClusterTraffic":true,"tags":["GKSv3","clustertype=manifest","clusterid=c34f002a","customerid=C00106"],"controlPlaneEndpoint":{"host":"","port":0},"bastion":{"enabled":false,"instance":{"cloudName":"","flavor":""}},"identityRef":{"kind":"Secret","name":"test-conversion-cloud-config"}}}}}}'
          kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha7","kind":"OpenStackClusterTemplate","metadata":{"annotations":{},"name":"test-conversion","namespace":"gks-c34f002a"},"spec":{"template":{"spec":{"allowAllInClusterTraffic":true,"apiServerLoadBalancer":{"enabled":true},"bastion":{"enabled":false},"cloudName":"openstack","externalNetworkId":"54258498-a513-47da-9369-1a644e4be692","identityRef":{"kind":"Secret","name":"test-conversion-cloud-config"},"managedSecurityGroups":true,"nodeCidr":"192.168.1.0/24","tags":["GKSv3","clustertype=manifest","clusterid=c34f002a","customerid=C00106"]}}}}
        creationTimestamp: "2024-05-03T05:47:40Z"
        generation: 1
        name: test-conversion
        namespace: gks-c34f002a
        resourceVersion: "81074279"
        uid: b57212f6-a432-498a-8289-79fb1afd4c72
      spec:
        template:
          spec:
            apiServerLoadBalancer:
              enabled: true
            bastion:
              enabled: true    <-----
            externalNetwork:
              id: 54258498-a513-47da-9369-1a644e4be692
            identityRef:
              cloudName: openstack
              name: test-conversion-cloud-config
            managedSecurityGroups:
              allowAllInClusterTraffic: true
            managedSubnets:
            - cidr: 192.168.1.0/24
            tags:
            - GKSv3
            - clustertype=manifest
            - clusterid=c34f002a
            - customerid=C00106

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.10.1
- Cluster-API version: v1.6.3
- OpenStack version: Yoga
- Minikube/KIND version: xxx
- Kubernetes version (use `kubectl version`): v1.29.2
- OS (e.g. from `/etc/os-release`): flatcar

**Comment by mdbooth** [comment]
I think I can see what's happening here: Bastion.Enabled has a type of optional.Bool with a default of true. I think this is a bug.

During conversion from `bool`, `optional.Bool` will convert `false` to `nil`, which is usually correct: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/2214514acdc66dbb40677a130dd3b7a7c058149e/pkg/utils/optional/conversion.go#L81-L89

However, in this case the v1alpha7 false value is converted to nil and omitted, which is then defaulted to true when read as v1beta1.

We should do 2 things:
- Bastion.Enabled should not use optional.Bool, as it is not safe in this case.
- Conversion of v1alpha7 clusterspec with `bastion: {enabled: false}}` should omit the bastion entirely in v1beta1.

The first is essential. The second is an optimisation.

**Comment by mdbooth** [comment]
I have a simple failing test case in apivalidations under cluster/v1alpha7:

```golang
		FIt("should not enable the bastion when upgrading to v1beta1", func() {
			cluster.Spec.Bastion = &infrav1alpha7.Bastion{Enabled: false}
			Expect(create(cluster)).To(Succeed(), "OpenStackCluster creation should succeed")

			// Fetch the infrav1 version of the cluster
			infrav1Cluster := &infrav1.OpenStackCluster{}
			Expect(k8sClient.Get(ctx, types.NamespacedName{Name: cluster.Name, Namespace: cluster.Namespace}, infrav1Cluster)).To(Succeed(), "OpenStackCluster fetch should succeed")

			Expect(*infrav1Cluster.Spec.Bastion.Enabled).To(BeFalse(), "Bastion should be disabled")
		})
```

This test case will almost certainly change before submission, but it's sufficient to work on the problem.
