### ISSUE TITLE
`GetInstanceStatusByName` doesn't return an error when > 1 instance if found

### ISSUE THREAD

**Issue by EmilienM** [kubernetes-sigs/cluster-api-provider-openstack#2088]
/kind bug

**What steps did you take and what happened:**

`GetInstanceStatusByName` doesn't return an error when > 1 instance if found and this can lead to cluster problems if we have two instances with the same name. Could be a leftover or a staled resource, that needs to be removed before creating a new one.

**What did you expect to happen:**

An error should be returned.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): latest

**Comment by mdbooth** [comment]
I think if we have 2 instances with the same name and can't distinguish between them we're just going to have to report an error to the user. I'm not sure we can safely do anything about it, now or with OpenStackServer.

**Comment by EmilienM** [comment]
ok so i'll submit a PR that just reports an error for now, gotcha.
