### ISSUE TITLE
global cluster http_proxy support / configuration

### ISSUE THREAD

**Issue by xinity** [kubernetes-sigs/cluster-api-provider-openstack#2089]
hello there,

i was wondering what would be the best way to support http_proxy globally ?
i am required to use an internal http_proxy and i want to make sure that all cluster deployed will be able to leverage it

is it something we can achieve using CAPO ? 

not sure if it's a CAPO or a CAPI topic to be honest :)

**Comment by mdbooth** [comment]
I don't think it's either, tbh; I think it's a kubernetes question. I know OpenShift can do this, but I'm not 100% clear on the mechanism. It wouldn't surprise me if it's something like injecting proxy environment variables into all pods on admission.

**Comment by jichenjc** [comment]
I think it's a k8s question , not something in CPO， so close this and feel free to reopen 

not sure whether openshift did something internally through setting on ingress or other things, no clear detail info only how to use it here ...
https://docs.openshift.com/container-platform/4.15/networking/enable-cluster-wide-proxy.html

**Comment by pawcykca** [comment]
You can achieve this by:
* image-builder -> preparing images with proxy configuration
* CAPI -> setting proxy configuration in `KubeadmControlPlane` and `KubeadmConfigTemplate`
