### ISSUE TITLE
RBAC: Controller is not allowed to access Machine and Cluster

### ISSUE THREAD

**Issue by chrigl** [kubernetes-sigs/cluster-api-provider-openstack#213]
See below for logs.

The Problem here is... we changed to RBAC autogeneration in #189 , which IMHO is a good idea.
This leads to use the namespace "system". See https://github.com/kubernetes-sigs/cluster-api-provider-openstack/commit/f5839bd6a5f8e83fbdd164fba59ceb6501029d7a#diff-4ed5c4aff360de81af5eb0f0c77a2ad6R13
... but the controller still lives in "openstack-provider-system".

Unfortunately the code of the controller-tools is not really flexible and the namespace can not be configured. See
* https://github.com/kubernetes-sigs/controller-tools/blob/fbf141159251d035089e7acdd5a343f8cec91b94/pkg/rbac/manifests.go#L141
* https://github.com/kubernetes-sigs/controller-tools/blob/fbf141159251d035089e7acdd5a343f8cec91b94/pkg/rbac/manifests.go#L59

```
[egarcia@emilio openstack]$ kubectl logs -n openstack-provider-system clusterapi-controllers-7f797bb8f8-p59p7
I0128 19:45:38.032130       1 main.go:73] Initializing Dependencies.
W0128 19:45:38.044373       1 controller.go:58] environment variable NODE_NAME is not set, this controller will not protect against deleting its own machine
2019/01/28 19:45:38 Starting the Cmd.
E0128 19:45:38.133125       1 reflector.go:205] sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.Cluster: clusters.cluster.k8s.io is forbidden: User "system:serviceaccount:openstack-provider-system:default" cannot list resource "clusters" in API group "cluster.k8s.io" at the cluster scope
E0128 19:45:38.133616       1 reflector.go:205] sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.Machine: machines.cluster.k8s.io is forbidden: User "system:serviceaccount:openstack-provider-system:default" cannot list resource "machines" in API group "cluster.k8s.io" at the cluster scope
E0128 19:45:39.231469    
```

**Comment by jichenjc** [comment]
ok, opened https://github.com/kubernetes-sigs/controller-tools/issues/133
 and see whether we can get some response..
