### ISSUE TITLE
Optional floating IPs in cluster machines

### ISSUE THREAD

**Issue by bartekle** [kubernetes-sigs/cluster-api-provider-openstack#2140]
/kind feature

**Describe the solution you'd like**
Possibility to associate floating IP with default port of cluster machine.

**Anything else you would like to add:**
This feature may be redundant in case of debuging and bastion host availability, but floating IP is also used as egress strategy - node has other, specific network path rather than default network nodes.

**Comment by mdbooth** [comment]
Is this different to the functionality provided by the floating IP IPAM provider?

/cc @huxcrux

**Comment by huxcrux** [comment]
> Is this different to the functionality provided by the floating IP IPAM provider?
> 
> /cc @huxcrux

A late reply but yes sounds like exactly what the FIP IPAM provides :)

So it should just be to create a Pool: https://cluster-api-openstack.sigs.k8s.io/api/v1alpha1/api#infrastructure.cluster.x-k8s.io/v1alpha1.OpenStackFloatingIPPool

And then refer to it in the [OpenStackMachineTemplate](https://cluster-api-openstack.sigs.k8s.io/api/v1beta1/api#infrastructure.cluster.x-k8s.io/v1beta1.OpenStackMachineTemplate) by setting floatingIPPoolRef to point towards the pool. 

Just be aware that the pool will create new FIPs by default meaning if you want to use an IP already in the project/tenant it needs to be added to the spec by setting preAllocatedFloatingIPs (a list).
