### ISSUE TITLE
Cloud init support v1beta1?

### ISSUE THREAD

**Issue by nilpntr** [kubernetes-sigs/cluster-api-provider-openstack#2171]
/kind feature

**Describe the solution you'd like**
I'm trying to convert our current cluster setup to cluster-api. We would like to use user data to insert bash scripts to install certain apt packages etc... I saw this is possible in old versions, is it also supported in v1beta1?

**Comment by EmilienM** [comment]
It's still supported; nothing changed on that: you still need to create a secret and give the ref to `Machine.Spec.Bootstrap.DataSec` which will be given to https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/api/v1alpha1/openstackserver_types.go#L103-L106 and handled by the openstackserver controller.

Please let us know and if that worked close the issue.

**Comment by nilpntr** [comment]
> It's still supported; nothing changed on that: you still need to create a secret and give the ref to `Machine.Spec.Bootstrap.DataSec` which will be given to https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/api/v1alpha1/openstackserver_types.go#L103-L106 and handled by the openstackserver controller.
> 
> Please let us know and if that worked close the issue.

I saw the same thing but it's not supported on v1beta1 version or should I use alpha for that feature?

**Comment by EmilienM** [comment]
> I saw the same thing but it's not supported on v1beta1 version or should I use alpha for that feature?

It's been supported for a long time and it's still supported. Nothing changed, you should be fine and if it's not working it's a high bug and we need to fix it. Let us know.
Again, the thing is a secret to create and use it as a ref in the Machine object. The rest is handled by CAPO for you.

**Comment by mdbooth** [comment]
> > It's still supported; nothing changed on that: you still need to create a secret and give the ref to `Machine.Spec.Bootstrap.DataSec` which will be given to https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/api/v1alpha1/openstackserver_types.go#L103-L106 and handled by the openstackserver controller.
> > Please let us know and if that worked close the issue.
> 
> I saw the same thing but it's not supported on v1beta1 version or should I use alpha for that feature?

This hasn't been removed in v1beta1. Can you give an example of what you are trying to do in v1alpha7 which isn't possible in v1beta1?

**Comment by nilpntr** [comment]
> > > It's still supported; nothing changed on that: you still need to create a secret and give the ref to `Machine.Spec.Bootstrap.DataSec` which will be given to https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/api/v1alpha1/openstackserver_types.go#L103-L106 and handled by the openstackserver controller.
> > > Please let us know and if that worked close the issue.
> > 
> > 
> > I saw the same thing but it's not supported on v1beta1 version or should I use alpha for that feature?
> 
> This hasn't been removed in v1beta1. Can you give an example of what you are trying to do in v1alpha7 which isn't possible in v1beta1?

I'm sorry I checked the wrong docs. Thanks for helping me!

**Comment by EmilienM** [comment]
Feel free to reopen if needed
