### ISSUE TITLE
SecurityGroup automatic removal during cluster deletion

### ISSUE THREAD

**Issue by eromanova** [kubernetes-sigs/cluster-api-provider-openstack#227]
Currently, users are able to set `managedSecurityGroups: true` in cluster ProviderSpec. This will create two security groups: one for control-plane machine and another for all nodes. But created SecurityGroups keep alive after machine removal. It'll be good to add their automatic removal during cluster deletion.

**Comment by gyliu513** [comment]
@eromanova where can I find this parameter `managedSecrityGroup: true`? I checked the code, but no such parameter, am I missing anything? Thanks!

**Comment by eromanova** [comment]
@gyliu513 I'm sorry, there was a typo in issue description. The parameter is called `managedSecurityGroups`. It's a boolean option in `Cluster.spec.ProviderSpec`. You can get more info from `README.md` file.
