### ISSUE TITLE
How control cluster if the user who create cluster is removed from keystone

### ISSUE THREAD

**Issue by nguyenhuukhoi** [kubernetes-sigs/cluster-api-provider-openstack#2336]
/kind bug

**What steps did you take and what happened:**

I have an OpenStack project that includes two users: user A and user B. Each user has their own cluster. One day, user B was removed from the project(delete user from Keystone). User A wants to control user B's cluster, such as adding or removing MachineDeployments, but is unable to do so because the Application Credential of user B could not be found. Can

**What did you expect to happen:**

I want to control this cluster such as add or remove nodegroup or node with other users who are same tenant.

**Anything else you would like to add:**

`1215 23:32:53.732329       1 controller.go:324] "Reconciler error" err="providerClient authentication err: Expected HTTP response code [201 202] when accessing [POST https://magcloud.net:5000/v3/auth/tokens], but got 404 instead: {\"error\":{\"code\":404,\"message\":\"Could not find Application Credential: 818a68654b65417396f29f9c1fa9cd24.\",\"title\":\"Not Found\"}}" controller="openstackmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackMachine" OpenStackMachine="magnum-system/kube-vh5r3-default-worker-kw6bs-hlnr9-cdz44" namespace="magnum-system" name="kube-vh5r3-default-worker-kw6bs-hlnr9-cdz44" reconcileID="14cbfbac-6689-49e2-8774-5f6a52b34823"`

@mdbooth was helped me ask https://app.slack.com/client/T09NY5SBT/C8TSNPY4T

**Environment:**

- Cluster API Provider OpenStack version : v0.11.3
- Cluster-API version : 1.9.1 
- OpenStack version: 2024.1
- Minikube/KIND version:
- Kubernetes version: v1.28.7
- OS: 22.04

**Comment by mdbooth** [comment]
This is an issue with your OpenStack credentials. You need to update them to be valid now that user B has been removed.

Assuming user A has sufficient privilege in OpenStack to manage resources created by user B, they need to create a new application credential and update the contents of the secret pointed to by the `identityRef` field in the CAPO objects.

If user A does not have sufficient privilege in OpenStack to manage resources create by user B they will have to go to their OpenStack administrator to get them.

**Comment by nguyenhuukhoi** [comment]
Hello, I would like know if
 OpenShift have this problem?

**Comment by mdbooth** [comment]
Yes, OpenShift would have the same issue. The issue here is that the OpenStack credentials are no longer valid. CAPO doesn't have any privileged access to OpenStack, only what is contained in the credentials the user gives us. If those credentials become invalid we literally can't do anything.
