### ISSUE TITLE
How to provision a k8s cluster with an existing k8s cluster but not bootstrap cluster?

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-openstack#263]
I found that the k8s provision with openstack can either use a bootstrap cluster or use an existing cluster, but there is  no document for how to use an existing cluster to provision new k8s cluster, does there are any document that I can refer? Thanks.

**Comment by jichenjc** [comment]
does cluster-api support this ? I think we may ask this in that part as well

**Comment by gyliu513** [comment]
An issue for cluster-api https://github.com/kubernetes-sigs/cluster-api/issues/825

**Comment by gyliu513** [comment]
Fixed by https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/299
