### ISSUE TITLE
support CoreOS

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#272]
coreos is important part of openshift IPI and UPI in the future..we should consider to enable it

**Comment by chrigl** [comment]
@ainmosni is working on this.

/cc @ainmosni

**Comment by ainmosni** [comment]
Yeah I'm in the final phases of testing a setup, expect a PR today or tomorrow.

**Comment by jichenjc** [comment]
@ainmosni ok, I actually tried deploy manually and already worked ,so in case you have something in hand, I am glad that I can help the try and review of the PR ,can you notify me when it's uploaded? THanks !

**Comment by ainmosni** [comment]
@jichenjc Thanks for the review offer, I just pushed the PR offer, so by all means, pick it apart. :)
