### ISSUE TITLE
Use `kubectl kustomize` instead of `kustomize` 

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-openstack#282]
`kustomize` is now a sub-command for `kubectl` https://github.com/kubernetes/kubernetes/pull/73033 , so there is no need to let end user install `kustomize` separately, but installing `kubectl` is good enough.

We can update the script and document to clarify how to use `kubectl kustomize`. 

/cc @dims 

FYI @jichenjc @morvencao @xunpan @clyang82

**Comment by iamemilio** [comment]
sounds good, just make sure we keep the kustomize version the same, otherwise it will have bugs

**Comment by jichenjc** [comment]
@gyliu513 is this still a todo? and seems @iamemilio 's point is valid, we support 1.0.11 kustomize only

**Comment by gyliu513** [comment]
I see, but why not fix bugs related to kustomize?

**Comment by jichenjc** [comment]
A valid point... , let's use https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/356 to track

**Comment by sbueringer** [comment]
@jichenjc I think this has been fixed here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/356

**Comment by jichenjc** [comment]
/close

yes, fixed already
