### ISSUE TITLE
Enable configuring docker for machine

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-openstack#288]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

When I was using kube 1.14.0, kubelet cannot start up due to following errors:
```
+ kubeadm init --config /etc/kubernetes/kubeadm_config.yaml
[init] Using Kubernetes version: v1.14.0
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
```

It is better to enable end user can configure docker cgroup driver in Machine Spec, comments?

Besides, someone may also want to use specified docker version as well, so it is better to enable end user can set some docker configurations as well.

/cc @dims @jichenjc 

FYI @xunpan @morvencao @clyang82

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jichenjc** [comment]
I think better way might be set cluster wide param in cluster.yaml (have some default value) so user can change  one place to change all machines, then optional we can set per-machine configuration but I double whether that's really useful

and this seems to be cluster api scope?

**Comment by gyliu513** [comment]
Thanks @jichenjc , Yes, this should be cluster-api scope feature. I opened an issue at https://github.com/kubernetes-sigs/cluster-api/issues/866
