### ISSUE TITLE
Delete a machine stuck for long time

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#294]
/kind bug

root@kvm-017751:~/go/src/sigs.k8s.io/cluster-api-provider-openstack/cmd/clusterctl# kubectl --kubeconfig=minikube.kubeconfig get machine
NAME                     AGE
openstack-master-clwxs   11m
root@kvm-017751:~/go/src/sigs.k8s.io/cluster-api-provider-openstack/cmd/clusterctl# kubectl --kubeconfig=minikube.kubeconfig delete machine openstack-master-clwxs
machine.cluster.k8s.io "openstack-master-clwxs" deleted

the delete stuck at here and nothing else, wait for long time and have to Ctrl+c

still see it after long wait

root@kvm-017751:~/go/src/sigs.k8s.io/cluster-api-provider-openstack/cmd/clusterctl# kubectl --kubeconfig=minikube.kubeconfig get machine
NAME                     AGE
openstack-master-clwxs   49m

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by chrigl** [comment]
@jichenjc Could you have a look at the logs of the `clusterapi-controllers-xxx`. Maybe this does point you in the right direction.

**Comment by gyliu513** [comment]
@jichenjc @chrigl I can delete master node successfully as

```
root@gyliu-dev1:~/go/src/sigs.k8s.io/cluster-api# kubectl delete machine liugya-master-cpr5j
machine.cluster.k8s.io "liugya-master-cpr5j" deleted
root@gyliu-dev1:~/go/src/sigs.k8s.io/cluster-api#
```

But here I have a question: If the bootstrap cluster was deleted, then we may not able to delete a master node via `kubectl delete machine`, as the cluster api controller was running on master node, and the delete of master node will delete the cluster api controller as well, for such case, not sure how master node would be cleaned up?

**Comment by gyliu513** [comment]
BTW: @jichenjc can you please update your problem a bit with mark down https://www.markdownguide.org/ , this is can make it easy to read ;-)

For some command, we recommended use following format:

```
your commands here
```

**Comment by jichenjc** [comment]
ok, thanks for the comments, I will use the format next time

and please note this doesn't always occur, some times I can delete the master sometimes I can't.... don't know what's magic there

and there is a env called NODE_NAME
https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machine/controller.go
line 40 to prevent the master be deleted by itself....
