### ISSUE TITLE
[Question]any plans to running clusterctl in container

### ISSUE THREAD

**Issue by hchenxa** [kubernetes-sigs/cluster-api-provider-openstack#304]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Do we have any plan to running clusterctl in container so that I can:

1) Use k8s job/cronjob to create the k8s cluster
2) Integrate with knative to use tekon pipeline for k8s cluster deploy.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by hchenxa** [comment]
cc @gyliu513 @jichenjc

**Comment by jichenjc** [comment]
@hchenxa  this might be a good question to ask https://github.com/kubernetes-sigs/cluster-api
as far as I know, clusterctl is mostly from cluster-api and openstack just provide some basic 'provider' specific info ,so how to use clusterctl can be asked there

**Comment by hchenxa** [comment]
based on comments https://github.com/kubernetes-sigs/cluster-api/issues/289#issuecomment-411568874, this should up to the different provider,  and refer https://console.cloud.google.com/gcr/images/cnx-cluster-api/GLOBAL, there current have some docker images but did not included the openstack provider.

**Comment by gyliu513** [comment]
I think this make sense, if we can put `clusterctl` to a container, it will be more simple to ship it to end user.

/cc @dims

**Comment by gyliu513** [comment]
@hchenxa You can create a PR if you have some cycle for this, refer to https://github.com/kubernetes-sigs/federation-v2/blob/master/Makefile#L79-L82 for a reference.

**Comment by jichenjc** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/143/commits/c80ec38865544e8019759a393463279db38636d8

that's only for CI purpose at beginning 
but I agree this should be useful in your use case, so refer to that commit should be helpful
