### ISSUE TITLE
can not force delete machines resources

### ISSUE THREAD

**Issue by hchenxa** [kubernetes-sigs/cluster-api-provider-openstack#307]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
I was trying to delete the machine by `kubectl delete machine --force --grace-period=0`, but find the command will still need the controller's to finish the machine delete operations. 
so :
1) if my controller was delete by mistake, how can I delete the cluster and machine resources.
2) If my controller can not connect to openstack environment, how can I delete the cluster and machine resources.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
1) the controller is gone, and this is a mistake, maybe just manual delete the nodes ( the VM spawned ) should be ok? 
2) if can't connect to, we should not allow delete resource or it will lead to orphan resource?

**Comment by hchenxa** [comment]
thanks for answer.

actually, there did not have VMs created on openstack, so I did not know how to clean up the garbage resources.

**Comment by jichenjc** [comment]
no VM created and the controller is gone, then every thing is cleaned?

**Comment by hchenxa** [comment]
let me clarify the cases here:

Case 1: I tried to use cluster-api to create the VMs on Openstack, but the VM creation failed due to auth failed, so I tried to delete the machine and the cluster but the operations also failed with the same reason of creation.

Case 2: Then I try to delete the machine and cluster resources with the paramemter `--force --grace-period=0` but did not help

Case 3: Then I delete the controller to see if it will help, but seems not, the resources can not deleted as well.

**Comment by chrigl** [comment]
@hchenxa As a short term workaround... there are a finalizers on each machine preventing the object to be deleted form etcd as long as the finalizers are there. Removing the finalizers by hand (e.g. `kubectl edit machine something`) should let Kubernetes remove the Machine entirely.

The longer term issue: There seems to be either a problem in create machine or delete machine, or both, that we need to find and work around.

**Comment by hchenxa** [comment]
closing this as we can remove the finalizers to force delete the resources.
