### ISSUE TITLE
Sync `cluster-api-provider-openstack` config with `cloud-provider-openstack`

### ISSUE THREAD

**Issue by chaosaffe** [kubernetes-sigs/cluster-api-provider-openstack#31]
As identified by @flaper87 we use a different authentication config than the `cloud-provider-openstack`, which can lead to confusion and prevents reuse of code. In addition to enabling authentications with a standard OpenStack`clouds.yaml` file being addressed in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/16 we should also adopt the `cloud-provider-openstack` structure for traditional credentials.

**Comment by flaper87** [comment]
To be honest, I'd rather deprecate the existing format in `cloud-provider-openstack` and have it adopt `clouds.yaml` as well. I presented this idea to some other folks from the OpenStack SIG and they seemed to like the idea. What do you think about it?

As part of #16, we're adding support for `clouds.yaml` to `cluster-api-provider-openstack`. Once that's done, we can move this code to the cloud provider and the vendor it here.

I'd prefer us to maintain a single implementation for the configuration format and I'd rather have it be the `clouds.yaml`, which is a standard that we've been using in OpenStack for a long time.

**Comment by flaper87** [comment]
@iamemilio FYI

**Comment by chaosaffe** [comment]
@flaper87 I'm not the OpenStack expert, but I talked to our internal team and they fully agree with dropping the env var credentials and only supporting `clouds.yaml`

Using a common base for the `clouds.yaml` support in `cloud-provider-openstack` and `cluster-api-provider-openstack` is certainly something I can get behind 😀
