### ISSUE TITLE
Enable OpenStack provider support different Kubuernetes Distributions

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-openstack#311]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

I have opened an issue at https://github.com/kubernetes-sigs/cluster-api/issues/853 and driving some discussion there, but would love to get some comments from here as well. ;-)

Currently the OpenStack Cloud Provider is using `user-data` to do post install, and the `user-data` will help to install native Kubernetes cluster via `kubeadm`.

In order to install different Kubernetes distributions, we can probably enhance `user-data` to support installing different Kubernetes distributions, like [IBM Cloud Private](https://www.ibm.com/cloud/private), OpenShift, K3S etc.

@dims @chrigl @jichenjc comments?

FYI @xunpan 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jichenjc** [comment]
I think you mean we can create some 'plugin' or 'like plugin' during generating or manual edit the user-data so that we can not only support upstream k8s but also other provider in the upstream?
I like the idea as we can have the framework to be extended to be adopted by different cloud operator who might not only need k8s upstream

**Comment by gyliu513** [comment]
@jichenjc I have some thinking at here https://github.com/kubernetes-sigs/cluster-api/issues/853#issuecomment-484780552 , and you may also see the cluster api use case do include supporting different vendor's cluster at https://github.com/kubernetes-sigs/cluster-api/pull/903#discussion_r276934608

**Comment by jichenjc** [comment]
yes, I saw 853 and thanks for 903 link, I am reading it :)

**Comment by CamelCaseNotation** [comment]
@jichenjc consider closing this issue since bootstrapping will be handled via an external provider in v1alpha2

**Comment by jichenjc** [comment]
yes, I knew v1alpha2 will have external provider...

**Comment by gyliu513** [comment]
@jichenjc @CamelCaseNotation can you please show me some detail for `external provider`? Any document that I can refer to?
