### ISSUE TITLE
check nil cluster is provided

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#317]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
At the moment, cluster-api-provider-openstack panics with a nil pointer if there is no cluster
We might want to make sure to return an error if a nil cluster is provided.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
@chrigl can you take a look whether I am finding the right place? I think during review on update cluster-api version PR, 
this is the place you talked about ? if cluster is nil, then we will panice
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/pkg/cloud/openstack/cluster/actuator.go#L31
seems aws has same issue? 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/aws/actuators/cluster/actuator.go#L61

or I am in wrong place ?

**Comment by chrigl** [comment]
@jichenjc Yes this is one place. Other places are in `machine/actuator.go`
* in `Create`: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/pkg/cloud/openstack/machine/actuator.go#L137
* and `Update`: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/pkg/cloud/openstack/machine/actuator.go#L276

Maybe just doing a check at the top of all of the `machine.Actuator` functions, to prevent further accident panics.

And also yes. The aws code also looks like to have this problem.
