### ISSUE TITLE
Migrate to CRD's

### ISSUE THREAD

**Issue by chaosaffe** [kubernetes-sigs/cluster-api-provider-openstack#32]
Now that `cluster-api` has migrated to using [`kubebuilder`](https://github.com/kubernetes-sigs/kubebuilder) to use CRD's instead of using `apiserver-builder` and API aggregation (ref: https://github.com/kubernetes-sigs/cluster-api/pull/494) we need to sync the openstack provider to use `kubebuilder` with the upstream

**Comment by Lion-Wei** [comment]
Thanks, I'm working on it. : )
