### ISSUE TITLE
Enable setting proxy for user-data

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-openstack#330]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I'm now proposing this for Cluster API use case at https://github.com/kubernetes-sigs/cluster-api/pull/903#discussion_r278838676

This is mainly used to handle the case where my VM cannot access external internet without a proxy.

**Comment by jichenjc** [comment]
will this cover the use case that deployed VM can't access internet at all so have to use internal stuff? or just proxy (NAT? ) the request through proxy server?
