### ISSUE TITLE
prefer to add accessIP in machine list

### ISSUE THREAD

**Issue by hchenxa** [kubernetes-sigs/cluster-api-provider-openstack#331]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Prefer to add machine accessIP in machine list so that I can easy find the access IP and use my crential to login the cluster.

below was the current behavior:
```
[root@hchenxa1 ~]# kubectl  get machine -o wide
NAME                    AGE
hchenxa1-master-qkcvs   1d
```
from the output, I only can see my machine list, so if I want to connect the machine, I need to get the accessIP from the detail of machine info, so prefer the machine list can have the accessIP like, and it also be good if the list can container the machine type like OS(centos, coreos, ubuntu)

```
[root@hchenxa1 ~]# kubectl  get machine -o wide
NAME                    AGE      floatingIP     image 
hchenxa1-master-qkcvs   1d     9.20.204.143   KVM-Ubt18.04-Srv-x64
```

Comments? @gyliu513 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gyliu513** [comment]
This is a limitation of CR as CR can only show `NAME` and `AGE` now, let me check more for this.

FYI @jichenjc @chrigl

**Comment by jichenjc** [comment]
similar to this one? 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/274 
I am working on this now, it's postponed due to cluster-api v0.1.0 adoption 

https://github.com/kubernetes-sigs/cluster-api/pull/851/commits

**Comment by chrigl** [comment]
This thing is... Since we are not the owner of the `Machine` custom resource, there is no way to configure provider specific fields.
Especially when it comes to the use case of allowing a "management cluster" being able to control child clusters at multiple providers. See https://github.com/kubernetes-sigs/cluster-api/pull/903

There is currently a whole lot going on in the cluster-api project. https://docs.google.com/document/d/1Ys-DOR5UsgbMEeciuG0HOgDQc8kZsaWIWJeKJ1-UfbY/

**Comment by jichenjc** [comment]
yeah, a lot going on.. we need catch up with them

and even the resource doesn't owned by us (such as floating ip), maybe we can generalize the thing we want to show to end user (floatingip --> provider ip ?) then set the value in provider side?

**Comment by jichenjc** [comment]
@hchenxa @chrigl if you don't have objection, I think 
https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/apis/cluster/v1alpha1/machine_types.go#L181
might be some place to handle, I can add a PR to set those info in our reconcile logic and 
create PR in cluster-api to make it showable to end user
please let me know any concern then I can go ahead and assign myself to work on it

**Comment by chrigl** [comment]
@jichenjc lgtm.

**Comment by jichenjc** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/951
