### ISSUE TITLE
the CAcert and CAkey from the cluster status was null 

### ISSUE THREAD

**Issue by hchenxa** [kubernetes-sigs/cluster-api-provider-openstack#333]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
the cluster out have CAcertification and CAProvateKey, but the value seems be null always like below:
```
apiVersion: cluster.k8s.io/v1alpha1
kind: Cluster
metadata:
  creationTimestamp: "2019-04-28T05:47:04Z"
  finalizers:
  - cluster.cluster.k8s.io
  generation: 1
  name: test2
  namespace: default
  resourceVersion: "621"
  selfLink: /apis/cluster.k8s.io/v1alpha1/namespaces/default/clusters/test2
  uid: 0d2cf2d0-6979-11e9-840f-fa163eb27512
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/12
  providerSpec:
    value:
      apiVersion: openstackproviderconfig/v1alpha1
      kind: OpenstackProviderSpec
      tags:
      - a_cluster_wide_tag
status:
  apiEndpoints:
  - host: 9.20.204.143
    port: 443
  providerStatus:
    CACertificate: null
    CAPrivateKey: null
    metadata:
      creationTimestamp: null
```

Does there need any specify configuration for this? 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
we should update the CAcert in reconcile function to sync the CA info? I can take a look as I am updating provide ID which should be similar to this ,
