### ISSUE TITLE
[Question]node lifecycle management

### ISSUE THREAD

**Issue by hchenxa** [kubernetes-sigs/cluster-api-provider-openstack#334]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
I have a question about the cluster-api lifecycle management.

currently, when I using cluster-api to deploy a cluster, the behavior seems like below:

1) the cluster and master node resources will be created on bootstrap node.
2) the master node will start a controller to start the worker node. 
3) the bootstrap node will not aware the new created resources.

and if I want to clean up the cluster, I need :
1) If I want to delete the worker node, I need to login sub-cluster master node to delete all worker node first.
2) After the steps 1 finished, I need to jump to bootstrap node to delete the cluster and master node then.

so the problem here is:
1) The bootstrap node can not control the new created resources from sub-cluster
2) I need to keep the bootstrap node to control the sub-cluster master node
3) If delete the master node on bootstrap node, the woerk nodes which created by sub-cluster will out-of-controller
4) If sub-cluster was deleted by it's self, I can not boot-up the master node on bootstrap node currently. 
...

@gyliu513 @jichenjc , any comments and suggestion here?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by gyliu513** [comment]
@hchenxa For deleting a worker node, you can run `kubectl delete machine xxx` on the provisioned cluster; But I was not clear how to delete a master node, and there are some discussion at https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/294#issuecomment-480136343 , can you help check more for this?

**Comment by jichenjc** [comment]
I think we should not allow a delete from master cluster, this means delete the master from itself, cluster-api has a env variable to be defined and it can prevent itself from deletion
https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machine/controller.go#L255

and 
>>>I need to keep the bootstrap node to control the sub-cluster master node
I *guess* maybe this is a good question to ask in one of 4 working groups in cluster-api.. maybe https://docs.google.com/document/d/1E7N_JcSsDnnJk2yqMCCriBFwRZZc8nnx4kxSt99z7As/edit# ? some the extension group?

**Comment by hchenxa** [comment]
it looks like the current behavior was changed, when the master node finish the provision, the CR and CRD will be deleted from the bootstrap nodes.

cc @gyliu513 @jichenjc

**Comment by gyliu513** [comment]
@hchenxa so the bootstrap cluster will not able to get the CR any more after provision finished and the end user has to logon to the new provisioned cluster to do some operations. Can you help check how to delete a master node in such condition?

**Comment by gyliu513** [comment]
@hchenxa so the bootstrap cluster will not able to get the CR any more after provision finished and the end user has to logon to the new provisioned cluster to do some operations. Can you help check how to delete a master node in such condition?

**Comment by jichenjc** [comment]
yes, let's do some test and see whether we can 'kubectl del machine xxxx-master' ? I think we do but need double check

**Comment by sbueringer** [comment]
@jichenjc What's the status of this issue? :)

**Comment by jichenjc** [comment]
this might need open for a while, see whether v1alpha2 can mitigate the issue

**Comment by sbueringer** [comment]
But is it specific to the Openstack provider? Seems to be an issue with clusterctl Workflow which then should be tracked in the cluster-api repo because it affects all providers

**Comment by jichenjc** [comment]
ok..
