### ISSUE TITLE
separate machine_providerconfig and cluster_provider config

### ISSUE THREAD

**Issue by Lion-Wei** [kubernetes-sigs/cluster-api-provider-openstack#34]
`OpenstackProviderConfig` can be separated into cluster scope and machine scope.

**Comment by chaosaffe** [comment]
Based on the [skeleton repo](https://github.com/davidewatson/cluster-api-provider-skeleton/tree/master/cloud/skeleton/actuators) maybe we should split the `machine` and `cluster` actuators into separate packages as well?

**Comment by Lion-Wei** [comment]
For now we don't have cluster actuators, but sure, when we add cluster actuators, we need consider separate then in two packages.

**Comment by chrigl** [comment]
/assign @chrigl 
Actuators already separated by #94.

I am currently working on an implementation of the cluster actuator which needs its own ProviderSpec.
