### ISSUE TITLE
Support OpenStack Stein

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#349]
/kind feature

**Describe the solution you'd like**

Support OpenStack Stein which is released on 10 April, 2019

**Comment by jichenjc** [comment]
Just curious, do you have a set of todo items(already found some missing stuffs or to be enhanced stuffs) or just a common test effort to make sure cluster-api-provider-openstack works on Stein version?

**Comment by hidekazuna** [comment]
@jichenjc I do not have specific todo items for supporting, I will try cluster-api-provider-openstack working with Stein version.
