### ISSUE TITLE
delete the network when the machine was deleted

### ISSUE THREAD

**Issue by hchenxa** [kubernetes-sigs/cluster-api-provider-openstack#352]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
currently, when delete the machine, the network will be remained, so it will generate many detached neutron port in the network pool. prefer the delete the these network when the machine was deleted.

cc @gyliu513 @jichenjc 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
Thanks for the bug report

to be clear, it's 'network' or 'subnet' or 'port' remaining? do we create network during instance (machine ) create stage ? I think we don't?

**Comment by hchenxa** [comment]
it should be neutron port.

**Comment by jichenjc** [comment]
I don't fully understand here..sorry, as we delete the machine, the port associated with the VM will be deleted in nova side ,it's not cluster api responsibility to delete the port ..is there some thing wrong in the openstack cloud itself?
