### ISSUE TITLE
support latest kustomize

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#356]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
we only support kustomize 1.0.11, at least we need know the reason and see what we can do to support latest one...

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
@jichenjc Are you still working on it? If not, I can take over. I migrated some of the kustomize files locally already to use the kustomize 2+

**Comment by jichenjc** [comment]
@sbueringer actually I had a PR here https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/357...  will it be enough or you want to have more input here?

**Comment by sbueringer** [comment]
Oh I didn't see it I'll compare later
