### ISSUE TITLE
support loadbalancer for HA support

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#367]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

per https://kubernetes.io/docs/setup/independent/high-availability/
it need load balancer to do further HA support for master , we need provide LB support
(maybe refer to cloud-provider-openstack? )

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by sbueringer** [comment]
I'll implement it with multi-node control plane.

**Comment by sbueringer** [comment]
PR is open: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/401

**Comment by sbueringer** [comment]
I think we can close this issue because we also have another issue for Octavia support.
