### ISSUE TITLE
clusterctl fails on creating bootstrap cluster due to unknown minikube flag --p 

### ISSUE THREAD

**Issue by dkt26111** [kubernetes-sigs/cluster-api-provider-openstack#373]
/kind bug

**What steps did you take and what happened:**
When following the README to build clusterctl and then creating the cluster, the clusterctl command fails with the following message:

`create_cluster.go:61] could not create bootstrap cluster: could not create bootstrap control plane: error running command 'minikube start --bootstrapper=kubeadm --kubernetes-version=v1.12.3 --p=clusterapi': exit status 64`

**What did you expect to happen:**
It should complete without errors.

**Anything else you would like to add:**
This issue was reported in cluster-api here: https://github.com/kubernetes-sigs/cluster-api/issues/874
It was fixed in this PR: https://github.com/kubernetes-sigs/cluster-api/pull/875

It looks like the cluster-api version in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/Gopkg.toml#L62 needs to be updated to use 0.1.3 in order to pick up this bug fix.  This is what other cloud providers have done: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/Gopkg.toml#L55

**Environment:**

- Cluster-api-provider-openstack version:  {GitCommit: 4ce690ef10710730e44c3814e9a85bebc6f83cab, GitBranch: master}
- Minikube/KIND version: v1.1.0
- Kubernetes version: (use `kubectl version`): 1.12.5
- OS (e.g. from `/etc/os-release`): macOS 10.13.6

**Comment by jichenjc** [comment]
Thanks for the bug @dkt26111 
will take action according to what you suggested
