### ISSUE TITLE
use go modules 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#381]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
per https://github.com/kubernetes-sigs/cluster-api/pull/1054/files
let's  plan to switch to go modules accordingly

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by hidekazuna** [comment]
@jichenjc May I take this issue?

**Comment by jichenjc** [comment]
sure :)

/assign hidekazuna
