### ISSUE TITLE
avoid ssh to master node to get kubeconfig if we can

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#387]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

we are getting kubeconfig from master node using ssh now, this can't be used in some method such as reconcile cluster (cluster-api is using this method to get secret now)

like aws provider, we need figure out a way to know how to create kubeconfig based on the info from cluster only
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by sbueringer** [comment]
Will be fixed with the reconcile cert PR from here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/382

**Comment by jichenjc** [comment]
thanks for the that PR!!, really helpful

**Comment by sbueringer** [comment]
Fixed via https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/394
