### ISSUE TITLE
failed to create master and node

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#391]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
kubelet failed to start, the kubelet is saying 'node openstack-master-xxxx' can not be found
and this blocked kubelet start and in turn master and node failed to start

we have to workaround this first then check the k8s community `cloud-provider` expectation.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
I am seeing this in /var/log/messages


Jul 10 00:07:46 openstack-master-5wgrw kubelet: I0710 00:07:46.990277    4340 kubelet.go:1822] skipping pod synchronization - container runtime status check may not have completed yet
Jul 10 00:07:46 openstack-master-5wgrw kubelet: E0710 00:07:46.993032    4340 kubelet.go:2248] node "openstack-master-5wgrw" not found
Jul 10 00:07:47 openstack-master-5wgrw kubelet: E0710 00:07:47.093151    4340 kubelet.go:2248] node "openstack-master-5wgrw" not found
Jul 10 00:07:47 openstack-master-5wgrw kubelet: E0710 00:07:47.193338    4340 kubelet.go:2248] node "openstack-master-5wgrw" not found
Jul 10 00:07:47 openstack-master-5wgrw cloud-init: I0710 00:07:47.224406    3906 round_trippers.go:419] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubeadm/v1.15.0 (linux/amd64) kubernetes/e8462b5" 'https://9.20.206.79:443/healthz?timeout=32s'
Jul 10 00:07:47 openstack-master-5wgrw cloud-init: I0710 00:07:47.225438    3906 round_trippers.go:438] GET https://9.20.206.79:443/healthz?timeout=32s  in 1 milliseconds
Jul 10 00:07:47 openstack-master-5wgrw cloud-init: I0710 00:07:47.225448    3906 round_trippers.go:444] Response Headers:
Jul 10 00:07:47 openstack-master-5wgrw kubelet: E0710 00:07:47.293504    4340 kubelet.go:2248] node "openstack-master-5wgrw" not found
Jul 10 00:07:47 openstack-master-5wgrw kubelet: E0710 00:07:47.294546    4340 controller.go:115] failed to ensure node lease exists, will retry in 800ms, error: Get https://9.20.206.79:443/apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/openstack-master-5wgrw?timeout=10s: dial tcp 9.20.206.79:443: connect: connection refused

**Comment by jichenjc** [comment]
seems it's related to novalocal which is domain above......

**Comment by hidekazuna** [comment]
@jichenjc My environment is OpenStack Stein on Ubuntu 18.04. --domain= parameter value is `openstacklocal` as shown below.

```bash
hidekazu@controller:~$ ps aux |grep 740a2259-7387-4c07-92a3-583200ad77c0
nobody    5683  0.0  0.0  51580  2572 ?        S    Jun23   0:42 dnsmasq --no-hosts --no-resolv --pid-file=/var/lib/neutron/dhcp/740a2259-7387-4c07-92a3-583200ad77c0/pid --dhcp-hostsfile=/var/lib/neutron/dhcp/740a2259-7387-4c07-92a3-583200ad77c0/host --addn-hosts=/var/lib/neutron/dhcp/740a2259-7387-4c07-92a3-583200ad77c0/addn_hosts --dhcp-optsfile=/var/lib/neutron/dhcp/740a2259-7387-4c07-92a3-583200ad77c0/opts --dhcp-leasefile=/var/lib/neutron/dhcp/740a2259-7387-4c07-92a3-583200ad77c0/leases --dhcp-match=set:ipxe,175 --dhcp-userclass=set:ipxe6,iPXE --local-service --bind-interfaces --dhcp-range=set:tag0,172.16.1.0,static,255.255.255.0,86400s --dhcp-option-force=option:mtu,1450 --dhcp-lease-max=256 --conf-file= --domain=openstacklocal
```

**Comment by prankul88** [comment]
@jichenjc I am using Stein on Ubuntu 18.04.

**Comment by jichenjc** [comment]
already provided a tip to handle this issue
