### ISSUE TITLE
Delete a cluster failed to complete

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#398]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

 ./clusterctl delete cluster -p examples/openstack/out/provider-components.yaml  --kubeconfig kubeconfig --bootstrap-type kind
I0716 01:04:36.306411   14851 clusterdeployer.go:160] Creating bootstrap cluster
I0716 01:04:36.306480   14851 createbootstrapcluster.go:27] Preparing bootstrap cluster
I0716 01:05:25.546045   14851 clusterdeployer.go:168] Pivoting Cluster API stack to bootstrap cluster
I0716 01:05:25.546086   14851 pivot.go:67] Applying Cluster API Provider Components to Target Cluster
I0716 01:05:26.841692   14851 pivot.go:72] Pivoting Cluster API objects from bootstrap to target cluster.

**What did you expect to happen:**
delete should end with machines and all rescources successfully deleted

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by CamelCaseNotation** [comment]
I think this is expected behavior for CAPI v1alpha1. See: https://cluster-api.sigs.k8s.io/common_code/machine_controller.html

>>> The Machine actuator methods expect both a Cluster and a Machine to be passed in. While there is not a strong link between Clusters and Machines, the machine controller will determine which cluster to pass by looking for a Cluster in the same namespace as the Machine

There are two consequences of this:

The machine actuator assumes there will be exactly one Cluster in the same namespace as any Machines it reconciles. See getCluster() for the details.
If the Cluster is deleted before the Machine it will not be possible to delete the Machine. Therefore Machines must be deleted before Clusters.

**Comment by jichenjc** [comment]
no , the expected behavior is not like this 

I did try delete and it says following:
I0726 01:07:24.192069    9961 clusterclient.go:799] retrying: machine status is empty

so the root cause is we need set machine status 

for v1alphe2 seems this is another story, but for v1alpha1, we need set status
