### ISSUE TITLE
port number 443 in master script is incorrect 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#399]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I0716 01:39:22.044227   23410 clusterclient.go:938] Waiting for kubectl apply... server not yet available: couldn't kubectl apply, output: unable to recognize "STDIN": Get https://9.20.206.79:6443/api?timeout=32s: dial tcp 9.20.206.79:6443: connect: connection refused
unable to recognize "STDIN": Get https://9.20.206.79:6443/api?timeout=32s: dial tcp 9.20.206.79:6443: connect: connection refused
unable to recognize "STDIN": Get https://9.20.206.79:6443/api?timeout=32s: dial tcp 9.20.206.79:6443: connect: connection refused
unable to recognize "STDIN": Get https://9.20.206.79:6443/api?timeout=32s: dial tcp 9.20.206.79:6443: connect: connection refused
unable to recognize "STDIN": Get https://9.20.206.79:6443/api?timeout=32s: dial tcp 9.20.206.79:6443: connect: connection refused
unable to recognize "STDIN": Get https://9.20.206.79:6443/api?timeout=32s: dial tcp 9.20.206.79:6443: connect: connection refused
unable to recognize "STDIN": Get https://9.20.206.79:6443/api?timeout=32s: dial tcp 9.20.206.79:6443: connect: connection refused
unable to recognize "STDIN": Get https://9.20.206.79:6443/api?timeout=32s: dial tcp 9.20.206.79:6443: connect: connection refused
unable to recognize "STDIN": Get https://9.20.206.79:6443/api?timeout=32s: dial tcp 9.20.206.79:6443: connect: connection refused
unable to recognize "STDIN": Get https://9.20.206.79:6443/api?timeout=32s: dial tcp 9.20.206.79:6443: connect: connection refused
unable to recognize "STDIN": Get https://9.20.206.79:6443/api?timeout=32s: dial tcp 9.20.206.79:6443: connect: connection refused
unable to recognize "STDIN": Get https://9.20.206.79:6443/api?timeout=32s: dial tcp 9.20.206.79:6443: connect: connection refused

I0716 01:39:22.044466   23410 createbootstrapcluster.go:36] Cleaning up bootstrap cluster.
I0716 01:39:22.044493   23410 kind.go:69] Running: kind [delete cluster --name=clusterapi]
I0716 01:39:23.216556   23410 kind.go:72] Ran: kind [delete cluster --name=clusterapi] Output: Deleting cluster "clusterapi" ...
F0716 01:39:23.216594   23410 create_cluster.go:61] unable to pivot cluster api stack to target cluster: unable to apply cluster api controllers: timed out waiting for the condition

**What did you expect to happen:**

6443 / 443 port are inconsistent......

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
Might have a way to fix this in the final PR for multi-node control plane. With that PR I would start generating the kubeadm config via Go Code. So I have access to the controlPlanEndpoint including the port. This can then be added to the Openstack IP annotation and getIP can then retrieve IP and Port. The clusterctl implementation can handle the port if it's also returned by getIP

**Comment by jichenjc** [comment]
I added some comments here:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/394#pullrequestreview-262906467
maybe change there from 6443 to 443 as default one is 443?

**Comment by sbueringer** [comment]
@jichenjc Yup you're right. Let's pin it for now to 443. With the last PR for multi-node control plane there will be a configuration in the Cluster CRD for this, so we can make it flexible again.
