### ISSUE TITLE
Example of `generate-yaml.sh` doesn't work for Container Linux any more

### ISSUE THREAD

**Issue by chrigl** [kubernetes-sigs/cluster-api-provider-openstack#402]
/kind bug

**What steps did you take and what happened:**

Trying to generate yamls for Container Linux using `generate-yaml.sh`

```
> ./generate-yaml.sh ~/.config/cluster-api/clouds.yaml openstack coreos
no output folder provided, use name 'out' by default
10:15:41 main [ERRO] Error updating document at index 0: yaml: line 15: could not find expected ':'
```

**What did you expect to happen:**

Properly generated yaml to startup Container Linux nodes

**Anything else you would like to add:**

There are two ideas coming to my mind.
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/master.yaml#L12

Replacing
```
inline: |
{{ CACert | Indent 10 }}
```

by either

```
inline: "{{ CACert | base64encode}}"
```
and providing the function base64encode...

or using

```
inline: "{{.CACert}}"
````
and providing base64 encoded data.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
@chrigl Should be fixed by https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/404.

Sorry I didn't tested generate yaml with my last PR. Will do with future ones :)
