### ISSUE TITLE
move from k8s.io to x-k8s.io

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#407]
/kind bug

see 
https://github.com/kubernetes-sigs/cluster-api/issues/1073

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
I think we should do this with v1alpha2 like CAPA. I don't think we have to migrate our v1alpha1 resource

**Comment by sbueringer** [comment]
I would close this issue in favor of: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/380#issuecomment-522018403 to not complicate it any further :)

**Comment by sbueringer** [comment]
We can close this as the first v1alpha2 PR (which also did this) was merged

**Comment by sbueringer** [comment]
@jichenjc
