### ISSUE TITLE
Use Bazel

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#415]
/kind feature

**Describe the solution you'd like**

Cluster-api-provider-openstack should use bazel to catch up with Cluster API and other main provider implementations.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by hidekazuna** [comment]
I will take this after #381 has finished.

**Comment by sbueringer** [comment]
Are we sure we want to migrate to Bazel? I read that in CAPA they want to remove Bazel as far as possible because in Repos which are not as complex as k/k they think it's not worth the additional complexity compared to simple go build

**Comment by hidekazuna** [comment]
@sbueringer Thanks for the information. When I create #411 ,  I found we do not use Bazel at all and have to study Makefile in cluster-api-provide-azure so that I thoughtit is better to migrate.

My real purpose is to create integration and e2e test. I may propose to migrate to Bazel if it's better when creating tests.

**Comment by sbueringer** [comment]
Okay yeah sure. Let's see if we need it for that.

**Comment by hidekazuna** [comment]
I studied cloud-provider-openstack CI job. I think we should use openlab rather than copy and paste integration test from aws or azure. I raised an issue #416

**Comment by sbueringer** [comment]
Sound's good

**Comment by jichenjc** [comment]
so we can close this one? @hidekazuna

**Comment by hidekazuna** [comment]
@jichenjc yes, we can close this.
