### ISSUE TITLE
Add e2e test

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#416]
/kind feature

**Describe the solution you'd like**

Implement e2e test on OpenLab and use it as CI like cloud-provider-openstack. We need to connect to openlab: https://docs.openlabtesting.org/contributors/connect-to-openlab

E2e test is really create k8s cluster and execute kubectl command.
Cloud-provider-openstack uses zuul jobs in OpenLab.
https://github.com/kubernetes/cloud-provider-openstack/blob/master/.zuul.yaml

**Anything else you would like to add:**
Issue in OpenLab was already raised.
https://github.com/theopenlab/openlab/issues/141

**Comment by jichenjc** [comment]
thanks for bring this ~ really helpful

**Comment by hidekazuna** [comment]
@jichenjc I am sorry confused you.  There is no relation between Bazel and e2e test.

**Comment by sbueringer** [comment]
I think we can keep this closed as we have: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/484 (which afaik does the same)
