### ISSUE TITLE
Problems setting up environment

### ISSUE THREAD

**Issue by prankul88** [kubernetes-sigs/cluster-api-provider-openstack#419]
/kind bug

**What steps did you take and what happened:**
I was setting up my environment and faced an issue where my master/management node was working fine but was unable to initiate a new machine from it. 
I checked logs for `clusterapi-controller-0` and found this,

> I0724 09:18:48.275236       1 machine_controller.go:113] Reconciling Machine "openstack-node-vrlsb"
E0724 09:20:55.530833       1 machine_controller.go:202] Failed to check if machine "openstack-node-vrlsb" exists: providerClient authentication err: Get http://192.168.xxx.xx/identity/: dial tcp 192.168.xxx.xx:80: connect: connection timed out

I did exec into the controller and was able to access the external net but could not reach the openstack endpoints.
I found out that the pod CIDR was 192.168.0.0/16 and conflicted with ip of my host machine.(192.168.xxx.xx)

So I tried changing the pod CIDR from cluster.yaml file and still faced similar issue. After exec into controller again I found out it is not even able to access external network now.

After help from @chrigl and @ophirtal, found out that Calico has hard coded CIDR range 192.168.0.0/16
To have a working environment I used own calico.yaml with CIDR changed and used it in [master-user-data.sh](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/5524321ddc489c7b68b1ebe6eaff31de4810e288/cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh#L239)

**Anything else you would like to add:**
IMO there need to be a note in the documentation where such scenario is put up. Or maybe a pre-check to throw a error in such case. I want to take up this issue and would love any inputs.

**Environment:**

- Cluster-api version: 
- Minikube/KIND version: 0.4.0
- Kubernetes version: (use `kubectl version`): 1.15
- OS (e.g. from `/etc/os-release`): ubuntu 16.04
- Openstack version : rocky

**Comment by hidekazuna** [comment]
Hi, you finally created k8s cluster with worker node successfully, right?

In my understanding, CIDR can be changed in cluster.yaml:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/cmd/clusterctl/examples/openstack/cluster.yaml#L10

**Comment by prankul88** [comment]
@hidekazuna Hello, yes I am having a working environment now with worker node.

> In my understanding, CIDR can be changed in cluster.yaml:

Yes it must be changed there but only changing that doesnot seem to work (possibly due to dependency of CNI). I changed the file mentioned in [master-user-data.sh ](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/5524321ddc489c7b68b1ebe6eaff31de4810e288/cmd/clusterctl/eamples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh#L239) and used my own [calico.yaml](https://github.com/prankul88/calico-test/blob/master/calico.yaml#L179) as well.

**Comment by hidekazuna** [comment]
@prankul88 Congratulations your first k8s cluster with cluster-api-provider-openstack!

Calico document says in https://docs.projectcalico.org/v3.8/getting-started/kubernetes/

> Note: If 192.168.0.0/16 is already in use within your network you must select a different pod network CIDR, replacing 192.168.0.0/16 in the above command as well as in any manifests applied below.

I understand this is known issue. As you proposed, it is better to note in the doc or so.

**Comment by prankul88** [comment]
@hidekazuna Thankyou for your help too.

> I understand this is known issue. As you proposed, it is better to note in the doc or so.

Sure I will push a PR for the same. Thanks

**Comment by jichenjc** [comment]
the PR merged, let's close this 

/close
