### ISSUE TITLE
Failed to create machine with nodeCidr and without networks

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#425]
/kind bug

**What steps did you take and what happened:**

When nodeCidr is set and networks is not set, server failed to be created.

```bash
W0805 13:01:57.560622       1 machine_controller.go:226] Failed to create machine "openstack-master-dvw8k": error creating Openstack ins
tance: create new server err: Bad request with: [POST http://controller.hidekazuna.test:8774/v2.1/servers], error message: {"badRequest"
: {"code": 400, "message": "Invalid input for field/attribute server. Value: {'availability_zone': 'nova', 'flavorRef': '1', 'imageRef':
 '3422e5fc-5c86-4cf4-8c8b-1716b8f3219d', 'key_name': 'cluster-api-provider-openstack', 'metadata': {'key': 'value'}, 'name': 'openstack-
master-dvw8k', 'security_groups': [{'name': '10adb7a1-5e5e-48da-aea2-d4e84a0b8ef3'}, {'name': '3b85495e-d51b-4f19-97fb-62f7ab645401'}], 
'tags': ['cluster-api-provider-openstack', 'default-test4010', 'a-machine-specific-tag', 'a_cluster_wide_tag'], 'user_data': 'IyEvdXNyL2
Jpbi9lbnYgYmFzaApzZXQgLWUKc2V0IC14CigKS1VCRUxFVF9WRVJTSU9OPTEuMTUuMApWRVJTSU9OPXYke0tVQkVMnCg=='}. 'networks' is a required property"}}
``` 

**What did you expect to happen:**

When nodeCidr is set and networks is not set, The network, subnet, and router are created, and server is created.

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-openstack: #401 
- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
If I understand it correctly, we're currently trying to create Ports (or reuse existing ones) in the networks given in the machineSpec. If the networks parameter is not set, to what network should we default to?

**Comment by hidekazuna** [comment]
@sbueringer This is the first time to create k8s cluster with nodeCidr so that I am sorry if I am wrong. I assumed if nodeCidr is given and networks is not given, network, subnet, and router are newly created and server uses the port of the network.

**Comment by hidekazuna** [comment]
@sbueringer I understand I need externalNetworkID for creating router in [your comment](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/422#issuecomment-518333167), thanks.

**Comment by jichenjc** [comment]
@hidekazuna the nodeCidr is clusterproviderspec, what about the networks? The machineProviderSpec, right? 

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/150 seems has some logic there to create and reconcile the network so that machines without networks defined can use the network defined in cluster ? @chrigl

**Comment by hidekazuna** [comment]
@jichenjc networks is https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/cmd/clusterctl/examples/openstack/machines.yaml.template#L20-L21

**Comment by jichenjc** [comment]
yes, thanks for the point, I do mean this definition :)

**Comment by sbueringer** [comment]
@hi

> @sbueringer This is the first time to create k8s cluster with nodeCidr so that I am sorry if I am wrong. I assumed if nodeCidr is given and networks is not given, network, subnet, and router are newly created and server uses the port of the network.

I took another look at the code and I think you're right. From a Cluster CRD perspective nodeCIDR is enough so that a network & subnet is created and it would make sense that they are used for the server we're creating later. Right now it's necessary to match the networks even though it's clear what the cluster networks are. So one idea would be to just use network & subnet from the Cluster status when networks in the MachineSpec is not set. What do you think?

**Comment by hidekazuna** [comment]
@sbueringer 

> I took another look at the code and I think you're right. From a Cluster CRD perspective nodeCIDR is enough so that a network & subnet is created and it would make sense that they are used for the server we're creating later. Right now it's necessary to match the networks even though it's clear what the cluster networks are. So one idea would be to just use network & subnet from the Cluster status when networks in the MachineSpec is not set. What do you think?

I want to make clear your settings. Does the networks in machines.yaml specify network name which would be created like 'cluster-api-provider-openstack-clusterName' in advance? I think it is not possible to know network id in advance.
I agree with your idea about using network and subnet from the Cluster status when networks in the MachineSpec is not set.

**Comment by sbueringer** [comment]
@hidekazuna I'm providing a nodeCidr on the cluster level and then re-use the created network/subnet  by specifying the following on the machines:
````
          networks:
          - filter:
              name: k8s-cluster-default-test
            subnets:
              - filter:
                  name: k8s-cluster-default-test
````
(test is the cluster name)

**Comment by hidekazuna** [comment]
@sbueringer Thanks, I will try to create the cluster with that configuration.

**Comment by hidekazuna** [comment]
@sbueringer I successfully created the cluster with the configuration in my octavia environment now, thanks.

**Comment by sbueringer** [comment]
So if we implement https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/428#issuecomment-520206614 and fallback to the cluster status networks in case no networks are specified on the machines this should be possible without specifying networks on the machines
