### ISSUE TITLE
create floating ip on the fly if it's not created yet

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#427]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
per discussion on #422 ,we need a floating ip to be created first, this works but can be enhanced, so we can create a floating ip by using the 'master ip' in cluster actuator

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by sbueringer** [comment]
How do you want to implement this? The floating ip of the LB is already only created if required. The only floating ip's which are not created in this way are the one from the machines.

**Comment by jichenjc** [comment]
ugly but which is I am testing on ... 

https://github.com/jichenjc/cluster-api-provider-openstack/tree/no_floating_ip

I believe we still don't allow create LB when no floating ip given..

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/pkg/cloud/openstack/services/networking/loadbalancer.go#L27

**Comment by sbueringer** [comment]
Ah maybe I understood it wrong. We want to create a floating ip even though no floting ip is set in the spec? Which one would we use?

**Comment by sbueringer** [comment]
@jichenjc This might fix your issue: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/435

Only the last 2 commits are actually new. Ever other commit is from the multi-node PR
