### ISSUE TITLE
support create LB with existing network/subnet

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#428]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
this is a use case at least in my env , you are not authorized to create network/subnet due to restriction on the system ,then you have to reuse existing network to create LB,
however, under current implementation we don't allow this use case, you have to create a new network by using the nodeCIDR setting.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jichenjc** [comment]
to add more info here:
1) some times there is no floating ip needed, e.g someone is using provider network and we need make that as least works without floating ip introduction
2) with 1) above, you don't need create a nodecidr in order to work, some existing network can be specified in order to make cluster api to create..

**Comment by sbueringer** [comment]
So we'll implement it like I proposed here?
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/422#issuecomment-519587486

**Comment by sbueringer** [comment]
I would open a PR to fix this, if it's okay :)

**Comment by jichenjc** [comment]
sure, I am too busy recently on other things. so please go ahead and push PR, thanks ~

**Comment by sbueringer** [comment]
/assign @sbueringer 
PR is open here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/475

**Comment by sbueringer** [comment]
Was fixed in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/477

/close
