### ISSUE TITLE
Allow to pass filters to Networks/SecurityGroups in the providerconfig

### ISSUE THREAD

**Issue by flaper87** [kubernetes-sigs/cluster-api-provider-openstack#43]
Networks and SecurityGroups currently only accept uuids. It'd be great to support other filters like Names, or even better filtering on other parameters.

**Comment by iamemilio** [comment]
Can you give me a little more context

**Comment by gdoctor** [comment]
Also wondering if we could support subnet UUID/names instead of just an overarching networking UUID. Currently I have some networks that are made up of more than 1 subnet. Essentially they were expanded upon once the initial subnet CIDR filled up.

**Comment by flaper87** [comment]
fixed by #68 
/close
