### ISSUE TITLE
Hostname missing in hosts file in openstack instance

### ISSUE THREAD

**Issue by prankul88** [kubernetes-sigs/cluster-api-provider-openstack#436]
/kind bug

**What steps did you take and what happened:**
While setting up cluster-api using clusterctl command, there was a portion in the clusterctl logs which had an error `exit status 255`  ~~while the command tried to ssh into the machine~~. This after a minute got resolved. After some searching, I found out it was related to the fact that hotsname was missing in /etc/hosts of the created openstack instance. 
Not sure if this is an issue of openstack or this repo. 

**What did you expect to happen:**
This error can be resolved by adding a command in the master-user-data.sh
Probably mapping loopback ip to the hostname will resolve the issue

**Anything else you would like to add:**
Once I get some feedback and if found valid, I can push a PR for the same.

**Environment:**

- Cluster-api version:
- Minikube/KIND version: v0.4.0
- Kubernetes version: (use `kubectl version`): v1.15
- OS (e.g. from `/etc/os-release`): Ubuntu16.04
-Openstack-release: Rocky

**Comment by sbueringer** [comment]
The current master version shouldn't try to ssh into the machine. Can you post us the logs?

**Comment by sbueringer** [comment]
Hostname is set here for CoreOS:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/common.yaml#L39-L43

Didn't find anything similar in Centos/Ubuntu user-data.sh files. But as I said I'm wondering why the controller tries to ssh onto the node

**Comment by jichenjc** [comment]
yeah, we should never try to ssh, I guess maybe @prankul88 you might need update your code to latest?

**Comment by prankul88** [comment]
@sbueringer @jichenjc Okay, thanks for clearing this doubt for me. I got a little confused. Just one more thing, I found something in the openstack logs 

> [   81.138455] cloud-init[1310]: + sudo apt-key add -
[   81.144172] cloud-init[1310]: + curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg
[   81.152234] cloud-init[1310]: **sudo: unable to resolve host openstack-master-ddwpq**
[   82.093848] cloud-init[1310]: OK

My master's hostname is not present in the /etc/hosts file.
Is it a concern for us?

**Comment by jichenjc** [comment]
I am not sure ...this depends on your DNS setting, e.g /etc/hosts or DNS server, usually, this info  should not in /etc/hosts (if you have many nodes, maitain them will be a big burden...)

is this log lead to your code or logic error ?

**Comment by prankul88** [comment]
Okay. No, it does not lead to any error as such but at times I have noticed that when `sudo apt-key add -`  command is executed, it leads to some delay as it is not able to find hostname.

**Comment by sbueringer** [comment]
Does it really have to be in the /etc/hosts file? Maybe it has an effect if you add it to /etc/hostname (btw for CoreOS we're adding the hostname to /etc/hostname) and there's also an issue for the kubeadm bootstrapper to do that: https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/116

But I"m not sure what they will do. In the long run it would be better to rely on what the kubeadm bootstrapper is doing (or allows via extensions)

**Comment by prankul88** [comment]
> But I"m not sure what they will do. In the long run it would be better to rely on what the kubeadm bootstrapper is doing (or allows via extensions)

@sbueringer Agreed. But in this case when I checked the master machine's (ubuntu) hostname, it is already present in /etc/hostname. What I felt is when any sudo commands run from master-user-data.sh, it hangs for a bit and then proceeds. If we can map loopback-ip to the hostname in /etc/hosts (can add command in master-user-data file), it would not get stuck.

I still agree that it must fetch hostname or anything else related to the machine from the extentions but this is for the delay while running the script. (maybe temp solution). Thoughts?

Surely this is not necessary but can help reduce the delay.

**Comment by sbueringer** [comment]
For me it would be okay to add it for now. In the long run we should discuss and align with the bigger ClusterAPI Community because bootstrapping won't be provider-specific in the future

**Comment by prankul88** [comment]
@sbueringer Thanks I will update.

**Comment by prankul88** [comment]
Closing, the patch has been merged.
