### ISSUE TITLE
Make providerConfig keys consistent

### ISSUE THREAD

**Issue by flaper87** [kubernetes-sigs/cluster-api-provider-openstack#44]
The security_group and availability_zone keys are not consistent with the format used in other keys `floatingIP`, etc. Make these keys consistent to improve the user experience.

**Comment by flaper87** [comment]
@iamemilio is this something you'd be interested to help with?

**Comment by iamemilio** [comment]
sure

**Comment by Lion-Wei** [comment]
Thanks, it do bother me a little.
