### ISSUE TITLE
Adopt PR icons

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#471]
I want to suggest adopting the PR icons which are currently used in Cluster API, CAPA, controller-runtime etc.

The convention is documented here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/CONTRIBUTING.md

The advantage is you directly see what kind of PRs are open:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls

And you can generate release notes like this (there's a go tool for this):
https://github.com/kubernetes-sigs/cluster-api/releases/tag/v0.2.2

**Comment by prankul88** [comment]
@sbueringer +1 for me. It helps in differentiation.

**Comment by prankul88** [comment]
If you like I can add that to the repo.
/assign

**Comment by sbueringer** [comment]
@prankul88 That would be nice. Afaik, there are the following TODOs:

* document the convention & update the PR template, e.g. like CAPA did it here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/506fa1021464fef2d45d122011ae0f5355034af7#diff-6a3371457528722a734f3c51d9238c13
* add the make target "release-notes" to our Makefile > https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/7a92e012ddfd973cbacefd9efba1880ca5b5b2ec
