### ISSUE TITLE
Generate separate multi-node and single-node control plane examples

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#473]
/kind feature

We're currently just generating one example for single and multi-node. Because the configurations for both are different it would be nice if the examples/generate.sh shell script could be adjusted to take a parameter `single-node-controlplane` or `multi-node-controlplane` and generate examples accordingly (or just generate both)

**Comment by jichenjc** [comment]
yeah ,this is something will be very helpful soon

**Comment by prankul88** [comment]
@sbueringer I can take this up if you like.

**Comment by sbueringer** [comment]
@prankul88 Yup that would be great. Do you know what the differences between single & multi-node control plane are? (not sure if it documented precisely anywhere) If not I can write it up here.

**Comment by prankul88** [comment]
>  If not I can write it up here.

@sbueringer Sure, I would love to have your inputs.

**Comment by sbueringer** [comment]
Okay so that's let differences I have in my single/ multi-node setups:

* cluster.yaml:
  * multi-node:
    * Cluster.spec.clusterNetwork.apiServerPort does not exist
    * OpenStackCluster.spec: .apiServerLoadBalancerAdditionalPorts, .apiServerLoadBalancerFloatingIP, .apiServerLoadBalancerPort are set
    * OpenStackCluster.spec.managedAPIServerLoadBalancer is true
    * OpenStackCluster.spec.useOctavia field exists (doesn't matter how it is set)
  * single-node:
    * Cluster.spec.clusterNetwork.apiServerPort field exists
    * OpenStackCluster.spec.apiServerLoadBalancer fields do not exist
    * OpenStackCluster.spec.managedAPIServerLoadBalancer is set to false
* controlplane.yaml:
  * multi-node: 
    * 3 Machines/OpenStackMachines/KubeadmConfigs
  * single-node
    * 1 Machines/OpenStackMachines/KubeadmConfigs
    * spec.floatingIP is set on OpenStackMachine
* machinedeployment.yaml
  * no differences

**Comment by jichenjc** [comment]
@sbueringer I think for multiple node we also need the network to be created on the fly while in the single node this is not mandatory? I remember I asked this as create a new network/subnet and assign a floating ip is not authorized in my env...

**Comment by sbueringer** [comment]
Yup should be this issue: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/428

**Comment by sbueringer** [comment]
> Yup should be this issue: #428
> 
> But with the current generated example the network is created on the fly (I guess that was the nodeCIDR property right?)

Should be fixed with https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/475. So we don't have to consider this for example generation?
