### ISSUE TITLE
LeaderElectionID should be unique

### ISSUE THREAD

**Issue by noamran** [kubernetes-sigs/cluster-api-provider-openstack#478]
/kind bug

**What steps did you take and what happened:**
This issue was reported in other providers - Running several Cluster API pods (e.g. CAPI + CABPK + an infra provider) in the same namespace results in leader election errors. 
Additional details here - kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#271

**Comment by jichenjc** [comment]
I am working on other projects for the leader election as well, so I will take a look but if anyone want to work on it, feel free to take ,thanks

**Comment by sbueringer** [comment]
Fixed via https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/479
