### ISSUE TITLE
CAPO Release v0.2.0

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#480]
Hi,

I would propose releasing a v0.2.0 version of CAPO after these 3 PRs are merged:
* [x] [LeaderElectionID should be unique](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/479)
* [x] [Pr use existing networks](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/477)
* [x] [Generate seperate multi-node and single-node yaml](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/476)
* [x] Release image (https://github.com/kubernetes/k8s.io/pull/433)
* [x] Finalize doc (https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/488)
* [x] Add CAPO to cluster api book (https://github.com/kubernetes-sigs/cluster-api/pull/1661)

@jichenjc @hidekazuna @prankul88 
What do you think? We can always release follow-up patch releases

The process is more or less opening a PR to publish our staging images to the production buckets.

**Comment by prankul88** [comment]
Sounds Good to me!

**Comment by jichenjc** [comment]
the plan works for me  :)

**Comment by hidekazuna** [comment]
Good to me, too.
