### ISSUE TITLE
Calico version in user-data needs to be updated

### ISSUE THREAD

**Issue by jazzsir** [kubernetes-sigs/cluster-api-provider-openstack#481]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
After my master node has been provisioned, I found that clusterapi-controller on the node couldn't reach external network including Openstack, I tried to ping by entering the controller with kubecl exec. 
For that reason, worker node was not created. 
(My security group allowed full port range for all protocols form all IPs).

**What did you expect to happen:**
The clusterapi-controller sends a request for the worker node to Openstack.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I solved it by replacing calico version in the master-user-data.sh with compatible one as below

`kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://docs.projectcalico.org/v3.5/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml`
->
`kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml`

I tested the version with Kubernetes 1.13.2, 1.14.x and 1.15.3
If it is valid, I can push a PR for the same.

**Environment:**
- Cluster-api version: v1alpha**1**
- Minikube/KIND version: existing cluster 1.15.3
- Kubernetes version: (use `kubectl version`): 1.15.3
- OS (e.g. from `/etc/os-release`): CentOS 7.6

**Comment by sbueringer** [comment]
Yup you can open a PR if you want. I myself work mostly with the master branch where we already have calico 3.8.2

**Comment by jazzsir** [comment]
> /kind bug
> 
> **What steps did you take and what happened:**
> [A clear and concise description of what the bug is.]
> After my master node has been provisioned, I found that clusterapi-controller on the node couldn't reach external network including Openstack, I tried to ping by entering the controller with kubecl exec.
> For that reason, worker node was not created.
> (My security group allowed full port range for all protocols form all IPs).
> 
> **What did you expect to happen:**
> The clusterapi-controller sends a request for the worker node to Openstack.
> 
> **Anything else you would like to add:**
> [Miscellaneous information that will assist in solving the issue.]
> I solved it by replacing calico version in the master-user-data.sh with compatible one as below
> 
> `kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://docs.projectcalico.org/v3.5/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml`
> ->
> `kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml`
> 
> I tested the version with Kubernetes 1.13.2, 1.14.x and 1.15.3
> If it is valid, I can push a PR for the same.
> 
> **Environment:**
> 
> * Cluster-api version: v1alpha**1**
> * Minikube/KIND version: existing cluster 1.15.3
> * Kubernetes version: (use `kubectl version`): 1.15.3
> * OS (e.g. from `/etc/os-release`): CentOS 7.6

**Comment by jazzsir** [comment]
Closing this PR merged
