### ISSUE TITLE
Need a CI job that tests CAPO with e2e/conformance tests

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/cluster-api-provider-openstack#484]
For CAPG, we have added a CI job which is able to test the CI artifacts from kubernetes/kubernetes every 4 hours:
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-gcp#capg-conformance-stable-k8s-master

We need a similar one for CAPO as well. Also see https://github.com/kubernetes/sig-release/issues/829 for more context on why this is valuable to not just CAPO, but the overall community by helping with the release process

@jichenjc @kiwik @liusheng @wangxiyuan @ZhengZhenyu @huangtianhua @sbueringer

**Comment by sbueringer** [comment]
@dims @ramineni @adisky @chrigl @jichenjc 

Just that I got it correctly this job in our case has to:
* build & push an OS Image to an OpenStack (I would usage image-builder of course)
* Install a Kubernetes cluster with CAPO
* execute Kubernetes e2e tests 

For GCP you have 3 Jobs:
* ci-cluster-api-provider-gcp-make-conformance-master: master branches 
* ci-cluster-api-provider-gcp-make-conformance-stable: CAPI/CABPK: stable branches other repos: master branches
* ci-cluster-api-provider-gcp-make-conformance-stable-k8s-ci-artifacts: CAPI/CABPK: stable branches other repos: master branches (but using k8s artifacts published by CI)

Prereqs would be:
* access to an OpenStack. Currently there are tests using OpenLab or an OpenStack from CityNetwork

Unknowns for me are:
* How do we get access to an OpenStack/ which one can/should we use
* How can I build Images with packer in Prow (I guess there are some jobs which are already doing the same?)

**Comment by jichenjc** [comment]
brand new to this CI , just to make me understand more
so we need leverage OpenLab env to create a cluster api cluster (openstack) for each PR we added then after those cluster is ready, we will start e2e k8s test (and this e2e test is standard for all k8s ecosystem?)

**Comment by wangxiyuan** [comment]
please create a issue in OpenLab to add the new job.  https://github.com/theopenlab/openlab/issues/new/choose

**Comment by dims** [comment]
@jichenjc we can start with a periodic job, then do a presubmit (for each PR). yes, we are talking about checking if the cluster we started is conformant (so running the conformance tests).

**Comment by jichenjc** [comment]
ok, understand more now ... need check whether we already have a issue in openlab ... will double check:)

**Comment by sbueringer** [comment]
@jichenjc So you'll check if we already have a issue there? I could try to implement the job afterwards. I have a few weeks until I"m on vacation. I dont have a lot of time until then, but maybe enough to implement it.

**Comment by jichenjc** [comment]
@sbueringer I might remember wrong thing since @hidekazuna seems opened a e2e test issue before.. anyway, I think you can go ahead and open the issue and work on it.. thanks~

**Comment by sbueringer** [comment]
@jichenjc Do I have to open a new issue in the OpenLab repo or can I reuse the existing one? (Can you link it here?)

**Comment by sbueringer** [comment]
@dims

I'm a little bit confused how all this can fit together. The gcp job is implemented via Prow. 

The existing OpenStack tests in CloudProvider Openstack are implemented using OpenLab Zuul. As far as I can see OpenLab is exclusively used via Zuul.

So if I implement a Job for CAPO similar to the existing ones it would be via Zuul. But what we need for Kubernetes is a Prow job, right? So are there any examples how to integrate Prow with Zuul? (if it's possible)

**Comment by adisky** [comment]
@sbueringer i suggest to make a new one, `conformance-cluster-api-openstack` sounds good

**Comment by sbueringer** [comment]
I'll be on vacation until end of Dezember and would continue with this Issue and accompanying PRs then.

If somebody want's to takeover in the meantime.
* Current version of the conformance test is available here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/491/files
* Currently it's impeded because sourcing of the OpenStack environment variables in OpenLab fails > https://github.com/theopenlab/openlab/issues/141

**Comment by sbueringer** [comment]
@dims The job is almost ready. Against which branches of Kubernetes should be tested? Only master or also something like the release-1.18 branch?

**Comment by dims** [comment]
@sbueringer yes at least one already released branch and master.

**Comment by sbueringer** [comment]
@dims Just that I get it correctly, not sure how the release branches are handled in k/k. 
There are the following branches:
* master (latest development version)
* release-1.18 (almost released version (1.18 rc))
* release-1.17 latest stable released version

So in this case it would be good to test at least master and release-1.18 in my opinion. The question is if it also makes sense to test release-1.17.

From a CAPO perspective I would test our CAPO PR's against the latest released version which in this case would be 1.17.

**Comment by dims** [comment]
at this point in time, yes adding jobs for. release-1.17 + release-1.18 + master make sense. As of today when 1.18.0 will get released, so it would be good to make sure CAPO works with 1.17 and 1.18 released versions and master as well

**Comment by sbueringer** [comment]
Okay thx.

**Comment by sbueringer** [comment]
@dims 
Test results are now available here: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-openstack#capo-conformance-stable-k8s-master
Job is run twice a day. For now periodic tests are only testing against master. I still have some stability issues which I'm trying to fix (when the tests are run in one specific OpenLab cluster they consistently fail, not sure yet why but looks like over-provisioning, or some strange nested virtualization bug (other CPU type is used))

**Comment by dims** [comment]
excellent! thanks @sbueringer !

**Comment by dims** [comment]
@sbueringer do you have at least 2 worker nodes in that configuration? (looks like the one conformance test failure may be because we need at least 2 nodes)

**Comment by sbueringer** [comment]
@dims Makes sense. I had them "all" green again but that was with parallel and that's a serial test. I'll add another worker node

**Comment by sbueringer** [comment]
@dims Increasing the worker count fixed the issue. So the only remaining problem is that if the tests are run on the wrong OpenLab cluster they don't work. There seems to be a difference in the used CPU (for more details see: https://github.com/theopenlab/openlab/issues/504)
