### ISSUE TITLE
upgrade gophercloud to v0.4.0

### ISSUE THREAD

**Issue by jsen-** [kubernetes-sigs/cluster-api-provider-openstack#485]
/kind feature

We're currently on OpenStack Ocata, and due to [date parsing issue](https://github.com/gophercloud/gophercloud/pull/1671), we need to build our own images.
The only difference is in `go.mod`:
```diff
-github.com/gophercloud/gophercloud v0.3.0
+github.com/gophercloud/gophercloud v0.4.0
```
Would it be possible to increase the version in master?
I can send a PR if there's no specific reason to stay on v0.3.0.

**Comment by jichenjc** [comment]
I see no issue to upgrade if everything works...
