### ISSUE TITLE
Replace in-tree cloud-provider by cloud-provider-openstack

### ISSUE THREAD

**Issue by chrigl** [kubernetes-sigs/cluster-api-provider-openstack#489]
/kind feature

**Describe the solution you'd like**

The current examples bring up a cluster with `cloud-provider: openstack`. This uses the kubernetes in-tree cloud-provider, which will be removed in the future.

We should be able to deploy a cluster with `cloud-provider: external` and deploy https://github.com/kubernetes/cloud-provider-openstack as an addon.

This might simplify stuff in the deployment, because there is no need to inject `/etc/kubernetes/cloud.conf` to VMs files any more.

**Anything else you would like to add:**

In this step, we could also thing about moving to https://github.com/kubernetes/cloud-provider-openstack/tree/master/examples/cinder-csi-plugin for storage.

**Comment by jichenjc** [comment]
so the suggestion here to remove the external cloud provider we added 
and for cloud-provider-openstack, actually it's not mandatory, so we may not include it ,correct? @chrigl

**Comment by sbueringer** [comment]
> so the suggestion here to remove the external cloud provider we added
> and for cloud-provider-openstack, actually it's not mandatory, so we may not include it ,correct? @chrigl

I'm a little bit confused. Where did we add the external cloud controller manager? :) And afaik if you want to have a healthy cluster the cloud controller manager is mandatory, because if you're not using it you won't get ready nodes (as soon as the internal one has been removed).

**Comment by jichenjc** [comment]
yeah, you are right, this is a must 

we have to create some containers and deployment just like network related parts? 
need more effort to make dependency on the cloud controller openstack and run that during the cluster init process ...

**Comment by sbueringer** [comment]
@jichenjc Not sure if this might be done by the control plane provider: https://master.cluster-api.sigs.k8s.io/developer/architecture/controllers/control-plane.html

**Comment by jichenjc** [comment]
@sbueringer will take a look and provide some comments later on, a quick look seems you are right, the cloud provide should be in the control pane, maybe need refer to other provider as they have clodu provider already for long time..

**Comment by jichenjc** [comment]
I tried to follow CCMO doc 

```
NAME                                       READY   STATUS        RESTARTS   AGE
calico-kube-controllers-75d56dfc47-4qkb7   1/1     Running       0          5h19m
calico-node-h8wqb                          1/1     Running       0          5h19m
coredns-66bff467f8-87kk6                   1/1     Running       0          5h20m
coredns-66bff467f8-jbjkd                   1/1     Running       0          5h20m
etcd-jjtest                                1/1     Running       0          5h20m
kube-apiserver-jjtest                      1/1     Running       0          5h20m
kube-controller-manager-jjtest             1/1     Running       2          5h20m
kube-proxy-qrcfz                           1/1     Running       0          5h20m
kube-scheduler-jjtest                      1/1     Running       2          5h20m
openstack-cloud-controller-manager-p8bt4   1/1     Running 0          5h20m

```

**Comment by jichenjc** [comment]
so I think we need consider move to external cloud provider soon or later 

maybe 
1) create controller plane with external cloud flag
2) create deployment as external cloud provider in controller plane
3) join controller by using external flag

**Comment by sbueringer** [comment]
@jichenjc I think we should talk to the main ClusterAPI project how this should be solved and I wouldn't want to implement it in our code. Of course setting the external flags can be done via the CRDs, but not so sure about the cloud controller manager deployments..

**Comment by jichenjc** [comment]
yes, that's a good suggestion, I will open an issue and discuss there.. thanks

**Comment by hidekazuna** [comment]
/assign @hidekazuna 

I will follow [cluster-api-provider-azure case](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/topics/external-cloud-provider.md).
