### ISSUE TITLE
migration of cluster-api v1alpha2 ==> v1alpha3

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#499]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

add v1alpha3 support due to clusterctl will be deprecated later, I tried 
https://cluster-api.sigs.k8s.io/user/quick-start.html able to create control pane but failed to create machines due to 
```
E0122 04:27:05.167452       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to retrieve Status.APIEndpoints from infrastructure provider for Cluster \"test-cluster\" in namespace \"test-cluster\": field not found"  "controller"="cluster" "request"={"Namespace":"test-cluster","Name":"test-cluster"
```
this is listed https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/providers/v1alpha2-to-v1alpha3.md

so the to do is
- [x] add v1alpha3 types
- [x] modify code to fit for v1alpha3 types
- [x] modify doc to remove clusterctl and a new method to create cluster
- [x] a new release of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/download/v0.2.0/infrastructure-components.yaml , currently something is missing such as namespace, secret, machines CRD etc

   

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jichenjc** [comment]
@sbueringer @prankul88 let me you know any comments on this ... thanks

**Comment by sbueringer** [comment]
@jichenjc I'm just starting to read up on v1alpha3. Do you have time to work on this issue?

**Comment by jichenjc** [comment]
yes, I have some time in upcoming 10-15 days so I will work on it recently


https://master.cluster-api.sigs.k8s.io/ is the book for v1alpha3 and 
https://cluster-api.sigs.k8s.io/ is for v1alpha2

so my plan is to make use my image (created locally) and switch code to v1alpha3 with master CAPI code ...

**Comment by prankul88** [comment]
@jichenjc +1 for the migration. Should there be a new branch or the current master branch would do?

>Are you sure upstream ClusterAPI Book is already based on v1alpha3?

Don't think it is completely in line with the v1Alpha3. Although it is frequently updated based on master

**Comment by jichenjc** [comment]
seems v1alpha3 is underway, not released yet..https://github.com/kubernetes-sigs/cluster-api/issues/2272 so it might take more time to go for us to adopt

**Comment by MPV** [comment]
Seems v1alpha3 is released now: 
https://github.com/kubernetes-sigs/cluster-api/releases/tag/v0.3.0

**Comment by sbueringer** [comment]
Jup. just merged initial support on master for CAPO. But not compatible with clusterctl yet. I would try to get a PR open the next few days to make it usable with clusterctl and then create some issues for some extended features

**Comment by sbueringer** [comment]
@jichenjc can we close this issue?

**Comment by jichenjc** [comment]
yes, we can close
