### ISSUE TITLE
Favor wrapping of errors to ease troubleshooting

### ISSUE THREAD

**Issue by petergardfjall** [kubernetes-sigs/cluster-api-provider-openstack#505]
/kind feature

**Describe the solution you'd like**
A lot of error context is "thrown away" by not wrapping errors. This makes errors harder to troubleshoot as the underlying cause is invisible. Instead of code like:

```
err = networkingService.ReconcileRouter(clusterName, openStackCluster)
if err != nil {
	return reconcile.Result{}, errors.Errorf("failed to reconcile router: %v", err)
}
```

I think it would be preferable to use code like:

```
err = networkingService.ReconcileRouter(clusterName, openStackCluster)
if err != nil {
	return reconcile.Result{}, errors.Wrap(err, "failed to reconcile router")
}
```

Becasue, at the moment, it is *very* difficult to understand why a reconciliation step fails. The controller log simly contains lines like:
```
E0212 11:21:28.715379       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile router: Resource not found"  "controller"="openstackcluster" "request"={"Namespace":"ck8s-0","Name":"ck8s-0"}
```
which gives very little possiblity to determine the root cause.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by detiber** [comment]
One of the things that we've done in core Cluster API as well as some of the other providers is to basically ignore the logging from controller-runtime (which handles any returned errors from `Reconcile()` and have opted instead to do structured logging with `klogr`.

That said we do try to leverage wrapping of errors to provide more debugging information when issues are encountered. One thing to keep in mind with this approach is that if there is any logic that handles inspecting errors (such as those returned from a cloud provider api) and those errors aren't being inspected immediately after the call is made (they are wrapped), you will likely need to use `errors.Cause()` prior to inspecting the error.

**Comment by sbueringer** [comment]
@petergardfjall Maybe I got it wrong. I thought wrapping errors is mostly useful if you want to expose the underlying error type and inspect it in go code. Just wrapping the error instead of using `%v` doesn't improve the log message (?)

**Comment by petergardfjall** [comment]
> @petergardfjall Maybe I got it wrong. I thought wrapping errors is mostly useful if you want to expose the underlying error type and inspect it in go code. Just wrapping the error instead of using `%v` doesn't improve the log message (?)

It does improve the error message by recursively unwrapping the error messages. As described by Dave Cheney here https://dave.cheney.net/2016/06/12/stack-traces-and-the-errors-package:


        err := errors.New("error")
        err = errors.Wrap(err, "open failed")
        err = errors.Wrap(err, "read config failed")

        fmt.Println(err) // read config failed: open failed: error

**Comment by sbueringer** [comment]
I see. We were talking about two different things. I though we're talking about error wrapping with Go 1.13 (`%w`).

```go
package main

import (
	"fmt"

	"github.com/pkg/errors"
)

func main() {
	fmt.Println("err")
	err := errors.New("error")
	err = errors.Wrap(err, "open failed")
	err = errors.Wrap(err, "read config failed")

	fmt.Println(err)
	fmt.Println(errors.Cause(err))
	fmt.Printf("%+v\n", err)

	fmt.Println("err2")
	err2 := fmt.Errorf("error")
	err2 = fmt.Errorf("open failed: %v", err2)
	err2 = fmt.Errorf("read config failed: %v", err2)
	fmt.Println(err2)
	fmt.Printf("%+v\n", err2)

	fmt.Println("err3")
	err3 := fmt.Errorf("error")
	err3 = fmt.Errorf("open failed: %w", err3)
	err3 = fmt.Errorf("read config failed: %w", err3)
	fmt.Println(err3)
	fmt.Printf("%+v\n", err3)
}
```

Leads to this output:
```
API server listening at: 127.0.0.1:32783
err
read config failed: open failed: error
error
error
main.main
	/home/sbuerin/code/src/git.daimler.com/c445/t1/example/test/main.go:11
runtime.main
	/snap/go/current/src/runtime/proc.go:203
runtime.goexit
	/snap/go/current/src/runtime/asm_amd64.s:1357
open failed
main.main
	/home/sbuerin/code/src/git.daimler.com/c445/t1/example/test/main.go:12
runtime.main
	/snap/go/current/src/runtime/proc.go:203
runtime.goexit
	/snap/go/current/src/runtime/asm_amd64.s:1357
read config failed
main.main
	/home/sbuerin/code/src/git.daimler.com/c445/t1/example/test/main.go:13
runtime.main
	/snap/go/current/src/runtime/proc.go:203
runtime.goexit
	/snap/go/current/src/runtime/asm_amd64.s:1357
err2
read config failed: open failed: error
read config failed: open failed: error
err3
read config failed: open failed: error
read config failed: open failed: error
```

So the only advantage I can see of the errors package is when the `%+v` option is used to print the whole stacktrace. 

What I was talking about before exposing the error I meant this:
> When adding additional context to an error, either with fmt.Errorf or by implementing a custom type, you need to decide whether the new error should wrap the original. There is no single answer to this question; it depends on the context in which the new error is created. Wrap an error to expose it to callers. Do not wrap an error when doing so would expose implementation details.
https://blog.golang.org/go1.13-errors (section `Whether to wrap`)

**Comment by petergardfjall** [comment]
> So the only advantage I can see of the errors package is when the `%+v` option is used to print the whole stacktrace, but not sure if that's a good idea because I guess the new lines will break the log format. I think the problem in your example above with gophercloud is that the error of gophercloud misses context information in the error text, not that we're using `%v`.

@sbueringer I think you're right. I was to quick to jump to conclusions. Given how brief error messages I was observing (a lot of `failed to reconcile X: resource not found`) I drew the wrong conclusion that it was becasuse errors weren't properly wrapped. The only thing the use of `errors.Wrap(err, "msg")` would give us here would be to preserve the stack trace which _could_ be useful but probably not provide that much value in this case. Using `error.Errorf("message: %v", err)` here actually seems like the proper way of handling it.

I'm gonna close off this issue (sorry for the confusion), but I still think that the problem persists in the sense that a lot of error messages are _really_ difficult to troubleshoot. I think that wrapping is not the issue here but either lack of error details in upstream dependencies (like gophercloud) or, in at least some instances, due to missing error details in the openstack provider code.

For example, in the above example 
```
	err = networkingService.ReconcileRouter(clusterName, openStackCluster)
	if err != nil {
		return reconcile.Result{}, errors.Errorf("failed to reconcile router: %v", err)
}
```
It seems to me that there are several possible places in `ReconcileRouter()` where a `Resource not found` error could be returned, but it is almost impossible for me to determine where it happened.

**Comment by jichenjc** [comment]
>>> I think the problem in your example above with gophercloud is that the error of gophercloud misses context information in the error text, not that we're using %v.

this is exactly the issue, gophercloud error contaxt info is the primary issue we are having..

**Comment by petergardfjall** [comment]
> this is exactly the issue, gophercloud error contaxt info is the primary issue we are having..

Yes, mostly I agree, but I think that there are instances where the openstack provider could add some context to gophercloud errors rather than just doing a `return err`. In some cases this could help troubleshooting immensely, I believe. However, that goes beyond the scope of this issue.

**Comment by jichenjc** [comment]
> > this is exactly the issue, gophercloud error contaxt info is the primary issue we are having..
> 
> Yes, mostly I agree, but I think that there are instances where the openstack provider could add some context to gophercloud errors rather than just doing a `return err`. In some cases this could help troubleshooting immensely, I believe. However, that goes beyond the scope of this issue.

fully agree, something we need do better as I have this kind of issue time to time, thanks for the suggestion and help

**Comment by sbueringer** [comment]
I also agree. Gophercloud errors are sometimes lacking to much context. Whenever possible we should add additional context to the error messages.
