### ISSUE TITLE
Readme instructions are not up to date with current project state

### ISSUE THREAD

**Issue by iamemilio** [kubernetes-sigs/cluster-api-provider-openstack#51]
examples:
cd $GOPATH/src/sigs.k8s.io/cluster-api-provider-openstack/clusterctl
---> this path no longer exists

clusterctl create cluster --provider openstack -c examples/openstack/out/cluster.yaml -m examples/openstack/out/machines.yaml -p examples/openstack/out/provider-components.yaml
---> pathing: /out/*.yaml is not how the directory is managed by default

**Comment by chaosaffe** [comment]
Thanks for reporting @iamemilio!
