### ISSUE TITLE
kubectl get machines will not work in v1alpha3

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#519]
/kind feature

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

after v1alpha3 used, the 
`kubectl get machines` will not work on the new created cluster

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
@sbueringer will this be something we need consider

I think sooner or later we will move to clusterctl?

**Comment by sbueringer** [comment]
> @sbueringer will this be something we need consider
> 
> I think sooner or later we will move to clusterctl?

Why will get machine not work?

I've setup a few CAPA clusters yesterday and the only major change regarding kubectl/clusterctl is that the clusterctl commands are different now. You're able to do mostly same but with different commands. With kubectl you can do the same as before as far as I could see

**Comment by jichenjc** [comment]
I destroyed my env yesterday, I think `clusterctl move` command will do the job but we seems didn't test that now, I will try this early next week if no conclusion from other folks
I am pretty sure it doesn't work because no migration from bootstrap cluster to new one for those CRDs..

**Comment by jichenjc** [comment]
@sbueringer this is what I am talking about..
```
 kubectl --kubeconfig=./kubeconfig get nodes
NAME                               STATUS   ROLES    AGE     VERSION
test-cluster-control-plane-qj2k8   Ready    master   11m     v1.17.1
test-cluster-md-0-5rxxl            Ready    <none>   7m38s   v1.17.1
root@jck8s4:~/go/src/sigs.k8s.io/cluster-api-provider-openstack# kubectl --kubeconfig=./kubeconfig get machines
error: the server doesn't have a resource type "machines"
```

**Comment by sbueringer** [comment]
Okay got it. That's mainly a change in workflow. You don't get a pivot per default (CAPI control plane will stay on your bootstrap cluster). But you can do a pivot like it's documented here: https://cluster-api.sigs.k8s.io/clusterctl/commands/move.html#pivot

**Comment by jichenjc** [comment]
ok, maybe we need do something there :), let me try this later

**Comment by jichenjc** [comment]
the move action of clusterctl doesn't work ... need further check
```
Performing move...
Discovering Cluster API objects
Secret Count=8
ConfigMap Count=0
Total objects Count=10
Moving Cluster API objects Clusters=0
Pausing the source cluster
Creating target namespaces, if missing
Creating objects in the target cluster
Deleting objects from the source cluster
Resuming the target cluster

```

**Comment by sbueringer** [comment]
> the move action of clusterctl doesn't work ... need further check
> 
> ```
> Performing move...
> Discovering Cluster API objects
> Secret Count=8
> ConfigMap Count=0
> Total objects Count=10
> Moving Cluster API objects Clusters=0
> Pausing the source cluster
> Creating target namespaces, if missing
> Creating objects in the target cluster
> Deleting objects from the source cluster
> Resuming the target cluster
> ```

Already tested with this version? https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/518
There should be a fix for this in there

**Comment by sbueringer** [comment]
@jichenjc  Can you test if there's an issue with v0.3.0? For me everything works

**Comment by jichenjc** [comment]
I will test and close it this later

**Comment by jichenjc** [comment]
# kubectl --kubeconfig kubeconfig get machines
error: the server doesn't have a resource type "machines"
root@jck8s4:~/go/src/sigs.k8s.io/cluster-api-provider-openstack# kubectl --kubeconfig kubeconfig get nodes
NAME                                  STATUS   ROLES    AGE     VERSION
capi-quickstart-control-plane-w2l6d   Ready    master   3m17s   v1.17.1
capi-quickstart-md-0-xljvr            Ready    <none>   2m4s    v1.17.1


I am still able to see this error on master code @sbueringer

**Comment by sbueringer** [comment]
If you don't pivot the capi control plane to your workload cluster it will stay on your initial cluster (probably kind). That's not a bug 😃

**Comment by jichenjc** [comment]
ah.... you are right, I totally forget this :(
thanks for point out

**Comment by jichenjc** [comment]
I can run this 
clusterctl init --kubeconfig kubeconfig --config ./out/clusterctl.yaml --infrastructure openstack

after that I can move (still some error , but should be my internal issue)
