### ISSUE TITLE
AZ usage of v1alpha3

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#525]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
my cloud actually have more than 1 az, and I noticed that current behavior is to create vm on random az , I checked cluster-api code and seems their az is try to find in a set of domains then pick fewest one

but openstack az is not such concept as far as I can tell... 
are we sure the cluster-api failuredomain concept is same to az in openstack? 
as cluster api has scale up and down ,I am really not convieneced it's suitable for openstack

and , where can I set failuredomain on control pane? I knew we can set on worker node but I am not that far 

```

func (r *KubeadmControlPlaneReconciler) failureDomainForScaleDown(cluster *clusterv1.Cluster, machines internal.FilterableMachineCollection) *string {
        // See if there are any Machines that are not in currently defined failure domains first.
        notInFailureDomains := machines.Filter(
                machinefilters.Not(machinefilters.InFailureDomains(cluster.Status.FailureDomains.FilterControlPlane().GetIDs()...)),
        )
        if len(notInFailureDomains) > 0 {
                // return the failure domain for the oldest Machine not in the current list of failure domains
                // this could be either nil (no failure domain defined) or a failure domain that is no longer defined
                // in the cluster status.
                return notInFailureDomains.Oldest().Spec.FailureDomain
        }

        // Otherwise pick the currently known failure domain with the most Machines
        return internal.PickMost(cluster.Status.FailureDomains.FilterControlPlane(), machines)
}

func (r *KubeadmControlPlaneReconciler) failureDomainForScaleUp(cluster *clusterv1.Cluster, machines internal.FilterableMachineCollection) *string {
        // Don't do anything if there are no failure domains defined on the cluster.
        if len(cluster.Status.FailureDomains.FilterControlPlane()) == 0 {
                return nil
        }
        return internal.PickFewest(cluster.Status.FailureDomains.FilterControlPlane(), machines)
}
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
@sbueringer @ncdc 
could you please help to provide some insight? thanks

**Comment by sbueringer** [comment]
I think Openstack availability zones are just like azs in other clouds and you can use them the same way as failure domain. If you don't want to you can pin the az in the openstackmachinetemplate of the kubeadmcontrolplane.

**Comment by jichenjc** [comment]
some cloud has az concept and openstack is different to that
https://docs.openstack.org/nova/latest/admin/availability-zones.html
https://www.mirantis.com/blog/the-first-and-final-word-on-openstack-availability-zones/

**Comment by sbueringer** [comment]
Jup. But as far as I know it depends on your Openstack. Our Openstack availability zones use different physical hosts and locations. So imho you can use azs in Openstack pretty similar to real clouds.

**Comment by jichenjc** [comment]
here's the detail analysis so far: 

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/controllers/openstackcluster_controller.go#L294

will get *all* az and return as failureDomain and all az will be marked as ControlPlane


https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha3/cluster_types.go#L213
will not filter any az because all set ControlPlan above


failure domain found here and used later on 
https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/controllers/scale.go#L39


https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/internal/control_plane.go#L130

finally create machine here with fd found above
https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/controllers/helpers.go#L223


so the fd will be selected by given from provider, we provided all az while some az in my cloud is actually not suitable for some workload
so I think we should pin the fd in openstack side

**Comment by jichenjc** [comment]
will add doc on how to pin this later with other doc changes

**Comment by sbueringer** [comment]
@jichenjc see the comment at the PR. I think your requirement is okay. But let's just make it possible to also pin it to multiple AZs not just one of them. So in your case you can pin it to one. In my case I could just 3 out of 5.
