### ISSUE TITLE
disableServerTags: true is not working

### ISSUE THREAD

**Issue by AllaeddineEL** [kubernetes-sigs/cluster-api-provider-openstack#543]
/kind bug

**What steps did you take and what happened:**
I'm trying to provision Kubernetes Cluster on Top of our OpenStack Provider, which it doesn't support port tags.
I've disabled the server tags `disableServerTags: true` in the `OpenStackCluster` config and I have no tags in the `OpenStackMachineTemplate`

**What did you expect to happen:**
Create OpenStack cluster without tags  

**Anything else you would like to add:**
```
$ kubectl describe openstackmachine devops-control-plane-trf55
Name:         devops-control-plane-trf55
Namespace:    default
Labels:       cluster.x-k8s.io/cluster-name=devops
              cluster.x-k8s.io/control-plane=
              kubeadm.controlplane.cluster.x-k8s.io/hash=724735395
Annotations:  <none>
API Version:  infrastructure.cluster.x-k8s.io/v1alpha3
Kind:         OpenStackMachine
Metadata:
  Creation Timestamp:  2020-04-06T14:29:27Z
  Finalizers:
    openstackmachine.infrastructure.cluster.x-k8s.io
  Generation:  1
  Owner References:
    API Version:           controlplane.cluster.x-k8s.io/v1alpha3
    Kind:                  KubeadmControlPlane
    Name:                  devops-control-plane
    UID:                   d22ddafb-17f8-4c79-ad6d-5b285a48a335
    API Version:           cluster.x-k8s.io/v1alpha3
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Machine
    Name:                  devops-control-plane-n88ww
    UID:                   db838279-5626-4e23-8126-7c33b6640e02
  Resource Version:        2889
  Self Link:               /apis/infrastructure.cluster.x-k8s.io/v1alpha3/namespaces/default/openstackmachines/devops-control-plane-trf55
  UID:                     d62c98e5-c9ff-40f0-a91e-5052f3299a8d
Spec:
  Cloud Name:  otc_doa
  Clouds Secret:
    Name:       devops-cloud-config
    Namespace:  default
  Flavor:       s2.large.1
  Image:        Standard_CentOS_7_prev_packer_test
  Security Groups:
    Name:        devops-k8s-master
    Name:        devops-k8s-master
    Name:        devops-local-ssh
    Name:        devops-k8s-ssh
    Name:        devops-k8s
  Ssh Key Name:  kubernetes-devops
Status:
  Error Message:  OpenStack instance cannot be created: error creating Openstack instance: tagging port for server err: Resource not found
  Error Reason:   UpdateError
Events:           <none>
```

**Environment:**

- Cluster-api version: v0.3.3 
- Minikube/KIND version: v1.17.0
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
@AllaeddineEL Yup looks like you're right:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/pkg/cloud/services/compute/instance.go#L153-L158

I'm not sure why exactly the disableServerTags flag was added I guess because some version of the Nova API doesn't support tagging. This seems to be the same for Neutron? (I guess ports are added via Neutron)

@jichenjc @hidekazuna do you know more about which versions of which API support tagging?

**Comment by hidekazuna** [comment]
@sbueringer  support server tagging is 2.52 which is [documented](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/docs/configuration.md#tagging) 😄 
Actually OpenStack Nova REST API Version History said so: https://docs.openstack.org/nova/latest/reference/api-microversion-history.html#id48

**Comment by jichenjc** [comment]
yes, @hidekazuna is correct,  maybe we need fix this by checking the version
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/manila/manilaclient/builder.go#L114
has some sample

@AllaeddineEL can you help to provide your openstack version?

**Comment by hidekazuna** [comment]
@jichenjc  If disableServerTags is false, micro version is set to 2.52, Otherwise, no setting: 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/pkg/cloud/services/compute/instance.go#L199-L206

Guarding by disableServerTags is better than checking version.

**Comment by jichenjc** [comment]
but 
>>> I've disabled the server tags disableServerTags: true in the OpenStackCluster config and I have no tags in the OpenStackMachineTemplate

seems it doesn't take effect.. need check this @hidekazuna

**Comment by sbueringer** [comment]
> but
> 
> > > > I've disabled the server tags disableServerTags: true in the OpenStackCluster config and I have no tags in the OpenStackMachineTemplate
> 
> seems it doesn't take effect.. need check this @hidekazuna

The code I linked (https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/pkg/cloud/services/compute/instance.go#L153-L158) doesn't handle the disableServerTags, I guess because a port is not a server :). That's why I'm confused. I wasn't aware that ports also need a minimum version (of probably Neutron?) to support tagging.

**Comment by sbueringer** [comment]
I assume that's the endpoint which is used: https://docs.openstack.org/api-ref/network/v2/?expanded=replace-all-tags-detail#replace-all-tags

**Comment by AllaeddineEL** [comment]
@sbueringer yes the port is created, I guess the problem is related to tagging of the port as our openstack cloud provider maybe not supports  tagging.
BTW, it's neutron version 2  
```
{
      "id": "fbea95ce-6a51-48ee-9e17-024debee5708",
      "name": "devops-control-plane-trf55",
      "status": "DOWN",
      "admin_state_up": true,
      "fixed_ips": [
        {
          "subnet_id": "652393ab-c558-416c-bfde-0b9088396817",
          "ip_address": "10.168.1.153"
        }
      ],
      "mac_address": "fa:16:3e:be:db:2d",
      "network_id": "fa458a07-6f66-4713-a0b2-7589a540095f",
      "tenant_id": "XXXXXXXXXXXXXXXXXXXXXX",
      "project_id": "XXXXXXXXXXXXXXXXXXXXX",
      "device_id": "",
      "device_owner": "",
      "security_groups": [
        "90367526-aa1a-45bc-a5f5-0272436fde2b",
        "9da04149-9911-4455-bc26-1b8533febd63",
        "e25213c2-bd4e-4b5d-883c-8f2bc31250ee",
        "f4ee8df8-8123-4fd2-90cf-1b00429be38d"
      ],
      "extra_dhcp_opts": [],
      "allowed_address_pairs": [],
      "binding:vnic_type": "normal",
      "binding:vif_details": {},
      "binding:profile": {},
      "created_at": "2020-04-06T14:29:32",
      "updated_at": "2020-04-06T14:29:32"
    }
```

**Comment by hidekazuna** [comment]
@sbueringer Thanks, I misunderstood.

**Comment by sbueringer** [comment]
So then the question is which neutron version is required to tag ports. Does anybody know how to find out?

**Comment by hidekazuna** [comment]
standard-attr-tag seems to be introduced in Pike:
https://bugs.launchpad.net/neutron/+bug/1682775

**Comment by AllaeddineEL** [comment]
I guess it's more related to the neutron API extensions rather than not only to the version as what this link says https://docs.openstack.org/neutron/pike/contributor/internals/tag.html
"The ‘tag-ext’ extension supports subnets, ports, routers, and subnet pools"

**Comment by sbueringer** [comment]
So I assume that extension is not enabled. Can you ask your provider if they can support tagging? It seems to be a standard feature. I would really like to avoid adding another flag like `disableNeutronTag`

**Comment by AllaeddineEL** [comment]
@sbueringer yes, I will try to ask about the possibility to enable this extension.
But why would you need to have `disable*Tag` at first place? I guess it will make more sense if there are no tags (explicitly) in the `MachineTemplate` no tags will be created for all resources

**Comment by jichenjc** [comment]
original code comes from here, from the commit message seems the purpose is to tag all the resources created from cluster api
in practice it only created server with tags but didn't do that for neutron and other stuffs 

commit a5ecff518263a0552f3965878593dd5e72ba05fc
Author: Emilio Garcia <iamemilio@users.noreply.github.com>
Date:   Wed Apr 10 10:30:20 2019 -0400

    Clearer tagging UI: Create tags for the whole cluster, or just specific machines (#281)

    Bug Fixes: Resolves bug caused by using ImageName(depricated in nova 2.36)

**Comment by jichenjc** [comment]
@sbueringer the resource not found usually occur when you post some request t o URL that doesn't exist, this can be true if the API is not eabled or even not implemented..

so how about use same flag to control this logic ?
```
_, err = attributestags.ReplaceAll(s.networkClient, "trunks", trunk.ID, attributestags.ReplaceAllOpts{
                                Tags: machineTags}).Extract()
                        if err != nil {
                                return nil, fmt.Errorf("tagging trunk for server err: %v", err)
                        }

```

**Comment by sbueringer** [comment]
I think @AllaeddineEL has a point here. Why are we adding these tags at all? We're not really using them we're just setting them. I think there is no need to magically add some tags. So I would propose:

* Only add tags when they are explicitly defined in the cluster or machine resource
* no magical adding of some additional tags
* if somebody wants the flags we're currently adding they can be added via the `tags` array in the OpenStackCluster and OpenStackMachine resource

**Comment by AllaeddineEL** [comment]
@sbueringer @jichenjc do you have any update regarding this issue?

**Comment by sbueringer** [comment]
@AllaeddineEL Not really. I assume we're open to contributions for this but nobody implemented it yet

**Comment by sreber84** [comment]
@sbueringer is https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/560 somehow related and something that could provide relief to this issue?

**Comment by jichenjc** [comment]
@sreber84 not sure as #560 is for security group...

**Comment by jichenjc** [comment]
I tested on my system and the port created does have tags with cluster name...
```
| tags                  | capi-openstack-3                                                                                                          |
|                       | cluster-api-provider-openstack             
```

**Comment by jichenjc** [comment]
instead of tags, maybe update description is a good way

**Comment by jichenjc** [comment]
so the plan is to 
1) avoid add tags at instance create stag
2) add description when the port is created so we know the port is created by capi

**Comment by jichenjc** [comment]
@AllaeddineEL @sbueringer @hidekazuna @sreber84 please check proposed PR
