### ISSUE TITLE
Can not access applications via LoadBalancer

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#553]
/kind bug

**What steps did you take and what happened:**
I deployed a web application using LoadBalancer type service on kubernetes cluster deployed by cluster-api-provider-openstack with Octavia. The application can not be accessed via loadbalancer.

**What did you expect to happen:**

The application can be accessed via loadbalancer.

**Anything else you would like to add:**
The application could be acccessed by adding security group rule which accept NodePort services(port range 30000-32767) to worker nodes.
I think we should update security group rules according to [Check required ports](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports)

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
reasonable suggestion :) so by default we should update security group to honor the ports listed

**Comment by sbueringer** [comment]
Sounds reasonable. Should we make this configurable as the service port range can be customized?

**Comment by hidekazuna** [comment]
> Sounds reasonable. Should we make this configurable as the service port range can be customized?

Ideally it should be, but I do not need it currently. I suggest first update with no customization, after that make configurable if some one need it.

**Comment by sbueringer** [comment]
@hidekazuna Fine for me. We're customizing our nodePort range but we probably won't use the CAPO security groups.

**Comment by hidekazuna** [comment]
In addition to NodePort services,  we need bidirectional BGP and IP-in-IP for calico, and Kubelet API for metrics-server.
FYI

- Cluster API now support only Calico CNI
  https://github.com/kubernetes-sigs/cluster-api/issues/3174

- AWS security groups implementation
  https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/services/ec2/securitygroups.go#L368-L488
