### ISSUE TITLE
Security Group Rules are not updated

### ISSUE THREAD

**Issue by eratnch** [kubernetes-sigs/cluster-api-provider-openstack#556]
/kind bug
Cluster API is not able to reach control plane end point of the openstack.

**What steps did you take and what happened:**
I have set up devstack on a VM running in public cloud.
I followed the quick start guide to initialize the and configure my management cluster running on kind.
I used cluster-template-without-lb.yaml to generate the workload manifest.
I had to manually add managedSecurityGroups attribute and set it to true. 
I enabled port security by setting disablePortSecurity: false
Cluster API creates 2 security groups. However there's is no rule to allow communication on port 6443.

In the controller manager logs, the error message appears as below
"name"="k8s-cluster-default-demo1cluster-secgroup-all"
I0608 18:14:36.939765       1 openstackcluster_controller.go:277] controllers/OpenStackCluster "msg"="No control plane node found yet, could not write OpenStackCluster.Spec.ControlPlaneEndpoint" "cluster"="demo1cluster" "namespace"="default" "openStackCluster"="demo1cluster"

I think this could be because the port is not open on the security groups.
The control plane machine is not attached to the control plane security group.

**What did you expect to happen:**
Be able to pass a flag in the clusterctl config command to enable port security and set managedsecuritygroups to true rather than editing the manifest manually.
Controlplane machine is attached to the security group.
Controlplane is reachable and controller is ready to communicate with the endpoint.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I have devstack installed in a VM (4 vCPUs and 15 GB RAM).
Cluster API and Kind are in same VM. 
I am using https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/docs/configuration.md as a configuration guide.
I am using ubuntu-1804-kube-v1.16.2 qcow2 image as an image to bring up k8s servers
I have set the ssh_key as part of the environment variables. But I don't see the ssh_key attached to the controlplane instance in horizon dashboard.

**Environment:**

- Cluster-api version:
clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.2-dirty", GitCommit:"867b2afed0e6a4509a74bb123b7c6f2ab0f7ffd7", GitTreeState:"dirty", BuildDate:"2020-03-19T19:29:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
cratnoc@openstack:~$

- Minikube/KIND version:
kind --version
kind version 0.7.0

- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
1.16.2

**Comment by sbueringer** [comment]
If we expose new properties via `clusterctl`, everybody has to set them. There is no such way as optional properties right now (afaik there is some ongoing work). So I'm leaning towards not making everything configurable via env variables right now, if not strictly necessary, as the list of mandatory properties gets longer and longer.

**Comment by jichenjc** [comment]
is this related to #555 ?

**Comment by hidekazuna** [comment]
I want to make clear your expectation.
If 
```yaml
managedSecurityGroups: true
disablePortSecurity: false
```
, generated security groups are added the instances and creating cluster ended with successfully, right?

**Comment by eratnch** [comment]
if managedSecurityGroups: true
  disablePortSecurity: false then security groups are created, however they don't get attached to the instances. I further noticed that port 6443 is not opened in the rules of the security groups.

**Comment by hidekazuna** [comment]
@eratnch Opening port 6443 was fixed by #534. Remaining issue is attaching generated security groups to the instances. I am not sure it is by design or not. @sbueringer @jichenjc Is it by design? I want to fix it, if it is OK to fix.

**Comment by sbueringer** [comment]
@hidekazuna I would have thought that they are used per default as they are configured in the [template ](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/templates/cluster-template.yaml#L125)

If they are not used for the created VMs, that sounds like a bug to me

**Comment by hidekazuna** [comment]
@sbueringer [v0.3.0 template](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/v0.3.0/templates/cluster-template.yaml) does not have `securityGroups`. We need bug fix release.

**Comment by sbueringer** [comment]
@hidekazuna Yup we can create a release. Maybe close the current PRs make sure master is stable and then create the release?

**Comment by hidekazuna** [comment]
@sbueringer For completely following [capi quickstart](https://cluster-api.sigs.k8s.io/user/quick-start.html), current master is good condition, because including #534 and #550 is mandatory and enough for bug fix. we do not need to wait current unmerged PRs.
