### ISSUE TITLE
do not fail deleting router if it does not exist

### ISSUE THREAD

**Issue by jsen-** [kubernetes-sigs/cluster-api-provider-openstack#557]
/kind bug

**What steps did you take and what happened:**
 - deleted router from openstack
 - deleted cluster

**What did you expect to happen:**
 - CAPO to realize that router does not exist and continue cleaning up remaining resources

**Anything else you would like to add:**
```
I0610 12:36:28.521243       1 openstackcluster_controller.go:113] controllers/OpenStackCluster "msg"="Reconciling Cluster delete" "cluster"="capi-quickstart" "namespace"="default" "openStackCluster"="capi-quickstart" 
I0610 12:36:29.126094       1 openstackcluster_controller.go:156] controllers/OpenStackCluster "msg"="Deleting router" "cluster"="capi-quickstart" "namespace"="default" "openStackCluster"="capi-quickstart" "name"="k8s-clusterapi-cluster-default-capi-quickstart"
E0610 12:36:29.542064       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to delete router: Resource not found"  "controller"="openstackcluster" "request"={"Namespace":"default","Name":"capi-quickstart"}
I0610 12:39:13.382433       1 openstackcluster_controller.go:113] controllers/OpenStackCluster "msg"="Reconciling Cluster delete" "cluster"="capi-quickstart" "namespace"="default" "openStackCluster"="capi-quickstart" 
I0610 12:39:13.997013       1 openstackcluster_controller.go:156] controllers/OpenStackCluster "msg"="Deleting router" "cluster"="capi-quickstart" "namespace"="default" "openStackCluster"="capi-quickstart" "name"="k8s-clusterapi-cluster-default-capi-quickstart"
E0610 12:39:14.526687       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to delete router: Resource not found"  "controller"="openstackcluster" "request"={"Namespace":"default","Name":"capi-quickstart"}
...
```

**Environment:**

- Cluster-api version: v0.3.0
- Minikube/KIND version
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
just to confirm, the question you are having is the router is created by cluster-api
then you delete the router through openstack API (out of cluster-api control)
then finally when deleting the cluster the delete action failed due to the router is gone?

**Comment by jichenjc** [comment]
@jsen- which version are you using ?
latest version it has the check here already
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/pkg/cloud/services/networking/router.go#L177

**Comment by jsen-** [comment]
>just to confirm, the question you are having is the router is created by cluster-api
then you delete the router through openstack API (out of cluster-api control)
then finally when deleting the cluster the delete action failed due to the router is gone?

yes

cluster-api version: 0.3.6
openstack provider version 0.3.0

**Comment by jichenjc** [comment]
@jsen- can you help to add a log at following line 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/78939acc1471c7b53b01b2421e7948f92a757d04/pkg/cloud/services/networking/router.go#L282

and indicate what's the error returned? 

I suspect we need do something simliar to 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L376

so need your help to add a log and provide additional info, thanks

**Comment by sbueringer** [comment]
@jichenjc Did we even delete the router with 0.3.0: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/v0.3.0/controllers/openstackcluster_controller.go#L110 ?

**Comment by jichenjc** [comment]
@sbueringer @jsen- I am confused... v0.3.0 doesn't have delete Router function
the delete Router function is added after 0.3.0, so how can we have Delete Router failure function at that code... @jsen- please help to check whether you are really using 0.3.0 or some other version
@sbueringer from code line in the log, looks like @jsen- might using latest code, so this might still be a valid bug


this one is v0.3.0
commit a59ae797bff86165f8405bcec10bf3741ba2a6c9 (tag: v0.3.0)
Author: Stefan Büringer <sbueringer@gmail.com>
Date:   Sun Mar 22 05:46:44 2020 +0100

this one introduced router delete function
commit 4b9c46d37423fade201d8b0cd18f8147cc7d7efa
Author: Hidekazu Nakamura <hidekazuna@gmail.com>
Date:   Tue Mar 24 01:22:57 2020 +0000

    Delete router/network/subnet
