### ISSUE TITLE
BYO security group consideration

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#558]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
this comes from 
https://github.com/kubernetes-sigs/cluster-api/issues/3174

https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1137

we are creating security groups while we don't know which CNI is used so that the port is unclear 
need a way to provide a way to specify the security groups ..

**Comment by hidekazuna** [comment]
If `managedSecurityGroups: false` and create security groups manually and add them to `securityGroups` in yaml, CNI other than Calico would be deployed.

**Comment by sbueringer** [comment]
Yeah I guess that's always the solution if we don't provide the exact right security groups
