### ISSUE TITLE
Login to the nodes using the bastion node like AWS

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#562]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Securely login to the nodes using the bastion node like AWS.
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/accessing-instances.md#accessing-nodes-via-ssh

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This issue comes from #561 .

**Comment by jichenjc** [comment]
if I understand this correctly (I didn't go to AWS implemention detail) 
guess what we might do is we will create another VM automatically and assign a floating ip to it then 
guide user to ssh from that VM, correct?

**Comment by hidekazuna** [comment]
@jichenjc Yes, that is correct.
