### ISSUE TITLE
Get openstackcluster outputs no ENDPOINT

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#565]
/kind bug

**What steps did you take and what happened:**

```bash
$ kubectl get openstackcluster -o wide
NAME              CLUSTER           READY   NETWORK                                SUBNET                                 ENDPOINT
capi-quickstart   capi-quickstart   true    285c6236-00d8-4259-98ac-c0d035c04378   15d5830c-9aa5-4371-b075-dfa5d860a0ec
```

**What did you expect to happen:**

ENDPOINT is shown.

**Anything else you would like to add:**
The following line seems not work.
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml#L39

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
@hidekazuna maybe you can describe the `openstackcluster ` about its status, I doubt 
openstackcluster `.status.network.apiServerLoadBalancer.IP` is not created at all

**Comment by hidekazuna** [comment]
@jichenjc `.status.network.apiServerLoadBalancer.ip` is created 😃

**Comment by jichenjc** [comment]
then it's weird :) 
guess it's because of the priority=1 thing..

**Comment by jichenjc** [comment]
can you help to paste the out of `kubectl describe openstackcluster`? 

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#additional-printer-columns

seems indicated priority=1 should be enough..
