### ISSUE TITLE
Discover external network, create floating IP, and add it

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#566]
/kind feature

**Describe the solution you'd like**

Discover external network, create floating IP, and add to load balancer or controller node if 
`OPENSTACK_EXTERNAL_NETWORK_ID` and `OPENSTACK_CONTROLPLANE_IP` are not given.  

**Anything else you would like to add:**

**Comment by sbueringer** [comment]
@hidekazuna Is it possible to not set these flags? As far as I know all variables are mandatory via clusterctl (not sure if that changed in the meantime)

**Comment by hidekazuna** [comment]
@sbueringer I found AWS provider template does not have these flags. Challenging is that `controlPlaneEndpoint` have to be set in the openstackcluster_controller.go. Please take a look #573 .

**Comment by jichenjc** [comment]
sorry, maybe I missed some info , is this talking about create floating ip etc and add to existing LB ? 
should this need some doc update later on? maybe that will be helpful

**Comment by sbueringer** [comment]
@hidekazuna I didn't mean mandatory in a sense that every provider has them. I meant if we have these properties in our templates it's mandatory to fill them and there's no way to leave them empty when generating the YAMLs via clusterctl

**Comment by hidekazuna** [comment]
@jichenjc 

> sorry, maybe I missed some info , is this talking about create floating ip etc and add to existing LB ?

Yes, you are right. If floating IP is not given, capo creates floating ip.

> should this need some doc update later on? maybe that will be helpful

Sure,  I will update doc later.

**Comment by hidekazuna** [comment]
> @hidekazuna I didn't mean mandatory in a sense that every provider has them. I meant if we have these properties in our templates it's mandatory to fill them and there's no way to leave them empty when generating the YAMLs via clusterctl

@sbueringer Sure, I will remove `apiServerLoadBalancerFloatingIP`, `apiServerLoadBalancerPort`, and `externalNetworkId`.
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/573/files#diff-a13d5b9325a3022286a0a671bc66b2cb
