### ISSUE TITLE
Unable to create target cluster with Octavia

### ISSUE THREAD

**Issue by eratnch** [kubernetes-sigs/cluster-api-provider-openstack#572]
/kind bug

Running kind cluster as CAPI management cluster
Devstack running on  a VM with Octavia installed
Trying to deploy a 1 control plane and 1 worker node target cluster on devstack
using cluster-api-quick start guide (v1alpha3) 
[A clear and concise description of what the bug is.]

In the capo-controller logs following error message appears

r" "name"="k8s-clusterapi-cluster-default-tgtcluster"
I0626 16:58:42.139027       1 loadbalancer.go:53] controllers/OpenStackCluster "msg"="Reconciling loadbalancer" "cluster"="tgtcluster" "namespace"="default" "openStackCluster"="tgtcluster" "name"="k8s-clusterapi-cluster-default-tgtcluster-kubeapi"
I0626 16:58:42.293451       1 loadbalancer.go:83] controllers/OpenStackCluster "msg"="Creating floating ip" "cluster"="tgtcluster" "namespace"="default" "openStackCluster"="tgtcluster" "ip"="172.24.4.21"
E0626 16:58:42.311835       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile load balancer: error allocating floating IP: Request forbidden: [POST http://192.168.79.131:9696/v2.0/floatingips], error message: {\"NeutronError\": {\"type\": \"PolicyNotAuthorized\", \"message\": \"(rule:create_floatingip and rule:create_floatingip:floating_ip_address) is disallowed by policy\", \"detail\": \"\"}}"  "controller"="openstackcluster" "request"={"Namespace":"default","Name":"tgtcluster"}

My target cluster manifest is (just pasting the LB section)

apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackCluster
metadata:
  name: tgtcluster
  namespace: default
spec:
  apiServerLoadBalancerAdditionalPorts:
  - 22
  apiServerLoadBalancerFloatingIP: 172.24.4.21
  apiServerLoadBalancerPort: 6443
  cloudName: devstack
  cloudsSecret:
    name: tgtcluster-cloud-config
    namespace: default
  disablePortSecurity: false
  disableServerTags: true
  dnsNameservers:
  - 8.8.8.8
  externalNetworkId: ee8ea78e-68da-485b-a8aa-59644bf0f6f9
  managedAPIServerLoadBalancer: true
  nodeCidr: 10.6.0.0/24

I have created floating ip 172.24.4.21 before running the test.

**What did you expect to happen:**
LB is created and target cluster is up and running with control plane and worker machine.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I could not find relevant documentation about what are the pre-requisites in order to deploy a target openstack cluster with LB support. I think it would be good to have a section in the quick start or repo itself about loadbalancer configuration with all attributes specific description.

**Environment:**

- Cluster-api version(v1alpha3):
clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.2-dirty", GitCommit:"867b2afed0e6a4509a74bb123b7c6f2ab0f7ffd7", GitTreeState:"dirty", BuildDate:"2020-03-19T19:29:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

- Minikube/KIND version:
kind v0.7.0 go1.13.6 linux/amd64
- Kubernetes version: (use `kubectl version`): 1.17.3
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
`rule:create_floatingip and rule:create_floatingip:floating_ip_address) is disallowed by policy`

is your openstack cloud doesn't allow such activity? e.g policy forbid such action? I understand we need provide more info about what's needed and what's recommended , just to ask for info..

**Comment by eratnch** [comment]
@jichenjc  I created floating ip on my openstack and provided that in the manifest section that I mentioned above. I normally do openstack floating ip create <public n/w name> and that seems to work fine all the time. It assigns a floating ip from the pool. 
 My understanding is that Octavia maps the floating ip to its vip. CAPI should simply use the float ip, not sure why it's trying to create the float ip again.

**Comment by sbueringer** [comment]
Yup usually it just uses the floating ip if it already exists. Maybe the floating ip is not accessible for CAPO (because it's e.g. in the wrong OpenStack tenant/project) ?

That's the code which checks for the existence of the floating ip: 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/pkg/cloud/services/loadbalancer/loadbalancer.go#L77-L91

So I suppose `checkIfFloatingIPExists` is not able to get the existing floating ip

**Comment by hidekazuna** [comment]
@eratnch I found I added load-balancer_member role to the no admin user. Please try
```bash
$ openstack role create load-balancer_member
$ openstack role add --user <user_id> --project <project_id> <load-balancer_member_role_id>
```

**Comment by jichenjc** [comment]
> Yup usually it just uses the floating ip if it already exists. Maybe the floating ip is not accessible for CAPO (because it's e.g. in the wrong OpenStack tenant/project) ?
> 
> That's the code which checks for the existence of the floating ip:
> https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/pkg/cloud/services/loadbalancer/loadbalancer.go#L77-L91
> 
> So I suppose `checkIfFloatingIPExists` is not able to get the existing floating ip


>>>.I have created floating ip 172.24.4.21 before running the test.

yes, so seems the check has some problem, maybe need add some logs to check what's really happen there
maybe add some V.4 or ask @eratnch to add logs at https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/07aede71b47be724dfe14dfb3131736b9268cbb6/pkg/cloud/services/loadbalancer/loadbalancer.go#L473 ?

**Comment by eratnch** [comment]
@hidekazuna @jichenjc  @sbueringer 
Thanks for your comments/responses.
Just wanted to give some updates.
I had to add the "admin" role to the "demo" user to make it work. Is this a pre-requisite for capo to create clusters? 
Other than this I noticed that disablePortSecurity has to be set to false, otherwise CAPI doesn't create the cluster. The default is "true", so I assume this should work. Is it by design to disable port security? Can you confirm please.

**Comment by jichenjc** [comment]
>>>I had to add the "admin" role to the "demo" user to make it work. 
this means by default normal user not allow to perform this action, only admin user can do
I guess it's a good way to indicate this is needed into doc ?
e.g under this configuration you must be able to perform xxx action

**Comment by hidekazuna** [comment]
> @hidekazuna @jichenjc @sbueringer
> Thanks for your comments/responses.
> Just wanted to give some updates.
> I had to add the "admin" role to the "demo" user to make it work. Is this a pre-requisite for capo to create clusters?

Could you teach me your OpenStack Octavia version? My environment is Octavia Stein ubuntu package.
User creating cluster has only member and load-balancer_member roles. Octavia user has admin role.

> Other than this I noticed that disablePortSecurity has to be set to false, otherwise CAPI doesn't create the cluster. The default is "true", so I assume this should work. Is it by design to disable port security? Can you confirm please.

I want to know the reason too. I like `disablePortSecurity` default is false.

**Comment by eratnch** [comment]
@hidekazuna my octavia version is installed using https://docs.openstack.org/devstack/latest/guides/devstack-with-lbaas-v2.html guide. Devstack version is victoria.
