### ISSUE TITLE
Release v0.3.1

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#574]
Hi,

as suggested by @hidekazuna [here](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/556) I would create a v0.3.1 release.

@jichenjc @prankul88 Okay for you? Does the current master work in your environments?

**Comment by jichenjc** [comment]
I have not created a cluster for a few weeks and I think nothing has big impact recently, so should be fine

**Comment by prankul88** [comment]
@sbueringer Perfectly good for me

**Comment by hidekazuna** [comment]
@sbueringer Please merge doc update #576 in v0.3.1.

**Comment by sbueringer** [comment]
@hidekazuna Yup I'll wait for #575 and #576. And will review you're other PR after the v0.3.1. 

@hidekazuna @jichenjc I only found a few nits in your PRs. As soon as they are corrected and the PRs merged I would create the release

**Comment by sbueringer** [comment]
@jichenjc can you approve? https://github.com/kubernetes/k8s.io/pull/1001
Afterwards I would publish the Github release

**Comment by hidekazuna** [comment]
@sbueringer I can not /lgtm due to not member of kubernetes orgs.

**Comment by jichenjc** [comment]
@sbueringer done

**Comment by sbueringer** [comment]
> @sbueringer I can not /lgtm due to not member of kubernetes orgs.

Ah right.

Okay release is published here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.3.1

Would be nice if somebody could do a final test with clusterctl if it works

**Comment by hidekazuna** [comment]
I tested manually by following quick start, ended successfully. ✨

**Comment by sbueringer** [comment]
Perfect thx:)
