### ISSUE TITLE
can't make controlplane ready now

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#588]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

it works fine last week but when I rebuild the cluster suddenly reach this error

```
root@jidevstack:~# kubectl get openstackmachine
NAME                                  CLUSTER           STATE    READY   INSTANCEID                                         MACHINE
capi-quickstart-control-plane-hg6r5   capi-quickstart   ACTIVE   true    openstack://cf33c8bc-6239-4907-aa85-8d1fcc724966   capi-quickstart-control-plane-ct7c7

root@jidevstack:~# kubectl get machines
NAME                                    PROVIDERID                                         PHASE
capi-quickstart-control-plane-ct7c7     openstack://cf33c8bc-6239-4907-aa85-8d1fcc724966   Provisioning


```

it will always be provisioning because the name check here will NOT be satisifed because of 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/controllers/openstackcluster_controller.go#L386

so I think we need use providerID compare instead of name...

@hidekazuna @sbueringer do you suffer same issue?

**Comment by hidekazuna** [comment]
@jichenjc  I am creating cluster every time creating new PR, but I have never encountered the issue. Could you show us commit ID?

**Comment by jichenjc** [comment]
@hidekazuna the latest one , it works for last week but yesterday suddenly have issue..

**Comment by hidekazuna** [comment]
@jichenjc using cluster-api v0.3.7?

**Comment by jichenjc** [comment]
my cluster is using  `image: us.gcr.io/k8s-artifacts-prod/cluster-api/cluster-api-controller:v0.3.7-rc.1`
but I don't have a good one to compare..

**Comment by hidekazuna** [comment]
I will try v0.3.7.

**Comment by jichenjc** [comment]
ok, I tried again and seems it works ..not sure what happened
I need more test to see what happened
