### ISSUE TITLE
Wrong parameter for a user provided network crashes the controller

### ISSUE THREAD

**Issue by pierrecregut** [kubernetes-sigs/cluster-api-provider-openstack#590]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Tried to specify in openstack cluster a network (which was wrong). Not only the deployment failed but the container crashed.

**What did you expect to happen:**
Just a failed deployment.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
In openstackcluster_controller line 300, an or (||) was probably intended on the check of err and the size of the network list.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
@pierrecregut do you have any logs can be shared?

**Comment by hidekazuna** [comment]
@pierrecregut @jichenjc 

I investigated from
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/controllers/openstackcluster_controller.go#L300

If wrong network name was given,

```go
if err != nil && len(networkList) == 0 {
    return errors.Errorf("failed to find network: %v", err)
}
```
did not return error, so reached

```go
openStackCluster.Status.Network = &infrav1.Network{
    ID:   networkList[0].ID,
    Name: networkList[0].Name,
}
```

networkList[0].ID can not be found and crashed.

**Comment by pierrecregut** [comment]
Yes exactly, sorry if it was not clear.

**Comment by hidekazuna** [comment]
> Yes exactly, sorry if it was not clear.

@pierrecregut Don't worry. Thanks for raising the issue!

**Comment by sbueringer** [comment]
Yup this should be fixed. I would propose checking it separately with two if conditions because in case of `err != nil` we want to append the error in case of `len(networkList) == 0` there is no error to append

**Comment by pramchan** [comment]
I edited and split the if len zero and err separate with two ifs to avoid the cash as asked. Is this good enough to create pull request or do i need to uses existing pull#590 to submit the patch?
               if len(networkList) == 0 {
			return errors.Errorf("failed to find any network: %v", err)
		}
		if err != nil {
			return errors.Errorf("failed to find network: %v", err)
		}
		if len(networkList) > 1 {
			return errors.Errorf("failed to find only one network (result: %v): %v", networkList, err)
		}
		openStackCluster.Status.Network = &infrav1.Network{
			ID:   networkList[0].ID,
			Name: networkList[0].Name,
		}

**Comment by hidekazuna** [comment]
@pramchan Please submit the patch as PR so that we can review.

**Comment by pramchan** [comment]
I though I did but seems something is wrong, it did not connect to right PR590 some mistake - may be need to resubmit
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/commit/a3188f458a3d6b9f32dfeb85703b780ddce2f

**Comment by pramchan** [comment]
hidekazuna - I got stuck due to some system issues and resubmitted back to my personal github after stashing and updated the fork I had in my repo  https://github.com/pramchan/cluster-api-provider-openstack. Question I have is do i need to create new pr# to submit this back?
