### ISSUE TITLE
Suggest updating the README to point to cluster-api channel on Slack and the sig-cluster-lifecycle mailing list

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-openstack#6]
- [#cluster-api on Kubernetes Slack](http://slack.k8s.io/messages/cluster-api)
- [SIG-Cluster-Lifecycle Mailing List](https://groups.google.com/forum/#!forum/kubernetes-sig-cluster-lifecycle)

**Comment by Lion-Wei** [comment]
Will do, thanks.
