### ISSUE TITLE
E2E test should be run as non admin user

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#603]
/kind bug

**What steps did you take and what happened:**

Currently E2E test run as admin user.
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/.zuul/playbooks/run.yaml#L56-L73

**What did you expect to happen:**

E2E test should be run as non admin user. Our use case is non admin user creates kubernetes cluster using CAPO.

**Anything else you would like to add:**

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
yeah, this is valid test requirement.. and the potential policy failure might help us in finding what's allowed  and what's not

**Comment by hidekazuna** [comment]
This is fixed by #606 

/close
