### ISSUE TITLE
Update OpenStack version using e2e test to Ussuri

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#604]
/kind feature

**Describe the solution you'd like**

Update OpenStack version from Train to Ussuri.

**Anything else you would like to add:**

Currently E2E test runs on OpenStack train.
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/.zuul/playbooks/run.yaml#L28

The Next version Ussuri has been [released](https://www.openstack.org/software/ussuri/) on May 13, 2020.

**Comment by jichenjc** [comment]
good point, maybe a quick update to make it U and check result?

**Comment by hidekazuna** [comment]
Fixed by #605
