### ISSUE TITLE
Floating IP remains after deleting cluster

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#621]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Automatically created floating IP remains after deleting cluster.

**What did you expect to happen:**

I expect floating IP to be deleted when I do not specify floating IP for endpoint explicitly.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
yeah .. this is reasonable thing to do ,we have several cases:
maybe check `openStackCluster.Spec.APIServerLoadBalancerFloatingIP` or `openStackCluster.Spec.ControlPlaneEndpoint.Host` is empty or not then we can go ahead and delete the created FP?

**Comment by hidekazuna** [comment]
`openStackCluster.Spec.ControlPlaneEndpoint.Host` must be set for creating cluster, even if we do not specify floating IP. This is requirement from CAPI.
We need to create new status variable to delete floating IP if when only specified floating IP.

**Comment by jichenjc** [comment]
> `openStackCluster.Spec.ControlPlaneEndpoint.Host` must be set for creating cluster, even if we do not specify floating IP. This is requirement from CAPI.
> We need to create new status variable to delete floating IP if when only specified floating IP.

yes, agree, we need create a variable..

**Comment by hidekazuna** [comment]
I was wrong..
When HA, use `openStackCluster.Spec.APIServerLoadBalancerFloatingIP`. so `openStackCluster.Spec.ControlPlaneEndpoint.Host` is set. Check `openStackCluster.Spec.APIServerLoadBalancerFloatingIP` is empty and delete floating IP.

When Non HA, use `openStackCluster.Spec.ControlPlaneEndpoint.Host` directly. we can not recognize floating IP is given not not.
