### ISSUE TITLE
Target cluster deployment fails with leader election error

### ISSUE THREAD

**Issue by eratnch** [kubernetes-sigs/cluster-api-provider-openstack#622]
/kind bug

**What steps did you take and what happened:**
A target cluster of 1 master and 1 worker node is being deployed on devstack.
Following error appears in capo-controller-manager logs

```
I0827 15:13:29.280210       1 securitygroups.go:54] controllers/OpenStackCluster "msg"="Reconciling security groups" "namespace"="default" "openStackCluster"="ostgt" "cluster"="default-ostgt"
I0827 15:13:47.108301       1 leaderelection.go:288] failed to renew lease capo-system/controller-leader-election-capo: failed to tryAcquireOrRenew context deadline exceeded
E0827 15:13:47.108395       1 main.go:237] setup "msg"="problem running manager" "error"="leader election lost"

```
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

The target cluster is deployed with 2 machines.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.8
- Minikube/KIND version: kind v0.8.1 go1.14.2 linux/amd64
- Kubernetes version: (use `kubectl version`): 1.17.3
- OS (e.g. from `/etc/os-release`): 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by jichenjc** [comment]
I created a cluster yesterday and no problem encoutnered

do you remember any actions or any special setting you made?
and if you try again , what happen?

**Comment by eratnch** [comment]
@jichenjc , this issue is intermittent in nature, but I have seen it occur multiple times. It happens frequently if a cluster creation fails for any reason the first time and if I try to run the same steps again in succession. Yesterday I ran into this issue and tried 3-4 times again and again but no luck. Then I changed the  control plane machine replica count in the target manifest, ran the exact same steps again and this time it worked.

I am not sure if capo is somehow getting in a corrupt state if you try to run multiple times. 
I'll keep an eye on this and add more information.

**Comment by jichenjc** [comment]
ok, so you are saying when capo first occur error, then next try will encounter same error? 
as change replica count seems not reasonable to impact the functionalities

**Comment by eratnch** [comment]
Yes, that's what happened in my case. I have seen this error happening before also but was not able to pinpoint how to reproduce. What I described above is the exact steps I did and ran into the error.
I am not sure what could be the root cause of the leader election loss issue. i would think when there are > 1 masters then capo is trying to select a leader as master.  But I have been successfully deploying clusters with 1 master node.

**Comment by jichenjc** [comment]
yes, that's reasonable , I have multiple masters privisoined before ...
have you deploy multiple masters before successfully?

**Comment by eratnch** [comment]
Yes I have deployed clusters with > 1 master node before.

**Comment by eratnch** [comment]
Ran into the same issue again today. Changing the replica count didn't make any difference this time.

Here is the complete log https://pastebin.com/4gb56jeR

**Comment by jichenjc** [comment]
@eratnch other projects seems have similar problems 
https://github.com/kubedb/project/issues/581
https://github.com/kubernetes/kubernetes/issues/76069

they mentioned it's related to network instablity and ask for increase the timeout etc..
how about disable leader election? not sure that will be helpful here as I didn't do it myself before

**Comment by eratnch** [comment]
@jichenjc  where should I add the following lines in the capo-manifest.yaml?
```
leaderElection:
          leaseDurationSeconds: 15
          renewDeadlineSeconds: 10
          retryPeriodSeconds: 2
```
Would it be under OpenstackCluster or KubeadmControlPlane or any other section? Can you please provide a sample? 

Thanks.

**Comment by jichenjc** [comment]
sorry, I don't this as well , if we have to , I think best way is to consider 
disable leader election to give a try or use something like --leader-election-timeout/renew then to configure it 
```
config/manager/manager.yaml:        - --enable-leader-election
config/manager/manager_auth_proxy_patch.yaml:        - "--enable-leader-election"
```


https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/leaderelection.go
defined how to do the configuration 
but currently capo is using 
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/leaderelection/leader_election.go

and this file seems don't honor the options in client-go... I need check more and maybe 
we can ask in controller-runtime repo as well

**Comment by sumitKash** [comment]
This has affected me as well...
I have created kubernetes cluster v1.18.8.... I have Kubeapi loadbalancer in between so any request meant for kube-api will be loadbalanced through Kube-api Loadbalancer.
The problem is, the Kube-schedular and Kube-controller restarts after 6-7 days, weired right?... I see below error in logs:

Kube-Controller:
2020-09-13T07:32:42.371644764Z stderr F E0913 07:32:42.371112       1 leaderelection.go:320] error retrieving resource lock kube-system/kube-controller-manager: Get https://kubelb:8443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2020-09-13T07:32:42.371813766Z stderr F I0913 07:32:42.371235       1 leaderelection.go:277] failed to renew lease kube-system/kube-controller-manager: timed out waiting for the condition
2020-09-13T07:32:42.371903367Z stderr F F0913 07:32:42.371370       1 controllermanager.go:279] leaderelection lost

**Comment by jichenjc** [comment]
yes, this is weird and listed above in some issues I found in other projects

I only saw it's related to api handling and timing issue etc.. didn't find a way to go deeper further
