### ISSUE TITLE
Worker node receives incorrect port for kube-apiserver on Master node for kubeadm join

### ISSUE THREAD

**Issue by chaosaffe** [kubernetes-sigs/cluster-api-provider-openstack#64]
The `kubeadm join` on worker nodes is provided the wrong port (`443`) for the `kube-apiserver` on the master node, i.e.
```
kubeadm join --token <redacted> 10.10.10.1:443 --ignore-preflight-errors=all --discovery-token-unsafe-skip-ca-verification
[preflight] running pre-flight checks
[discovery] Trying to connect to API Server "10.10.10.1:443"
[discovery] Created cluster-info discovery client, requesting info from "https://10.10.10.1:443"
```

The configured port for the `kube-apiserver` is `6443`, resulting in worker nodes being unable to join the cluster.

**Comment by chaosaffe** [comment]
It appears that the [UpdateClusterObjectEndpoint](https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go) func uses a [const](https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go#L40) to set the port, disregarding any `kube-apiserver` configuration

**Comment by chaosaffe** [comment]
Not yet, I haven't had free cycles to continue investigating this

**Comment by flaper87** [comment]
I've created an issue on cluster-api: https://github.com/kubernetes-sigs/cluster-api/issues/559 We can workaround this issue if we just use 443 for now. Trying to figure out a good way to solve this
