### ISSUE TITLE
Bastion remains once created

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#647]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

- Deployed a cluster with bastion by the manifest `bastion.enabled: true`
- Applied the manifest  `bastion.enabled: false`
- Bastion remains

**What did you expect to happen:**

I expected bastion is deleted by  `bastion.enabled: false`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): 89b3519fbe56128d0f056323d3027ec52f53e48d
- Cluster-API version: 0.3.9
- Minikube/KIND version: 0.7.0
- Kubernetes version (use `kubectl version`): 1.18.9
- OS (e.g. from `/etc/os-release`):

**Comment by MPV** [comment]
I noticed this yesterday also. 
Any ideas on solutions? 😍

**Comment by jichenjc** [comment]
guess 2 logics we need support? delete the openstackcluster need delete the bastion and then if update from bastion:true to false should do same job?

**Comment by hidekazuna** [comment]
@MPV I will copy CAPA code here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/services/ec2/bastion.go#L48-L58

**Comment by sbueringer** [comment]
Sounds reasonable to me.
