### ISSUE TITLE
Add support for Tilt based dev 

### ISSUE THREAD

**Issue by eratnch** [kubernetes-sigs/cluster-api-provider-openstack#649]
/kind feature

Capo should provide a Tiltfile and tilt-provider.json file to make use of Tilt based dev and test.
Providers such as Capz, Capa support this feature. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jichenjc** [comment]
I remember this used to be supported (Tilt), but tilt-provider.json is brand new to me..
and yes, we need check capo doc..

**Comment by prankul88** [comment]
@eratnch Will work this.

**Comment by prankul88** [comment]
@eratnch Seeing other providers implementation I have a few pointers:

- Providers like Azure, metal3 have separate TiltFile conf in their repo and use `tilt up` command  from provider's repo to spin up the dev setup through that. That way they have "Tilt for dev in CAPO/CAPZ/Metal3"

- CAPI already has a TiltFile and we just need to integrate with it (adding tilt-provider.json). Providers like CAPA and CAPG follow this. In this way, they have "Tilt for dev in both CAPA/CAPG and CAPI"

Wanted to take opinion for the approach we must follow. I have created a PR for now that enables Tilt support by integrating with CAPI.

**Comment by prankul88** [comment]
^^ /cc @jichenjc

**Comment by eratnch** [comment]
Thanks @prankul88.
Both the approaches you mentioned seem fine to me.

**Comment by prankul88** [comment]
@eratnch Great. For now lets go by integrating with CAPI
