### ISSUE TITLE
Reference latest version of CAPO in Makefile

### ISSUE THREAD

**Issue by prankul88** [kubernetes-sigs/cluster-api-provider-openstack#651]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/Makefile#L319
`make create-cluster` command refer to old CAPO version.

**What did you expect to happen:**
This should be changed to v0.3.1

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by hidekazuna** [comment]
The directory name must follow the semantic versioning: vX.Y.Z.
We are developing master branch so it is OK the name is v9.9.9 for example.

**Comment by prankul88** [comment]
@hidekazuna Sorry I must have missed the conversation.



> The directory name must follow the semantic versioning: vX.Y.Z.
> We are developing master branch so it is OK the name is v9.9.9 for example.

Ohh okay, got your point. I just saw the PR for the same got merged. Is there something that needs to be changed now?
Thanks for helping

**Comment by hidekazuna** [comment]
@prankul88 It is ok to be merged 😄  I do not know the best.
