### ISSUE TITLE
0.3.2 release being blocked 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#661]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I created release 0.3.2 
but failed to start due to 
`us.gcr.io/k8s-artifacts-prod/capi-openstack/capi-openstack-controller:v0.3.2: not found`

not sure how to push images to the location (I am not authorized)
do you happen to know ? @hidekazuna @sbueringer ?

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by hidekazuna** [comment]
@jichenjc Sorry I do not know.

**Comment by jichenjc** [comment]
ok, I'll see what I can do ..

**Comment by hidekazuna** [comment]
@jichenjc I think you have to do the image promotion (PR creation) process defined [here](https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io#image-promoter).

**Comment by jichenjc** [comment]
thanks :), I will check what I can do there ~

**Comment by jichenjc** [comment]
https://github.com/kubernetes/k8s.io/pull/1397

**Comment by sbueringer** [comment]
Sorry was away for a while here :)

@jichenjc did you figure it out, any open questions? It should all be documented here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/RELEASE.md

**Comment by jichenjc** [comment]
@sbueringer thanks :) I should search internal first about this ... 
seems the image is merged recently and let's see whether it works or not

**Comment by jichenjc** [comment]
```
# kind create cluster;clusterctl init --infrastructure=openstack
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Thanks for using kind! 😊
Fetching providers
Installing cert-manager
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v0.3.10" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v0.3.10" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v0.3.10" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-openstack" Version="v0.3.2" TargetNamespace="capo-system"

Your management cluster has been initialized successfully!

You can now create your first workload cluster by running the following:

  clusterctl config cluster [name] --kubernetes-version [version] | kubectl apply -f -

```

**Comment by jichenjc** [comment]
@sbueringer can you help to guide me why 
```
# docker pull us.gcr.io/k8s-artifacts-prod/capi-openstack/capi-openstack-controller:v0.3.2
Error response from daemon: manifest for us.gcr.io/k8s-artifacts-prod/capi-openstack/capi-openstack-controller:v0.3.2 not found: manifest unknown: Failed to fetch "v0.3.2" from request "/v2/k8s-artifacts-prod/capi-openstack/capi-openstack-controller/manifests/v0.3.2".
```

I think the image not uploaded successfully, the kubernetes/k8s.io#1397 merged and what's next I need to do to make a release (create the image ...) thanks

**Comment by jichenjc** [comment]
@sbueringer any guide and comments?

**Comment by hidekazuna** [comment]
@jichenjc I checked SHA digest value and have a question. Merged sha digest value in [images.yaml](https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/images/k8s-staging-capi-openstack/images.yaml#L7) is:

```
sha256:3e5906f953f4250534be17ea349401d6871d1db2f5f6df60bc219564eb1e73e5
```
but in my understanding, [The staging repository](https://console.cloud.google.com/gcr/images/k8s-staging-capi-openstack/GLOBAL/capi-openstack-controller@sha256:cfdd7a67771e7a3fd956205c3351ad116e912b47982a95902b120bba036d7775/details?tab=info) shows
```
sha256:cfdd7a67771e7a3fd956205c3351ad116e912b47982a95902b120bba036d7775 
```

**Comment by jichenjc** [comment]
ok, I don't know what wrong I did, let me update the sha and try again, thanks for point me that

**Comment by jichenjc** [comment]
```
# kubectl get deployment capo-controller-manager -n capo-system -o yaml | grep capi-openstack-controller
        image: us.gcr.io/k8s-artifacts-prod/capi-openstack/capi-openstack-controller:v0.3.2
```
