### ISSUE TITLE
Bastion is gone after cluster creation for a while

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#670]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
```
  bastion:
    enabled: true
    flavor: m1.tiny
    image: cirros-0.5.1-x86_64-disk
```

no BASTION showing after cluster creating for a while
```
# kubectl get openstackcluster
NAME               CLUSTER            READY   NETWORK                                SUBNET                                 BASTION
capi-openstack-3   capi-openstack-3   true    f18b19b9-0e8d-4b8f-893a-6b201ecd4302   62dd859a-685c-432b-b897-ddc19bdc24fc 
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by hidekazuna** [comment]
Bastion was shown in my environment. Was bastion shown just after the cluster was created?

**Comment by jichenjc** [comment]
yes, it show up but after a while it's gone
the  issue occurs on my v0.3.2 env

**Comment by hidekazuna** [comment]
Only bastion status was deleted or floating IP disassociated?
Anyway try latest code,please.

**Comment by jichenjc** [comment]
v0.3.2 is latest .. I will build a new image and try again

**Comment by jichenjc** [comment]
@hidekazuna I used latest and seems the result is same...

**Comment by hidekazuna** [comment]
@jichenjc Can you show me your manifest?
