### ISSUE TITLE
V0.3.2 Template missing clusterctl.cluster.x-k8s.io/move: "true" label

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#674]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

[released v0.3.2 cluster-template.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/download/v0.3.2/cluster-template.yaml) does not have `clusterctl.cluster.x-k8s.io/move: "true"` label.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

[v0.3.2 cluster-template.yaml in the repository](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/v0.3.2/templates/cluster-template.yaml) has the label.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.3.2
- Cluster-API version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
@hidekazuna master branch has those labels .. 
maybe you want to release v0.3.3?

**Comment by hidekazuna** [comment]
@jichenjc Yes, I want. Do you know the reason why this happened? We should avoid the same situation.

**Comment by jichenjc** [comment]
I guess I used wrong commit since this is the first time make release.. so let's create v0.3.3 and give a try

**Comment by sbueringer** [comment]
@jichenjc If I guess correctly you just uploaded the incorrect file? As the file on the release just does not match the one of the tag I would suggest just exchanging the file on the release (just delete and upload the right one)

**Comment by jichenjc** [comment]
@sbueringer thanks for pointing out :)

Just updated the release and please check whether it works for you @hidekazuna

**Comment by hidekazuna** [comment]
@jichenjc Honestly I expected new release includes #668 😅 . Deleting cluster cause the management cluster with floating IP not to be connected due to removing floating IP.

**Comment by jichenjc** [comment]
that's new stuffs.. we need a new release then (above action just update the template file which is wrong)

**Comment by jichenjc** [comment]
#678 created to track
