### ISSUE TITLE
Need logging policy

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#676]
/kind feature

**Describe the solution you'd like**

Some user feels "Creating Machine" log message is confusing #673 . But actually currently create or delete resource start message is not logged. such messages are recorded as event. We need consistent log message policy. 

**Anything else you would like to add:**

- Kubernetes [Logging Conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md)

**Comment by sbueringer** [comment]
I think it would probably also make sense to take a look at how other cluster api providers are doing this

**Comment by jichenjc** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/controllers/awsmachine_controller.go#L430


https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/controllers/awsmachine_controller.go#L601

I think we might follow their pattern

**Comment by hidekazuna** [comment]
> https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/controllers/awsmachine_controller.go#L601

This is just you wanted to avoid.
