### ISSUE TITLE
Create v0.3.3 release

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#678]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
on behalf of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/674

**Comment by hidekazuna** [comment]
@jichenjc Could you release using the pre-release option?

[Release document](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/RELEASE.md#process) says:
11. Publish release. Use the pre-release option for release candidate versions of Cluster API Provider OpenStack.

**Comment by sbueringer** [comment]
@hidekazuna @jichenjc That's meant to be used for releases like `v0.3.3-rc.0`. If you want to release a RC that's fine. I wouldn't use pre-release for `v0.3.3`

**Comment by hidekazuna** [comment]
@sbueringer OK, I understand.
@jichenjc Please release v0.3.3.

**Comment by hidekazuna** [comment]
@jichenjc I completely followed quick start guide and ended successfully. Deleting cluster is also fine.

/close
