### ISSUE TITLE
v0.3.2 release includes unnecessary archive file

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#684]
/kind bug

**What steps did you take and what happened:**

I found unnecessary release file. Please remove this file.
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/download/v0.3.2/cluster-api-provider-openstack.tgz

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
@hidekazuna I deleted the file

/close
