### ISSUE TITLE
v0.3.2 infrastructure-components.yaml is wrong

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#685]
/kind bug

**What steps did you take and what happened:**

- I created cluster using v0.3.2.
- I deleted cluster.
- Bastion node failed to be deleted.

**What did you expect to happen:**

Bastion node is deleted sucessfully.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Bastion status does not have id which is key for deleting bastion.
Root cause is v0.3.2 infrastructure-components.yaml is wrong. Bastion type should be Instance by #641 which should be included in v0.3.2, but actually it is Bastion in  v0.3.2 infrastructure-components.yaml.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.3.2
- Cluster-API version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
@hidekazuna is this issue still there? Or was it already fixed on master / v0.3.3?

**Comment by hidekazuna** [comment]
@sbueringer This is the issue of release v0.3.2 asset.

**Comment by sbueringer** [comment]
Yup, just thinking about how we can resolve this issue. 

It sounds like, e.g. a known issue in 0.3.2 which was then fixed in 0.3.3?

I don't really like patching an already released release artifact to fix a bug in 0.3.2

(I don't really know the details of this issue/bug)

**Comment by hidekazuna** [comment]
I will test v0.3.2 and v0.3.3 follows the steps in this issue, give me hours.

**Comment by sbueringer** [comment]
Yeah no problem, take your time ;)

**Comment by hidekazuna** [comment]
I tested whether bastion can be deleted or not by `clusterctl delete`

### v0.3.2

bastion can not be deleted. Cluster PHASE remains Deleting. I found the following error.

```
E0220 06:38:36.445666       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to delete bastion: resourceId should
be specified to  get detail" "controller"="openstackcluster" "name"="nonha" "namespace"="default"
```

### v0.3.3

bastion was deleted successfully.

### Note

Bastion deletion was fixed in #641 which includes API change before v0.3.2 release.
Actually v0.3.2 source code archive has this change, but infrastructure-components.yaml does not have the change. I wonder if we  released wrong infrastructure-components.yaml due to something like missing `make generate` to generate infrastructure-components.yaml.

**Comment by hidekazuna** [comment]
@jichenjc PTAL

**Comment by sbueringer** [comment]
@hidekazuna I think we should just add a note to the 0.3.2 release that there was an error in the release process 
and that the version 0.3.3 (or 0.3.4) should be used instead.
It already doesn't really look like the other releases: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.3.2

**Comment by hidekazuna** [comment]
@sbueringer I agree and really said so: https://kubernetes.slack.com/archives/CFKJB65G9/p1605924023022900

**Comment by jichenjc** [comment]
@hidekazuna as our latest 0.3.3 is good , I agree with you and @sbueringer that we only need doc somewhere 
about 0.3.2 and as people use latest one to test, it should be a minor problem now

**Comment by sbueringer** [comment]
Alright. I'll add a short note on the release page and close this issue
> https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.3.2

/close
