### ISSUE TITLE
PR: SecurityGroup on NeutronLoadbalancerPort

### ISSUE THREAD

**Issue by zoltan0907** [kubernetes-sigs/cluster-api-provider-openstack#699]
/kind feature

**Describe the solution you'd like**
As decribed in here https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/694 i would like make a pull request for that feature. Should i simply create a pull request to the master branch, and/or what are the requirements to make a pull request. 

Regards
Tino

**Comment by jichenjc** [comment]
you don't need create a new issue, just create a PR then link the PR to the issue should be good enough

**Comment by zoltan0907** [comment]
I made a pull request. I had to do this from my personal github-account and with our company-account which i used in #694
