### ISSUE TITLE
SecurityGroupInUse error

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#701]
/kind bug

**What steps did you take and what happened:**
- Try to create a cluster
- Creating a worker machine is in Provisioning phase for a long time due to Quota exceeded for cores
- Try to delete the cluster
- Failed to delete the cluster, continued to be Deleting phase
- Deleted the port created for the worker node manually
- Wait for deleting the cluster for minutes
- The cluster has been deleted successfully.

**What did you expect to happen:**

I expect the cluster can be deleted when the cluster failed to be created due to cores quota error.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): 0.3.3
- Cluster-API version: 0.3.11
- OpenStack version: Stein
- Minikube/KIND version: kind v0.7.0 go1.13.6 linux/amd64
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by jichenjc** [comment]
>>>Try to create a cluster
Failed to create a worker machine due to Quota exceeded for cores
Try to delete the cluster

just to clarify , so our expecation is when do the 'delete' action, the whole cluster should be deleted instead of pending and in deleting phase and manual actions should be avoided, correct?

**Comment by hidekazuna** [comment]
> > > > Try to create a cluster
> > > > Failed to create a worker machine due to Quota exceeded for cores
> > > > Try to delete the cluster
> 
> just to clarify , so our expecation is when do the 'delete' action, the whole cluster should be deleted instead of pending and in deleting phase and manual actions should be avoided, correct?

Yes, I want. Because explicitly I run clusterctl delete cluster mycluster.
