### ISSUE TITLE
env.rc fails with yq >= 4.0.0

### ISSUE THREAD

**Issue by alexpilotti** [kubernetes-sigs/cluster-api-provider-openstack#717]
/kind bug

**What steps did you take and what happened:**
_env.rc_ fails with versions of yq >= 4.0.0, which is what gets installed now on at least Ubuntu (_snap install yq_) and Macos (_brew install yq_).

```
Error: unknown command "r" for "yq"
Run 'yq --help' for usage.
```

The reason is that yq v4 breaks the CLI compatibility with v3, see: https://mikefarah.gitbook.io/yq/v/v4.x/upgrading-from-v3

Here's an example of the required change:

yq < 4.0.0 
`CAPO_USERNAME=$(echo "$CAPO_OPENSTACK_CLOUD_YAML_CONTENT" | yq r - clouds.${CAPO_CLOUD}.auth.username)
`
yq >= 4.0.0:
`CAPO_USERNAME=$(echo "$CAPO_OPENSTACK_CLOUD_YAML_CONTENT" | yq e .clouds.${CAPO_CLOUD}.auth.username) -
`

**What did you expect to happen:**

env.rc should work with the current version of yq. 

**Anything else you would like to add:**

Workaround:
```
GOPATH=$(pwd) GO111MODULE=on go get github.com/mikefarah/yq/v3
export PATH=$(pwd)/bin:$PATH
```
**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.3.11
- Cluster-API version: v0.3.11
- OpenStack version: Ussuri
- Minikube/KIND version: 0.9.0
- Kubernetes version (use `kubectl version`): v1.19.1
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS

**Comment by jichenjc** [comment]
I reproduced above issue, so we need fix it

**Comment by sbueringer** [comment]
@jichenjc I assume this should be fixed now as the PR was merged? https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/792

**Comment by sbueringer** [comment]
As the PR has been merged, it should be fixed now. Feel free to reopen if there are still issues.

/close
