### ISSUE TITLE
Deleting router fails if the router interface is not present

### ISSUE THREAD

**Issue by alexpilotti** [kubernetes-sigs/cluster-api-provider-openstack#718]
/kind bug

**What steps did you take and what happened:**
`
kubectl delete cluster capi-quickstart
` gets stuck on a loop while trying to delete the router if the interface was already deleted:  

`E1231 15:04:46.539212       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to delete router: unable to remove router interface: Resource not found" "controller"="openstackcluster" "name"="capi-quickstart" "namespace"="default"
`

**What did you expect to happen:**

The provider should check if the interface exists before calling _routers.RemoveInterface_ or handle the error in case it doesn't exist, and still delete the router. 

**Anything else you would like to add:**

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.3.11
- Cluster-API version: v0.3.11
- OpenStack version: Ussuri
- Minikube/KIND version: 0.9.0
- Kubernetes version (use `kubectl version`): v1.19.1
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS

**Comment by jichenjc** [comment]
yes, this is something we tried to fix before and guess this one is not covered at that time..
