### ISSUE TITLE
expose CLUSTER_API_OPENSTACK_INSTANCE_CREATE_TIMEOUT`

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#721]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

in slack channel we are asked whether CLUSTER_API_OPENSTACK_INSTANCE_CREATE_TIMEOUT` is something we can expose 

maybe put into template so that it will be easier to consume ..

**Comment by sbueringer** [comment]
@jichenjc I wouldn't add this an additional parameter to the template. 

We got rid of a lot of configuration variables in the templates over time and I think one idea of the templates is to be able to easily use them and you only have to set a few environment variables to do it. So I think this timeout is by for not important enough to qualify as "one of the 10 most important configuration options" we absolutely need in the templates. 

Our current variables are: (I didn't count the ones that clusterctl has standardized)
* OPENSTACK_DNS_NAMESERVERS
* OPENSTACK_CLOUD
* OPENSTACK_CLOUD_YAML_B64
* OPENSTACK_CLOUD_CACERT_B64
* OPENSTACK_CLOUD_PROVIDER_CONF_B64
* OPENSTACK_FAILURE_DOMAIN
* OPENSTACK_CONTROL_PLANE_MACHINE_FLAVOR
* OPENSTACK_NODE_MACHINE_FLAVOR
* OPENSTACK_IMAGE_NAME
* OPENSTACK_SSH_KEY_NAME

**Comment by sbueringer** [comment]
@jichenjc The way it currently works, I wouldn't want to implement this feature (and close the issue), wdyt @jichenjc ?

**Comment by jichenjc** [comment]
yes, let's close this
