### ISSUE TITLE
Create floating IP for compute nodes 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#722]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

this is asked in slack channel, seems a reasonable use case

**Comment by sbueringer** [comment]
I'm wondering what the use case behind this is. Usually, services in a Kubernetes cluster get exposed via a service of type loadbalancer. It seems a bit excessive to give every single compute node its own floating ip.

**Comment by jichenjc** [comment]
I don't remember who asked this but it's asked there..

the use case is for debug and access compute node for update .. with bastion introduced, seems this is not needed anymore
