### ISSUE TITLE
Update kube-rbac-proxy to v0.8.0

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#728]
/kind feature

**Describe the solution you'd like**

Current kube-rbac-proxy version is v0.4.1. But It seems better to update kube-rbac-proxy to v0.8.0.

**Anything else you would like to add:**

Cluster API uses v0.8.0.
https://github.com/kubernetes-sigs/cluster-api/blob/master/config/manager/manager_auth_proxy_patch.yaml

**Comment by jichenjc** [comment]
@hidekazuna I think we can close this as we have a v1alpha4 PR already

**Comment by hidekazuna** [comment]
@jichenjc I will close this issue if #748 is merged.
