### ISSUE TITLE
v0.3.4 release

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#730]
Hi,

what do you think about releasing a v0.3.4 version with the latest fixes?

@hidekazuna @jichenjc

**Comment by hidekazuna** [comment]
@sbueringer It is good release cadence to me. #732 and #733 are on the way to the v0.3.4.

**Comment by sbueringer** [comment]
@hidekazuna Sounds good to me

**Comment by sbueringer** [comment]
@jichenjc can you then give feedback here (regarding: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/736#issuecomment-781024027)

**Comment by jichenjc** [comment]
@sbueringer I am not sure when I can verify ..maybe early next week,
we can go ahead and create 0.3.4 if you think it's ok

**Comment by sbueringer** [comment]
@jichenjc Early next week is absolutely fine for me. If you don't have the time until then, I will test it locally in our env, no problem.

**Comment by jichenjc** [comment]
@sbueringer please go ahead the release of 0.3.4 w/ or w/o the verfication, my devstack env is broken and 
not sure I can get it back soon

**Comment by sbueringer** [comment]
I got it working here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/746
and in my local environment. I would continue/start with the release process. I'll try to talk to the main 
CAPI project, maybe we're able to improve the CI situation (which is a disaster :/)

**Comment by sbueringer** [comment]
@jichenjc image promotion PR is open here: https://github.com/kubernetes/k8s.io/pull/1687

**Comment by jichenjc** [comment]
@sbueringer the promotion PR is merged, so I think we are good now?

**Comment by sbueringer** [comment]
@jichenjc Yes, thank you. I published the release: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.3.4

/close
