### ISSUE TITLE
Deployment fails behind proxy environment

### ISSUE THREAD

**Issue by nakkoh** [kubernetes-sigs/cluster-api-provider-openstack#734]
/kind bug

I failed k8s deployment behind proxy environment.
How can I deploy clusters behind proxy environment?

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Deploy k8s cluster on OpenStack with [Quick Start](https://cluster-api.sigs.k8s.io/user/quick-start.html).

**What did you expect to happen:**

The Cluster status is "Provisioned".

```
$ kubectl get cluster --all-namespaces
NAMESPACE   NAME              PHASE
default     capi-quickstart   Provisioned
$ kubectl get kubeadmcontrolplane --all-namespaces
NAMESPACE   NAME                            INITIALIZED   API SERVER AVAILABLE   VERSION   REPLICAS   READY   UPDATED   UNAVAILABLE
default     capi-quickstart-control-plane                                        v1.18.5   1                  1         1
```

But the worker node status is "Pending".

```
$ k get machine
NAME                                    PROVIDERID                                         PHASE          VERSION
capi-quickstart-control-plane-fc2mc     openstack://205d5bf5-3b7a-4bff-90a6-deead7017385   Provisioning   v1.18.5
capi-quickstart-md-0-6fbbc8486f-8m4bx                                                      Pending        v1.18.5
capi-quickstart-md-0-6fbbc8486f-cg9np                                                      Pending        v1.18.5
capi-quickstart-md-0-6fbbc8486f-j7mcm                                                      Pending        v1.18.5
```

On the control plane node, the containerd failed pulling images.

```
● containerd.service - containerd container runtime
     Loaded: loaded (/etc/systemd/system/containerd.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/containerd.service.d
             └─boot-order.conf, max-tasks.conf, memory-pressure.conf
     Active: active (running) since Wed 2021-02-03 01:36:51 UTC; 7h ago
       Docs: https://containerd.io
    Process: 494 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
   Main PID: 510 (containerd)
      Tasks: 11
     Memory: 64.4M
     CGroup: /system.slice/containerd.service
             └─510 /usr/local/bin/containerd

Feb 03 01:42:36 capi-quickstart-control-plane-4wrwr containerd[510]: time="2021-02-03T01:42:36.950095844Z" level=info msg="PullImage \"k8s.gcr.io/kube-proxy:v1.18.5\""
Feb 03 01:42:56 capi-quickstart-control-plane-4wrwr containerd[510]: time="2021-02-03T01:42:56.981426777Z" level=error msg="PullImage \"k8s.gcr.io/kube-proxy:v1.18.5\" failed" error="failed to pull and unpack image \"k8s.gcr.io/kube-proxy:v1.18.5\": failed to resolve reference \"k8s.gcr.io/kube-proxy:v1.18.5\": failed to do request: Head \"https://k8s.gcr.io/v2/kube-proxy/manifests/v1.18.5\": dial tcp: lookup k8s.gcr.io: Temporary failure in name resolution"

--- snip ---
```

After I set proxy settings of containerd , containerd succeeded in pulling images.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): `v0.3.3`
- Cluster-API version: `v0.3.13`
- OpenStack version: `Queens`
- Minikube/KIND version: `kind v0.9.0 go1.15.2 linux/amd64`
- Kubernetes version (use `kubectl version`): `v1.18.5`
- OS (e.g. from `/etc/os-release`): 

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by hidekazuna** [comment]
Please try setting `http_proxy` and `https_proxy` in images/capi/packer/config/common.json and re-build your image for CAPO.
https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/packer/config/common.json#L6-L7

**Comment by nakkoh** [comment]
@hidekazuna Thank you. I can configure proxy settings with your method.
But users must create QCOW2 images each proxy settings.
Is it possible to configure http(s) proxy settings dynamically?
Can I configure http(s) proxy using userdata & cloud-init?

**Comment by jichenjc** [comment]
https://cloudinit.readthedocs.io/en/latest/topics/examples.html is the guide of cloud-init configuration on proxy..

I think mostly it's out of CAPI scope .. not sure worthy a doc

**Comment by nakkoh** [comment]
OK. Thanks.
I close the issue.
