### ISSUE TITLE
Can not delete cluster due to SecurityGroupInUse

### ISSUE THREAD

**Issue by nakkoh** [kubernetes-sigs/cluster-api-provider-openstack#741]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

1. Create a workload cluster
2. Delete the workload cluster

**What did you expect to happen:**

Deleting the cluster is not completed.
OpenStack instances is deleted.
But the following resources are not deleted.

 * network
 * security groups

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

A cause of the trouble is failure of security group deletion.
See the following logs:

```
$ k -n capo-system logs capo-controller-manager-7595db778f-9rl8n manager

--- snip ---

E0215 03:34:29.362070       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to delete security group: Expected HTTP response code [] when accessing [DELETE https://172.16.71.80:9696/v2.0/security-groups/b9d2ad4d-dfc3-4f27-8a33-7bbba21b3cb3], but got 409 instead\n{\"NeutronError\": {\"message\": \"Security Group b9d2ad4d-dfc3-4f27-8a33-7bbba21b3cb3 in use.\", \"type\": \"SecurityGroupInUse\", \"detail\": \"\"}}" "controller"="openstackcluster" "name"="capi-quickstart" "namespace"="default"
```

Deleting the security group for worker nodes was failed.
The security group was applied to ports.
So the ports must be deleted before deleting the security groups.

Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): `v0.3.3`
- Cluster-API version: `v0.3.13`
- OpenStack version: `Queens`
- Minikube/KIND version: `kind v0.9.0 go1.15.2 linux/amd64`
- Kubernetes version (use `kubectl version`): `v1.18.15`
- OS (e.g. from `/etc/os-release`): 

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by hidekazuna** [comment]
Did you create workload cluster successfully? If not, check out #701 , please.

**Comment by nakkoh** [comment]
@hidekazuna Yes. I succeeded.

**Comment by nakkoh** [comment]
I tried deleting cluster again and the operation succeeded.
So I close the issue.
I'm sorry for upsetting you.

**Comment by jichenjc** [comment]
I think it might be neutron port and neutron security rules/groups has dependency
What command you used? @nakkoh , I assume the first delete removed some rules and next 
it will delete the groups? I think worthy another look as 2nd try success doesn't mean it's user's fault

**Comment by nakkoh** [comment]
Yes. I said about neutron port.
I deleted the ports applied the security group for worker nodes using `openstack port delete <port-id>`.
Security group for control plane was deleted ithout problems.

**Comment by jichenjc** [comment]
so you are saying `openstack port delete <port-id>` is manually executed after your first failure?
and after the command execution then 2nd try succeed?

**Comment by nakkoh** [comment]
Yes. I manually deleted the ports after your first failure.
After port deletion, the security group was automatically deleted.
I didn't have to execute `cluster delete` command again.

**Comment by sbueringer** [comment]
You probably don't have to re-execute the delete command because the first time you ran it he deletionTimestamp was set. This means that the cluster is in `Terminating` so the capo controller should retry the cluster deletion until it works. 

So when you fix the blocking issue in the meantime it's expected that the CAPO controller will succeed on the next retry.

**Comment by sbueringer** [comment]
@nakkoh I hit the same issue when implementing the e2e tests. I"ll fix it in: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/798

(My issue was that after the server were deleted some ports were left. I'll add a port cleanup before the sec group deletion)

**Comment by sbueringer** [comment]
To be precise here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/798#discussion_r602041457

Also this seems to be a duplicate of: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/723
