### ISSUE TITLE
v0.4.0 (v1alpha4)

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#745]
/kind feature

v1alpha4 implementation is on the main branch now. This issue will provide an overview of open tasks until the v1alpha4 release:
* [x] Implement cluster infra contract change externally managed: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/859
* [x] we might have to make some changes to the way we retrieve the cloud secret: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/920
* [x] create the v0.4.0 release

Postponed to v0.5+:
* LB provider implementation https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/839

**Comment by sbueringer** [comment]
@jichenjc @hidekazuna 
If you want and have some time. The v1alpha4 PR is ready for review: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/748

I'm still fighting a bit with OpenLab but I already had green conformance test and only had a minor issue left regarding cluster delete. But now it fails, imho because of random reboots of OpenLab servers. But I think fixing those issues (and probably just retrying a lot) won't lead to a lot of changes on the PR.

**Comment by sbueringer** [comment]
I would keep this issue for now to track further work regarding v1alpha4. Afaik the plan is to release cluster-api v1alpha4 in a few weeks.

**Comment by sbueringer** [comment]
Current plan is to release CAPI v1alpha4 in June. I keep this issue for an overview over ongoing implementations for v1alpha4. Currently, there is nothing to do.

**Comment by sbueringer** [comment]
As writte in [Slack](https://kubernetes.slack.com/archives/CFKJB65G9/p1625027460065700). We will probably release next week.

**Comment by hidekazuna** [comment]
Since CAPI v0.4.0 has been released, does not include https://github.com/kubernetes-sigs/cluster-api/pull/4514/, I think we can release v0.4.0 does not care https://github.com/kubernetes-sigs/cluster-api/pull/4514/.

**Comment by jichenjc** [comment]
> 
> 
> Since CAPI v0.4.0 has been released, does not include [kubernetes-sigs/cluster-api#4514](https://github.com/kubernetes-sigs/cluster-api/pull/4514), I think we can release v0.4.0 does not care [kubernetes-sigs/cluster-api#4514](https://github.com/kubernetes-sigs/cluster-api/pull/4514).

is it mandatory? If it's an enhancement we can always have 0.4.1 + ?

**Comment by sbueringer** [comment]
If we got the code ready I would really prefer merging it before. Afaik it's absolutely intended to be binding for v1alpha4. Otherwise imho they would have to wait probably until v1alpha5/v1beta1 with a change like this.

And I would much rather imnplement this in CAPO v0.4.0 then have a breaking change in v0.4.1

**Comment by jichenjc** [comment]
> 
> 
> If we got the code ready I would really prefer merging it before. Afaik it's absolutely intended to be binding for v1alpha4. Otherwise imho they would have to wait probably until v1alpha5/v1beta1 with a change like this.
> 
> And I would much rather imnplement this in CAPO v0.4.0 then have a breaking change in v0.4.1

not realize it's a breaking change ,if it is, then yes, definitely need wait

**Comment by sbueringer** [comment]
@jichenjc I think it's a breaking change because we change fields in the InfraCluster CRD. It's somewhat mitigated between v0.3.0 and v0.4.0 with the conversion. But I don't want to implement a conversion webhook for v0.4.0 to v0.4.1 (and I don't know if it's possible :)).

**Comment by hidekazuna** [comment]
We are now beta mode then we wait for the following PRs?

- #937 for following  kubernetes-sigs/cluster-api#4514
- #934 
- #921 
 
/cc @Xenwar @iamemilio @tobiasgiese

**Comment by tobiasgiese** [comment]
@hidekazuna I will push the last commits of my PR in a few seconds and remove the WIP label. Then it should be ready to merge the next days.

**Comment by tobiasgiese** [comment]
I created an issue regarding the readme.
We should update it before we‘re releasing to have the correct readme in the release archive.
WDYT?

**Comment by hidekazuna** [comment]
> 
> 
> We are now beta mode then we wait for the following PRs?
> 
>     * [✨ Add conversion for SecretReference to string #937](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/937) for following  [Provide more prescriptive guidance on multi-tenancy cluster-api#4514](https://github.com/kubernetes-sigs/cluster-api/pull/4514)
> 
>     * [✨ Allow Trunk configuration at a Port level #934](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/934)
> 
>     * [Apply Port Security as an Update to Ports #921](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/921)
> 
> 
> /cc @Xenwar @iamemilio @tobiasgiese

We've decided not to wait for #934 and #921. https://kubernetes.slack.com/archives/CFKJB65G9/p1626244978144500

**Comment by tobiasgiese** [comment]
Further, the last PRs for the release v0.4.0 are merged

- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/933
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/937
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/944
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/945

So we are good to release

**Comment by sbueringer** [comment]
All done

/close
