### ISSUE TITLE
Support rootVolume for bastion

### ISSUE THREAD

**Issue by MPV** [kubernetes-sigs/cluster-api-provider-openstack#752]
/kind feature

**Describe the solution you'd like**
Today it's possible to configure `rootVolume` for machines (via `OpenStackMachineTemplate`), but we'd like to be able to do the same for the **bastion** as well.

**Anything else you would like to add:**

i.e. the equivalent of this:

>For example in OpenStackMachineTemplate set spec.rootVolume.diskSize to something greater than 0 means boot from volume.
>
>```
>apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
>kind: OpenStackMachineTemplate
>metadata:
>  name: <cluster-name>-controlplane
>  namespace: <cluster-name>
>spec:
>...
>  rootVolume:
>    diskSize: <image size>
>    sourceType: "image"
>    SourceUUID: <image id>
>...
>```
>
>From: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/docs/configuration.md#boot-from-volume

It would alleviate this error we're currently getting:

`controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile bastion: create new server err: error creating Openstack instance: Request forbidden: [POST https://compute-region1.our-provider.cloud:8774/v2.1/servers], error message: {\"forbidden\": {\"code\": 403, \"message\": \"Only volume-backed servers are allowed for flavors with zero disk.\"}}" "controller"="openstackcluster" "name"="prod-1-os-cluster-1" "namespace"="prod-1"`

**Comment by jichenjc** [comment]
@MPV thanks for report this , yes this is a feature gap, @hidekazuna as you created the bastion, do you want to add this ? Thanks

**Comment by hidekazuna** [comment]
> @MPV thanks for report this , yes this is a feature gap, @hidekazuna as you created the bastion, do you want to add this ? Thanks

I do not need this feature personally, but it is OK to be add.

**Comment by jichenjc** [comment]
@hidekazuna I gave another thought here

can we reconsider your bastion definition to 
```

type Instance struct {
       ......
}

// Bastion represents basic information about the bastion node
type Bastion struct {
        //+optional
        Enabled bool `json:"enabled"`

        Instance  Instance ·json:"enabled"`
}
```
so that we will inherit all fields from Instance so that we can specify and utilize it?

**Comment by jichenjc** [comment]
if so, I can update my exisitng PR to this way ...

**Comment by jichenjc** [comment]
code merged, please check with latest image
