### ISSUE TITLE
Support failureDomain (availability zone) for bastion

### ISSUE THREAD

**Issue by MPV** [kubernetes-sigs/cluster-api-provider-openstack#753]
/kind feature

**Describe the solution you'd like**

Today it's possible to set `failureDomain` on OpenStack machines (via `MachineDeployment`).

We'd like to be able to set this for the **bastion** too.

**Comment by MPV** [comment]
@hidekazuna as you created the bastion, what are your thoughts on this?

**Comment by MPV** [comment]
Opening this issue since after working around #752 by creating a custom OpenStack flavor with a root disk, our bastion couldn't start because it tries to schedule into our provider's default availability zone (which is a HyperV hypervisor, not our preferred KVM hypervisor in our non-default AZ).

Today our bastion can't start, we only get: `Exceeded maximum number of retries. Exceeded max scheduling attempts 3 for instance 1dbf29d7-41bb-4ca4-9fc8-29d07c5c774b. Last exception: Invalid image format 'qcow2'` (due to incorrect hypervisor/AZ being picked).

**Comment by jichenjc** [comment]
I think it's reasonable to add this option ..

**Comment by hidekazuna** [comment]
> @hidekazuna as you created the bastion, what are your thoughts on this?

@MPV Current bastion creation is implemented from minimal requirement. Adding az option is reasonable.

**Comment by jichenjc** [comment]
it should not be that hard
let's add one input field of AZ to Bastion

then put into create param of Bastion
