### ISSUE TITLE
no CI check job for doc and non-code file changes

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#764]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

avoid conformance and CI check jobs for doc related non-code file changes

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by sbueringer** [comment]
Have to clarify if that's possible in Prow. I'm not sure if we can skip mandatory jobs on doc PRs. 

Maybe it's possible with `run_if_changed`. But this means we have to match on all files where we want to run the tests (i.e. we need a list when they should be run, not a list when they should not be run)

**Comment by sbueringer** [comment]
@jichenjc What do you think, is it still relevant with Prow? If yes, we could give it a try with `run_if_changed`.

**Comment by jichenjc** [comment]
let's close this , not sure `run_if_changed` is helpful here, need more time to check
but anyway, openlab is not valid any more
