### ISSUE TITLE
update yq commands in scripts file 

### ISSUE THREAD

**Issue by wuli-jessica** [kubernetes-sigs/cluster-api-provider-openstack#769]
/kind feature

**Describe the solution you'd like**
YAML processor yq have released V4 which is quite different from previous versions. We'd like to update the code of create_cloud_conf.sh and env.rc to support both new and old versions of yq.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by hidekazuna** [comment]
I am wondering why we support  both versions. Since [support for v3 will cease August 2021](https://github.com/mikefarah/yq#v4-released), it is enough to support v4 for us.

**Comment by sbueringer** [comment]
I assume because this would enforce every consumer of CAPO to migrate to yq 4 in all places where yq is used (or use a different version for CAPO).

**Comment by jichenjc** [comment]
I think we can still add v3 and may remove it after end of support of v3
just copy code and don't do too much test is good enough, if error /issue come out, let's fix it~

**Comment by hidekazuna** [comment]
OK, yq is used in small amount of scripts.
