### ISSUE TITLE
Provide documentation website (like CAPA/CAPZ)

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#783]
/kind feature

**Describe the solution you'd like**
Would be really nice if we could provide our documentation like CAPA/CAPZ:
* https://capz.sigs.k8s.io/
* https://cluster-api-aws.sigs.k8s.io/

I think it's way nicer then our current markdown files

**Comment by jichenjc** [comment]
ok, this is better doc

I will read the process and check how we can create such (maybe a framework first then keep adding stuffs)

**Comment by sbueringer** [comment]
@jichenjc Just fyi. I already sync the Makefiles a bit with the ones from AWS in this PR: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/782

Could make sense to build on top of that when we want to implement it the same / a similar way as CAPA

**Comment by jichenjc** [comment]
@sbueringer yes, I think some debug/test need to be done as I encountered some golang issue yesterday
maybe we can do additional changes after 782 merged

**Comment by sbueringer** [comment]
Just to keep the issue up-to-date. Related PRs:
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/838
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/822

**Comment by tobiasgiese** [comment]
I think we have to request a subdomain here. Does someone know where this have to be requested? Maybe @sbueringer? Otherwise I'll take a look.

/remove-lifecycle rotten

**Comment by sbueringer** [comment]
No idea how this works. I think you have to ask in Slack.

**Comment by tobiasgiese** [comment]
Seems like we have to create a Netlify (or sth else) App to publish our documentation.
After that, we can create a redirect via [https://github.com/davidewatson/k8s.io/blob/master/dns/zone-configs/k8s.io.yaml](https://github.com/davidewatson/k8s.io/blob/master/dns/zone-configs/k8s.io.yaml)

**Comment by tobiasgiese** [comment]
Found the [Subproject Site Requests](https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md)

**Comment by tobiasgiese** [comment]
Added Netlify Request: https://github.com/kubernetes/org/issues/2883

**Comment by hidekazuna** [comment]
/close

we provide documentation here: https://cluster-api-openstack.sigs.k8s.io/
