### ISSUE TITLE
Using OpenStack keypair to access a Kubernetes node

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#784]
/kind bug

**What steps did you take and what happened:**

I created a ssh key pair and tried to jump onto a control plane node via this key. I was able to jump onto the bastion node 
but not onto a control plane node. Problem was that the ssh key from OpenStack is only created for the root user but ssh 
login for the root user is blocked. How is this supposed to work? :) If it works for anyone, how is the ssh key configured on 
the control plane node in your case?

**What did you expect to happen:**
I should be able to jump onto control plane nodes via the bastion host with the OpenStack key pair

**Anything else you would like to add:**

Reference: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/759#discussion_r592828132

**Comment by jichenjc** [comment]
it never works for me before...

**Comment by jichenjc** [comment]
>>>Problem was that the ssh key from OpenStack is only created for the root user but ssh

I assume you are talking about our mechanism? I believe openstack/cloud-init itself doesn't have such limitation

**Comment by sbueringer** [comment]
@jichenjc Yes I'm talking about our OpenStack ssh key pair. I think for our integration tests I will just use an additional user and username/pw as that's simpler anyway.

But I think when we provide the property we should have a documentation how to use it, if it's not trivial. Maybe it works, but not with the image-builder image?

**Comment by jichenjc** [comment]
yes, I doubt the image itself configuration because we are using image builder now and not with CAPO /cluster api the non-root username/key works very well , so we need check image builder first and fix potential issue then test with new image and may doc the behavior as well

**Comment by sbueringer** [comment]
I think it's a feature and not an issue that you're not able to use ssh with the root user (as that's an antipattern). Just not sure if OpenStack e.g. allows adding the key to another user.

**Comment by sbueringer** [comment]
@hidekazuna do you maybe have some ideas? We deliberately dropped the standard CAPI way (compatible with *all* providers) to do this in our templates in favor of this method. I think if our OpenStack method doesn't work I would go back to the CAPI way of doing this, as it's way easier to use the same way as in all other providers and it works.

**Comment by hidekazuna** [comment]
@sbueringer As you said, we can use non-root user to login control plane and worker node via bastion. It is enough for feature. I still do not understand why we need to use root user to login control plane and worker node via bastion. Is that needed for only e2e test?

**Comment by sbueringer** [comment]
I am not able to login with a non-root user because the OpenStack feature only adds the key to the root user and I'm not able to log in with that one. Maybe I"m doing it wrong.

**Comment by hidekazuna** [comment]
I understand. I built image builder os image few months ago and use ubuntu user to login control plane and worker node via bastion. I will try building image builder again.

**Comment by sbueringer** [comment]
@hidekazuna Thank you. If it works for you, I would add some more information about how I (and our e2e tests) are doing it and maybe we can find out what's the difference.

**Comment by sbueringer** [comment]
@hidekazuna You can also use the one we're using in our tests if you want:
* https://github.com/sbueringer/cluster-api-provider-openstack-images/releases/tag/ubuntu-2004-v1.18.15-0
* It's build with this script: https://github.com/sbueringer/cluster-api-provider-openstack-images/blob/main/.github/workflows/build.sh

**Comment by hidekazuna** [comment]
@sbueringer  I built image builder image and logged in  one of control plan node via bastion as ubuntu user successfully.
image builder was commit 271b8a0b59f201d82c1095b39c31fa5d1706f39a

**Comment by hidekazuna** [comment]
@sbueringer I will try the image you built next :)

**Comment by sbueringer** [comment]
@hidekazuna Thx. It would be especially useful to know for which users the authorized key has been added and if there is anything special how the keypair has to be created in OpenStack.

**Comment by hidekazuna** [comment]
@sbueringer I was not able to login bastion using your image.

> P.S. maybe the difference is Ubuntu 20.04 vs 18.04?

I built 20.04 image builder image and confirmed login to one of control plane node via bastion as ubuntu user as 18.04.

your building script [converts the image to qcow2](https://github.com/sbueringer/cluster-api-provider-openstack-images/blob/main/.github/workflows/build.sh#L58), but the image is already qcow2 and converting is not needed. Please remove converting.

**Comment by sbueringer** [comment]
@hidekazuna The script converts the image from qcow2 to compressed qcow2 to save upload/download bandwith  (`-c` option)

**Comment by hidekazuna** [comment]
@sbueringer Thanks. I compressed my images and was able to login bastion successfully. 
https://github.com/kubernetes-sigs/image-builder/pull/562 may be the reason. This is merged 2 days ago.
I investigated your image and found cloud-initramfs-growroot in the image actually.  Can you try latest image builder?

**Comment by sbueringer** [comment]
I can update yes. Did you already have time to test if you can also log in with my image?

**Comment by hidekazuna** [comment]
I booted from your image but could not login. I mounted the image locally using qemu-nbd and found cloud-initramfs-growroot in it. My image did not include cloud-initramfs-growroot.

**Comment by sbueringer** [comment]
@hidekazuna okay thank you very much. I'll try the image and get back to you

**Comment by sbueringer** [comment]
@hidekazuna the problem was not the image, I had the same problem even with the new image.

The problem is actually that I added the capi user to the `users` config in KubeadmControlPlane and KubeadmConfigTemplate. This apparently overwrote the config that the `ubuntu` user is the default user. OpenStack seems to add the key either to the default user or root if there is none.

so tl;dr. you can either specify key pair or users but not both, which is fine imho.


What I just realized is that the key pair feature is very limited. It allows only to add *1* key and you can only add it to the default users. I think it's pretty rare in production use cases that all administrators share the same ssh key. I guess that's also why the internet is full of OpenStack users asking how to add multiple keys and the answer is always you should use cloud-init to do that.

**Comment by hidekazuna** [comment]
@sbueringer Can't you add `users` in kubeadmConfigSpec like the following?

```yaml
spec:
  kubeadmConfigSpec:
    users:
    - name: capo
      sudo: "ALL=(ALL) NOPASSWD:ALL"
      sshAuthorizedKeys:
      - "..."
```

I added above and done the following:

- scp private key into bastion as ubuntu user(since bastion spec is not related to kubeadm, we can not use capo) 
- ssh bastion as ubuntu user using private key.
- ssh one of controller node as capo user using private key.

**Comment by sbueringer** [comment]
@hidekazuna Yes that works no problem. I just can't add a user via kubeadmConfigSpec and use the OpenStack key pair at the same time, because it's then added to the root user. But I think that's okay.

**Comment by sbueringer** [comment]
I tested it by specifying the following:
```
    users:
      - name: ubuntu
        sudo: "ALL=(ALL) NOPASSWD:ALL"
        lockPassword: True
      - name: "capi"
        sudo: "ALL=(ALL) NOPASSWD:ALL"
        # user: capi, passwd: capi
        passwd: "$6$rounds=4096$yKTFKL6RmN128$a7cGMiNjeTSd091s6QzZcUNrMTgm3HhML5rVmpDFlCfgD7scTW7ZHr0OChcXCaeiO/kbhdn0XzIzWk63nSqRH1"
```

Result was:
```bash
Mar 27 10:32:32 cluster-e2e-ecrex5-control-plane-8mmgm cloud-init[441]: [CLOUDINIT]2021-03-27 10:32:32,689 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 561 bytes
```

I think the problem is that we're adding users at all and we loose the default user config (from `/etc/cloud/cloud.cfg`) which looks like this:
```bash
users:
   - default
```

It's no possible to add a `- default` entry via ClusterAPI, just regular array entries


So the result is pretty simple:
> You can either use the OpenStack keypair feature *or* configure the `users` array in `KubeadmControlPlane`, both won't work at the same time.


I think that's totally fine and I'll open a PR to include the OpenStack keypair variant in our testing.

**Comment by sbueringer** [comment]
Thx for your help finding this out @hidekazuna 

I'll close the issue as it's not a bug and the PR to test this (#815) is just a follow-up

/close
