### ISSUE TITLE
Remove OpenLab integration

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#785]
As master is now using Prow instead of OpenLab I would try to get rid of our OpenLab integration. This would include:
* [x] cleanup in OpenLab repos, e.g.: periodic scheduled jobs: https://github.com/theopenlab/openlab-zuul-jobs/pull/1134
* [x] remove OpenLab application from the GitHub repo: https://github.com/kubernetes/org/issues/2580
* [x] tests on release-0.3 (cherry-pick Prow conformance test?): https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/787
* [x] cleanup buckets / testgrid configuration
  * [x] https://github.com/kubernetes/test-infra/pull/21445
  * [x] https://github.com/kubernetes/k8s.io/pull/1807

WDYT?

**Comment by jichenjc** [comment]
I am +1 to all the stuffs above , thanks for driving this ~

**Comment by sbueringer** [comment]
All done
/close
