### ISSUE TITLE
goimports: fix sorting

### ISSUE THREAD

**Issue by seanschneeweiss** [kubernetes-sigs/cluster-api-provider-openstack#790]
/kind bug

**What steps did you take and what happened:**

I would suggest to adapt a certain sorting standard for the go imports.

Have a look at e.g. `loadbalancer.go`:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/8f03cd602fbc94ac2337637daa11d8742beceb85/pkg/cloud/services/loadbalancer/loadbalancer.go#L19-L39

**What did you expect to happen:**

The following structure is commonly used:
```go
import (
  stdlib

  3rd-party

  local (sigs.k8s.io/cluster-api-provider-openstack)
)
```
For the example, this would lead to:
```go
import (
	"errors"
	"fmt"
	"time"

	"github.com/go-logr/logr"
	"github.com/gophercloud/gophercloud"
	"github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners"
	"github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers"
	"github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors"
	"github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools"
	"github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups"
	"github.com/gophercloud/gophercloud/openstack/networking/v2/ports"
	"k8s.io/apimachinery/pkg/util/wait"
	clusterv1 "sigs.k8s.io/cluster-api/api/v1alpha4"
	"sigs.k8s.io/cluster-api/util"

	infrav1 "sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4"
	"sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/services/networking"
	"sigs.k8s.io/cluster-api-provider-openstack/pkg/record"
)
```

**Anything else you would like to add:**

We could add the following to the `.golangci.yml`:
```yaml
goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: sigs.k8s.io/cluster-api-provider-openstack
```

**Environment:**

- Cluster API Provider OpenStack version: master

<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by sbueringer** [comment]
Sounds good to me
