### ISSUE TITLE
Provide qemu OS images via the capo staging bucket

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#794]
/kind feature

**Describe the solution you'd like**

We have a pretty fragile dependency on qcow2 images on Github releases at the moment.
Let's add a job which periodically builds and pushes Ubuntu 20 images with the help of the
image-builder repo. Probably the best "target" would be our staging bucket (but I would compare 
that how it's done with cluster-api nightly builds at the moment)

xref:
* https://kubernetes.slack.com/archives/C8TSNPY4T/p1616157439092100

/assign

**Comment by jichenjc** [comment]
I checked that slack info and seems still lost some background
just for education, you want to create new images time to time (ubuntu 20) so that we can use latest 
image with kubeadm etc to make sure we won't suffer any not-up-to-date issue? @sbueringer

**Comment by sbueringer** [comment]
@jichenjc
Yes. Problem right now is that we depend on an old Ubuntu image I uploaded on a previous release in our e2e tests. 
With my current PRs it gets a bit bitter (imho), as I'll now depend on images from [here](https://github.com/sbueringer/cluster-api-provider-openstack-images/releases). Ideally we don't depend on images of some of my repos. But I think that's a long-term discussion and I have to figure out with who I should talk about it

**Comment by jichenjc** [comment]
@sbueringer thanks for the info, make sense to me :)

**Comment by sbueringer** [comment]
My current plan is to add documentation and build scripts to the CAPO repo. With this documentation and sufficient rights to our bucket the images can then be manually build and uploaded.
