### ISSUE TITLE
Reorganize code to conform to what is in skeleton repo

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/cluster-api-provider-openstack#8]
please see https://github.com/davidewatson/cluster-api-provider-skeleton

**Comment by chaosaffe** [comment]
/assign @Lion-Wei 

Can we close this per: https://kubernetes.slack.com/archives/C8TSNPY4T/p1538106855000100?

**Comment by Lion-Wei** [comment]
I think this issue can be closed since we already conformed to skeleton repo. 
Since we are migrating to crd, maybe need another reorganize...

xref: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/37
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/32
