### ISSUE TITLE
Create and use server group for masters to ensure anti affinity

### ISSUE THREAD

**Issue by bl0m1** [kubernetes-sigs/cluster-api-provider-openstack#808]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

I want to ensure that masters are spread cross availability zones.
I know some companies are deploying a cluster in a specific AZ so I think this option if implemented should be opt-in.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

A similar thing might be implemented by other providers? if so it may be nice to handle this question in a similar way.

**Comment by jichenjc** [comment]
we have failure domain https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/api/v1alpha3/openstackcluster_types.go#L126 defined

and it's updated here
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/controllers/openstackcluster_controller.go#L278

and the instance of control pane is created at cluster-api side and  cluster-api seems randomly select the Failure Domain if multiple given if I remember correctly 

so the requirement is we should provide multiple AZ to the openstack cluster and let it choose for each instance created? the affiinity and anti-affinity is per-host level (e.g VM to one host then next VM to same/different host)

**Comment by sbueringer** [comment]
Maybe I got it wrong, but we can currently deploy the control plane nodes either:
* without config randomly spread in multiple azs (it uses the available ones)
* in a configured set of azs
* in only one specific az

Do you require something else?

We're not using server groups in our env, so I'm not really familiar with how they work.

What I could read [here](https://docs.platform9.com/v5.0/openstack/virtual-machines-anti-affinity) was that 
you can specify affinity/ anti-affinity of hypervisor hosts. So would this be away to ensure that server *in the same* az
are spread over multiple hypervisor hosts? (so you could say a second layer of failure domain below the az)

Is this the same OpenStack feature as: https://docs.openstack.org/nova/latest/admin/configuration/schedulers.html (ServerGroupAntiAffinityFilter)

Do you know how this relates to scheduler hints?

**Comment by jichenjc** [comment]
> 
> 
> Maybe I got it wrong, but we can currently deploy the control plane nodes either:
> 
>     * without config randomly spread in multiple azs (it uses the available ones)
> 
>     * in a configured set of azs
> 
>     * in only one specific az
> 
> 
> Do you require something else?
> 
> We're not using server groups in our env, so I'm not really familiar with how they work.
> 
> What I could read [here](https://docs.platform9.com/v5.0/openstack/virtual-machines-anti-affinity) was that you can specify affinity/ anti-affinity of hypervisor hosts. So would this be a way to ensure that server _in the same_ az are spread over multiple hypervisor hosts? (so you could say a second layer of failure domain below the az)
> 
> Is this the same OpenStack feature as: https://docs.openstack.org/nova/latest/admin/configuration/schedulers.html (ServerGroupAntiAffinityFilter)
> 
> Do you know how this relates to scheduler hints?

2 topics， one is az selection and the other is affinity 

I think the ask is for cross AZ deployment, which is , let's say 3 az, you can put 3 masters into those AZ
but I highly doubt this in reality because this means master especially etcd cluster will be put into different AZ
 and this might lead to further issue 

so soft anti-affinity should be introduced so that we can at least ensure those masters are not in same host by default, thoughts?

**Comment by sbueringer** [comment]
I think I want to wait for feedback from @bl0m1 . Distributing control plane nodes across azs already works today and is as far as I know the main use case (e.g. in CAPA). Apart from that I'm not entirely sure to which OpenStack feature this issue refers to (or if there are related OpenStack features that cover similar use cases)

**Comment by bl0m1** [comment]
As mentioned CAPA currently seems to spread masters across AZ based on internal logic. When using server groups this logic is no longer needed (away from specifying the group on instance creation) and based on configuration the group can be used for booth affinity and anti-affinity.

Openstack server group can ensure that instances are located in different az's and/or on different hosts.

This means if I for example have 3 AZ's and spins up 6 master nodes I can make sure that there is 2 in each availability zone running on different hosts. To my knowledge this is the only way in default openstack to ensure instances in the same AZ is not running on the same underlaying server

Server group would also work for worker nodes even if they are scheduled within the same availability zone since it can spread instances cross underlaying servers.

**Comment by sbueringer** [comment]
@bl0m1 Thx for the clarification. 

What further complicates this is that failure domains is not a provider specifc feature. CAPO/CAPA controllers provider the kubeadm control plane with a list of failure domains (they don't have to be az's). The kubeadm control plane controller then explicitly creates severs in different failure domains.

So I think we would have to figure out how this fits together:
* on the one side OpenStack takes care of distributing severs onto different failure domains
* on the other side it's done by the kubeadm control plane controller

I was thinking maybe it's possible to explicitly tell OpenStack via scheduler hints (or whatever, I don't know enough about OpenStack)  to put a server on a specific az and host. Then it might be possible to hand over CAPI failure domains with mutiple layers (az & host) and CAPI can manage it.

But overall I think I have to re-read the proposals / documentations of CAPI which are mentioning failure domains:  (and probably the code):
* https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/cluster-infrastructure.md
* https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20191017-kubeadm-based-control-plane.md

**Comment by MPV** [comment]
In our case, since our provider doesn't have multiple AZs per data center, we'd like to be able to use server groups for spreading our control plane across hypervisors (to increase resilience).

**Comment by jichenjc** [comment]
https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/internal/control_plane.go#L169

so the control plane will select less VM on that failuredomain (AZ) then schedule workload to it ...

**Comment by jichenjc** [comment]
if we provide multiple AZ (failuredomain), then likely control plane will spread among them
might need some quick test though..

**Comment by sbueringer** [comment]
What would be interesting to me is:
* is it possible to discover the available in hosts in OpenStack
* is it possible to specify a specific host when creating a server

I think then we can use the CAPI failure domain feature to distribute server onto different hosts. If it isn't, it has to be implemented independently of the CAPI failure domain feature (e.g. a property in the OpenStackMachineTemplate referenced in the KubeadmControlPlane)

**Comment by jichenjc** [comment]
>>>I think then we can use the CAPI failure domain feature to distribute server onto different hosts

no , failure domain and AZ is targeting to differnet AZ/host aggregate 

for host, it's different story, either we select a host, or we let scheduler choose one?

**Comment by bl0m1** [comment]
> > > > I think then we can use the CAPI failure domain feature to distribute server onto different hosts
> 
> no , failure domain and AZ is targeting to differnet AZ/host aggregate
> 
> for host, it's different story, either we select a host, or we let scheduler choose one?

I have not found any way of selecting a host when scheduling an instance. however az can be specified

**Comment by sbueringer** [comment]
@bl0m1 okay thx. Then I assume implementing it via a property on the `OpenStackMachineTemplate` is the way this should be implemented. 

How is this usually done?

From what I can see in the doc I would have assumed:
* create a server group with policy soft-anti-affinity before creating the server 
  * I assume soft-anti-affinity is preferred. I guess otherwise the server will not come up
* assign the server group  to the respective servers via `os:scheduler_hints.group`

I think we also have to find a way to specify to which server group a server belongs. If we do this right we can also spread out worker nodes.

OpenStack doc:
* https://docs.openstack.org/python-openstackclient/pike/cli/command-objects/server-group.html
* https://docs.openstack.org/api-ref/compute/?expanded=create-server-detail,create-server-group-detail#create-server-group

**Comment by bl0m1** [comment]
> @bl0m1 okay thx. Then I assume implementing it via a property on the `OpenStackMachineTemplate` is the way this should be implemented.
> 
> How is this usually done?
> 
> From what I can see in the doc I would have assumed:
> 
> * create a server group with policy soft-anti-affinity before creating the server
>   
>   * I assume soft-anti-affinity is preferred. I guess otherwise the server will not come up
> * assign the server group  to the respective servers via `os:scheduler_hints.group`
> 
> I think we also have to find a way to specify to which server group a server belongs. If we do this right we can also spread out worker nodes. My initial idea would be to add a property for the name and the policy of the server group to the OpenStackMachine(Template).
> 
> OpenStack doc:
> 
> * https://docs.openstack.org/python-openstackclient/pike/cli/command-objects/server-group.html
> * https://docs.openstack.org/api-ref/compute/?expanded=create-server-detail,create-server-group-detail#create-server-group

I agree that soft-anti-affinity would be the best default option since some smaller providers maybe doesn't have that many hosts.

Regarding assignment you are correct about setting os:scheduler_hints.group during instance creation

Regarding what group a server belongs. I guess there is 2 ways. 
1. Assign each machine deployment to a separate group. 
2. Create one group for masters and one for workers. (this is probably most inline with other projects)

**Comment by sbueringer** [comment]
We're reconciling on a per OpenStackMachine basis. So we can:
* either try to derive the security group from a parent/owner resource (which is either a MachineDeployment or a KubeadmControlPlane) or 
* let it be explicitly configured in the OpenStackMachineTemplate or
* both: if it's explicitly configured in the OpenStackMachineTemplate use it from there, if not fallback to the parent/owner resource

I think the last option provides the most flexibility. In combination with a configurable policy it would be possible to configure arbitrary (soft) affinity / anti-affinity.

**Comment by jichenjc** [comment]
I think we might want to sync with openshift implementation ... 

https://github.com/openshift/cluster-api-provider-openstack/blob/master/pkg/cloud/openstack/clients/machineservice.go#L735

@iamemilio can you help to confirm openshift contains such feature already?

**Comment by sbueringer** [comment]
@jichenjc Ah nice finding. Looks like the OpenShift fork contains more or less exactly what we want (maybe we want additionally to make the policy configurable)

**Comment by mdbooth** [comment]
> 
> 
> > > > > I think then we can use the CAPI failure domain feature to distribute server onto different hosts
> > 
> > 
> > no , failure domain and AZ is targeting to differnet AZ/host aggregate
> > for host, it's different story, either we select a host, or we let scheduler choose one?
> 
> I have not found any way of selecting a host when scheduling an instance. however az can be specified

Incidentally this is not possible by design, as hosts are only visible to admin. AZs are exposed to users.

I can't find the name of the property right now, but Nova metadata does expose a salted, hashed value which corresponds to the identity of the hypervisor, but this value is only used for neighbour detection.

**Comment by mdbooth** [comment]
It's also worth noting there's a long-standing bug in Nova which means soft anti-affinity will race on concurrent server creation. This means that if you create several servers simultaneously with a soft-antiaffinity policy there's a high probability of them ending up on the same hypervisor, violating the anti-affinity policy. I don't think the OpenShift CAPO handles this, although we do handle it in the corresponding terraform implementation used by the installer.

There are 3 workarounds:
1. Switch to a hard anti-affinity policy
2. Create all servers in a single API call
3. Serialise server creation until vm state reaches 'BUILDING'

Of the 3 I think the latter is likely the simplest and most robust. (1) Won't permit the deployment of 3 masters unless if you have at least 3 available workers. (2) has been a problematic api since it was created, and [as the documentation suggests](https://docs.openstack.org/api-ref/compute/?expanded=create-multiple-servers-detail#create-multiple-servers) isn't exactly recommended. Multi-create can also race with other multi-creates, which could be complex to implement. (3) Shouldn't be relatively straightforward to implement.

**Comment by jichenjc** [comment]
>>>although we do handle it in the corresponding terraform implementation used by the installer.

thanks for the sharing, yes, I recently also noticed openshift has such [info ](https://github.com/openshift/installer/blob/master/docs/user/openstack/known-issues.md#control-plane-scale-out-anti-affinity)listed in the Openstack installer about soft-affinity , not sure you are talking about same one

and I don't know whether we are able to control that master creation as it's seems buried in cluster-api projects while worker nodes we can control

**Comment by sbueringer** [comment]
@jichenjc all servers in OpenStack are eventually created by the CAPO machine controller. So we can wait there if we want.

@mdbooth I assume you mean `should` instead of `shouldn't` regarding option 3? :)

**Comment by mdbooth** [comment]
> @mdbooth I assume you mean `should` instead of `shouldn't` regarding option 3? :)
🤦‍♂️

**Comment by jichenjc** [comment]
>>>@jichenjc all servers in OpenStack are eventually created by the CAPO machine controller. So we can wait there if we want.

@sbueringer not sure, as we need distinguish worker and master node creation as well in such case
because this apply to master (control plane) only?

**Comment by sbueringer** [comment]
@jichenjc  No sure what exactly we are talking about. I assume we set a field for this feature on the `OpenStackMachineTemplate`. Eventually all those Machines are created by our machine controller (doesn't matter if they are control plane or worker nodes).

If I got it right we just have to delay server creation (return with retryAfter), if another server is already in `BUILDING`. 

But I think it's doable in any case so I think we can discuss this details once a PR is open.

**Comment by jichenjc** [comment]
> 
> 
> @jichenjc No sure what exactly we are talking about. I assume we set a field for this feature on the `OpenStackMachineTemplate`. Eventually all those Machines are created by our machine controller (doesn't matter if they are control plane or worker nodes).
> 
> If I got it right, we just have to delay server creation (return with retryAfter), if another server has been created but isn't in `BUILDING` yet.
> 
> But I think it's doable in any case so I think we can discuss this detail once a PR is open.

ok, yes, let's talk with code and PR :)

**Comment by MPV** [comment]
Did https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/879 solve this? Or how is that related to this issue?

**Comment by jichenjc** [comment]
>>> want to ensure that masters are spread cross availability zones.
I know some companies are deploying a cluster in a specific AZ so I think this option if implemented should be opt-in.

my understanding the original question is around az and we only honor the server group now through above 
az, I myself didn't try multiple az and multiple server group and relation between those concepts before, so I am not 100% sure can fit for the original request

**Comment by sbueringer** [comment]
Hm I think we should be mostly good (maybe I'm missing something). AZs should already work because it's a feature of CAPI and not CAPO specific. Server groups should basically work but it sounded like it's maybe not entirely safe the way we do it (race conditions). Maybe it would be better to create a new separate issue to fix those race conditions if necesssary (@mdbooth what do you think?).
