### ISSUE TITLE
unable to load clouds.yaml

### ISSUE THREAD

**Issue by blencoff** [kubernetes-sigs/cluster-api-provider-openstack#825]
/kind bug

**What steps did you take and what happened:**
I've tried to perform steps from [Cluster API Quick Start](https://cluster-api.sigs.k8s.io/user/quick-start.html) in order to create test k8s cluster in our 'on-premise' OpenStack, but faced with an issue after applying cluster manifest.
Cluster has stuck on _Provisioning_ phase, machine resources has stuck in _WaitingForInfrastructure_ state.
```sh
# kubectl get cluster --all-namespaces
NAMESPACE   NAME              PHASE
default     capi-quickstart   Provisioning

# kubectl get kubeadmcontrolplane --all-namespaces
NAMESPACE   NAME                            INITIALIZED   API SERVER AVAILABLE   VERSION    REPLICAS   READY   UPDATED   UNAVAILABLE
default     capi-quickstart-control-plane                                        v1.18.16

# clusterctl describe cluster capi-quickstart --disable-grouping --disable-no-echo 
NAME                                                                         READY  SEVERITY  REASON                           SINCE  MESSAGE
/capi-quickstart                                                             False  Info      WaitingForControlPlane           5m19s
├─ClusterInfrastructure - OpenStackCluster/capi-quickstart
├─ControlPlane - KubeadmControlPlane/capi-quickstart-control-plane
└─Workers
  └─MachineDeployment/capi-quickstart-md-0
    ├─Machine/capi-quickstart-md-0-55fd7d7567-22h5r                          False  Info      WaitingForInfrastructure         5m18s  0 of 2 completed
    │ ├─BootstrapConfig - KubeadmConfig/capi-quickstart-md-0-qbggm           False  Info      WaitingForClusterInfrastructure  5m19s
    │ └─MachineInfrastructure - OpenStackMachine/capi-quickstart-md-0-x4f8g
    ├─Machine/capi-quickstart-md-0-55fd7d7567-7zshr                          False  Info      WaitingForInfrastructure         5m18s  0 of 2 completed
    │ ├─BootstrapConfig - KubeadmConfig/capi-quickstart-md-0-7l4mx           False  Info      WaitingForClusterInfrastructure  5m18s
    │ └─MachineInfrastructure - OpenStackMachine/capi-quickstart-md-0-5tcg2
    └─Machine/capi-quickstart-md-0-55fd7d7567-nrl9f                          False  Info      WaitingForInfrastructure         5m18s  0 of 2 completed
      ├─BootstrapConfig - KubeadmConfig/capi-quickstart-md-0-qpjqh           False  Info      WaitingForClusterInfrastructure  5m19s
      └─MachineInfrastructure - OpenStackMachine/capi-quickstart-md-0-9lvpz
```

Pod _capo-controller-manager_ reports that it unable to load _clouds.yaml_ 
```sh
E0401 12:58:22.237151       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="auth option failed for cloud pilotcloud: unable to load clouds.yaml: no clouds.yaml file found" "controller"="openstackcluster" "name"="capi-quickstart" "namespace"="default"
I0401 12:58:22.237283       1 openstackmachine_controller.go:340] controllers/OpenStackMachine "msg"="Cluster infrastructure is not ready yet, requeuing machine" "cluster"="capi-quickstart" "machine"="capi-quickstart-md-0-55fd7d7567-7zshr" "namespace"="default" "openStackCluster"="capi-quickstart" "openStackMachine"="capi-quickstart-md-0-5tcg2"
I0401 12:58:30.404497       1 openstackmachine_controller.go:340] controllers/OpenStackMachine "msg"="Cluster infrastructure is not ready yet, requeuing machine" "cluster"="capi-quickstart" "machine"="capi-quickstart-md-0-55fd7d7567-7zshr" "namespace"="default" "openStackCluster"="capi-quickstart" "openStackMachine"="capi-quickstart-md-0-5tcg2"
I0401 12:58:30.405240       1 openstackmachine_controller.go:340] controllers/OpenStackMachine "msg"="Cluster infrastructure is not ready yet, requeuing machine" "cluster"="capi-quickstart" "machine"="capi-quickstart-md-0-55fd7d7567-22h5r" "namespace"="default" "openStackCluster"="capi-quickstart" "openStackMachine"="capi-quickstart-md-0-x4f8g"
I0401 12:58:30.768171       1 openstackmachine_controller.go:340] controllers/OpenStackMachine "msg"="Cluster infrastructure is not ready yet, requeuing machine" "cluster"="capi-quickstart" "machine"="capi-quickstart-md-0-55fd7d7567-nrl9f" "namespace"="default" "openStackCluster"="capi-quickstart" "openStackMachine"="capi-quickstart-md-0-9lvpz"
```
But at the same time secret _capi-quickstart-cloud-config_ exists and contains _clouds.yaml_ inside
```sh
# kc get secret capi-quickstart-cloud-config -n default -o yaml | grep ' clouds.yaml'
  clouds.yaml: Y2x<base64-string>ECg==
```

Also this base64 string could be successfully decoded
```sh
# echo 'Y2x<base64-string>ECg==' | base64 -d
clouds:
  pilotcloud:
    cloud: pilotcloud
    region_name: RegionOne
    interface: public
    user_domain_name: Default
    project_domain_name: default
    key: /root/envs/pilotcloud/signing_key.pem
    cert: /root/envs/pilotcloud/signing_cert.pem
    cacert: /root/envs/pilotcloud/ca.pem
    auth:
      auth_url: https://pilotcloud:55000/v3/
      username: <username>
      password: <password>
      project_name: TEST_TENANT
```

**What did you expect to happen:**
Provider will try to connect to OpenStack at least.

**Anything else you would like to add:**
-

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.3.4
- Cluster-API version: v1.13.15
- OpenStack version: -
- KIND version: v0.10.0
- Kubernetes version (use `kubectl version`): Client Version: v1.19.1; Server Version: v1.20.2
- OS (e.g. from `/etc/os-release`): CentOS Linux 7.8

**Comment by sbueringer** [comment]
I think the error is not that it couldn't find the key in the secret. I think the error is returned here:

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/6b4da71c432f3a126c799c0872790cc8b205b68f/pkg/cloud/services/provider/provider.go#L87-L91

This means that `unable to load clouds.yaml: no clouds.yaml file found` is returned by `clientconfig.AuthOptions(clientOpts)` which is a func von gophercloud which we are using. I assume that this func is unable to parse your clouds.yaml file and then returns this (frankly) weird error. I guess it might be because of the references files for cert/key/cacert.

**Comment by blencoff** [comment]
@sbueringer 
I've removed cert/key/cacert parameters from clouds.yaml for test purposes

```sh
# kc get secret capi-quickstart-cloud-config -n capo-system -o yaml | grep ' clouds.yaml'
  clouds.yaml: Y2x...Ao=
# echo 'Y2x...RAo=' | base64 -d
clouds:
  pilotcloud:
    cloud: pilotcloud
    region_name: RegionOne
    interface: public
    user_domain_name: Default
    project_domain_name: default
    auth:
      auth_url: https://pilotcloud:55000/v3/
      username: <username>
      password: <password>
      project_name: TEST_TENANT
```

But errors are still remains
```sh
E0401 14:18:22.029484       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="auth option failed for cloud zephyr01cn: unable to load clouds.yaml: no clouds.yaml file found" "controller"="openstackcluster" "name"="capi-quickstart" "namespace"="capo-system"
```

**Comment by sbueringer** [comment]
@blencoff I assume the mismatch in the cloud name is just in this issue? :)

**Comment by blencoff** [comment]
@sbueringer Oops, my bad, forgot to replace real cloud name with 'pilotcloud' in error message... :)
Actually there is the same cloud name in secret and error message.

**Comment by sbueringer** [comment]
No problem :)

Unfortunately the code of the util is not easily decipherable. Can you try to only speicfy the properties as we use them in our e2e tests?
```bash
clouds:
  ${CLUSTER_NAME}:
    auth:
      username: ${OS_USERNAME}
      password: ${OS_PASSWORD}
      user_domain_id: ${OS_USER_DOMAIN_ID}
      auth_url: ${OS_AUTH_URL}
      domain_id: default
      project_name: demo
    verify: false
    region_name: RegionOne
````

I suspect the `cloud`property is throwing the util off. I can later try to step through in the debugger to find out where it goes wrong.

**Comment by blencoff** [comment]
As a first test I used clouds file like this:

```sh
clouds:
  pilotcloud:
    region_name: RegionOne
    verify: false
    auth:
      auth_url: https://pilotcloud:55000/v3/
      username: ...
      password: ...
      project_name: ...
      domain_id: default
      user_domain_id: Default
```

And got this error
```sh
E0401 15:09:50.474823       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="providerClient authentication err: Authentication failed" "controller"="openstackcluster" "name"="capi-quickstart" "namespace"="default"
```

**Comment by blencoff** [comment]
Now I've tried this
```sh
clouds:
  pilotcloud:
    region_name: RegionOne
    interface: public
    user_domain_name: Default
    project_domain_name: default
    key: /root/envs/pilotcloud/signing_key.pem
    cert: /root/envs/pilotcloud/signing_cert.pem
    cacert: /root/envs/pilotcloud/ca.pem
    auth:
      auth_url: https://pilotcloud:55000/v3/
      username: ...
      password: ...
      project_name: ...
```

And got this
```sh
E0401 15:23:00.376410       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="providerClient authentication err: You must provide exactly one of DomainID or DomainName in a Scope with ProjectName" "controller"="openstackcluster" "name"="capi-quickstart" "namespace"="default"
```

So I think you're right, rootcause was in `cloud` property

**Comment by sbueringer** [comment]
@blencoff Okay good. Should be possible to get it to work now. I'll check if we can use another util func which not randomly tries to parse a cloud.yaml which does not exist.

**Comment by blencoff** [comment]
It could save a lot of time if there would be more informative error message, e.g. "unknown parameter" or at least "failed to parse clouds.yaml".

**Comment by jichenjc** [comment]
I knew https://github.com/kubernetes/cloud-provider-openstack had some check on the yaml and params
maybe worthy a steal

**Comment by jichenjc** [comment]
I knew https://github.com/kubernetes/cloud-provider-openstack had some check on the yaml and params
maybe worthy a steal

**Comment by sbueringer** [comment]
> It could save a lot of time if there would be more informative error message, e.g. "unknown parameter" or at least "failed to parse clouds.yaml".

Yeah the problem is that we would have to make this change upstream in goperclouds/utils and I assume the error is not even wrong from there point of few. I hope we're just using the wrong func

**Comment by sbueringer** [comment]
> I knew https://github.com/kubernetes/cloud-provider-openstack had some check on the yaml and params
> maybe worthy a steal

I think there are not using the cloud.yaml but the cloud.conf format?

**Comment by sbueringer** [comment]
I think I know how to fix it. I'll open a PR, let's discuss there

**Comment by jichenjc** [comment]
> 
> 
> > I knew https://github.com/kubernetes/cloud-provider-openstack had some check on the yaml and params
> > maybe worthy a steal
> 
> I think there are not using the cloud.yaml but the cloud.conf format?

they use .. in the CSI side

**Comment by sbueringer** [comment]
Ah okay. Apart from that, I think my fix is correct for the current problem, we should never set the cloud in the `clientOpts` if it cannot work. We currently rely on that it's not set in the "incoming" cloud.yaml.
