### ISSUE TITLE
OpenStack network resources are not deleted just after created

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#841]
/kind bug

**What steps did you take and what happened:**

- Create cluster
- Delete cluster just after OpenStack network resources(Load balancer, network, subnet, router, security groups) are created.
- Cluster was deleted successfully, but OpenStack network resources are not deleted at all.

**What did you expect to happen:**

OpenStack network resources are deleted successfully just after they are created, cluster is still provisioning phase.

**Anything else you would like to add:**

I think we should not see openStackCluster.Status when deleting cluster.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): fa64ad4694324ffbdd3054aeb62c7946afccf8d5
- Cluster-API version: v1alpha4
- OpenStack version: Stein
- Minikube/KIND version: v0.10.0
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):

**Comment by hidekazuna** [comment]
I will try not to see openStackCluster.Status when deleting cluster.

**Comment by sbueringer** [comment]
Just out of curiosity. So the cluster is not completed created and then a deletion does not cleanup successfully because the status is not complete?

So the idea is to delete based on the properties in the Spec and not in Status?

**Comment by hidekazuna** [comment]
> the cluster is not completely created and then a deletion does not cleanup successfully 

Yes... I am not completely sure status is the reason. but I think so from code base.

> 
> So the idea is to delete based on the properties in the Spec and not in Status?

based on Spec and get actual status from OpenStack API each time instead of Status.

I found CAPA has network Status, but CAPZ does not. I wonder if we should not have OpenStack related Status at all.
Anyway we faced the real usage bug like this PR, so first I try to remove using OpenStack related Status in deleting cluster.

**Comment by sbueringer** [comment]
Got it. Let's see how it goes.

There's something about controller reentrancy in the ClusterAPI book: https://cluster-api.sigs.k8s.io/reviewing#controller-reentrancy
This might provide some valuable insight. I think the cluster controller and machine controller can be considered as separate controllers in this regard:
> It is acceptable to rely on status flags/conditions set by other controllers.

**Comment by jichenjc** [comment]
@hidekazuna I think if you paste some logs should be helpful here? e.g 
we didn't go to delete branch of network resources or we enter but no actions taken due to Status/Spec phase?
that will be helpful to know the root cause...

**Comment by hidekazuna** [comment]
@jichenjc I added debug logs in controllers/openstackcluster_controller.go:

```go
if openStackCluster.Status.Network == nil {
                log.Info("openStackCluster.Status.Network is nil ")
        }

        if openStackCluster.Spec.ManagedAPIServerLoadBalancer && openStackCluster.Status.Network != nil {
```
and 
```go
if openStackCluster.Status.WorkerSecurityGroup == nil {
                log.Info("openStackCluster.Status.WorkerSecurityGroup is nil ")
        }

        if workerSecGroup := openStackCluster.Status.WorkerSecurityGroup; workerSecGroup != nil {
```

Result is openStackCluster.Status.Network and openStackCluster.Status.WorkerSecurityGroup are nil:

```bash
I0412 04:46:30.345618       1 loadbalancer.go:426] controller-runtime/manager/controller/openstackcluster "msg"="Waiting for load balancer listener"[18/1883$"="external" "name"="external" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster" "id"="b2216074-77b8-4b2f-8b59-549d575d815c" "targetStatus"="ACTIVE"
I0412 04:46:30.465734       1 loadbalancer.go:119] controller-runtime/manager/controller/openstackcluster "msg"="Creating load balancer pool" "cluster"="external" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster" "name"="k8s-clusterapi-cluster-default-external-kubeapi-6443"
I0412 04:46:30.577123       1 loadbalancer.go:415] controller-runtime/manager/controller/openstackcluster "msg"="Waiting for load balancer" "cluster"="external" "name"="external" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster" "id"="2f8cd79e-de46-4c40-8266-4fdeddcc9618" "targetStatus"="ACTIVE"
I0412 04:47:02.556323       1 loadbalancer.go:141] controller-runtime/manager/controller/openstackcluster "msg"="Creating load balancer monitor" "cluster"="external" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster" "name"="k8s-clusterapi-cluster-default-external-kubeapi-6443"
I0412 04:47:02.666249       1 loadbalancer.go:415] controller-runtime/manager/controller/openstackcluster "msg"="Waiting for load balancer" "cluster"="external" "name"="external" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster" "id"="2f8cd79e-de46-4c40-8266-4fdeddcc9618" "targetStatus"="ACTIVE"
I0412 04:47:33.022426       1 openstackcluster_controller.go:302] controller-runtime/manager/controller/openstackcluster "msg"="Reconciling Bastion" "cluster"="external" "name"="external" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster"
I0412 04:47:44.801599       1 recorder.go:104] controller-runtime/manager/events "msg"="Normal"  "message"="Created server external-bastion with id b5a2eb3f-eb80-406f-a2f7-fb7f4086b962" "object"={"kind":"OpenStackCluster","namespace":"default","name":"external","uid":"77276ec2-b83b-42c1-bcd7-79f6a7387a6e","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha4","resourceVersion":"4840858"} "reason"="SuccessfulCreateServer"
I0412 04:47:45.394130       1 recorder.go:104] controller-runtime/manager/events "msg"="Normal"  "message"="Created floating IP 10.0.0.248 with id b9b63fcf-dfe9-4770-8ccc-32b1c6352ff7" "object"={"kind":"OpenStackCluster","namespace":"default","name":"external","uid":"77276ec2-b83b-42c1-bcd7-79f6a7387a6e","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha4","resourceVersion":"4840858"} "reason"="SuccessfulCreateFloatingIP"
I0412 04:47:46.644365       1 openstackcluster_controller.go:297] controller-runtime/manager/controller/openstackcluster "msg"="Reconciled Cluster create successfully" "cluster"="external" "name"="external" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster"
I0412 04:47:46.669133       1 openstackcluster_controller.go:121] controller-runtime/manager/controller/openstackcluster "msg"="Reconciling Cluster delete" "cluster"="external" "name"="external" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster"
I0412 04:47:46.990407       1 openstackcluster_controller.go:143] controller-runtime/manager/controller/openstackcluster "msg"="openStackCluster.Status.Network is nil " "cluster"="external" "name"="external" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster"
I0412 04:47:46.991681       1 openstackcluster_controller.go:161] controller-runtime/manager/controller/openstackcluster "msg"="openStackCluster.Status.WorkerSecurityGroup is nil " "cluster"="external" "name"="external" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster"
I0412 04:47:46.992386       1 openstackcluster_controller.go:191] controller-runtime/manager/controller/openstackcluster "msg"="Reconciled Cluster delete successfully" "cluster"="external" "name"="external" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster"
```
