### ISSUE TITLE
Improve unit test coverage

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#843]
/kind feature

We now have e2e / integration / conformance tests but basically zero unit tests. I think we should change that.
I think we need at least unit tests on 2 layers:
* CAPO controllers
* OpenStack / gophercloud utils

I would start with an initial implementation to establish patterns how we do unit tests for those layers

Some considerations:
* controller-runtime: fakeclient vs envtest
* how to mock gophercloud
* how to unit test gophercloud

Notes:
* I expect that we have to refactor some of our code to reduce the complexity and make it unit-testable (we can probably adjust the gocyclo linter to  about 10-20 (only if appropriate))

After the initial implementation I would create a list of additional unit tests for follow-up PRs, which I would then flag with help wanted / good first issue.

**Comment by sbueringer** [comment]
/unassign

Didn't have time for this. So let's see if somebody wants to pick it up until the next minor release

**Comment by sbueringer** [comment]
Related to this slack conversation: https://kubernetes.slack.com/archives/CFKJB65G9/p1623237546041600

@macaptain  just fyi, this is the corresponding issue :)

Are you currently on it?

**Comment by macaptain** [comment]
@sbueringer, yes I was hoping to have a go this week.

/assign

**Comment by sbueringer** [comment]
@macaptain Perfect, great!

**Comment by tobiasgiese** [comment]
@macaptain are you still on this?

**Comment by macaptain** [comment]
@tobiasgiese, I completed an initial implementation of mocking the OpenStack API to support unit tests in CAPO (#935).

Per the issue description:

> After the initial implementation I would create a list of additional unit tests for follow-up PRs, which I would then flag with help wanted / good first issue.

I expect we could do this now. @mdbooth had a really promising draft #1030 mocking out the interfaces in the compute module which would also help!

/unassign
