### ISSUE TITLE
Leverage cloud-provider-openstack

### ISSUE THREAD

**Issue by chaosaffe** [kubernetes-sigs/cluster-api-provider-openstack#85]
Our implementations currently focus on using the Kubernetes OpenStack built-ins which are deprecated. We should make the switch to using [cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack) instead once [Use standard clouds.yaml file as config file](https://github.com/kubernetes/cloud-provider-openstack/issues/323) closes.

**Comment by iamemilio** [comment]
/assign @iamemilio 
> https://github.com/kubernetes/cloud-provider-openstack/pull/350
