### ISSUE TITLE
Expose gophercloud requests metrics

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#856]
/kind feature

**Describe the solution you'd like**
A while back we contributed metrics about gophercloud requests to cloud-provider-openstack. I think it would be great to have the same metrics in CAPO

**Anything else you would like to add:**

Ref to the ccm PR: https://github.com/kubernetes/cloud-provider-openstack/pull/1178
(this pr also adds reconcile metrics, I wouldn't do this for now, as controller-runtime already exposes those)

**Comment by jichenjc** [comment]
um... what do we want to expose? I knew 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/metrics.md
and it expose OCCM data, what kind of metrics we want to expose for CAPO?  the CAPO API calls?

**Comment by sbueringer** [comment]
@jichenjc I was mainly thinking about the 3 listed here: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/metrics.md#openstack-api-calls

**Comment by jichenjc** [comment]
ok, I can give a try as I did part of CPO metrics job
/assign

**Comment by sbueringer** [comment]
Okay :)

**Comment by tobiasgiese** [comment]
@jichenjc what is the current status here? Are you done with this issue or can I support you / take over?

**Comment by jichenjc** [comment]
part of the metrics added at #863 

there are some todo (e.g GET/query part) , if you like ,you can work on it at your convenience :) @tobiasgiese

**Comment by tobiasgiese** [comment]
Okay, I'll take a look at it :)
/assign
