### ISSUE TITLE
Drop UserDataSecret field

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#857]
/kind feature

**Describe the solution you'd like**
We still have the field `UserDataSecret` which was in an earlier CAPI version (v1alpha1 or v1alpha2) used to reference a secret which contains the user data. Let's drop this field with v1alpha4

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jichenjc** [comment]
just for learning perspecitve, user data is important for init the VM
after remove this , what should we do to provide this mechanism to let VM consume the user data?

**Comment by sbueringer** [comment]
That is all handled by the kubeadm controllers since v1alpha3. We currently don't read this field outside of generated code. So functionally nothing will change when we delete the field.

**Comment by chrischdi** [comment]
I'd be happy to help and contribute here :-)

**Comment by jichenjc** [comment]
> 
> 
> That is all handled by the kubeadm controllers since v1alpha3. We currently don't read this field outside of generated code. So functionally nothing will change when we delete the field.

ok, thanks for the info
