### ISSUE TITLE
Block updates on the Template resources OpenStackMachineTemplate

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#858]
/kind feature

**Describe the solution you'd like**

Issue is based on this Slack thread: https://app.slack.com/client/T09NY5SBT/C8TSNPY4T/thread/C8TSNPY4T-1618296322.489700
Rest is (mostly) copied from CAPZ

As documented in https://cluster-api.sigs.k8s.io/tasks/change-machine-template.html

> These MachineTemplate resources should be immutable, unless the infrastructure provider documentation indicates otherwise for certain fields (see below for more details).
> Some infrastructure providers may, at their discretion, choose to support in-place modifications of certain infrastructure machine template fields. This may be useful if an infrastructure provider is able to make changes to running instances/machines, such as updating allocated memory or CPU capacity. In such cases, however, Cluster API will not trigger a rolling update.

Currently, updates to OpenStackMachineTemplate are allowed which is misleading as it results in no changes being applied to the running OpenStackMachines and no rolling update being triggered. We should block updates and instruct the user to create a new OpenStackMachineTemplate instead + point to the doc above in the error message.

How: add a validation webhook and reject all updates to OpenStackMachineTemplate.

**Anything else you would like to add:**
xref:
* Azure issue: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1255
* Azure PR: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1275
* Slack thread: https://app.slack.com/client/T09NY5SBT/C8TSNPY4T/thread/C8TSNPY4T-1618296322.489700

**Comment by johannesfrey** [comment]
I would like to give this a try :slightly_smiling_face:
