### ISSUE TITLE
Handle "cluster.x-k8s.io/managed-by" annotation

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#859]
/kind feature

**Describe the solution you'd like**
CAPI v1alpha4 introduced a mechanism to manage the cluster resource externally. This is triggered by the `managed-by` annotation. For more context, please see: 
* https://github.com/kubernetes-sigs/cluster-api/pull/4135
* https://github.com/kubernetes-sigs/cluster-api/pull/4303

**Anything else you would like to add:**
Notes:
* We should make sure we do all that's necessary. I'm not entirely sure if it's enough to just ignore the cluster when the annotation is set. Please read the proposal for details
* Prereq: we need a rebase onto current CAPI before

**Comment by jichenjc** [comment]
@sbueringer just to confirm, this need v1alpha4 land first, correct?

**Comment by sbueringer** [comment]
@jichenjc No it just needs a rebase onto the current CAPI branch (which I'll do later today)

**Comment by chrischdi** [comment]
Also relevant discussion maybe: https://kubernetes.slack.com/archives/C8TSNPY4T/p1620749340371300
