### ISSUE TITLE
Add description and tag of created floating ip

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#868]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Floating ip should honor the tag settings and add descriptions as well..

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by tobiasgiese** [comment]
I'll take a look at it and create a PR the next days.

/assign

**Comment by tobiasgiese** [comment]
Fixed with #925 
/close

**Comment by jichenjc** [comment]
@tobiasgiese thanks for the reminder :)
