### ISSUE TITLE
no external network but a vlan network  in openstack environment 

### ISSUE THREAD

**Issue by wuli-jessica** [kubernetes-sigs/cluster-api-provider-openstack#875]
/kind feature

Hi. We have some customers whose openstack environment does not have an external network. They use vlan network. The management cluster and tenant network are connected through vlan. Thus there is no floating ip. How does OpenStackCluster handle such a situation? Because the external network seems to be necessary in OpenstackCluster Reconcile.

**Comment by sbueringer** [comment]
@wuli-jessica right now we have a hard dependency on an external network if I'm not mistaken

**Comment by wuli-jessica** [comment]
@sbueringer Do you already have some plans about the network? 
We(our company)  will do some development about that in the future to enable it to use the vlan network. If we come up with a plan or make progress, I will write it here.

**Comment by sbueringer** [comment]
@sbueringer I personally don't have a plan to implement it or are aware of any. But I think we're open to contributions if fits into the current implementation.

**Comment by jichenjc** [comment]
@sbueringer agree and we should be open to any contributions that doesn't break existing functions

@wuli-jessica I am +1 to what you proposed here,  I am facing same issue in our openstack solutions.. that's the reason why we asked openshift to support no floating ip (https://github.com/openshift/installer/blob/master/docs/user/openstack/README.md#without-floating-ips) here..  so I can help you in review the proposed solution, thanks

**Comment by mkjpryor** [comment]
+1 from me as well - we have the exact same problem with our customers.
