### ISSUE TITLE
Generator always puts output files in ubuntu directory

### ISSUE THREAD

**Issue by iamemilio** [kubernetes-sigs/cluster-api-provider-openstack#88]
looks like this is the culprit: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/3584374fec7dc9c32c851cafc2f40b870c873c6e/cmd/clusterctl/examples/openstack/generate-yaml.sh#L55

**Comment by chrigl** [comment]
PR: #90 is in master now. Issue seems to be solved, or do I miss something?
