### ISSUE TITLE
Add missing binaries for envtest

### ISSUE THREAD

**Issue by Xenwar** [kubernetes-sigs/cluster-api-provider-openstack#887]
For the envtest to usable, the ```etcd, kubectl and kube-apiserver``` binaries are required. As we have it now, none of the make targets install the binaries.
Due to this issue, the current test suit is skipped and none of the tests could run, preventing creation of new controllers’ tests.

Therefore, adding the following is beneficial.

1. Add a make target to install the missing binaries
2. Change the ```test``` target taking these binaries into account
3. Add a ```test-cover``` target

/kind feature

**Comment by jichenjc** [comment]
@Xenwar thanks for the update, yes, I think it's something we need address~

**Comment by sbueringer** [comment]
I would prefer to implement it the same way as the main repo (regarding how the binaries are pulled, added to the path and how the test targets are named)
