### ISSUE TITLE
Support machine instance state "migrating"

### ISSUE THREAD

**Issue by MPV** [kubernetes-sigs/cluster-api-provider-openstack#889]
/kind bug

**What steps did you take and what happened:**

An OpenStack machine was ["live migrated"](https://docs.openstack.org/nova/pike/admin/live-migration-usage.html), but the `openstackmachine` resource ended up being stuck in `MIGRATING` state:

```shell
$ kubectl get openstackmachine
NAME                                       CLUSTER          INSTANCESTATE   READY   PROVIDERID                                          MACHINE
prod-1-osmt-control-plane-g2-2-4-004vxjz   prod-1-cluster   MIGRATING       true    openstack:///2b3fb754-bf0d-4b25-a820-0720953e8429   prod-1-kubeadm-control-plane-t2cnm
[...]
```

```json
$ kubectl get openstackmachine prod-1-osmt-control-plane-g2-2-4-004vxjz -o json | jq -r .status
{
  "addresses": [
    {
      "address": "10.224.1.30",
      "type": "InternalIP"
    }
  ],
  "errorMessage": "OpenStack instance state \"MIGRATING\" is unexpected",
  "errorReason": "UpdateError",
  "instanceState": "MIGRATING",
  "ready": true
}
```

...but the migration in OpenStack seems to have completed successfully:

<img width="1449" alt="Skärmavbild 2021-06-01 kl  17 11 37" src="https://user-images.githubusercontent.com/62675/120347315-737c3880-c2fc-11eb-8dc5-baf79a7ecb3e.png">

```
$ openstack server show prod-1-osmt-control-plane-g2-2-4-004vxjz -f json | jq .status
"ACTIVE"
```

**What did you expect to happen:**

Reconciles progressing, and not being blocked by invalid state on the instance.

**Anything else you would like to add:**

It seems we only accept `ACTIVE` and `BUILDING` states, not `MIGRATING`:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/release-0.3/controllers/openstackmachine_controller.go#L403-L412

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): 0.3
- Cluster-API version: 
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
it's a valid bug, we never tried this before 
and actually there might be more to consider (e.g resize, migrate , live-migrate, shelve, pause etc) 

so I think we can use this to track `live-migrate` and use others potential issue to track other state

**Comment by MPV** [comment]
I asked our supplier of OpenStack of what triggered this to happen for us this week, and they said:

>Instances are continuously migrated around to balance the cluster.

**Comment by jichenjc** [comment]
>>>Instances are continuously migrated around to balance the cluster.

this is typical and normal, so yes, we should take live migrate state into consideration (which is , fix this issue)

**Comment by sbueringer** [comment]
I agree. We should not fail when this state occurs. But we have to be careful when adjusting this code. I guess when a machine is in this state we should retry reconciles at a later time.

**Comment by jichenjc** [comment]
>>.retry reconciles at a later time.

yeah it depends, live migration might not need such but resize definitely need some consideration 
anyway, agree need to be very careful

**Comment by hidekazuna** [comment]
/remove-lifecycle stale

We need to address this issue.

**Comment by jichenjc** [comment]
I tried `SHUTOFF` which is a very normal case and got similar result...

```
root@jitest28:~# kubectl get openstackmachine
NAME                                  CLUSTER           INSTANCESTATE   READY   PROVIDERID                                          MACHINE
capi-quickstart-control-plane-lkwlb   capi-quickstart   ACTIVE          true    openstack:///dddf685b-1a34-46dd-92cf-9f30bd7cd6b6   capi-quickstart-control-plane-c95bs
capi-quickstart-md-0-rvkns            capi-quickstart   SHUTOFF         true    openstack:///d19ac136-10c2-479c-810c-06fac0829a0b   capi-quickstart-md-0-7d869f6fb9-6kxwx
```


```
        ],
        "errorMessage": "OpenStack instance state \"SHUTOFF\" is unexpected",
        "errorReason": "UpdateError",
        "instanceState": "SHUTOFF",
        "ready": true
    }

```
