### ISSUE TITLE
Adding failureMessage and failureReason fields at the openStackCluster level

### ISSUE THREAD

**Issue by Xenwar** [kubernetes-sigs/cluster-api-provider-openstack#890]
openStackCluster is the top level resource in CAPO. Error could occur at any level in the hierarchy of objects. 
It would be beneficial to show the error/failure related information at openStackCluster level. These fields can also be used for assertion in test cases.

These fields exist at the capi cluster level
```
- failureMessage <string>: FailureMessage indicates that there is a fatal problem reconciling the state, and will be set to a descriptive error message.
- failureReason<string>:  FailureReason indicates that there is a fatal problem reconciling the state, and will be set to a token value suitable for programmatic interpretation.
```
There is also a reference implementation: [here](metal3/blob/68b709ffb5d6c94a9ff9277d70025ac7b607d174/api/v1alpha4/metal3cluster_types.go#L66-L71)
https://github.com/metal3-io/cluster-api-provider-

/kind feature

**Comment by jichenjc** [comment]
agree this is something we need consider , need check to what extend we need report such info (e.g which error we report and which not ) need refer to meta3 and other providers
