### ISSUE TITLE
 Openstack credentials saved on KCP node disk

### ISSUE THREAD

**Issue by Xenwar** [kubernetes-sigs/cluster-api-provider-openstack#896]
During provisioning of KCP nodes with CAPO, openstack credentials are saved to disk. 

 The following content was found in /var/lib/cloud/.... . 
```
# cat /etc/kubernetes/cloud.conf
[Global]
auth-url=https://mycloud.com:5000
username="user1"
password="password1"
tenant-name="Project10"
domain-name="Project10"
ca-file="/etc/certs/cacert"
region="region1"
```
There are two reasons why such files should not be saved on the KCP node's disk.

1. The data is sensitive in that it allows access to other resources in the openstack cloud.
2. It causes deployment of KCP nodes to fail as kubelet tries to use it in `kubeadm-flags.env `, this is a blocker, no an inconvenience

/kind bug

**Comment by Xenwar** [comment]
Also relevant, 

```
/var/lib/kubelet# cat kubeadm-flags.env 
KUBELET_KUBEADM_ARGS="--cloud-config=/etc/kubernetes/cloud.conf --cloud-provider=openstack --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.2"

```

**Comment by sbueringer** [comment]
I think the solution to this is to only use the external ccm and change the ccm deployment to use a secret instead? I'm not sure when but the internal cloud provider should be gone pretty soon.

**Comment by sbueringer** [comment]
I'm not sure how we could solve this for the "internal" cloud provider in Kubelet or if we should even attempt to given that it's deprecated since a while.
