### ISSUE TITLE
The Cluster status is stuck in "Deleting"

### ISSUE THREAD

**Issue by wuli-jessica** [kubernetes-sigs/cluster-api-provider-openstack#906]
/kind bug

**What steps did you take and what happened:**
Hi. When I created the workload cluster, I encountered the "providerClient authentication err: Authentication failed" in openstack-provider because I wrote something wrong in clouds.yaml , and when I executed "kubectl delete" to delete the Cluster, the command did not return and the Cluster was stuck in "Deleting" status, check the log, the deletion process also meets the "Authentication failed" error.

**What did you expect to happen:**

the cluster should be deleted in case of "failed to Authentication Openstack"

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.3.4
- Cluster-API version: v0.3.15
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
I don't think we should skip our delete logic when we're unable to communicate with OpenStack. If this is a use case you regularly encounter you can always remove finalizer from CAPO resources so they get deleted.

**Comment by jichenjc** [comment]
+1 to what @sbueringer mentioned, this is error case and if we can do some hacking/workaround , maybe we doc that as tips and not skip the delete action otherwise it might lead to orphan resource

**Comment by wuli-jessica** [comment]
The delete logic is reasonable, but we can adjust the logic of "add finalizer".

Now we add finalizer without checking if it can connect to openstack.  But if connecting to openstack is necessary to remove finalizer, maybe we should also check that before add finalizer.

Look at the following code （Intercepted from openstackcluster_controller.go reconcileNormal）

`

	// If the OpenStackCluster doesn't have our finalizer, add it.
	controllerutil.AddFinalizer(openStackCluster, infrav1.ClusterFinalizer)
	// Register the finalizer immediately to avoid orphaning OpenStack resources on delete
	if err := patchHelper.Patch(ctx, openStackCluster); err != nil {
		return reconcile.Result{}, err
	}

	osProviderClient, clientOpts, err := provider.NewClientFromCluster(r.Client, openStackCluster)
	if err != nil {
		return reconcile.Result{}, err
	}

`

A possible solution：move NewClientFromCluster before AddFinalizer. 

and so do openstackmachine_controller.

@jichenjc  @sbueringer

**Comment by jichenjc** [comment]
thanks, that's reasonable , if not able to connect , seems we can return directly without the finalizer

**Comment by sbueringer** [comment]
I don't think that's a good idea. In general we should always add the finalizer. Imho we shouldn't support use cases where CAPO is not able to connect to OpenStack with changes like that?

I hope encountering thinks like this is an absolute exception. And in those cases you can remove the finalizer after the delete cluster call.
