### ISSUE TITLE
Add a feature to configure Port level PortSecurity

### ISSUE THREAD

**Issue by Xenwar** [kubernetes-sigs/cluster-api-provider-openstack#911]
Add a feature to configure Port level PortSecurity such that

- Each port is configured independently. When disabled, both SecurityGroups and allowedAddressPairs values on that port should be removed. specified by `OpenStackMachineTemplate.spec..template.spec.ports[0].disablePortSecurity: false/true`

- When PortSecurity is disabled at the network level, then it is also disabled at each port level. specified by (OpenStackCluster.spec.disablePortSecurity: false)

/kind feature

**Comment by hidekazuna** [comment]
`OpenStackCluster.spec.disablePortSecurity` works for new create network and ports as https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/913#issuecomment-866754954. So second feature is already implemented.

**Comment by chrischdi** [comment]
xref https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/921 for alternative solution

**Comment by jichenjc** [comment]
@Xenwar should we close this now given the PR propsed merged #921? Thanks

**Comment by jichenjc** [comment]
/close 

close this in favor of new way
