### ISSUE TITLE
Allow mix of trunk/untrunked ports. 

### ISSUE THREAD

**Issue by adduarte** [kubernetes-sigs/cluster-api-provider-openstack#929]
/kind feature

**Describe the solution you'd like**
Currently you can specify ports to be attached to the instance through 
[openStackMachine.Spec.Ports , and/or openStackMachine.Spec.Networks](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/0fe03161c96e8acd86331b2ae6075d42e4716ac1/pkg/cloud/services/compute/instance.go#L146)

And then [ALL ports are either Trunked or Not Trunked depending on config.Trunk depending on instance.Trunk](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/0fe03161c96e8acd86331b2ae6075d42e4716ac1/pkg/cloud/services/compute/instance.go#L197)

Some NFV use cases use the vnic_type= direct to connet the VFs of an SR-IOV capable NIC to the  node VM as additional untrunked ports using openStackMachine.Spec.Ports whilst attaching the node VM to the primary network via a  virtio port using openStackMachine.Spec.Networks

As an OpenShift user I would like to be able to deploy a node VM attached to the primary network through a Trunked port with additional ports attached to the vm which are NOT trunked.

**Comment by Xenwar** [comment]
@adduarte 
Do you see the PR https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/934 addressing  the requirements ?
If not, I can create a separate issue for it. 
Thanks.

**Comment by adduarte** [comment]
@Xenwar #934 looks good to me. Thanks.

**Comment by mdbooth** [comment]
@adduarte Since #934 merged I think this is resolved. If you're happy please could you close this issue?
