### ISSUE TITLE
Add OpenStackClusterTemplate type

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api-provider-openstack#931]
/kind feature

**Describe the solution you'd like**
Add a new CRD named OpenStackClusterTemplate. This is needed for ClusterClass.
In the short term this type will not be used outside of ClusterClass.

xref [DockerClusterTemplate](https://github.com/kubernetes-sigs/cluster-api/issues/4900)
also see https://kubernetes.slack.com/archives/C8TSNPY4T/p1625767242134600

**Comment by tobiasgiese** [comment]
I'll take a look at it
/assign
