### ISSUE TITLE
Creating instances fails when using tags

### ISSUE THREAD

**Issue by petrutlucian94** [kubernetes-sigs/cluster-api-provider-openstack#936]
/kind bug

**What steps did you take and what happened:**
The cluster spec allows setting instance tags. The issue is that this feature requires Nova >=2.52 but CAPO doesn't set the microversion. For this reason, Nova returns an error:

```
 controller-runtime/controller "msg"="Reconciler error" "error"="error creating Openstack instance: create new server err: error creating Openstack instance: Bad request with: [POST http://10.222.0.33/compute/v2.1/servers], error message: {\"badRequest\": {\"code\": 400, \"message\": \"Invalid input for field/attribute server. Value: {'availability_zone': 'nova', 'flavorRef': 'm1.large', 'imageRef': 'e1af6391-6d7f-418f-a9b7-572b286e5bd9', 'key_name': 'mykey', 'name': 'cluster-control-plane-rjg74', 'networks': [{'port': '7c40ba07-30eb-4b51-ba40-1dbfea3b6aef'}], 'security_groups': [{'name': 'f24a5de8-b320-4b57-a439-00a672758d7a'}], 'tags': ['TestAppliance'], 'user_data': '...'}. Additional properties are not allowed ('tags' was unexpected)\"}}" "controller"="openstackmachine" "name"="cluster-control-plane-rjg74" "namespace"="default"
```

Tags 

**What did you expect to happen:**

Since the tag is exposed by the cluster spec, I'd expect CAPO to be able to set it.

**Anything else you would like to add:**

CAPO might set a global Nova microversion or pick it based on the spec. Special care must be taken as bumping the microspec may also change the Nova response format and gophercloud may not be able to parse it.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.3.4
- Cluster-API version: v0.3.16
- OpenStack version: Victoria
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`): 1.18
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by jichenjc** [comment]
@petrutlucian94 please check #917 
if you agree it's duplicate, could you please close this one? Thanks

**Comment by petrutlucian94** [comment]
Indeed, it's a duplicate. Thanks for mentioning the other issue!
