### ISSUE TITLE
e2e tests hanging when trying sshuttle tunnel

### ISSUE THREAD

**Issue by macaptain** [kubernetes-sigs/cluster-api-provider-openstack#940]
/kind bug

The e2e tests are hanging indefinitely (over 2 hour long runs) during setup steps when using sshuttle to connect to OpenStack.

https://prow.k8s.io/log?container=test&id=1415576850691788800&job=pull-cluster-api-provider-openstack-e2e-test
```
1322.58 - Thu, 15 Jul 2021 08:04:23 +0000 - v. 20.4.1-0ubuntu1~20.04.1
Opening tunnel to 10.0.2.15 via 34.150.157.178
usage: sshuttle [-l [ip:]port] -r [user@]sshserver[:port] <subnets...>
sshuttle: error: unrecognized arguments: --ttl=65
Failed to discover available identity versions when contacting http://10.0.2.15/identity. Attempting to parse version from URL.
Could not find versioned identity endpoints when attempting to authenticate. Please check that your auth_url is correct. Unable to establish connection to http://10.0.2.15/identity: HTTPConnectionPool(host='10.0.2.15', port=80): Max retries exceeded with url: /identity (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f17acf8ea20>: Failed to establish a new connection: [Errno 110] Connection timed out'))
failed 1 times: openstack versions show
```

The version of sshuttle has changed:

Broken:
```
Created wheel for sshuttle: filename=sshuttle-1.0.6.dev79+gbd00a53-py2.py3-none-any.whl size=70134 sha256=7784fad1c19b323cac10d60a6844b66561dcf17bb9b6a33815c2aa29119c0be2
```

Last known working:
```
Created wheel for sshuttle: filename=sshuttle-1.0.6.dev77+g6ae0b51-py2.py3-none-any.whl size=70768 sha256=e719ebeb258044e71b3bcb9817872b17d4afcc56d5ecdd31e246b54e575bd8c7
```

This pull request may be the change: https://github.com/sshuttle/sshuttle/pull/661, since it removes the `--ttl` option.

**Comment by macaptain** [comment]
Here's where `sshuttle` is used in the tests, and the justification for setting `--ttl` is described in the comment:

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/010f0b9da188172b393ab519ab83e3fabf2779ad/hack/ci/devstack-on-gce-project-install.sh#L190-L192

**Comment by sbueringer** [comment]
Oh, yeah that's pretty bad (as was the hack :)). According to the sshuttle PR we should be able to just drop --ttl? (and if that doesn't work we can pin sshuttle to the old version for an immediate fix/mitigation)

**Comment by macaptain** [comment]
> Oh, yeah that's pretty bad (as was the hack :)). According to the sshuttle PR we should be able to just drop --ttl? (and if that doesn't work we can pin sshuttle to the old version for an immediate fix/mitigation)

Yes, having looked over the sshuttle PR, we should just be able to drop --ttl. Let's give that a try. I'll have a PR in a few moments to test.

/assign
