### ISSUE TITLE
v1alpha4: Update Readme

### ISSUE THREAD

**Issue by tobiasgiese** [kubernetes-sigs/cluster-api-provider-openstack#943]
**Describe the solution you'd like**

With the upcoming CAPO release v0.4.0 we have to update the [README.md](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/README.md).
At least the compatibility matrix has to be adapted to the new version.

As the readme is part of the release (i.e., in the release archive), it should be done before we're releasing.

part of #745

/kind feature

**Comment by jichenjc** [comment]
@tobiasgiese yes, please feel free to submit a PR, thanks ~
