### ISSUE TITLE
Do not update floating ip if its already mapped correct

### ISSUE THREAD

**Issue by tobiasgiese** [kubernetes-sigs/cluster-api-provider-openstack#948]
/kind feature

**Describe the solution you'd like**

We had problems reconciling our clusters with legacy load balancers, which were migrated from Neutron LBaaS to Octavia. The issue is that the port has no project id associated.
Therefore, a floating ip association will fail with the error:

```
Bad floatingip request: Cannot process floating IP association with Port a52bde06-ea25-4264-85b9-3af36628109b, since that port is owned by a different tenant.
```

**Comment by hidekazuna** [comment]
@tobiasgiese I wonder if this is not feature but bug. Update issue description using bug template, please.
