### ISSUE TITLE
Do not update floating ip if its already mapped correct

### ISSUE THREAD

**Issue by tobiasgiese** [kubernetes-sigs/cluster-api-provider-openstack#949]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

We had problems reconciling our clusters with legacy load balancers, which were migrated from Neutron LBaaS to Octavia. The issue is that the port has no project id associated.
Therefore, a floating ip association will fail with the error:

```
Bad floatingip request: Cannot process floating IP association with Port a52bde06-ea25-4264-85b9-3af36628109b, since that port is owned by a different tenant.
```

**What did you expect to happen:**

The floating ip shouldn't be handled at all if it's already mapped.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.4.0
- Cluster-API version: v0.4.0 (latest master)
- OpenStack version: VIO 7.0
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`): v1.21.3
- OS (e.g. from `/etc/os-release`):

**Comment by hidekazuna** [comment]
I do not know the difference between Ocatavia load balancer migrated from Neutron LBaaS  and new Octavia load balancer, but your expectation is reasonable.
