### ISSUE TITLE
Add webhook health check

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-openstack#954]
/kind feature

**Describe the solution you'd like**
It would be nice if the controller health checks would use the readiness of the webhook server (instead of the no-op Ping).

For reference, the implementation in cluster-api: https://github.com/kubernetes-sigs/cluster-api/pull/4989

**Anything else you would like to add:**
This requires at least controller-runtime v0.9.3.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by tobiasgiese** [comment]
/assign

A nice gap stopgap :)
