### ISSUE TITLE
Cluster templates using deprecated option "openstack" instead of "external"

### ISSUE THREAD

**Issue by raildo** [kubernetes-sigs/cluster-api-provider-openstack#956]
When using the templates cluster-template-without-lb.yaml and cluster-template.yaml, it will fail due the deprecated option
cloud-provider: openstack in the KubeadmControlPlane object.  Based on the latest versions of kubelet, it should be user cloud-provider: external instead

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:  0.3.22
- OpenStack version: stable/Victoria
- Kubernetes version (use `kubectl version`): v1.19.11
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by raildo** [comment]
Sorry about the kind/bug flag, First time reporting an issue here, I forgot to remove the tag on the bug template. This issue was found using a cluster deployed via kubadm.

**Comment by jichenjc** [comment]
have you check https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/docs/book/src/topics/external-cloud-provider.md ?

**Comment by jichenjc** [comment]
I noticed there is a broken link, fixing https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/957

**Comment by raildo** [comment]
@jichenjc Hey, thanks for the link! I didn't check this link before, I'll give a shoot on it, and I'll let you know, but thanks for reviewing and the current PR anyway!

**Comment by raildo** [comment]
I believe this was fixed by https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/957 I'm closing this issue for now.
