### ISSUE TITLE
VM instances with error state cann't be deleted successfully

### ISSUE THREAD

**Issue by zhangdb-git** [kubernetes-sigs/cluster-api-provider-openstack#959]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1. Create a workload cluster.
2. Failed to create worker intances because of some exception of nova, state of instances are "error".
3. Delete this workload cluster.
4. Worker instances are not deleted successfully.

**What did you expect to happen:**
Worker instances can be deleted successfully.

**Anything else you would like to add:**
We should check state of instance before detaching interfaces from instance, because it is not allowed to detach interfaces from an error instance.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.4.0
- Cluster-API version: v0.4.0
- OpenStack version: Rocky
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`): 1.20.10
- OS (e.g. from `/etc/os-release`): centos-8

**Comment by jichenjc** [comment]
>>>We should check state of instance before detaching interfaces from instance, because it is not allowed to detach interfaces from an error instance.

If I understand this correctly, you are trying to delete a cluster and the worker node become error
so you want to delete the cluster but it failed due to instance go error state and detach interface failed ?

**Comment by zhangdb-git** [comment]
@jichenjc  Thanks. Error occur at line 668, error message in log is:
```
Cannot 'detach_interface' instance aafa08c1-b4b7-413e-816e-732651f4fa0b while it is in vm_state error
```

My suggestion is: check instance state, if it is "active" or "shutoff", then detach, or skip detaching.

**Comment by jichenjc** [comment]
the issue might be https://github.com/openstack/nova/blob/master/nova/compute/api.py#L5051
then https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/attach_interfaces.py#L227

so we should ignore 409 error at such case..
