### ISSUE TITLE
Support reset password for vm

### ISSUE THREAD

**Issue by ruifaling** [kubernetes-sigs/cluster-api-provider-openstack#979]
/kind feature
 in the current version,after launch a cluter,if we do not know the password for root from the image ,we can only connet to the vm by keypair,I hope we can reset the password,the we could connect to the vm by password

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jichenjc** [comment]
@ruifaling please let me know whether it works for you or I will close this issue.. thanks

**Comment by ruifaling** [comment]
> @ruifaling please let me know whether it works for you or I will close this issue.. thanks

Thanks,it works for me.If can, could i  submit the code to the project ?

**Comment by jichenjc** [comment]
sure, feel free to contribute :) appreciate the help~

**Comment by jichenjc** [comment]
/close

close this as we have nothing to do now 
feel free to reopen
