### ISSUE TITLE
Periodic e2e CI- Signal on openstack providers

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api-provider-openstack#98]
Please add periodic jobs to https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-cluster-api-provider-openstack to give feedback on CI signal.

**Comment by dims** [comment]
cc @flaper87 @mrhillsman

**Comment by mrhillsman** [comment]
ack @timothysc @dims

**Comment by mrhillsman** [comment]
i believe this has been resolved - @flaper87 @timothysc @dims ?

**Comment by dims** [comment]
@mrhillsman the testgrid above does not show any new CI jobs in openlab that test the cluster-api-provider-openstack. Is it on another url?
