### ISSUE TITLE
Conversion webhook is not initialized

### ISSUE THREAD

**Issue by Lirt** [kubernetes-sigs/cluster-api-provider-openstack#987]
/kind bug

CAPO conversion webhook from `v1alpha3` to `v1alpha4` is not initialized. You can notice this in two ways:

1. Creating `v1alpha3` CAPO resources doesn't work. 
2. There is no log about conversion webhook registered (log line should be `conversion webhook enabled`).

Error output:

```bash
Error from server (InternalError): error when creating "xxx.yaml": Internal error occurred: conversion webhook for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=OpenStackMachine failed: the server could not find the requested resource
```

During troubleshooting me and my colleague @jsen- ran debug mode in VSCode and we noticed that during webhook setup the schema implemented only Hub interface and no Convertible. This was because the `v1alpha3` schema is not added in the [main.go](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/1576e9c1ff8e2f292d8ec01840367cf16246f21c/main.go#L73).

**Environment:**

- Cluster API Provider OpenStack version: Tested both with `main` (`1576e9c1ff8e2f292d8ec01840367cf16246f21c`) and `0.4.0`
- Cluster-API version: 0.4.1
- OpenStack version: ---
- Kubernetes version (use `kubectl version`): 1.20.2

Fix opened in MR https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/988

**Comment by tobiasgiese** [comment]
There is already an open PR (#985) regarding this issue

**Comment by Lirt** [comment]
Oh, I didn't register this PR in the meantime. Difference in code change is that it includes also old CAPI schemas, which are IMO not needed here.

**Comment by jichenjc** [comment]
@Lirt #985  merged, do we still have TODOs here? or can we close this?

**Comment by Lirt** [comment]
Hi @jichenjc we can close this, but I assume you should do new release as this is critical otherwise users will use the old one and report this same bug.
