### ISSUE TITLE
Ability to specify security group rules for CNIs other than Calico

### ISSUE THREAD

**Issue by mkjpryor** [kubernetes-sigs/cluster-api-provider-openstack#995]
/kind feature

It would be great to be able to specify the ingress rules for the managed security groups for CNIs other than Calico, defaulting to the Calico rules if not otherwise specified. This is better than pre-creating security groups for each CNI as it still enables the user to easily have separate security groups for each cluster that are tied to the cluster lifecycle.

Assuming that managed security groups are requested, the allow-all egress rules would always be added. Then if custom ingress rules are specified, they would be used for the control plane and worker groups. If no custom rules are specified, the Calico groups used now will be used.

An alternative, maybe even better, solution would be to have a set of supported CNIs that we maintain rulesets for. If a user wants to use an unsupported CNI, they can use unmanaged security groups to do this or submit a patch to add the rules.

**Comment by mkjpryor** [comment]
Another alternative, which would be the most simple to implement, is to have an option that just configures rules that allow all traffic between cluster nodes.

**Comment by jichenjc** [comment]
@hidekazuna FYI in case you might have some suggestions

>>>supported CNIs that we maintain rulesets for. 

just curious how we can test this .. as we might have various options ,test is a question mark.
I think maybe we default to Calico (and test it ) ,provide custom options to inject rules but 
claim no test for it, user need make sure it works for them by their own?

**Comment by hidekazuna** [comment]
I want to make clear.
Currently for using CNI other than Calico, you do not use managed security groups and add your own security group to `OpenStackMachineTemplate`. It is troublesome. So you want managed security group for CNIs other than Calico, right?

**Comment by mkjpryor** [comment]
@hidekazuna 

Exactly. I want security groups for other CNIs that only allow traffic within the cluster whose lifecycle is tied to the cluster.

I think the first thing to implement that would cover all possible use cases is just a flag to allow all **in cluster** ingress. I actually don't mind this as a fallback approach that will work for all CNIs. Then in the future we can maybe look at having specific rules for other CNIs or allowing the user to specify their own rules.

**Comment by hidekazuna** [comment]
@mkjpryor Thanks, I understand your motivation. I want to consider other CNIs from the beginning. How about explicitly write CNI plugin name in `OpenStackCluster` spec like below?

Use calico: use current managed security groups

```yaml
managedSecurityGroups: true
cniPlugin: calico
```

Use Cilium: open firewall rules in the [cilium doc](https://docs.cilium.io/en/stable/operations/system_requirements/#firewall-rules)

```yaml
managedSecurityGroups: true
cniPlugin: cilium
```

Allow all in-cluster ingress: open all ingress

```yaml
managedSecurityGroups: true
```

`managedSecurityGroups: true` behavior changes so that we need proper API conversion.

**Comment by mkjpryor** [comment]
@hidekazuna 

Are you happy with the PR I proposed in #998 for now, which is backwards compatible, or would you prefer we implement something more like the breaking change you have proposed above from the start?

**Comment by jichenjc** [comment]
@hidekazuna I like #998  and I think it's not sustainable for us to maintain the CNI 
as we don't have too much test coverage on all the CNI we might support, thus provide a interface 
to let someone to extend and take risk at their own is healthy...

**Comment by hidekazuna** [comment]
> @hidekazuna
> 
> Are you happy with the PR I proposed in #998 for now, which is backwards compatible, or would you prefer we implement something more like the breaking change you have proposed above from the start?

@mkjpryor If you will propose something breaking change like my idea in the future, I want to have the breaking change from the beginning. If not, It is OK to me.

**Comment by hidekazuna** [comment]
> @hidekazuna I like #998 and I think it's not sustainable for us to maintain the CNI
> as we don't have too much test coverage on all the CNI we might support, thus provide a interface
> to let someone to extend and take risk at their own is healthy...

@jichenjc I understand your motivation. You do not want to maintain managed security groups for CNI other than Calico. Resources are limited, I agree.

**Comment by mkjpryor** [comment]
@jichenjc @hidekazuna 

I also think that maintaining rules for multiple CNIs is unsustainable. So I am happy with #998 and don’t see a need for anything else. 

If anything, I would rather just get rid of the Calico rules and just make the default to allow all in-cluster traffic. If users want more security, they can supply their own security groups. But I appreciate this breaks backwards compatibility so I think #998 as it is should be fine.

**Comment by hidekazuna** [comment]
@mkjpryor Thanks, I understand your current motivation. I misunderstand from the issue comment actually.

**Comment by mkjpryor** [comment]
@hidekazuna 

I wrote the issue before I thought about what was reasonable to implement! I’m definitely happy with the solution in #998 though.
