### ISSUE TITLE
Prometheus metrics when making API calls are inconsistent

### ISSUE THREAD

**Issue by macaptain** [kubernetes-sigs/cluster-api-provider-openstack#997]
/kind bug

**What steps did you take and what happened:**

Prometheus metrics for OpenStack API calls are made throughout the codebase as `mc.ObserveRequest(err)` calls. They're inconsistent in places:

* Sometimes we make a call without recording a metric
* Sometimes deletion events which return 404 (not found) are recorded as errors and sometimes not
* ReplaceAttributes call is recorded as 'trunk update', but it should probably be recorded as its own type

**What did you expect to happen:**
Ideally all Prometheus metric counters for OpenStack API calls are consistent.

After refactoring the networking logic into a separate client (#935), metrics recordings for networks can be tidied up from around the codebase and all put in client.go. If we apply a similar refactor to the compute package, we should be able to move all the `metrics` package usage into client implementation files only and see that all the metrics gathering is consistent.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): 754371d1ebb96202ba73474f3b9f7e5a4d3eb7d9
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
@macaptain you are right, we should move the code into one place so that we can handle all the logic well
so yes, refactor of compute node is something better to have (for ut andmetrics collection both)
